const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'act_17_16_34',
    intro: 'O discurso de Paulo no Areópago em Atenas é um dos encontros mais fascinantes entre o Evangelho cristão e a filosofia pagã no Novo Testamento. Atenas era o centro intelectual e cultural do mundo antigo, a cidade de Sócrates, Platão e Aristóteles. No entanto, quando Paulo chega, ele não fica impressionado com a arquitetura ou a filosofia; o seu espírito se revolta ao ver a cidade "inteiramente entregue à idolatria". Paulo começa a debater na sinagoga e na praça do mercado, chamando a atenção dos filósofos epicureus e estoicos. Eles o levam ao Areópago (o conselho supremo da cidade) para explicar a sua "nova doutrina". O sermão de Paulo é uma obra-prima de apologética, onde ele usa a cultura local como ponte para apresentar o Deus Criador, Juiz e Salvador.',
    desc1: 'Paulo começa o seu discurso com uma observação cultural brilhante e respeitosa, mas subversiva: "Senhores atenienses, em tudo vos vejo um tanto supersticiosos; porque, passando eu e vendo os vossos santuários, achei também um altar em que estava escrito: AO DEUS DESCONHECIDO". Os atenienses tinham tantos deuses que, com medo de ofender algum que tivessem esquecido, fizeram um altar genérico. Paulo usa esse altar como ponto de partida: "Esse, pois, que vós honrais, não o conhecendo, é o que eu vos anuncio". Ele não ataca os ídolos imediatamente; ele preenche o vazio do "Deus desconhecido" com a revelação do Deus verdadeiro.',
    desc2: 'Paulo então apresenta uma teologia radicalmente diferente da mitologia grega. Ele declara que Deus é o Criador do universo: "O Deus que fez o mundo e tudo que nele há, sendo Senhor do céu e da terra, não habita em templos feitos por mãos de homens". Isso destruía a ideia de deuses locais confinados a santuários. Em seguida, ele afirma que Deus é o Sustentador da vida: "Nem tampouco é servido por mãos de homens, como que necessitando de alguma coisa; pois ele mesmo é quem dá a todos a vida, e a respiração, e todas as coisas". Os deuses gregos precisavam de sacrifícios para se alimentar; o Deus cristão não precisa de nada, Ele é a fonte de tudo. Paulo até cita poetas gregos (Epimênides e Arato) para provar que a humanidade é geração de Deus, argumentando que é ilógico pensar que a Divindade seja semelhante a ouro, prata ou pedra esculpida.',
    desc3: 'O clímax do sermão é o chamado ao arrependimento e a declaração do juízo final. Paulo diz: "Mas Deus, não tendo em conta os tempos da ignorância, anuncia agora a todos os homens, e em todo o lugar, que se arrependam". A ignorância não é mais uma desculpa. O motivo do arrependimento é a certeza do juízo: "Porquanto tem determinado um dia em que com justiça há de julgar o mundo, por meio do homem que destinou". A prova irrefutável desse juízo e da autoridade de Cristo é a ressurreição: "e disso deu certeza a todos, ressuscitando-o dentre os mortos". Quando Paulo menciona a ressurreição física (um conceito absurdo para a filosofia grega, que via o corpo como uma prisão da alma), o sermão é interrompido. Alguns zombam, outros adiam a decisão, mas alguns creem, incluindo Dionísio, o areopagita, e uma mulher chamada Dâmaris.',
    concl: 'O sermão de Paulo em Atenas nos ensina como comunicar o Evangelho a uma cultura secular e pluralista. Devemos encontrar pontos de contato na cultura, mas nunca comprometer a verdade de que Deus é o Criador soberano e o Juiz justo. O Evangelho sempre confrontará a idolatria humana e culminará na exigência de arrependimento e na loucura (para o mundo) da cruz e da ressurreição de Cristo.'
  },
  {
    id: 'gen_15_1_6',
    intro: 'O capítulo 15 de Gênesis é um dos textos mais importantes de toda a Bíblia para a compreensão da doutrina da justificação pela fé. Abrão (cujo nome ainda não havia sido mudado para Abraão) havia acabado de retornar de uma vitória militar impressionante contra quatro reis para resgatar o seu sobrinho Ló. Apesar do sucesso, Abrão estava com medo (talvez de retaliação) e profundamente frustrado. Deus havia prometido fazer dele uma grande nação, mas os anos passavam, ele estava envelhecendo, e a sua esposa Sarai continuava estéril. É neste momento de dúvida e vulnerabilidade que Deus aparece a Abrão em visão, reafirma a Sua promessa e estabelece o princípio fundamental de como um ser humano pecador pode ser declarado justo diante de um Deus santo.',
    desc1: 'A visão começa com uma palavra de encorajamento e proteção: "Não temas, Abrão, eu sou o teu escudo, o teu grandíssimo galardão". Deus promete ser a defesa de Abrão (escudo) e a sua recompensa (galardão). No entanto, a resposta de Abrão revela a sua angústia: "Senhor Deus, que me hás de dar, pois ando sem filhos, e o mordomo da minha casa é o damasceno Eliézer?". Abrão não estava interessado em riquezas ou proteção se não tivesse um herdeiro para cumprir a promessa. Ele argumenta que, como Deus não lhe deu descendência, um servo nascido na sua casa seria o seu herdeiro (uma prática legal comum na época). A fé de Abrão estava vacilando diante da realidade biológica e do tempo.',
    desc2: 'Deus responde à dúvida de Abrão com uma rejeição categórica do plano humano e uma reafirmação da promessa divina: "Este não será o teu herdeiro; mas aquele que de tuas entranhas sair, este será o teu herdeiro". Deus então tira Abrão da sua tenda (o lugar da sua visão limitada) e o leva para fora, sob o céu noturno do deserto. Deus lhe dá uma ilustração visual da promessa: "Olha agora para os céus, e conta as estrelas, se as podes contar. E disse-lhe: Assim será a tua descendência". Deus não apenas promete um filho, mas uma nação inumerável. A promessa era biologicamente impossível para um homem idoso e uma mulher estéril; exigia um milagre de ressurreição de ventres mortos.',
    desc3: 'O versículo 6 é o clímax teológico da narrativa e o pilar da salvação no Antigo e no Novo Testamento: "E creu ele no Senhor, e imputou-lhe isto por justiça". Abrão não fez nenhuma obra, não ofereceu nenhum sacrifício, não foi circuncidado (isso aconteceria anos depois) e a Lei de Moisés ainda não existia. Ele simplesmente "creu" (a palavra hebraica aman, da qual deriva "amém", significa confiar, apoiar-se, considerar firme e verdadeiro) na promessa de Deus. Em resposta a essa fé, Deus "imputou-lhe" (creditou na sua conta) a justiça. Abrão não se tornou moralmente perfeito naquele momento, mas Deus o declarou legalmente justo com base na sua fé na promessa.',
    concl: 'Gênesis 15:6 é o texto que o apóstolo Paulo usa em Romanos 4 e Gálatas 3 para provar que a salvação sempre foi pela graça através da fé, e nunca pelas obras da lei. Assim como Abrão foi justificado por crer na promessa de Deus sobre o descendente que viria (Isaque, e em última análise, Cristo), nós somos justificados por crermos no Descendente que já veio, Jesus Cristo, que morreu pelos nossos pecados e ressuscitou para a nossa justificação.'
  },
  {
    id: 'exo_17_1_7',
    intro: 'O episódio da água da rocha em Refidim é uma das narrativas mais tensas e reveladoras sobre a rebelião de Israel e a paciência de Deus durante a jornada no deserto. O povo havia acabado de experimentar a provisão milagrosa do maná (capítulo 16), mas a fé deles continuava superficial e dependente das circunstâncias imediatas. Ao chegarem a Refidim, seguindo a direção da nuvem de Deus, eles não encontram água. A crise física rapidamente se transforma em um motim espiritual. Em vez de orar e confiar no Deus que abriu o Mar Vermelho, o povo ataca Moisés e questiona a própria presença de Deus no meio deles. A resposta de Deus a essa rebelião é um milagre que se tornaria um dos símbolos mais profundos da obra redentora de Cristo.',
    desc1: 'A crise começa com uma exigência agressiva: "Dá-nos água para beber". Moisés responde apontando para a raiz do problema: "Por que contendeis comigo? Por que tentais ao Senhor?". A murmuração do povo não era apenas uma reclamação sobre a sede; era um "tentar" a Deus, ou seja, colocar Deus no banco dos réus e exigir que Ele provasse o Seu amor e poder nos termos deles. A sede aumenta, e a murmuração se transforma em uma acusação irracional e letal: "Por que nos fizeste subir do Egito, para nos matares de sede, a nós e aos nossos filhos, e ao nosso gado?". O povo estava pronto para apedrejar Moisés. O medo e a incredulidade sempre procuram um bode expiatório humano para culpar pelos problemas.',
    desc2: 'Moisés, temendo pela sua vida, clama ao Senhor: "Que farei a este povo? Daqui a pouco me apedrejará". A resposta de Deus é surpreendente pela sua graça. Deus não envia fogo do céu para consumir os rebeldes. Ele ordena a Moisés: "Passa adiante do povo, e toma contigo alguns dos anciãos de Israel; e toma na tua mão a tua vara, com que feriste o rio, e vai". A vara que feriu o rio Nilo e trouxe juízo sobre o Egito agora seria usada para trazer salvação a Israel. Deus diz a Moisés: "Eis que eu estarei ali diante de ti sobre a rocha, em Horebe, e tu ferirás a rocha, e dela sairão águas e o povo beberá". A imagem é profunda: o próprio Deus se coloca sobre a rocha para receber o golpe da vara do juízo, a fim de que a água da vida flua para o povo rebelde.',
    desc3: 'Moisés obedece, fere a rocha na presença dos anciãos, e a água jorra abundantemente no deserto, saciando a sede de toda a nação e dos seus rebanhos. No entanto, o milagre não apaga a gravidade do pecado do povo. Moisés chama o nome daquele lugar de Massá (Tentação) e Meribá (Contenda), "por causa da contenda dos filhos de Israel, e porque tentaram ao Senhor, dizendo: Está o Senhor no meio de nós, ou não?". A maior tragédia de Refidim não foi a falta de água, mas a dúvida fundamental sobre a presença e a bondade de Deus. Eles queriam os benefícios de Deus sem confiar no caráter de Deus.',
    concl: 'O apóstolo Paulo revela o significado definitivo deste evento em 1 Coríntios 10:4: "E beberam todos de uma mesma bebida espiritual, porque bebiam da pedra espiritual que os seguia; e a pedra era Cristo". A rocha ferida em Refidim é um tipo de Cristo. Jesus foi ferido (crucificado) pela vara do juízo de Deus para que a água viva do Espírito Santo pudesse fluir e saciar a sede da humanidade rebelde. A graça de Deus sempre flui das feridas do Salvador.'
  },
  {
    id: 'jdg_16_15_22',
    intro: 'A queda de Sansão é uma das histórias mais trágicas de potencial desperdiçado em toda a Bíblia. Sansão foi o único juiz de Israel cujo nascimento foi anunciado por um anjo. Ele foi consagrado como nazireu desde o ventre materno (o que exigia abstenção de vinho, de tocar em cadáveres e de cortar o cabelo) e foi dotado pelo Espírito Santo com uma força física sobre-humana para libertar Israel dos filisteus. No entanto, Sansão era um homem de paixões descontroladas, que brincava constantemente com o pecado e com os seus votos. O capítulo 16 narra o clímax da sua rebelião: o seu relacionamento com Dalila, uma mulher filisteia subornada pelos líderes do seu povo para descobrir o segredo da sua força. A história de Sansão é um aviso aterrorizante sobre a cegueira espiritual e a perda da unção de Deus.',
    desc1: 'A narrativa atinge o seu ponto crítico quando Dalila, após três tentativas frustradas de descobrir o segredo de Sansão, usa a manipulação emocional extrema: "Como dirás: Tenho-te amor, não estando comigo o teu coração? Já três vezes zombaste de mim, e ainda me não declaraste em que consiste a tua força". Ela o importuna todos os dias com as suas palavras, até que a alma de Sansão se angustia "até a morte". Em vez de fugir da tentação (como José fez com a mulher de Potifar), Sansão cede à pressão e revela todo o seu coração: "Nunca passou navalha pela minha cabeça, porque sou nazireu de Deus desde o ventre de minha mãe; se vier a ser rapado, ir-se-á de mim a minha força". O cabelo não era a fonte mágica da força, mas o símbolo da sua consagração a Deus. Ao entregar o segredo, Sansão estava entregando a sua aliança.',
    desc2: 'Dalila percebe que ele finalmente falou a verdade. Ela chama os príncipes dos filisteus, recebe o dinheiro do suborno e faz Sansão dormir no seu colo. Ela chama um homem para cortar as sete tranças do cabelo de Sansão. O texto diz: "e começou a afligi-lo, e retirou-se dele a sua força". O pecado sempre promete prazer e descanso (o colo de Dalila), mas entrega aflição e fraqueza. Dalila então grita: "Os filisteus vêm sobre ti, Sansão!". Sansão acorda do sono e diz a frase mais trágica da sua vida: "Sairei ainda esta vez como dantes, e me sacudirei". Ele achava que podia continuar pecando e mantendo o poder de Deus. Mas o texto revela a terrível realidade: "Porque ele não sabia que já o Senhor se tinha retirado dele". A perda da presença de Deus é frequentemente silenciosa e imperceptível para quem está entorpecido pelo pecado.',
    desc3: 'As consequências da desobediência são imediatas e brutais. Os filisteus o prendem, arrancam-lhe os olhos (a cegueira física reflete a cegueira espiritual que o levou até ali) e o levam para Gaza amarrado com duas cadeias de bronze. O grande libertador de Israel é reduzido a um escravo, forçado a girar um moinho na prisão como um animal. O pecado o cegou, o prendeu e o moeu. No entanto, o versículo 22 oferece um vislumbre de esperança e graça no meio do juízo: "E o cabelo da sua cabeça começou a crescer, como quando foi rapado". O crescimento do cabelo simboliza o início do arrependimento de Sansão e a disposição de Deus de restaurar a Sua força para um último ato de redenção.',
    concl: 'A queda de Sansão nos adverte que a unção e os dons espirituais não são garantia de caráter. Podemos ter grande poder nas mãos, mas se não tivermos domínio próprio no coração, o pecado nos destruirá. A história nos ensina que não podemos brincar com a tentação e presumir que a graça de Deus nos protegerá das consequências das nossas escolhas. A força verdadeira não está nos músculos, mas na santidade e na obediência a Deus.'
  },
  {
    id: '2sa_12_1_13',
    intro: 'O confronto do profeta Natã com o rei Davi é um dos momentos mais dramáticos de exposição do pecado e de arrependimento na Bíblia. Cerca de um ano havia se passado desde que Davi cometeu adultério com Bate-Seba e orquestrou o assassinato do marido dela, Urias, o heteu, para encobrir a gravidez. Davi casou-se com Bate-Seba e o filho nasceu. Aos olhos do povo e da corte, Davi parecia ter escapado impune. Ele havia silenciado a sua consciência e continuava a governar e a adorar como se nada tivesse acontecido. No entanto, o texto anterior termina com a frase: "Porém esta coisa que Davi fez pareceu mal aos olhos do Senhor". Deus não ignora o pecado dos Seus filhos. Ele envia o profeta Natã com uma parábola brilhante para perfurar a armadura de autojustificação do rei e levá-lo ao arrependimento.',
    desc1: 'Natã não entra na sala do trono acusando Davi diretamente (o que poderia resultar na morte do profeta). Em vez disso, ele conta uma história sobre uma injustiça local. Havia dois homens numa cidade: um rico, com muitíssimas ovelhas e vacas, e um pobre, que tinha apenas uma pequena cordeira, que ele havia comprado, criado com os seus filhos e que comia do seu pão e bebia do seu copo, sendo para ele "como uma filha". Quando um viajante chega à casa do homem rico, em vez de pegar uma das suas muitas ovelhas para o banquete, o rico rouba a única cordeira do homem pobre e a prepara para o seu hóspede. A parábola é projetada para despertar o senso de justiça de Davi, que no fundo ainda era um pastor de ovelhas.',
    desc2: 'A reação de Davi à história é imediata e furiosa. O seu senso de justiça, que estava adormecido para o seu próprio pecado, desperta violentamente para o pecado do outro. O texto diz: "Então o furor de Davi se acendeu em grande maneira contra aquele homem". Davi profere a sentença: "Vive o Senhor, que digno de morte é o homem que fez isso. E pela cordeira tornará a dar o quadruplicado, porque fez tal obra, e porque não se compadeceu". Davi julga o homem rico com a severidade da Lei. É nesse momento exato, quando Davi está cheio de indignação justa, que Natã aponta o dedo para o rei e profere a frase mais devastadora: "Tu és este homem". A parábola era um espelho. O rico era Davi (com as suas muitas esposas); o pobre era Urias; a cordeira era Bate-Seba.',
    desc3: 'Natã então entrega a mensagem de juízo de Deus. Deus lembra Davi de toda a graça que lhe havia sido dada (a unção, o livramento de Saul, o trono de Israel) e pergunta: "Por que, pois, desprezaste a palavra do Senhor, fazendo o mal diante de seus olhos?". O pecado de Davi não foi apenas contra Urias e Bate-Seba; foi um desprezo direto a Deus. Natã profetiza que a espada jamais se apartaria da casa de Davi e que o mal se levantaria da sua própria família (profecias que se cumpriram tragicamente com Amnom, Absalão e Adonias). Diante da exposição total do seu pecado, Davi não dá desculpas, não culpa Bate-Seba e não tenta matar o profeta. Ele simplesmente confessa: "Pequei contra o Senhor". A resposta de Natã é imediata: "Também o Senhor perdoou o teu pecado; não morrerás".',
    concl: 'O confronto de Natã nos ensina que é incrivelmente fácil sermos cegos para os nossos próprios pecados enquanto julgamos severamente os pecados dos outros. O pecado não confessado endurece o coração, mas a Palavra de Deus, como uma espada, é capaz de perfurar a nossa hipocrisia. A história também revela a grandeza da graça de Deus: o arrependimento genuíno e imediato de Davi (expresso no Salmo 51) trouxe o perdão imediato de Deus, embora as consequências terrenas do seu pecado permanecessem.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 26');
