const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: '1th_4_13_18',
    intro: 'A Primeira Epístola aos Tessalonicenses foi escrita para uma igreja jovem que estava enfrentando perseguição e confusão teológica. Paulo havia ensinado sobre a iminente volta de Cristo (a Parousia), mas, após a sua partida, alguns membros da igreja morreram. A congregação entrou em pânico e luto profundo, temendo que os cristãos falecidos perdessem a glória do retorno de Jesus e o Reino futuro. O capítulo 4 (versículos 13 a 18) é a resposta pastoral e teológica de Paulo a esse medo. Ele não escreve para satisfazer a curiosidade escatológica, mas para trazer consolo, revelando a ordem dos eventos da ressurreição e garantindo que a morte não pode separar nenhum crente da vitória final de Cristo.',
    desc1: 'Paulo começa abordando a natureza do luto cristão: "Não quero, porém, irmãos, que sejais ignorantes acerca dos que já dormem, para que não vos entristeçais, como os demais, que não têm esperança". Paulo não proíbe a tristeza (o luto é uma resposta natural à perda e ao amor), mas proíbe o luto "sem esperança" que caracterizava o mundo pagão. Para os pagãos, a morte era o fim absoluto ou uma jornada para um submundo sombrio. Para os cristãos, a morte é descrita como um "sono" (uma metáfora para o descanso do corpo, não da alma, que está consciente com Cristo), implicando que haverá um despertar. A base dessa esperança é histórica: "Porque, se cremos que Jesus morreu e ressuscitou, assim também aos que em Jesus dormem, Deus os tornará a trazer com ele".',
    desc2: 'Paulo então revela a ordem dos eventos do arrebatamento, baseada na "palavra do Senhor" (uma revelação direta). Ele garante que os vivos não terão nenhuma vantagem sobre os mortos: "nós, os que ficarmos vivos para a vinda do Senhor, não precederemos os que dormem". A descrição da descida de Cristo é majestosa e audível: "Porque o mesmo Senhor descerá do céu com alarido, e com voz de arcanjo, e com a trombeta de Deus". O retorno de Jesus não será um evento secreto ou silencioso, mas uma invasão cósmica gloriosa. O primeiro evento dessa invasão é a ressurreição: "e os que morreram em Cristo ressuscitarão primeiro". Os corpos dos crentes falecidos serão ressuscitados e glorificados antes de qualquer outra coisa acontecer.',
    desc3: 'Imediatamente após a ressurreição dos mortos, ocorre a transformação e o arrebatamento dos vivos: "Depois nós, os que ficarmos vivos, seremos arrebatados juntamente com eles nas nuvens, a encontrar o Senhor nos ares". A palavra "arrebatados" (harpazo) significa ser agarrado ou levado com força repentina. Os vivos e os ressuscitados serão reunidos (a grande reunião familiar da Igreja) para encontrar o Senhor nos ares. O encontro nos ares reflete a prática antiga onde os cidadãos saíam da cidade para receber um rei vitorioso e escoltá-lo de volta. O clímax não é apenas o evento, mas o estado eterno: "e assim estaremos sempre com o Senhor". Paulo conclui com o propósito de toda essa revelação: "Portanto, consolai-vos uns aos outros com estas palavras".',
    concl: '1 Tessalonicenses 4 nos ensina que a escatologia bíblica não foi dada para criar debates teológicos ou gráficos do fim dos tempos, mas para produzir esperança e consolo. A morte não é o fim da história para o crente, nem o exclui da glória futura. A promessa do arrebatamento nos garante que a morte será derrotada, a Igreja será reunida e nós estaremos para sempre na presença do nosso Salvador.'
  },
  {
    id: '2ti_3_1_17',
    intro: 'A Segunda Epístola a Timóteo é o testamento final do apóstolo Paulo. Ele está preso em Roma, em uma masmorra fria e úmida, aguardando a sua execução iminente por ordem do imperador Nero. A maioria dos seus amigos o abandonou. Neste contexto de isolamento e morte iminente, Paulo escreve ao seu jovem discípulo Timóteo (que pastoreava a difícil igreja de Éfeso) para encorajá-lo a permanecer firme. O capítulo 3 é uma advertência profética sobre a corrupção moral e religiosa que caracterizaria os "últimos dias" (o período entre a primeira e a segunda vinda de Cristo). Diante dessa avalanche de falsidade e perseguição, Paulo aponta para a única âncora segura e inabalável para o ministério e para a vida cristã: a suficiência e a inspiração da Palavra de Deus.',
    desc1: 'Paulo começa com um diagnóstico sombrio dos "últimos dias", descrevendo-os como "tempos trabalhosos" (ou difíceis, perigosos). Ele não prevê uma utopia onde o mundo melhora gradualmente, mas uma decadência moral profunda. Ele lista 19 características dessa corrupção, começando com "homens amantes de si mesmos, avarentos, presunçosos, soberbos". A raiz de todo o mal na lista é o amor distorcido: amor a si mesmo, amor ao dinheiro e "mais amigos dos deleites do que amigos de Deus". O perigo maior, no entanto, não é o paganismo secular, mas a hipocrisia religiosa: "Tendo aparência de piedade, mas negando a eficácia dela". Esses falsos mestres se infiltram nas igrejas (e nas casas) e resistem à verdade, assim como Janes e Jambres resistiram a Moisés.',
    desc2: 'Em contraste com os falsos mestres, Paulo lembra Timóteo do seu próprio exemplo de vida e sofrimento: "Tu, porém, tens seguido a minha doutrina, modo de viver, intenção, fé, longanimidade, amor, paciência, perseguições e aflições". Paulo não esconde o custo do discipulado. Ele garante que a perseguição não é uma anomalia, mas a norma: "E também todos os que piamente querem viver em Cristo Jesus padecerão perseguições". A piedade atrai a hostilidade de um mundo impiedoso. Enquanto os homens maus e enganadores irão de mal a pior, a ordem para Timóteo é a perseverança: "Tu, porém, permanece naquilo que aprendeste, e de que foste inteirado, sabendo de quem o tens aprendido".',
    desc3: 'A base dessa perseverança é a Escritura. Paulo lembra que Timóteo conhece as "sagradas letras" desde a infância, as quais podem fazê-lo "sábio para a salvação, pela fé que há em Cristo Jesus". Então, Paulo profere a declaração definitiva sobre a natureza da Bíblia (v. 16-17): "Toda a Escritura é divinamente inspirada (theopneustos, soprada por Deus)". A Bíblia não é uma coleção de ideias humanas sobre Deus, mas a própria respiração de Deus. Por ser inspirada, ela é totalmente proveitosa para quatro coisas: ensinar (doutrina), redarguir (repreender o erro), corrigir (restaurar ao caminho certo) e instruir em justiça (treinar para a santidade). O objetivo final é "para que o homem de Deus seja perfeito (maduro, completo), e perfeitamente instruído para toda a boa obra".',
    concl: '2 Timóteo 3 nos adverte que não devemos nos surpreender com a corrupção moral do mundo ou com a hipocrisia dentro da igreja. A nossa resposta a tempos difíceis não deve ser o pânico ou a inovação teológica, mas um retorno radical à suficiência da Escritura. A Palavra soprada por Deus é a única ferramenta capaz de nos salvar, nos santificar e nos equipar completamente para qualquer obra que Ele nos chame a fazer.'
  },
  {
    id: 'heb_12_1_13',
    intro: 'O capítulo 12 de Hebreus é a aplicação prática e vigorosa do majestoso capítulo 11 (a Galeria da Fé). Após desfilar os heróis do Antigo Testamento que viveram e morreram confiando nas promessas de Deus, o autor muda a metáfora de uma galeria de arte para um estádio olímpico. Ele convoca os cristãos (que estavam exaustos e tentados a desistir devido à perseguição) a entrarem na pista de corrida. A vida cristã não é descrita como um passeio tranquilo ou uma corrida de cem metros rasos, mas como uma maratona extenuante que exige resistência, disciplina e, acima de tudo, um foco absoluto no exemplo supremo: Jesus Cristo. O autor também aborda o tema difícil da disciplina divina, mostrando que o sofrimento não é um sinal de abandono, mas a prova do amor paternal de Deus.',
    desc1: 'A corrida começa com uma dupla preparação (v. 1): "Portanto nós também, pois que estamos rodeados de uma tão grande nuvem de testemunhas, deixemos todo o embaraço, e o pecado que tão de perto nos rodeia, e corramos com paciência a carreira que nos está proposta". A "nuvem de testemunhas" não são espectadores no céu torcendo por nós, mas os heróis do capítulo 11 cujo testemunho de vida nos encoraja a perseverar. Para correr bem, precisamos nos despir de duas coisas: o "pecado" (a desobediência direta) e o "embaraço" (pesos que não são necessariamente pecados, mas distrações, apegos ou ansiedades que nos atrasam). A corrida exige "paciência" (hupomone, resistência ativa sob pressão).',
    desc2: 'O segredo da resistência é o foco (v. 2-3): "Olhando para Jesus, autor e consumador da fé". Não devemos olhar para as circunstâncias, para os outros corredores ou para nós mesmos, mas exclusivamente para Jesus. Ele é o "autor" (o pioneiro que abriu o caminho) e o "consumador" (o aperfeiçoador) da nossa fé. Jesus correu a Sua própria corrida suportando a cruz e desprezando a afronta, motivado pela "alegria que lhe estava proposta" (a glória da salvação e a exaltação à destra de Deus). O autor exorta os crentes a "considerarem" (pensarem profundamente) em Jesus e na oposição que Ele suportou dos pecadores, para que não "enfraqueçam, desmaiando em vossos ânimos". O antídoto para a exaustão espiritual é a contemplação da cruz.',
    desc3: 'A partir do versículo 4, o autor muda o foco para a disciplina de Deus. Os crentes estavam sofrendo, mas ainda não haviam "resistido até ao sangue" (martírio). Eles haviam esquecido a exortação de Provérbios 3: "Filho meu, não desprezes a correção do Senhor... Porque o Senhor corrige o que ama, e açoita a qualquer que recebe por filho". O sofrimento na vida do crente não é o juízo de um juiz irado, mas a disciplina (treinamento, educação) de um Pai amoroso. Se não fôssemos disciplinados, seríamos bastardos, não filhos. A disciplina no momento parece ser motivo de tristeza, mas "depois produz um fruto pacífico de justiça nos exercitados por ela". O autor conclui convocando-os a levantar as mãos cansadas e os joelhos vacilantes, e a fazer caminhos retos para os seus pés.',
    concl: 'Hebreus 12 nos ensina que a vida cristã é uma maratona de resistência que não pode ser vencida se carregarmos o peso do pecado ou as distrações do mundo. Quando a perseguição ou a disciplina de Deus nos deixarem exaustos, não devemos desistir. Devemos fixar os nossos olhos em Jesus, lembrando que o sofrimento presente é o treinamento do Pai para produzir em nós a santidade e a justiça eternas.'
  },
  {
    id: 'exo_14_10_31',
    intro: 'A travessia do Mar Vermelho é o evento redentor central do Antigo Testamento, o momento em que Deus liberta definitivamente Israel da escravidão egípcia. Após as dez pragas, Faraó havia deixado o povo ir, mas logo mudou de ideia e perseguiu-os com todo o poder militar do Egito (seiscentos carros escolhidos e cavaleiros). Deus havia guiado Israel intencionalmente para um beco sem saída: o deserto de um lado, as montanhas do outro, o Mar Vermelho à frente e o exército mais poderoso do mundo atrás. Este cenário impossível não foi um erro de navegação divina, mas uma armadilha orquestrada por Deus para destruir o poder do Egito, expor a incredulidade de Israel e demonstrar a Sua própria glória salvadora de forma inegável.',
    desc1: 'Quando os israelitas veem o exército de Faraó se aproximando, o pânico se instala. A fé que eles tinham ao sair do Egito evapora diante da ameaça visível. Eles clamam ao Senhor, mas imediatamente se voltam contra Moisés com sarcasmo e desespero: "Não havia sepulcros no Egito, para nos tirares de lá, para que morramos neste deserto? ... Melhor nos fora servir aos egípcios, do que morrermos no deserto". O medo distorce a realidade, fazendo a escravidão parecer melhor do que a liberdade que exige fé. Moisés responde com uma das maiores declarações de fé da Bíblia: "Não temais; estai quietos, e vede o livramento do Senhor... O Senhor pelejará por vós, e vós vos calareis". A salvação não viria do esforço humano, mas da intervenção exclusiva de Deus.',
    desc2: 'A resposta de Deus a Moisés é surpreendente: "Por que clamas a mim? Dize aos filhos de Israel que marchem". Havia um tempo para orar e um tempo para agir em obediência. Deus ordena que Moisés levante a sua vara e estenda a mão sobre o mar para dividi-lo. Durante a noite, o Anjo de Deus e a coluna de nuvem, que iam adiante de Israel, movem-se para trás, colocando-se entre o acampamento de Israel e o dos egípcios. Para os egípcios, a nuvem era escuridão; para Israel, era luz. Deus protege o Seu povo enquanto prepara o milagre. Um forte vento oriental sopra a noite toda, dividindo as águas e secando o fundo do mar. Israel atravessa a seco, com as águas formando "um muro à sua direita e à sua esquerda".',
    desc3: 'Os egípcios, cegos pela arrogância e pelo ódio, perseguem Israel para dentro do mar seco. Na vigília da manhã, o Senhor "olhou para o campo dos egípcios" através da coluna de fogo e nuvem, e os perturbou. Ele tirou as rodas dos seus carros, fazendo-os andar com dificuldade. Os egípcios entram em pânico e reconhecem a derrota: "Fujamos da face de Israel, porque o Senhor por eles peleja contra os egípcios". Mas já era tarde. Deus ordena a Moisés que estenda a mão novamente. As águas retornam com força total ao amanhecer, cobrindo os carros, os cavaleiros e todo o exército de Faraó. "Não ficou nem sequer um deles". Israel vê os egípcios mortos na praia, teme ao Senhor e crê nEle e no Seu servo Moisés.',
    concl: 'A travessia do Mar Vermelho nos ensina que Deus frequentemente nos conduz a "becos sem saída" na vida para nos mostrar que a nossa salvação não depende dos nossos recursos, mas do Seu poder. Quando o inimigo nos persegue e o mar está à nossa frente, somos chamados a parar de murmurar, ficar quietos, confiar que o Senhor pelejará por nós e marchar em obediência quando Ele abrir o caminho.'
  },
  {
    id: '1sa_17_32_51',
    intro: 'A história de Davi e Golias é, sem dúvida, a narrativa de batalha mais famosa da Bíblia e um dos maiores arquétipos literários de todos os tempos (o fraco derrotando o forte). O exército de Israel, liderado pelo rei Saul, estava paralisado de medo no Vale de Elá. Durante quarenta dias, Golias, um gigante filisteu de quase três metros de altura, fortemente armado e experiente na guerra, desafiava os exércitos de Israel para um combate individual. Ninguém ousava enfrentá-lo. É nesse cenário de covardia nacional e humilhação do nome de Deus que Davi, um jovem pastor de ovelhas que estava ali apenas para entregar comida aos seus irmãos, se voluntaria para a batalha. A vitória de Davi não é uma história de autoajuda sobre "acreditar em si mesmo", mas uma demonstração teológica de que a batalha pertence ao Senhor.',
    desc1: 'Davi apresenta-se a Saul e diz: "Não desfaleça o coração de ninguém por causa dele; teu servo irá, e pelejará contra este filisteu". Saul, olhando com a visão natural, rejeita a ideia: "tu és ainda moço, e ele homem de guerra desde a sua mocidade". Davi não argumenta com base na sua força, mas no seu currículo de fé invisível. Ele conta como, enquanto cuidava das ovelhas do seu pai, matou um leão e um urso que tentaram roubar o rebanho. Davi atribui essas vitórias não à sua habilidade, mas a Deus: "O Senhor me livrou das garras do leão, e das do urso; ele me livrará da mão deste filisteu". A fidelidade nas pequenas batalhas ocultas (no pasto) prepara o crente para as grandes batalhas públicas (no vale).',
    desc2: 'Saul tenta vestir Davi com a sua própria armadura real. Davi tenta andar, mas não consegue, e rejeita a armadura: "Não posso andar com isto, pois não o experimentei". Davi recusa-se a lutar a batalha de Deus usando as armas e os métodos do mundo. Ele pega o que conhece: o seu cajado de pastor, cinco pedras lisas do ribeiro e a sua funda. Quando Golias vê Davi, ele o despreza e o amaldiçoa pelos seus deuses. A resposta de Davi (v. 45-47) é o coração teológico da história: "Tu vens a mim com espada, e com lança, e com escudo; porém eu venho a ti em nome do Senhor dos Exércitos, o Deus dos exércitos de Israel, a quem tens afrontado". Davi muda o foco da batalha: não era Davi contra Golias, mas Golias contra o Deus Todo-Poderoso.',
    desc3: 'Davi declara o propósito da vitória antes mesmo de lançar a pedra: "para que toda a terra saiba que há Deus em Israel; e saberá toda esta congregação que o Senhor salva, não com espada, nem com lança; porque do Senhor é a guerra". Davi não recua de medo; ele corre em direção ao gigante. Ele coloca uma pedra na funda, atira e atinge Golias exatamente na testa (o único lugar desprotegido pela armadura). A pedra afunda na testa, e o gigante cai com o rosto em terra. Como Davi não tinha espada, ele pega a própria espada de Golias e corta a cabeça do gigante. Vendo o seu campeão morto, os filisteus fogem, e o exército de Israel, antes paralisado pelo medo, levanta-se com um grito de vitória e os persegue.',
    concl: 'A vitória de Davi sobre Golias nos ensina que os "gigantes" que enfrentamos (problemas, vícios, oposição) não são derrotados pelas armas da carne ou pelas estratégias do mundo. Eles são derrotados quando enfrentamos a batalha em nome do Senhor dos Exércitos, confiando que a guerra pertence a Ele. Nós não somos Davi nesta história; Jesus é o nosso verdadeiro Davi, que derrotou o gigante do pecado e da morte, e nós, como o exército de Israel, apenas corremos atrás dEle para desfrutar da vitória que Ele conquistou.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 31');
