const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'isa_6_1_8',
    intro: 'A visão de Isaías no capítulo 6 é um dos relatos mais impressionantes sobre a santidade de Deus em toda a Bíblia. Ocorre em um momento de crise nacional: "No ano em que morreu o rei Uzias". Uzias havia reinado por 52 anos, trazendo estabilidade e prosperidade, mas morreu leproso por causa de seu orgulho. Quando o trono terreno fica vazio e a nação teme o futuro, Isaías é levado em visão ao Templo celestial para ver o Rei eterno que nunca morre e cujo trono jamais fica vazio. Esta visão da santidade absoluta de Deus transforma completamente a vida, a teologia e o ministério do profeta.',
    desc1: 'A visão começa com a majestade transcendente de Deus. Ele está assentado sobre um "alto e sublime trono", e as abas de Suas vestes enchem o Templo, simbolizando Sua glória onipresente. Acima dEle estão os serafins (literalmente, "os ardentes"), seres angelicais de fogo. Com duas asas eles voam (prontidão para servir), com duas cobrem os pés (humildade) e com duas cobrem o rosto (reverência, pois nem mesmo anjos sem pecado podem contemplar a glória nua de Deus). Eles clamam uns para os outros: "Santo, Santo, Santo é o Senhor dos Exércitos". É o único atributo de Deus elevado à terceira potência na Bíblia, indicando perfeição absoluta e separação total de tudo o que é criado ou pecaminoso.',
    desc2: 'A reação de Isaías à visão da santidade não é de fascínio, mas de terror absoluto. Ele grita: "Ai de mim! Estou perdido! Porque sou um homem de lábios impuros... e os meus olhos viram o Rei". A luz da santidade de Deus expõe a escuridão do coração humano. Isaías, que era o melhor homem de Judá, sente-se totalmente condenado diante de Deus. No entanto, o reconhecimento do pecado é imediatamente seguido pela provisão da graça. Um serafim voa com uma brasa viva tirada do altar (o lugar do sacrifício e da expiação) e toca os lábios do profeta, declarando: "A tua iniquidade foi tirada, e perdoado, o teu pecado". A purificação vem do altar de Deus, não do esforço humano.',
    desc3: 'Apenas após ser confrontado com a santidade, quebrantado pelo seu pecado e purificado pela graça, Isaías está pronto para ouvir a voz de Deus. A Trindade faz uma pergunta que ecoa pela eternidade: "A quem enviarei, e quem há de ir por nós?". A resposta de Isaías não é baseada em suas habilidades, mas na gratidão pela graça recebida. Ele não pergunta para onde vai, qual será o salário ou o tamanho do desafio. Sua resposta é imediata, incondicional e voluntária: "Eis-me aqui, envia-me a mim".',
    concl: 'A verdadeira adoração sempre culmina em missão. Um encontro genuíno com a santidade de Deus destrói o nosso orgulho, produz um arrependimento profundo e gera uma disposição radical para servir. Não podemos dizer "Eis-me aqui" para o mundo até que tenhamos dito "Ai de mim" diante de Deus e experimentado o toque purificador da Sua graça.'
  },
  {
    id: 'mt_6_5_15',
    intro: 'No coração do Sermão do Monte, Jesus aborda a prática mais fundamental da vida espiritual: a oração. No entanto, Ele não ensina apenas "como" orar, mas ataca frontalmente as motivações erradas que corrompem a oração. Ele contrasta a oração hipócrita dos fariseus (que oravam para serem vistos pelos homens) e a oração mecânica dos gentios (que usavam vãs repetições achando que seriam ouvidos pelo muito falar) com a oração autêntica de um filho que se dirige ao seu Pai. O "Pai Nosso" não foi dado como uma reza mágica para ser repetida sem pensar, mas como um esqueleto teológico, um modelo perfeito que deve moldar as prioridades e o conteúdo de todas as nossas orações.',
    desc1: 'Jesus começa corrigindo a motivação. A oração não é um show de piedade para impressionar os outros, nem uma técnica de persuasão para torcer o braço de Deus. É um encontro secreto e íntimo com o "Pai que vê em secreto". A promessa é que o Pai, que vê o que está oculto, recompensará publicamente. Além disso, Jesus nos liberta da ansiedade de ter que usar palavras bonitas ou longas repetições, lembrando-nos de uma verdade consoladora: "Vosso Pai sabe o que vos é necessário, antes de vós lho pedirdes". A oração não é para informar Deus, mas para alinhar nosso coração a Ele.',
    desc2: 'A primeira metade do Pai Nosso é radicalmente teocêntrica; o foco está inteiramente em Deus e na Sua glória. Começa com intimidade ("Pai nosso") e reverência ("que estás nos céus"). As três primeiras petições são: 1) "Santificado seja o teu nome" (que o caráter de Deus seja reverenciado e honrado no mundo e em nós); 2) "Venha o teu Reino" (que o governo e a autoridade de Deus se estabeleçam, destruindo as obras do diabo); 3) "Seja feita a tua vontade, assim na terra como no céu" (a submissão total dos nossos desejos aos propósitos perfeitos de Deus). Antes de pedirmos qualquer coisa para nós, devemos buscar a glória dEle.',
    desc3: 'A segunda metade do Pai Nosso volta-se para as necessidades humanas, mostrando que Deus se importa com a nossa totalidade. Pedimos o "pão nosso de cada dia", reconhecendo nossa dependência diária de Deus para a provisão física (não o pão para o ano todo, mas para hoje). Pedimos perdão ("perdoa-nos as nossas dívidas"), mas com uma condição assustadora: "assim como nós perdoamos aos nossos devedores". Jesus atrela o perdão que recebemos à nossa disposição de perdoar os outros. Por fim, pedimos proteção espiritual: "não nos deixes cair em tentação, mas livra-nos do mal" (ou do Maligno), reconhecendo nossa fraqueza diante do inimigo.',
    concl: 'O Pai Nosso nos ensina que a oração verdadeira equilibra a adoração mais profunda com a dependência mais básica. Ela nos eleva às realidades celestiais (o Nome, o Reino, a Vontade) sem nos desconectar das necessidades terrenas (o pão, o perdão, a proteção). Orar o Pai Nosso é declarar que a nossa vida, do sustento físico à vitória espiritual, depende inteiramente da graça do Pai.'
  },
  {
    id: 'mt_28_16_20',
    intro: 'A Grande Comissão é o clímax do Evangelho de Mateus e a ordem de marcha definitiva para a Igreja de Cristo. Proferida pelo Jesus ressurreto em uma montanha na Galileia, estas palavras não são uma sugestão, um conselho ou uma opção para cristãos super-espirituais; elas são o mandato imperativo para todo aquele que se chama discípulo. É o momento em que Jesus transfere a responsabilidade da missão para os Seus seguidores, definindo o propósito da existência da Igreja na terra até o fim dos tempos.',
    desc1: 'A base e o fundamento da missão não residem na capacidade, na eloquência ou nos recursos da Igreja, mas na autoridade absoluta do Cristo ressurreto. Jesus declara: "Toda a autoridade me foi dada no céu e na terra". Ele é o Rei cósmico, o Senhor soberano sobre todas as nações, governos, anjos e demônios. É por causa desse "Portanto" (baseado na Sua autoridade) que a Igreja tem o direito e a ousadia de ir a todas as nações e exigir que os homens se submetam ao senhorio de Cristo. Nós não vamos em nosso próprio nome, mas como embaixadores do Rei do universo.',
    desc2: 'O núcleo da Grande Comissão é um único verbo no imperativo no texto grego: "fazei discípulos" (matheteusate). Os outros três verbos (indo, batizando e ensinando) são particípios que explicam como fazer discípulos. Fazer discípulos envolve: 1) "Ir" (cruzar fronteiras geográficas, culturais e sociais para alcançar os perdidos); 2) "Batizar em nome do Pai, do Filho e do Espírito Santo" (integrar o novo convertido na comunidade da fé e na comunhão da Trindade através de um testemunho público); 3) "Ensinar a guardar todas as coisas" (não apenas transmitir conhecimento teológico, mas treinar para a obediência prática e a transformação de vida).',
    desc3: 'A missão de alcançar todas as nações é humanamente impossível. Ela envolve perseguição, rejeição, barreiras culturais e guerra espiritual. Sabendo disso, Jesus não envia Seus discípulos sozinhos. Ele encerra o Evangelho com a maior e mais consoladora de todas as promessas: "E eis que eu estou convosco todos os dias, até a consumação do século". A presença do "Emanuel" (Deus conosco), prometida no capítulo 1 de Mateus, é agora garantida para sempre à Igreja que obedece ao Seu chamado. A autoridade de Cristo nos envia, e a presença de Cristo nos sustenta.',
    concl: 'A Igreja não existe para si mesma; ela existe para a missão. Fazer discípulos não é um departamento da igreja, é a sua essência. Uma igreja que não evangeliza, não batiza e não ensina a obediência está em desobediência direta ao seu Senhor. O nosso chamado é levar o Evangelho até os confins da terra, confiando que o Rei que nos enviou marchará conosco até o fim.'
  },
  {
    id: 'jn_3_1_21',
    intro: 'O encontro noturno entre Jesus e Nicodemos é um dos diálogos mais teológicos e reveladores do Novo Testamento. Nicodemos não era um pecador comum; ele era um fariseu, um membro do Sinédrio (a suprema corte judaica) e "o mestre em Israel". Ele representava o ápice da religião, da moralidade e do conhecimento teológico de sua época. Ele procura Jesus à noite (talvez por medo ou para ter uma conversa ininterrupta) e começa com um elogio polido. Jesus, no entanto, corta as amenidades e lança uma bomba teológica que destrói a confiança na religião humana: a necessidade absoluta e inegociável do Novo Nascimento.',
    desc1: 'Jesus declara com autoridade divina: "Em verdade, em verdade te digo que se alguém não nascer de novo (ou nascer do alto), não pode ver o reino de Deus". Nicodemos, preso à lógica física, pergunta como um homem velho pode voltar ao ventre materno. Jesus esclarece que o nascimento físico ("o que é nascido da carne é carne") só produz natureza humana caída. Para entrar no Reino espiritual, é necessário um nascimento espiritual ("nascer da água e do Espírito"). A salvação não é uma questão de reforma moral, de aprender novas regras ou de melhorar a velha natureza; é uma recriação radical, uma obra soberana e misteriosa do Espírito Santo, invisível como o vento, mas inegável em seus efeitos.',
    desc2: 'Diante da perplexidade de Nicodemos ("Como pode ser isso?"), Jesus o repreende por ser mestre em Israel e não entender as Escrituras (que já prometiam um novo coração, como em Ezequiel 36). Jesus então aponta para a cruz como o meio pelo qual esse novo nascimento é possível. Ele usa uma ilustração do Antigo Testamento (Números 21): assim como Moisés levantou a serpente de bronze no deserto para que os israelitas picados por cobras olhassem e fossem curados, o Filho do Homem precisava ser "levantado" (crucificado) para que todo o que nEle crê tenha a vida eterna. A cura vem por olhar com fé para o sacrifício de Cristo.',
    desc3: 'O diálogo culmina no versículo mais famoso da Bíblia, João 3:16, que resume a essência do Evangelho. A motivação da salvação é o amor insondável de Deus ("Porque Deus amou o mundo de tal maneira"). A ação da salvação é o sacrifício supremo ("que deu o seu Filho unigênito"). A condição da salvação é a fé ("para que todo aquele que nele crê"). O resultado da salvação é a libertação da condenação e a posse da vida eterna ("não pereça, mas tenha a vida eterna"). Jesus deixa claro que Ele não veio para condenar o mundo, mas a condenação já existe para aqueles que amam as trevas e rejeitam a Luz.',
    concl: 'A conversa com Nicodemos estabelece que a religião, a moralidade e o conhecimento teológico, por melhores que sejam, não podem salvar ninguém. O céu não é para pessoas "boas", mas para pessoas "novas". Precisamos de uma nova natureza que não podemos produzir por nós mesmos; ela é um dom da graça, recebido pela fé no Cristo crucificado e operado pelo poder do Espírito Santo.'
  },
  {
    id: 'jn_15_1_17',
    intro: 'No caminho para o Getsêmani, poucas horas antes de Sua prisão, Jesus profere o Seu último grande discurso aos discípulos, conhecido como a alegoria da Videira Verdadeira. No Antigo Testamento, Israel era frequentemente comparado a uma videira que Deus plantou, mas que repetidamente produziu uvas bravas e falhou em seu propósito. Agora, Jesus declara: "Eu sou a videira verdadeira". Ele é o cumprimento de tudo o que Israel falhou em ser. Esta passagem é a mais profunda e bela explicação sobre a natureza da vida cristã: uma união vital, orgânica e ininterrupta com Cristo, que é a única fonte de vida e frutificação.',
    desc1: 'Jesus estabelece os personagens da alegoria: Ele é a Videira (a fonte de vida e seiva), o Pai é o Agricultor (aquele que cuida, limpa e disciplina) e os discípulos são os ramos. O propósito da videira não é produzir madeira, mas fruto. O Pai realiza duas ações distintas: Ele corta e lança fora os ramos que não dão fruto (falsos discípulos, como Judas, que têm aparência de conexão, mas não têm vida), e Ele "limpa" (poda) os ramos que dão fruto. A poda divina (através de provações, da Palavra e da disciplina) é dolorosa, mas é a prova do amor do Pai para que o ramo produza "mais fruto".',
    desc2: 'O imperativo central do texto é repetido várias vezes: "Permanecei em mim". A vida cristã não é baseada no esforço independente, mas na dependência contínua. Jesus é categórico: "Como o ramo de si mesmo não pode dar fruto... assim também vós, se não permanecerdes em mim... porque sem mim nada podeis fazer". Separados de Cristo, podemos fazer atividades religiosas, mas não podemos produzir fruto espiritual eterno. A promessa para aqueles que permanecem nEle e têm a Sua Palavra permanecendo neles é extraordinária: orações respondidas, muito fruto e a glorificação do Pai.',
    desc3: 'Nos versículos finais, Jesus explica o que significa "permanecer" na prática: significa permanecer no Seu amor e obedecer aos Seus mandamentos. A obediência não é a condição para ser amado, mas a evidência de que estamos permanecendo no amor dEle. O resultado dessa comunhão íntima é duplo: primeiro, a "alegria completa" (a alegria do próprio Cristo em nós, que as circunstâncias não podem roubar); segundo, o amor sacrificial uns pelos outros ("que vos ameis uns aos outros, assim como eu vos amei"). Jesus nos eleva da condição de servos para a de "amigos", revelando-nos os segredos do Pai.',
    concl: 'Deus não nos chamou para o ativismo religioso exaustivo, mas para a intimidade profunda com Cristo. O fruto espiritual (o caráter de Cristo e a salvação de almas) não é algo que fabricamos com o nosso suor, mas o resultado natural e inevitável de uma vida que extrai sua seiva e força da Videira Verdadeira. A nossa única responsabilidade é permanecer.'
  },
  {
    id: 'acts_2_1_13',
    intro: 'O Dia de Pentecostes, registrado em Atos 2, é o evento divisor de águas na história da redenção. Cinquenta dias após a ressurreição de Jesus e dez dias após a Sua ascensão, a promessa do Pai finalmente se cumpre. Os discípulos, que antes eram medrosos, confusos e se escondiam a portas fechadas, são radicalmente transformados. O Espírito Santo desce com poder e autoridade, inaugurando a era da Igreja, capacitando os crentes para a missão global e marcando o início do cumprimento da profecia de Joel de que Deus derramaria o Seu Espírito sobre toda a carne.',
    desc1: 'O capítulo começa com a postura da Igreja: "estavam todos reunidos no mesmo lugar". A unidade e a obediência à ordem de Jesus (de esperar em Jerusalém) precederam o derramamento. De repente, o sobrenatural invade o cenáculo com três sinais inconfundíveis. Primeiro, o som: "um som, como de um vento impetuoso" (simbolizando o poder invisível e irresistível do Espírito). Segundo, a visão: "línguas, como de fogo, que se repartiram e pousaram sobre cada um deles" (simbolizando a purificação, o zelo e a presença de Deus, como a sarça ardente). Terceiro, a experiência interna: "Todos ficaram cheios do Espírito Santo".',
    desc2: 'O milagre que se segue é profundamente teológico e missional: eles começaram a "falar em outras línguas, segundo o Espírito lhes concedia que falassem". Devido à festa de Pentecostes, Jerusalém estava cheia de judeus devotos de todas as nações do mundo conhecido. A multidão se ajunta e fica perplexa, pois cada um ouvia os galileus (pessoas sem instrução formal) falando "em nossas próprias línguas maternas as grandezas de Deus". Este milagre é a reversão da maldição da Torre de Babel (Gênesis 11). Em Babel, o pecado causou a confusão das línguas e a dispersão; no Pentecostes, o Espírito usa as línguas para trazer unidade e reunir os povos em Cristo.',
    desc3: 'Como sempre acontece quando Deus se move com poder, a manifestação do Espírito gerou duas reações distintas e opostas na multidão. A primeira reação foi de temor, perplexidade e busca por significado: "Que quer isto dizer?". Eles reconheceram o sobrenatural e estavam abertos à explicação (que Pedro daria em seguida). A segunda reação foi de cinismo, zombaria e rejeição: "Estão embriagados de vinho doce". O homem natural não compreende as coisas do Espírito de Deus e frequentemente tenta explicar o sobrenatural através de causas naturais e ridicularização.',
    concl: 'O Pentecostes nos ensina que o Espírito Santo não foi dado à Igreja apenas para proporcionar experiências emocionais ou êxtases espirituais privados. Ele foi derramado para revestir a Igreja de poder (dunamis) com um propósito específico: ser testemunhas de Cristo até os confins da terra. A Igreja nasceu no fogo do Espírito e só pode cumprir sua missão se continuar dependendo desse mesmo poder.'
  },
  {
    id: '1cor_13_1_13',
    intro: 'Conhecido universalmente como o "Hino ao Amor", 1 Coríntios 13 é um dos textos mais belos e profundos da literatura mundial. No entanto, ele não foi escrito para ser lido em casamentos românticos, mas como uma forte repreensão a uma igreja carnal. A igreja de Corinto era rica em dons espirituais, mas pobre em maturidade. Eles brigavam por status, processavam uns aos outros e se orgulhavam de seus dons espetaculares (especialmente o dom de línguas). No meio dessa confusão, Paulo interrompe seu ensino sobre os dons (capítulos 12 e 14) para mostrar o "caminho sobremodo excelente": o amor ágape, sem o qual toda a religiosidade é inútil.',
    desc1: 'Paulo começa com uma série de hipóteses chocantes para demonstrar a inutilidade dos dons sem o amor. Ele diz que se falasse as línguas dos homens e dos anjos (o dom mais valorizado pelos coríntios), mas não tivesse amor, seria apenas um barulho irritante ("sino que retine"). Se tivesse o dom de profecia, conhecesse todos os mistérios e tivesse uma fé capaz de mover montanhas, sem amor, ele "nada seria". Mais radical ainda: se ele doasse todos os seus bens aos pobres e entregasse seu próprio corpo para ser queimado (o sacrifício extremo), sem amor, isso "de nada me aproveitaria". O amor é a métrica pela qual Deus avalia todas as nossas ações.',
    desc2: 'Nos versículos 4 a 7, Paulo não define o amor com adjetivos românticos, mas com verbos de ação. O amor ágape não é um sentimento passivo, mas uma escolha ativa de buscar o bem do outro. Ele personifica o amor com 15 características: é paciente e benigno; não arde em ciúmes, não se ufana, não se ensoberbece, não se conduz inconvenientemente, não procura os seus interesses, não se exaspera, não se ressente do mal; não se alegra com a injustiça, mas regozija-se com a verdade. O amor "tudo sofre, tudo crê, tudo espera, tudo suporta". Se substituirmos a palavra "amor" por "Jesus" nestes versículos, teremos a biografia perfeita de Cristo.',
    desc3: 'Na conclusão do capítulo, Paulo contrasta a natureza temporária dos dons com a permanência eterna do amor. "O amor jamais acaba". As profecias serão aniquiladas, as línguas cessarão e a ciência passará, pois são apenas ferramentas temporárias para o tempo presente, como ver "por espelho, em enigma". Quando vier o que é perfeito (a consumação do Reino ou a presença de Cristo), os dons não serão mais necessários. No entanto, "agora, pois, permanecem a fé, a esperança e o amor, estes três; mas o maior destes é o amor", porque o amor é a própria essência do caráter de Deus e a atmosfera da eternidade.',
    concl: 'A verdadeira maturidade espiritual não é medida pelo poder dos nossos dons, pela profundidade do nosso conhecimento teológico ou pelos nossos sacrifícios religiosos, mas exclusivamente pela profundidade do nosso amor por Deus e pelo próximo. Os dons são ferramentas para construir a Igreja, mas o amor é o próprio edifício.'
  },
  {
    id: 'gal_5_16_26',
    intro: 'Em Gálatas 5, o apóstolo Paulo aborda a dinâmica prática da santificação cristã. A igreja da Galácia estava sendo tentada a voltar ao legalismo (tentar agradar a Deus guardando a Lei de Moisés). Paulo argumenta que a verdadeira liberdade cristã não é a licença para pecar (antinomianismo), nem a escravidão às regras (legalismo), mas uma vida guiada e empoderada pelo Espírito Santo. Este texto descreve a intensa guerra civil que acontece dentro de cada crente e contrasta as obras destrutivas da natureza humana caída com o belo e harmonioso fruto produzido pelo Espírito.',
    desc1: 'Paulo começa com um imperativo e uma promessa: "Andai no Espírito, e jamais satisfareis a concupiscência da carne". Ele reconhece a realidade do conflito interno: a "carne" (a nossa natureza pecaminosa remanescente) milita contra o Espírito, e o Espírito contra a carne. Eles são opostos e irreconciliáveis. O cristão não está isento de tentações, mas agora tem um novo poder habitando nele. A vitória sobre o pecado não vem por tentar guardar a lei com as próprias forças, mas por uma submissão contínua, passo a passo ("andar"), à direção do Espírito Santo.',
    desc2: 'Para deixar claro o que está em jogo, Paulo lista as "obras da carne" (no plural, indicando caos e fragmentação). A lista é assustadora e abrange todas as áreas da vida: pecados sexuais (prostituição, impureza, lascívia), pecados religiosos (idolatria, feitiçaria), pecados de intemperança (bebedices, glutonarias) e, notavelmente, uma longa lista de pecados relacionais que destroem a comunidade (inimizades, porfias, ciúmes, iras, discórdias, dissensões, facções, invejas). Paulo adverte severamente que aqueles que vivem na prática contínua e impenitente dessas coisas "não herdarão o reino de Deus".',
    desc3: 'Em contraste absoluto, Paulo apresenta o "fruto do Espírito" (no singular, indicando uma unidade orgânica e indivisível do caráter de Cristo). O Espírito produz: amor (a base de tudo), alegria (independente das circunstâncias), paz (com Deus e os homens), longanimidade (paciência com pessoas difíceis), benignidade (gentileza), bondade (ação generosa), fidelidade (confiabilidade), mansidão (poder sob controle) e domínio próprio (controle dos apetites). Paulo conclui que "contra estas coisas não há lei", pois quem vive assim já cumpre todo o propósito da lei moral de Deus.',
    concl: 'O caráter cristão não é fabricado pelo nosso próprio esforço moral, assim como uma maçã não é fabricada pela macieira, mas é o fruto natural da vida que flui nela. A nossa responsabilidade é crucificar a carne com as suas paixões (uma decisão radical de rejeitar o pecado) e viver em sintonia diária com o Espírito Santo. A evidência da graça não são os dons espetaculares, mas o fruto transformador.'
  },
  {
    id: 'phil_2_1_11',
    intro: 'O capítulo 2 de Filipenses contém um dos textos cristológicos mais profundos e reverenciados de todo o Novo Testamento, frequentemente chamado de "Hino de Filipenses". A igreja em Filipos era uma comunidade amorosa, mas estava começando a sofrer com divisões internas, egoísmo e vaidade. Para resolver esse problema pastoral, Paulo não apresenta apenas um conjunto de regras morais; ele eleva os olhos da igreja para o exemplo supremo de Jesus Cristo. Ele traça a trajetória impressionante do Filho de Deus: da glória eterna à humilhação mais profunda, e de volta à exaltação soberana.',
    desc1: 'Paulo começa com um apelo apaixonado à unidade da igreja, baseando-se na consolação, no amor e na comunhão do Espírito que eles já experimentavam em Cristo. A receita para a unidade é a morte do ego: "Nada façais por partidarismo ou vanglória, mas por humildade, considerando cada um os outros superiores a si mesmo". O cristão é chamado a não olhar apenas para os seus próprios interesses, mas também para os interesses dos outros. Para ilustrar como isso é possível, Paulo diz: "Tende em vós o mesmo sentimento (ou atitude) que houve também em Cristo Jesus".',
    desc2: 'Os versículos 6 a 8 descrevem a "Kenosis" (o esvaziamento) de Cristo. Jesus, existindo na "forma de Deus" (possuindo a essência e a glória divinas), não considerou a Sua igualdade com Deus como algo a ser retido ou usado para vantagem própria. Em vez disso, Ele "a si mesmo se esvaziou". Ele não deixou de ser Deus, mas abriu mão de Seus privilégios divinos, assumindo a "forma de servo" e tornando-se semelhante aos homens. A humilhação não parou na encarnação; Ele se humilhou ainda mais, tornando-se obediente até a morte, e a morte mais vergonhosa e dolorosa possível: a morte de cruz.',
    desc3: 'A humilhação voluntária de Cristo resulta na Sua exaltação soberana pelo Pai (v. 9-11). "Pelo que também Deus o exaltou soberanamente, e lhe deu o nome que é sobre todo nome". O caminho para baixo foi o caminho para a glória. Deus O vindicou publicamente, declarando que o Jesus crucificado é o Senhor do universo. A promessa escatológica é que um dia, voluntariamente ou por força, "ao nome de Jesus se dobre todo joelho, nos céus, na terra e debaixo da terra, e toda língua confesse que Jesus Cristo é Senhor, para glória de Deus Pai".',
    concl: 'A teologia de Filipenses 2 destrói o orgulho humano. No Reino de Deus, o caminho para cima é para baixo. A verdadeira grandeza não é encontrada na busca por status, poder ou reconhecimento, mas quando imitamos a atitude servil, humilde e sacrificial de Jesus Cristo. Aquele que desceu mais baixo do que todos é agora Aquele que está acima de todos.'
  },
  {
    id: 'rev_21_1_8',
    intro: 'O livro do Apocalipse, e toda a narrativa bíblica, não culmina em uma destruição caótica, mas em uma gloriosa recriação. Apocalipse 21 é o clímax da esperança cristã. Após a derrota final de Satanás, da besta, do falso profeta e da própria morte no capítulo 20, João tem uma visão deslumbrante do destino eterno dos redimidos. A história da redenção, que começou em um jardim (Éden) onde a comunhão com Deus foi perdida, termina em uma Cidade Santa onde Deus habita permanentemente com o Seu povo em um universo totalmente restaurado e livre da maldição do pecado.',
    desc1: 'A visão começa com uma renovação cósmica: "Vi novo céu e nova terra, pois o primeiro céu e a primeira terra passaram, e o mar já não existe". A velha ordem, manchada pelo pecado e pela rebelião, é substituída por uma nova criação perfeita. João então vê a "Cidade Santa, a nova Jerusalém, que descia do céu, da parte de Deus". A cidade não é construída por mãos humanas, mas é um dom divino. Ela é descrita com a imagem mais íntima e bela possível: "preparada como uma noiva adornada para o seu marido", simbolizando a pureza e o amor eterno entre Cristo e Sua Igreja.',
    desc2: 'O coração da eternidade não são as ruas de ouro, mas a presença de Deus. Uma forte voz do trono declara a maior de todas as promessas: "Eis o tabernáculo de Deus com os homens. Deus habitará com eles. Eles serão povos de Deus, e Deus mesmo estará com eles". A separação causada pelo pecado no Éden é finalmente desfeita. O resultado dessa presença íntima é o fim de todo o sofrimento humano: "E lhes enxugará dos olhos toda lágrima, e a morte já não existirá, já não haverá luto, nem pranto, nem dor, porque as primeiras coisas passaram". O mal é banido para sempre.',
    desc3: 'Aquele que está assentado no trono (o Alfa e o Ômega, o Princípio e o Fim) sela a visão com uma garantia: "Eis que faço novas todas as coisas". Ele oferece a água da vida gratuitamente àqueles que têm sede, prometendo que o vencedor herdará todas as coisas e será reconhecido como filho. No entanto, o capítulo termina com uma advertência solene: os covardes, incrédulos, abomináveis, assassinos, impuros, feiticeiros, idólatras e mentirosos não terão parte nesta cidade. O destino deles é o lago de fogo (a segunda morte), mostrando que a santidade de Deus exige a exclusão final do mal.',
    concl: 'A visão dos Novos Céus e da Nova Terra é a âncora da alma cristã em tempos de sofrimento. Ela nos garante que a dor, a injustiça e a morte não têm a última palavra. A história humana está caminhando para um final glorioso onde Deus fará justiça, restaurará a Sua criação e viverá em comunhão perfeita e eterna com aqueles que foram redimidos pelo sangue do Cordeiro.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done');
