const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'isa_40_27_31',
    intro: 'O capítulo 40 de Isaías marca uma transição profunda no livro, mudando do tom de juízo (capítulos 1-39) para uma mensagem de consolo e esperança (capítulos 40-66). O povo de Israel, enfrentando a realidade do exílio na Babilônia, estava exausto, desanimado e sentindo-se abandonado por Deus. O versículo 27 captura o lamento da nação: "O meu caminho está encoberto ao Senhor, e o meu juízo passa de largo do meu Deus". Eles acreditavam que Deus não via o seu sofrimento ou não se importava com a sua causa. Para curar esse desespero, o profeta não oferece soluções políticas ou estratégias militares, mas eleva os olhos do povo para a grandeza, a eternidade e o poder inesgotável do Criador, revelando o segredo da verdadeira renovação espiritual.',
    desc1: 'Isaías responde ao lamento do povo com uma série de perguntas retóricas que os chamam de volta à teologia básica: "Não sabes, não ouviste que o eterno Deus, o Senhor, o Criador dos fins da terra, nem se cansa nem se fatiga?". O desespero humano frequentemente nasce do esquecimento de quem Deus é. Nós nos cansamos porque somos limitados; Deus nunca se cansa porque Ele é a fonte infinita de toda a energia e poder. Além disso, "é inescrutável o seu entendimento". Não podemos compreender todos os caminhos de Deus ou o porquê da nossa dor, mas podemos confiar que a Sua sabedoria é perfeita e que Ele nunca perde o controle da história.',
    desc2: 'A grandeza de Deus não O torna distante, mas O torna a fonte da nossa força. O versículo 29 declara: "Dá força ao cansado, e multiplica as forças ao que não tem nenhum vigor". Deus não dá força aos fortes, mas aos que reconhecem a sua fraqueza. Isaías destrói a ilusão da autossuficiência humana no versículo 30: "Os jovens se cansarão e se fatigarão, e os moços certamente cairão". A juventude, o vigor físico e a força de vontade natural têm um limite e inevitavelmente falharão diante das pressões da vida. A força humana é um recurso esgotável; a força divina é inesgotável.',
    desc3: 'O clímax da passagem revela o segredo para acessar essa força inesgotável: "Mas os que esperam no Senhor renovarão as forças". Esperar no Senhor não é uma passividade preguiçosa, mas uma confiança ativa, uma dependência contínua e uma expectativa focada em Deus. O resultado dessa espera é uma renovação tripla: "subirão com asas como águias" (a capacidade de voar acima das tempestades e ter uma perspectiva celestial), "correrão, e não se cansarão" (a força para os momentos de crise e urgência), e "caminharão, e não se fatigarão" (a perseverança para a rotina diária e monótona da vida).',
    concl: 'Quando nos sentimos esquecidos por Deus ou exaustos pelas batalhas da vida, a solução não é tentar ser mais forte, mas reconhecer a nossa fraqueza e esperar nEle. A verdadeira renovação espiritual acontece quando trocamos a nossa força limitada pelo poder inesgotável do Criador, permitindo-nos voar, correr e caminhar sem desfalecer.'
  },
  {
    id: 'jhn_3_1_16',
    intro: 'O encontro entre Jesus e Nicodemos é um dos diálogos teológicos mais importantes do Novo Testamento. Nicodemos não era um homem comum; ele era um fariseu (a seita mais rigorosa do judaísmo), um "príncipe dos judeus" (membro do Sinédrio, a suprema corte judaica) e um "mestre em Israel" (um teólogo altamente respeitado). Ele procura Jesus "de noite", possivelmente por medo de perder o seu status ou para ter uma conversa ininterrupta. Nicodemos representa o ápice da religiosidade, da moralidade e do conhecimento humano. No entanto, Jesus destrói toda a sua estrutura religiosa ao declarar que nada do que ele alcançou é suficiente; para ver o Reino de Deus, é necessária uma transformação radical e sobrenatural: o novo nascimento.',
    desc1: 'Nicodemos começa a conversa com um elogio diplomático, reconhecendo que Jesus é um mestre vindo de Deus por causa dos Seus milagres. Jesus ignora o elogio e vai direto ao cerne do problema espiritual de Nicodemos: "Na verdade, na verdade te digo que aquele que não nascer de novo, não pode ver o reino de Deus". Jesus estabelece que a entrada no Reino não é uma questão de reforma moral, de melhorar o comportamento ou de acumular conhecimento teológico. É uma questão de vida ou morte. Assim como não tivemos parte no nosso primeiro nascimento físico, não podemos produzir o nosso nascimento espiritual. É uma obra exclusiva de Deus.',
    desc2: 'Nicodemos, preso à lógica humana e literal, pergunta como um homem velho pode voltar ao ventre materno. Jesus explica: "Aquele que não nascer da água e do Espírito, não pode entrar no reino de Deus". A "água e o Espírito" referem-se à purificação do pecado e à regeneração do coração, conforme profetizado em Ezequiel 36. Jesus contrasta as duas naturezas: "O que é nascido da carne é carne, e o que é nascido do Espírito é espírito". A carne (a natureza humana decaída) só pode produzir carne; ela nunca pode evoluir para se tornar espiritual. O novo nascimento é o Espírito Santo implantando a vida de Deus em um coração espiritualmente morto.',
    desc3: 'Jesus ilustra a obra do Espírito com o vento: não podemos vê-lo ou controlá-lo, mas podemos ouvir o seu som e ver os seus efeitos. Assim é todo aquele que é nascido do Espírito. O diálogo culmina com a revelação do amor de Deus e do meio da salvação. Jesus compara a Sua futura crucificação à serpente de bronze levantada por Moisés no deserto: assim como os israelitas envenenados olhavam para a serpente e viviam, a humanidade envenenada pelo pecado deve olhar para o Filho do Homem levantado na cruz. Isso leva ao versículo mais famoso da Bíblia (João 3:16), que resume o Evangelho: o amor motivador de Deus, a dádiva do Seu Filho unigênito, a condição da fé e a promessa da vida eterna.',
    concl: 'A história de Nicodemos nos ensina que a religião sem regeneração é inútil. Não importa quão bons, morais ou conhecedores da Bíblia sejamos; sem a obra miraculosa do Espírito Santo nos dando um novo coração, estamos perdidos. A salvação não é virar uma nova página, mas receber uma nova vida através da fé no Filho de Deus.'
  },
  {
    id: 'act_2_1_13',
    intro: 'O Dia de Pentecostes marca o nascimento oficial da Igreja Cristã e o cumprimento da maior promessa de Jesus: o derramamento do Espírito Santo. O Pentecostes (Festa das Semanas) era uma das três grandes festas judaicas de peregrinação, celebrada cinquenta dias após a Páscoa, originalmente para agradecer pelas primícias da colheita e, mais tarde, para comemorar a entrega da Lei no Monte Sinai. Havia judeus de todas as nações do mundo conhecido reunidos em Jerusalém. É nesse cenário global e festivo que Deus escolhe derramar o Seu Espírito sobre os 120 discípulos que estavam reunidos em oração e obediência. Este evento transforma um grupo de seguidores medrosos em testemunhas ousadas e poderosas do Evangelho.',
    desc1: 'A descida do Espírito Santo é acompanhada por três sinais sobrenaturais e inegáveis. Primeiro, um sinal auditivo: "De repente veio do céu um som, como de um vento veemente e impetuoso, e encheu toda a casa". O vento (pneuma) é um símbolo do Espírito, representando o poder invisível, incontrolável e vivificador de Deus. Segundo, um sinal visual: "E foram vistas por eles línguas repartidas, como que de fogo, as quais pousaram sobre cada um deles". O fogo simboliza a presença santa de Deus (como na sarça ardente) e a purificação. O fato de pousar sobre "cada um" indica que a presença de Deus não estava mais restrita a um templo de pedra ou a líderes específicos, mas habitava em cada crente individualmente.',
    desc2: 'O terceiro sinal foi vocal e prático: "E todos foram cheios do Espírito Santo, e começaram a falar noutras línguas, conforme o Espírito Santo lhes concedia que falassem". O milagre das línguas no Pentecostes não foi um balbuciar incompreensível, mas a capacidade sobrenatural de falar em idiomas humanos reais e desconhecidos pelos discípulos (que eram galileus iletrados). A multidão internacional que estava em Jerusalém ficou perplexa ao ouvir, cada um na sua própria língua materna, "as grandezas de Deus". Este milagre reverteu a maldição da Torre de Babel: enquanto em Babel as línguas foram confundidas para espalhar a humanidade em rebelião, no Pentecostes as línguas foram dadas para unir a humanidade na adoração a Cristo.',
    desc3: 'A reação da multidão foi dividida, como sempre acontece diante da manifestação do poder de Deus. A maioria ficou atônita e perplexa, perguntando: "Que quer isto dizer?". Eles reconheceram o milagre, mas precisavam da explicação teológica (que Pedro daria no seu sermão logo a seguir). Outros, no entanto, reagiram com cinismo e zombaria, dizendo: "Estão cheios de mosto (vinho doce)". O mundo frequentemente confunde a alegria e a ousadia do Espírito Santo com embriaguez ou loucura. No entanto, a embriaguez do mundo leva à perda de controle e à vergonha, enquanto a plenitude do Espírito leva à coragem, à clareza e à proclamação do Evangelho.',
    concl: 'O Pentecostes nos ensina que a Igreja não pode cumprir a sua missão de evangelizar o mundo baseada apenas em estratégias humanas, intelecto ou força de vontade. Precisamos desesperadamente do poder do Espírito Santo. Quando somos cheios do Espírito, o nosso medo é substituído por ousadia, e as nossas palavras ganham o poder de transformar corações de todas as nações.'
  },
  {
    id: 'gen_28_10_22',
    intro: 'O sonho de Jacó em Betel ocorre no momento mais vulnerável e solitário da sua vida. Jacó, o enganador, havia roubado a bênção do seu irmão Esaú e, como resultado, teve que fugir de casa para salvar a sua vida. Ele deixa para trás o conforto da tenda de sua mãe e viaja em direção a Harã. No meio do caminho, o sol se põe, e ele é forçado a dormir no deserto, usando uma pedra como travesseiro. Jacó estava fugindo do seu passado, incerto sobre o seu futuro e, provavelmente, sentindo-se totalmente abandonado por Deus. É exatamente nesse lugar de isolamento e quebra que Deus se revela a ele, transformando um deserto de desespero na "Casa de Deus".',
    desc1: 'Enquanto Jacó dorme, ele tem um sonho extraordinário: "Eis uma escada posta na terra, cujo topo tocava no céu; e eis que os anjos de Deus subiam e desciam por ela". A escada (ou rampa) representa a comunicação e o acesso entre o céu e a terra. Jacó achava que estava sozinho e longe da presença de Deus (que ele associava à casa do seu pai), mas o sonho revela que o céu está ativamente envolvido na terra e que os anjos estão ministrando a seu favor. Séculos mais tarde, Jesus aplicaria essa imagem a Si mesmo (João 1:51), revelando que Ele é a verdadeira "escada", o único mediador que une o Deus santo à humanidade pecadora.',
    desc2: 'No topo da escada, o próprio Senhor se apresenta a Jacó: "Eu sou o Senhor Deus de Abraão teu pai, e o Deus de Isaque". Deus não repreende Jacó pelos seus enganos recentes; em vez disso, Ele reafirma a aliança abraâmica e a estende pessoalmente a Jacó. Deus promete a terra, uma descendência inumerável e que todas as famílias da terra seriam abençoadas através dele. Mas a promessa mais reconfortante para um fugitivo solitário vem no versículo 15: "E eis que estou contigo, e te guardarei por onde quer que fores... porque te não deixarei, até que haja cumprido o que te tenho falado". A graça de Deus persegue Jacó no seu pior momento.',
    desc3: 'Quando Jacó acorda, a sua perspectiva sobre o lugar e sobre Deus muda radicalmente. Ele declara com temor reverente: "Na verdade o Senhor está neste lugar; e eu não o sabia... Quão terrível (reverendo) é este lugar! Este não é outro lugar senão a casa de Deus; e esta é a porta dos céus". Ele pega a pedra que usou como travesseiro, ergue-a como uma coluna (um memorial) e derrama azeite sobre ela, chamando o lugar de Betel (Casa de Deus). Jacó então faz um voto, prometendo que, se Deus o guardasse e o trouxesse de volta em paz, o Senhor seria o seu Deus e ele daria o dízimo de tudo. O encontro com a graça transforma a pedra de tropeço em um altar de adoração.',
    concl: 'A história de Betel nos ensina que Deus frequentemente nos encontra nos nossos "desertos", quando estamos fugindo das consequências dos nossos erros e nos sentindo mais distantes dEle. A Sua graça não depende do nosso mérito, mas da Sua fidelidade à aliança. Quando os nossos olhos são abertos para a presença de Deus, qualquer lugar de dor pode ser transformado em uma porta para os céus.'
  },
  {
    id: 'exo_17_8_16',
    intro: 'A batalha contra Amaleque em Refidim é o primeiro conflito militar que Israel enfrenta após a saída do Egito. Até este ponto, Deus havia lutado por eles de forma miraculosa (as pragas, a abertura do Mar Vermelho), mas agora, Deus exige que eles peguem em armas e lutem. Os amalequitas eram um povo nômade e cruel que atacou Israel de forma covarde, atingindo os mais fracos e cansados na retaguarda (Deuteronômio 25:17-18). Esta narrativa é uma das ilustrações mais vívidas e profundas da Bíblia sobre a dinâmica da guerra espiritual, revelando que a vitória não é conquistada apenas pela força da espada no vale, mas, fundamentalmente, pela perseverança da oração no monte.',
    desc1: 'A estratégia para a batalha envolve duas frentes simultâneas e interdependentes. Moisés ordena a Josué: "Escolhe-nos homens, e sai, peleja contra Amaleque; amanhã eu estarei no cume do outeiro, e a vara de Deus estará na minha mão". Josué lidera o exército no vale, enfrentando o inimigo corpo a corpo. O esforço humano, a coragem e a estratégia militar eram necessários. No entanto, Moisés sobe ao monte com Arão e Hur, levando a "vara de Deus" (o símbolo da autoridade e do poder divino). A batalha no vale (o esforço prático) seria inútil sem a batalha no monte (a intercessão espiritual). A vida cristã exige tanto a ação corajosa quanto a oração fervorosa.',
    desc2: 'O texto descreve um padrão espiritual fascinante: "E acontecia que, quando Moisés levantava a sua mão, Israel prevalecia; mas quando ele abaixava a sua mão, Amaleque prevalecia". As mãos levantadas de Moisés representavam a dependência de Deus, a intercessão contínua e o apelo ao poder divino. O sucesso de Josué no vale estava diretamente ligado à postura de Moisés no monte. Isso nos ensina que a nossa vitória sobre o pecado, a carne (frequentemente tipificada por Amaleque) e os inimigos espirituais não depende da nossa força de vontade, mas da nossa conexão contínua com Deus através da oração.',
    desc3: 'Moisés era um grande líder, mas era humano. As suas mãos ficaram pesadas e cansadas. A intercessão é um trabalho exaustivo. É aqui que entra a importância vital da comunidade e do apoio espiritual: "Tomaram uma pedra, e a puseram debaixo dele, para assentar-se sobre ela; e Arão e Hur sustentaram as suas mãos, um de um lado e o outro do outro; assim ficaram as suas mãos firmes até que o sol se pôs". Moisés não venceu sozinho. A vitória de Israel dependeu do apoio de Arão e Hur. Como resultado, Josué desfez a Amaleque a fio de espada. Após a vitória, Moisés constrói um altar e o chama de "Jeová-Nissi" (O Senhor é a minha bandeira/estandarte).',
    concl: 'A batalha contra Amaleque nos lembra que estamos em uma guerra espiritual constante. Não podemos vencer os nossos inimigos apenas com esforço humano; precisamos levantar as mãos em oração. Além disso, a história nos ensina que nenhum líder ou cristão é forte o suficiente para interceder sozinho o tempo todo; precisamos de "Arões e Hures" para sustentar as nossas mãos quando estamos exaustos, para que a vitória seja alcançada para a glória de Jeová-Nissi.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 16');
