const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'rom_8_31_39',
    intro: 'O final do capítulo 8 de Romanos é frequentemente considerado o cume do Everest teológico do Novo Testamento. Após expor a condenação universal do homem (capítulos 1-3), a justificação pela fé (capítulos 4-5), a santificação (capítulos 6-7) e a vida no Espírito (capítulo 8), o apóstolo Paulo irrompe em um hino triunfante e inabalável sobre a segurança eterna do crente. Ele faz uma série de perguntas retóricas que desafiam qualquer inimigo terreno, espiritual ou cósmico a tentar anular a obra redentora de Cristo. Este texto é a âncora definitiva para a alma do cristão em tempos de dúvida, sofrimento e perseguição.',
    desc1: 'Paulo começa com a pergunta fundamental que resume todo o Evangelho: "Que diremos, pois, a estas coisas? Se Deus é por nós, quem será contra nós?". A segurança do crente não se baseia na sua própria força, mas no fato de que o Deus soberano do universo está ativamente a seu favor. Para provar o tamanho desse compromisso, Paulo usa o argumento do maior para o menor: "Aquele que nem mesmo a seu próprio Filho poupou, antes o entregou por todos nós, como nos não dará também com ele todas as coisas?". Se Deus já pagou o preço infinito (a morte de Cristo) para nos salvar, Ele certamente nos dará a graça necessária para nos manter.',
    desc2: 'Em seguida, Paulo leva a nossa segurança para o tribunal divino. Ele pergunta: "Quem intentará acusação contra os escolhidos de Deus? É Deus quem os justifica. Quem é que condena?". O inimigo (cujo nome significa "acusador") tenta constantemente nos paralisar com a culpa dos nossos pecados passados e presentes. Mas Paulo declara que o Supremo Juiz (Deus) já pronunciou o veredito de "justificado" (declarado justo). Além disso, temos o melhor Advogado de Defesa: "Pois é Cristo quem morreu, ou antes quem ressuscitou dentre os mortos, o qual está à direita de Deus, e também intercede por nós". A nossa defesa é a obra consumada e a intercessão contínua de Cristo.',
    desc3: 'O clímax do texto é o desafio final: "Quem nos separará do amor de Cristo?". Paulo lista os piores cenários humanos (tribulação, angústia, perseguição, fome, nudez, perigo, espada) e declara que, em todas essas coisas, não somos apenas sobreviventes, mas "somos mais do que vencedores, por aquele que nos amou". A vitória cristã não é escapar do sofrimento, mas triunfar dentro dele. Paulo conclui com uma lista exaustiva de forças cósmicas (morte, vida, anjos, principados, presente, futuro, altura, profundidade) e garante que absolutamente nada na criação "nos poderá separar do amor de Deus, que está em Cristo Jesus nosso Senhor".',
    concl: 'A segurança da nossa salvação não depende da perfeição do nosso desempenho, mas da perfeição do amor e da obra de Cristo. Quando compreendemos que fomos justificados pelo sangue do Filho e que somos guardados pelo poder do Pai, podemos enfrentar qualquer acusação, sofrimento ou força do inferno com a certeza absoluta de que somos mais do que vencedores.'
  },
  {
    id: 'jas_1_2_12',
    intro: 'A Epístola de Tiago (provavelmente o primeiro livro escrito do Novo Testamento) foi endereçada a cristãos judeus que haviam sido dispersos por causa da perseguição em Jerusalém. Eles haviam perdido as suas casas, os seus empregos e a sua segurança, e estavam enfrentando severas provações. Em vez de oferecer um falso consolo ou prometer que o sofrimento acabaria rapidamente, Tiago abre a sua carta com uma das exortações mais radicais e contraculturais de toda a Bíblia. Ele ensina que o sofrimento não é um acidente sem sentido ou um castigo de Deus, mas uma ferramenta indispensável na forja divina para produzir maturidade e caráter no crente.',
    desc1: 'A exortação começa com um imperativo chocante: "Meus irmãos, tende grande gozo (alegria) quando cairdes em várias tentações (provações)". Tiago não está dizendo que devemos ser masoquistas e gostar da dor, nem que devemos fingir que não estamos sofrendo. A alegria cristã na provação não é uma emoção superficial, mas uma atitude baseada no conhecimento do propósito de Deus. Ele explica o motivo dessa alegria: "sabendo que a prova da vossa fé opera a paciência (perseverança)". A fé não testada é uma fé não confiável. O sofrimento é o ginásio onde o músculo da perseverança é desenvolvido.',
    desc2: 'A perseverança, no entanto, não é o objetivo final; ela é o meio para um fim maior. Tiago diz: "Tenha, porém, a paciência a sua obra perfeita, para que sejais perfeitos e completos, sem faltar em coisa alguma". O objetivo de Deus para nós não é o nosso conforto imediato, mas a nossa maturidade espiritual ("perfeitos e completos"). Quando tentamos escapar do processo da provação prematuramente (através de atalhos ou murmuração), interrompemos a obra de Deus no nosso caráter. Para suportar o processo, Tiago nos instrui a pedir sabedoria a Deus (v. 5), não para entender "por que" estamos sofrendo, mas "como" devemos nos portar no sofrimento para glorificá-Lo.',
    desc3: 'Tiago conclui esta seção com uma promessa escatológica (futura) que dá sentido ao sofrimento presente: "Bem-aventurado o homem que suporta a tentação; porque, quando for provado, receberá a coroa da vida, a qual o Senhor tem prometido aos que o amam". A provação é temporária, mas a recompensa é eterna. A coroa da vida não é um prêmio por mérito humano, mas a consumação da vida eterna concedida àqueles cujo amor por Deus foi provado e purificado no fogo da aflição.',
    concl: 'O sofrimento é inevitável, mas o desespero é opcional. Quando mudamos a nossa perspectiva e vemos as provações não como inimigas que vêm para nos destruir, mas como ferramentas nas mãos de um Pai amoroso para nos amadurecer, podemos enfrentar as tempestades da vida com uma alegria profunda, sabendo que a nossa fé está sendo forjada para a eternidade.'
  },
  {
    id: '1sa_17_38_51',
    intro: 'A história de Davi e Golias é, sem dúvida, a narrativa de batalha mais famosa da Bíblia. O exército de Israel, liderado pelo rei Saul, estava paralisado pelo medo no Vale de Elá, enfrentando os filisteus. Durante quarenta dias, Golias, um gigante de quase três metros de altura, fortemente armado e experiente em guerra, zombava de Israel e desafiava qualquer homem para um combate corpo a corpo. A paralisia de Israel ocorreu porque eles estavam medindo o gigante com a régua humana. É nesse cenário de covardia nacional que Davi, um jovem pastor de ovelhas, chega ao acampamento. Ele não traz armas sofisticadas, mas traz a única coisa que faltava ao exército: uma perspectiva teológica correta.',
    desc1: 'Quando Davi se oferece para lutar, o rei Saul tenta vesti-lo com a sua própria armadura (capacete de bronze e couraça). Saul representa a lógica humana e a dependência de recursos carnais. Davi tenta andar com a armadura, mas logo a rejeita: "Não posso andar com isto, pois não estou acostumado". Davi entende que não se pode vencer uma batalha espiritual usando as armas do mundo ou tentando imitar os métodos dos outros. Ele escolhe as armas que Deus já havia treinado ele para usar no deserto: o seu cajado de pastor, uma funda e cinco pedras lisas do ribeiro. Deus usa a nossa autenticidade e o treinamento que Ele nos deu na obscuridade.',
    desc2: 'O confronto no vale é um choque de cosmovisões. Golias olha para o jovem Davi, o despreza, o amaldiçoa pelos seus deuses e promete dar a sua carne às aves. Golias confia no seu tamanho, na sua lança e nos seus deuses falsos. A resposta de Davi é uma das maiores declarações de fé do Antigo Testamento: "Tu vens a mim com espada, e com lança, e com escudo; porém eu venho a ti em nome do Senhor dos Exércitos, o Deus dos exércitos de Israel, a quem tens afrontado". Davi não nega o tamanho do gigante, mas ele sabe que o gigante é minúsculo em comparação com o tamanho do seu Deus.',
    desc3: 'Davi declara o propósito da batalha antes mesmo de lançar a pedra: "E toda a terra saberá que há Deus em Israel... porque do Senhor é a guerra". Ele corre em direção ao gigante (a fé não recua diante do medo), coloca uma pedra na funda e a atira. A pedra afunda na testa de Golias, e o gigante cai com o rosto em terra (a postura de adoração forçada diante do Deus de Israel). Davi, não tendo espada, usa a própria espada de Golias para cortar a sua cabeça. A vitória de um único homem corajoso quebra o feitiço do medo, e todo o exército de Israel se levanta e persegue os filisteus.',
    concl: 'Os "Golias" nas nossas vidas (problemas insuperáveis, doenças, crises financeiras ou pecados persistentes) não são derrotados pela nossa própria força, inteligência ou armaduras humanas. Eles caem quando paramos de medir o tamanho do problema e começamos a focar na grandeza do Nome do Senhor dos Exércitos. A guerra é dEle, e a vitória é garantida pela fé.'
  },
  {
    id: 'psa_23_1_6',
    intro: 'O Salmo 23, escrito por Davi, é o poema mais amado, recitado e reconfortante de toda a literatura mundial. Sendo ele mesmo um pastor de ovelhas na sua juventude, Davi usa a metáfora do pastoreio para descrever o relacionamento íntimo, protetor e abundante de Deus com o Seu povo. A ovelha é um dos animais mais indefesos, míopes e dependentes da criação; ela não tem garras para se defender, não tem senso de direção para encontrar o caminho de volta e não sabe procurar pastos limpos. Ao declarar "O Senhor é o meu pastor", Davi reconhece a sua total vulnerabilidade e a suficiência absoluta de Deus em todas as fases da vida.',
    desc1: 'O salmo começa com uma declaração de suficiência que define tudo o que se segue: "O Senhor é o meu pastor, nada me faltará". Porque Deus é o pastor, a provisão é garantida. Davi descreve essa provisão em termos de descanso e direção: "Deitar-me faz em verdes pastos, guia-me mansamente a águas tranquilas". Ovelhas só se deitam quando estão livres do medo, da fome e da tensão no rebanho. Deus não apenas nos dá o que precisamos, mas nos leva a lugares de paz onde a nossa alma pode ser restaurada. Ele nos guia "pelas veredas da justiça, por amor do seu nome", garantindo que o nosso caminho tenha um propósito eterno.',
    desc2: 'No versículo 4, o tom do salmo muda radicalmente. A jornada sai dos pastos verdes e entra no "vale da sombra da morte" (os momentos de crise profunda, luto, depressão e perigo iminente). O pronome também muda: Davi para de falar sobre Deus ("Ele me guia") e começa a falar diretamente com Deus ("Tu estás comigo"). O vale não é um acidente, mas parte do caminho do pastor. A ausência de medo no vale não se deve à ausência do perigo, mas à presença do Pastor. A "vara" (para defender contra lobos) e o "cajado" (para resgatar e guiar a ovelha) de Deus trazem consolo e segurança no meio da escuridão.',
    desc3: 'Nos versículos finais, a metáfora muda de um pastor no campo para um anfitrião real em um banquete. "Preparas uma mesa perante mim na presença dos meus inimigos". Deus não remove os inimigos, mas nos dá paz e honra no meio deles. "Unges a minha cabeça com óleo, o meu cálice transborda". A unção com óleo era um sinal de hospitalidade, cura e alegria. A vida com Deus não é apenas de sobrevivência, mas de abundância transbordante. Davi conclui com a certeza absoluta: "Certamente que a bondade e a misericórdia me seguirão (literalmente, me perseguirão) todos os dias da minha vida; e habitarei na casa do Senhor por longos dias".',
    concl: 'O Salmo 23 nos garante que não precisamos temer a escassez, a confusão ou a própria morte. Quando o Senhor é o nosso Pastor, temos descanso nos pastos verdes, segurança no vale mais escuro e a promessa de um banquete eterno na Sua casa. A bondade e a misericórdia de Deus são os cães de guarda que nos perseguem até chegarmos ao lar.'
  },
  {
    id: 'pro_3_1_12',
    intro: 'O capítulo 3 de Provérbios é um dos textos mais fundamentais da literatura de sabedoria do Antigo Testamento. Escrito como o conselho de um pai amoroso para o seu filho, este trecho resume a essência da vida sábia: uma confiança radical e incondicional em Deus que se manifesta em todas as áreas da vida prática. A sabedoria bíblica não é apenas o acúmulo de conhecimento intelectual ou a capacidade de resolver problemas complexos; é, fundamentalmente, uma postura de reverência, submissão e dependência do Criador. Este texto nos ensina que a verdadeira prosperidade e a paz duradoura são os frutos inevitáveis de uma vida ancorada na confiança em Deus.',
    desc1: 'O coração do texto encontra-se nos versículos 5 e 6: "Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento. Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas". A confiança em Deus deve ser total ("de todo o coração"), não dividida. O maior obstáculo para essa confiança é o nosso "próprio entendimento" (a nossa lógica humana, a nossa experiência e a nossa capacidade de prever o futuro). A sabedoria exige que abdiquemos do trono do controle e reconheçamos a soberania de Deus em cada decisão (relacionamentos, finanças, carreira). A promessa é que Ele removerá os obstáculos e guiará os nossos passos.',
    desc2: 'A confiança em Deus se manifesta em atitudes práticas. O versículo 7 adverte contra o orgulho intelectual: "Não sejas sábio a teus próprios olhos; teme ao Senhor e aparta-te do mal". O temor do Senhor é o antídoto contra a arrogância e o pecado, e traz saúde física e vigor (v. 8). Em seguida, a sabedoria é aplicada à área mais sensível do coração humano: as finanças. "Honra ao Senhor com os teus bens, e com a primeira parte de todos os teus ganhos" (v. 9). A generosidade e a entrega das primícias não são uma transação comercial com Deus, mas a prova tangível de que confiamos nEle como o nosso Provedor, e não na nossa própria riqueza.',
    desc3: 'O texto conclui abordando o mistério do sofrimento na vida do sábio (v. 11-12): "Filho meu, não rejeites a correção do Senhor, nem te enojes da sua repreensão. Porque o Senhor repreende aquele a quem ama, assim como o pai ao filho a quem quer bem". A verdadeira sabedoria entende que as dificuldades e as disciplinas da vida não são sinais da ira de Deus, mas provas do Seu amor paternal. Deus nos ama demais para nos deixar confortáveis no nosso pecado ou na nossa imaturidade. A correção divina é a ferramenta que Ele usa para esculpir o caráter de Cristo em nós.',
    concl: 'A vida de sabedoria é uma jornada de rendição contínua. Quando paramos de confiar na nossa própria inteligência, honramos a Deus com os nossos recursos e aceitamos a Sua disciplina com humildade, experimentamos a promessa de que Ele endireitará os nossos caminhos e nos guiará em paz.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 14');
