const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'rom_8_1_17',
    intro: 'Romanos 8 é frequentemente considerado o clímax teológico do Novo Testamento, o "Everest" das epístolas de Paulo. Após descrever a luta agonizante contra o pecado no capítulo 7, Paulo irrompe em um hino de vitória. Este capítulo descreve a transição gloriosa da condenação e derrota sob a Lei para a liberdade, vitória e segurança absolutas através da obra consumada de Cristo e do poder habitador do Espírito Santo. É o manifesto definitivo da segurança eterna do crente e da sua nova identidade como filho amado de Deus.',
    desc1: 'O capítulo começa com a declaração mais libertadora de toda a Bíblia: "Portanto, agora nenhuma condenação há para os que estão em Cristo Jesus". A culpa foi cancelada. A razão dessa liberdade não é o nosso esforço, mas porque a "lei do Espírito da vida" nos libertou da "lei do pecado e da morte". O que a Lei de Moisés era impotente para fazer (porque a nossa carne era fraca), Deus fez enviando Seu próprio Filho em semelhança de carne pecaminosa, condenando o pecado na carne para que a justa exigência da Lei se cumprisse em nós.',
    desc2: 'Paulo estabelece um contraste absoluto entre duas mentalidades e dois estilos de vida: a carne e o Espírito. A mente controlada pela carne (a natureza humana caída) inclina-se para a morte, é inimizade contra Deus e é incapaz de se submeter à Sua lei. Em contraste, a mente controlada pelo Espírito inclina-se para a vida e a paz. A marca do verdadeiro cristão não é a perfeição sem pecado, mas a habitação do Espírito Santo. O mesmo Espírito que ressuscitou Jesus dentre os mortos agora habita em nós, garantindo não apenas a santificação presente, mas a ressurreição futura.',
    desc3: 'A obra do Espírito culmina na adoção. Não somos mais escravos vivendo com medo do castigo, mas fomos adotados na família cósmica de Deus. O Espírito testifica com o nosso espírito que somos filhos de Deus, permitindo-nos clamar "Aba, Pai" (uma expressão de profunda intimidade e confiança). Como filhos, somos também herdeiros de Deus e co-herdeiros com Cristo. No entanto, Paulo lembra que essa herança gloriosa inclui a participação nos sofrimentos de Cristo no tempo presente, como preparação para a glória futura.',
    concl: 'A vida cristã não é um esforço carnal e exaustivo para tentar agradar a um Deus distante e exigente. É uma caminhada diária no poder e na dependência do Espírito Santo, baseada na nossa nova e inabalável identidade como filhos perdoados, justificados e amados. Em Cristo, o nosso passado está perdoado, o nosso presente é capacitado e o nosso futuro está eternamente garantido.'
  },
  {
    id: 'lk_10_25_37',
    intro: 'A Parábola do Bom Samaritano é uma das narrativas mais conhecidas e revolucionárias de Jesus. Ela surge de um debate teológico com um perito na lei que, tentando justificar sua própria falta de amor, faz a pergunta minimalista: "Quem é o meu próximo?". Em resposta, Jesus conta uma história que destrói completamente as barreiras religiosas, raciais e sociais da época. Ele redefine o amor não como um sentimento passivo por aqueles que são iguais a nós, mas como uma ação sacrificial, custosa e incondicional em favor de qualquer pessoa em necessidade.',
    desc1: 'O diálogo começa com o perito na lei testando Jesus sobre como herdar a vida eterna. Jesus o direciona para a Lei: amar a Deus sobre todas as coisas e ao próximo como a si mesmo. O problema surge quando o homem tenta "justificar-se". A religião legalista frequentemente busca estabelecer limites para a obediência: "Até onde eu tenho que ir? Quem eu sou obrigado a amar e quem eu posso ignorar?". O amor de Cristo, no entanto, não busca limites, mas oportunidades para se manifestar.',
    desc2: 'Na história, um homem é assaltado, espancado e deixado quase morto na perigosa estrada de Jerusalém para Jericó. Ironicamente, os representantes máximos da religião oficial – um sacerdote e um levita – passam pelo mesmo caminho, veem o homem ferido, mas passam de largo. Eles provavelmente colocaram a pureza ritual (o medo de tocar em um cadáver e ficarem impuros para o serviço no Templo) acima da misericórdia. A religião que prioriza rituais em detrimento do amor humano é vazia e condenada por Deus.',
    desc3: 'O herói da história é a pessoa mais improvável e odiada pelos judeus: um samaritano. Os samaritanos eram considerados hereges e mestiços. No entanto, é este inimigo histórico quem sente profunda compaixão. Ele não apenas sente pena, mas age: ele se aproxima, arrisca sua própria segurança na estrada perigosa, usa seus próprios recursos (óleo e vinho) para tratar as feridas, coloca o homem em sua própria montaria, leva-o a uma hospedaria e paga todas as despesas da recuperação. O amor verdadeiro é prático e custoso.',
    concl: 'No final, Jesus inverte a pergunta do perito na lei. Em vez de perguntar "quem é o meu próximo?" (focando no objeto do amor), devemos perguntar "de quem eu serei o próximo?" (focando no sujeito que ama). O valor do Reino de Deus é a misericórdia que age, cura e restaura, independentemente da raça, religião ou status de quem precisa de ajuda. Jesus nos chama a "ir e fazer o mesmo".'
  },
  {
    id: 'jn_13_1_17',
    intro: 'O episódio do Lava-Pés ocorre na véspera da crucificação e marca uma transição profunda no ministério de Jesus. Sabendo que Sua hora havia chegado e que o Pai Lhe dera todo o poder e autoridade sobre todas as coisas, Jesus realiza um ato surpreendente. Em vez de exigir um trono, uma coroa ou ser servido, Ele pega uma toalha e uma bacia de água. Ele demonstra visualmente que, no Seu Reino, a verdadeira grandeza não é medida pelo poder de dominar os outros, mas pela disposição de descer e servir aos outros em humildade radical.',
    desc1: 'O texto destaca a plena consciência de Jesus sobre Sua identidade divina: Ele sabia que viera de Deus e voltava para Deus, e que o Pai Lhe entregara tudo nas mãos. É exatamente a partir dessa posição de soberania absoluta que Ele escolhe assumir a tarefa do escravo mais baixo da casa: lavar os pés sujos e empoeirados de Seus discípulos. O amor de Cristo (que os amou "até o fim") não é teórico; ele se abaixa, toca a sujeira humana e serve. Chocantemente, Ele lava até mesmo os pés de Judas, sabendo que este O trairia.',
    desc2: 'A reação de Pedro é imediata e veemente: "Tu nunca me lavarás os pés!". Pedro está preso à lógica do mundo, onde os maiores nunca servem os menores. Ele não compreende que a ação de Jesus é um símbolo da própria salvação. Jesus responde que, se não o lavar, Pedro não terá parte com Ele. A salvação exige que abandonemos nosso orgulho e aceitemos que precisamos ser purificados pelo serviço humilhante de Cristo na cruz. Não podemos salvar a nós mesmos; precisamos permitir que Ele nos lave.',
    desc3: 'Após lavar os pés de todos, Jesus reassume Seu lugar e explica a lição: "Vós me chamais Mestre e Senhor, e dizeis bem, porque eu o sou. Ora, se eu, Senhor e Mestre, vos lavei os pés, vós deveis também lavar os pés uns aos outros". Jesus estabelece um novo e revolucionário padrão de liderança e relacionamento para a Sua Igreja. A liderança cristã não é sobre posição, títulos ou privilégios, mas sobre sacrifício, serviço e colocar as necessidades dos outros acima das nossas.',
    concl: 'O mundo mede a grandeza por quantas pessoas estão servindo a você; Cristo mede a grandeza por quantas pessoas você está servindo. Jesus conclui com uma promessa: "Se sabeis estas coisas, bem-aventurados sois se as praticardes" (v. 17). A verdadeira felicidade e realização na vida cristã não vêm apenas do conhecimento teológico, mas da prática diária da humildade e do amor sacrificial.'
  },
  {
    id: 'mk_10_17_27',
    intro: 'O encontro de Jesus com o Jovem Rico é uma das narrativas mais tristes e reveladoras dos Evangelhos. Um homem que aparentemente tinha tudo – juventude, riqueza, moralidade irrepreensível, zelo religioso e posição social – corre até Jesus e se ajoelha, buscando a garantia da vida eterna. No entanto, este encontro expõe a falência da justiça própria e revela que o coração humano é uma fábrica de ídolos. Jesus demonstra que a salvação exige mais do que bom comportamento; exige a rendição total do coração e o abandono de tudo o que concorre com Deus pelo primeiro lugar.',
    desc1: 'O jovem aborda Jesus com uma pergunta baseada em mérito: "Bom Mestre, que farei para herdar a vida eterna?". Ele acredita que a salvação é algo que pode ser conquistado ou comprado através de boas obras. Quando Jesus lista os mandamentos referentes ao próximo, o jovem responde com confiança: "Tudo isso tenho guardado desde a minha juventude". Ele conhecia a letra da lei e tinha um comportamento moral exemplar, mas não conhecia a profundidade do seu próprio pecado nem o espírito da lei.',
    desc2: 'Marcos registra um detalhe tocante: "Jesus, olhando para ele, o amou". Não foi com raiva, mas com amor confrontador que Jesus tocou no ídolo escondido no coração do jovem: "Falta-te uma coisa: vai, vende tudo quanto tens, dá-o aos pobres... e vem, segue-me". Jesus não estava ensinando que a salvação se compra com filantropia, mas estava expondo que o deus daquele homem era o seu dinheiro. O jovem retirou-se triste, pois "tinha muitas propriedades". Ele escolheu o conforto temporário de suas riquezas em vez do tesouro eterno do Reino.',
    desc3: 'Após a partida do jovem, Jesus choca Seus discípulos com uma declaração contundente: "Quão dificilmente entrarão no reino de Deus os que têm riquezas!". Ele usa a hipérbole do camelo passando pelo fundo de uma agulha para ilustrar que é humanamente impossível alguém salvar a si mesmo, especialmente quando confia em seus próprios recursos. Os discípulos, atônitos, perguntam: "Quem, pois, pode ser salvo?". A resposta de Jesus é a essência do evangelho: "Para os homens é impossível, mas não para Deus, porque para Deus todas as coisas são possíveis".',
    concl: 'A salvação não é uma transação comercial nem o resultado do nosso esforço moral; é um milagre exclusivo da graça de Deus. Cristo exige rendição total e exclusividade. O valor do Reino de Deus não é medido pelo que acumulamos nesta terra, mas pelo que estamos dispostos a abandonar com alegria para seguir a Jesus.'
  },
  {
    id: 'jn_8_1_11',
    intro: 'A história da mulher pega em adultério é um dos relatos mais belos e dramáticos sobre o contraste entre a religião legalista e a graça redentora. Os escribas e fariseus, movidos por ódio e inveja, usam uma mulher quebrada e humilhada como um mero peão em um jogo teológico para tentar prender Jesus em uma armadilha. Eles trazem a condenação fria da Lei e pedem pedras para a execução; Jesus, no entanto, traz a luz da Graça, expõe a hipocrisia humana e oferece um novo começo, demonstrando que a misericórdia triunfa sobre o juízo.',
    desc1: 'A armadilha era cruel e bem elaborada. A mulher é arrastada e exposta publicamente no centro do Templo, reduzida ao seu pior pecado. Os líderes religiosos citam a Lei de Moisés, que exigia o apedrejamento, e perguntam a Jesus: "Tu, pois, que dizes?". Se Jesus dissesse para não apedrejar, seria acusado de quebrar a Lei de Deus; se dissesse para apedrejar, perderia Sua reputação de misericórdia e entraria em conflito com a lei romana (que proibia os judeus de executarem a pena de morte). A religião sem amor usa as pessoas para provar seus pontos.',
    desc2: 'Em vez de responder imediatamente, Jesus se inclina e começa a escrever na terra com o dedo. Quando eles insistem, Ele se levanta e profere a sentença que muda a história da ética: "Aquele que dentre vós está sem pecado seja o primeiro que atire pedra contra ela". Jesus não revoga a Lei, mas qualifica os juízes. Ele transfere o julgamento da mulher para a consciência dos acusadores. Expostos pela luz da verdade, os hipócritas se retiram um a um, começando pelos mais velhos, deixando as pedras no chão.',
    desc3: 'Ficam no centro apenas a miséria humana e a Misericórdia divina. Jesus pergunta: "Mulher, onde estão aqueles teus acusadores? Ninguém te condenou?". Ao ouvir que não, Jesus profere as palavras de absolvição: "Nem eu também te condeno". Jesus não minimiza o pecado nem diz que o adultério não importa. A graça não ignora a justiça. Ele pode perdoá-la porque Ele mesmo, o único sem pecado ali, estava a caminho da cruz para receber as pedras do juízo de Deus no lugar dela. E a graça vem com uma nova direção: "Vai-te, e não peques mais".',
    concl: 'O valor supremo de Cristo é a restauração, não a destruição. A religião legalista aponta o dedo e atira pedras; o Evangelho estende a mão e levanta o caído. A graça de Deus nos aceita exatamente como estamos, mas nos ama demais para nos deixar como estamos. O perdão precede e capacita a transformação.'
  },
  {
    id: 'lk_18_9_14',
    intro: 'A Parábola do Fariseu e do Publicano é um ataque direto e cirúrgico à justiça própria e ao orgulho espiritual. Lucas registra que Jesus contou esta história especificamente "para alguns que confiavam em si mesmos, crendo que eram justos, e desprezavam os outros". Através de dois personagens diametralmente opostos orando no Templo, Jesus destrói a ideia de que o acesso a Deus se baseia no nosso currículo moral ou religioso, e estabelece que a única base para a justificação é o quebrantamento e a dependência absoluta da misericórdia divina.',
    desc1: 'O fariseu representa a elite religiosa. Ele fica em pé e ora "de si para si mesmo". Sua oração não é uma petição, mas um relatório de suas realizações e uma comparação arrogante. Ele agradece a Deus por não ser como os outros homens (roubadores, injustos, adúlteros) e, especialmente, por não ser como o publicano ali presente. Ele lista seus méritos: jejua duas vezes por semana e dá o dízimo de tudo. Ele não pede nada a Deus porque, em sua cegueira espiritual, ele acha que não precisa de nada. Sua religião é um monumento ao seu próprio ego.',
    desc2: 'Em total contraste, o publicano (um cobrador de impostos, considerado um traidor e pecador público) fica de longe. Ele sente o peso de sua indignidade, não ousa sequer levantar os olhos para o céu e bate no peito em sinal de profundo luto e contrição. Sua oração é curta, desesperada e teologicamente precisa: "Ó Deus, tem misericórdia de mim, pecador!". A palavra grega para misericórdia aqui (hilaskomai) está ligada à propiciação e ao sacrifício. Ele está clamando: "Deus, sê propício a mim através de um sacrifício expiatório". Ele reconhece sua falência total.',
    desc3: 'O veredito de Jesus choca a audiência: "Digo-vos que este (o publicano) desceu justificado para sua casa, e não aquele (o fariseu)". A justificação (ser declarado justo diante do tribunal de Deus) não foi concedida ao homem que tinha uma vida moralmente limpa, mas orgulhosa; foi concedida ao homem moralmente falido, mas quebrantado. Jesus conclui com um princípio espiritual imutável: "Qualquer que a si mesmo se exalta será humilhado, e qualquer que a si mesmo se humilha será exaltado".',
    concl: 'O Reino de Deus pertence àqueles que sabem que não o merecem. O valor central do Evangelho é a justificação pela graça mediante a fé. A nossa única esperança diante de um Deus santo não é apresentar as nossas obras como mérito, mas clamar pela Sua misericórdia, confiando inteiramente na obra de Cristo por nós.'
  },
  {
    id: 'gen_12_1_9',
    intro: 'O chamado de Abrão (mais tarde Abraão) em Gênesis 12 marca um dos pontos de virada mais cruciais em toda a história bíblica. Após a rebelião global em Babel, Deus muda Sua estratégia. Em vez de lidar com as nações em massa, Ele escolhe um homem comum, de uma família idólatra em Ur dos Caldeus, para iniciar uma nova nação através da qual o Messias viria para abençoar o mundo inteiro. Este texto é o paradigma da jornada da fé: um chamado para deixar o conhecido e caminhar em direção às promessas de Deus, confiando exclusivamente em Sua Palavra.',
    desc1: 'O chamado de Deus começa com um desafio radical de renúncia: "Sai-te da tua terra, da tua parentela e da casa de teu pai, para a terra que eu te mostrarei". Deus pede que Abrão abandone suas três maiores fontes de segurança no mundo antigo: sua pátria (identidade), sua tribo (proteção) e sua família (herança). A fé frequentemente exige que abandonemos nossas zonas de conforto, nossas seguranças terrenas e nosso passado para podermos abraçar o futuro que Deus tem preparado. O destino não é revelado de imediato; a bússola de Abrão seria apenas a voz de Deus.',
    desc2: 'Acompanhando a ordem difícil, Deus faz promessas extraordinárias, conhecidas como a Aliança Abraâmica. Deus promete fazer dele uma grande nação (embora sua esposa Sarai fosse estéril), abençoá-lo, engrandecer o seu nome e protegê-lo ("abençoarei os que te abençoarem..."). No entanto, o propósito final dessa bênção não é o egoísmo, mas a missão: "e em ti serão benditas todas as famílias da terra". A eleição de Abrão não foi para exclusivismo, mas para ser o canal da redenção global. Somos abençoados por Deus com o propósito de sermos uma bênção para os outros.',
    desc3: 'A resposta de Abrão é o modelo da fé obediente: "Assim partiu Abrão como o Senhor lhe tinha dito". Ele não argumentou, não pediu um mapa detalhado e não exigiu garantias visíveis. Aos 75 anos de idade, ele iniciou uma jornada de peregrinação. Ao chegar à terra de Canaã, que já estava ocupada pelos cananeus, Deus aparece a ele novamente e reafirma a promessa. A resposta de Abrão é construir altares (em Siquém e Betel). Os altares marcam sua jornada com adoração, sacrifício e um testemunho público de sua fé em uma terra pagã.',
    concl: 'A verdadeira fé não é apenas um assentimento intelectual a fatos sobre Deus, mas uma confiança ativa que resulta em obediência, mesmo quando não vemos o destino final. A jornada de Abraão nos ensina que a vida cristã é uma peregrinação constante, onde a nossa única segurança verdadeira é a promessa inabalável daquele que nos chamou.'
  },
  {
    id: 'ex_3_1_15',
    intro: 'O encontro na Sarça Ardente é uma das teofanias (manifestações de Deus) mais sagradas e transformadoras da Escritura. Moisés, que outrora fora um príncipe poderoso no Egito, agora é um pastor de ovelhas exilado e esquecido no deserto de Midiã há 40 anos. É neste cenário de aparente fracasso e rotina que Deus irrompe na história para iniciar o Êxodo. Este encontro revela não apenas o plano de Deus para libertar Israel, mas, mais importante, revela a própria natureza, o caráter compassivo e o Nome sagrado do Deus Todo-Poderoso.',
    desc1: 'O encontro começa com o sagrado e o sobrenatural invadindo o comum. Moisés vê uma sarça (um arbusto comum do deserto) que queima com fogo, mas não se consome. Quando Moisés se aproxima para ver, Deus o chama pelo nome: "Moisés, Moisés!". A primeira instrução é um chamado à reverência: "Tira as sandálias dos pés, porque o lugar em que estás é terra santa". A santidade não estava na terra em si, mas na presença de Deus. Deus então se identifica como o Deus da aliança: "Eu sou o Deus de teu pai, o Deus de Abraão, de Isaque e de Jacó".',
    desc2: 'Os versículos 7 a 10 revelam o coração compassivo de Deus. Ele declara: "Tenho visto atentamente a aflição do meu povo... tenho ouvido o seu clamor... e conheci as suas dores". Deus não é um ser distante e apático; Ele é profundamente afetado pelo sofrimento do Seu povo. Essa compaixão se traduz em ação redentora: "Portanto, desci para livrá-lo". No entanto, a ação divina envolve a agência humana. Deus comissiona o relutante Moisés: "Vem agora, pois, e eu te enviarei a Faraó, para que tires o meu povo do Egito".',
    desc3: 'Diante da missão impossível, Moisés é tomado pela insegurança e pergunta: "Quem sou eu para ir a Faraó?". Deus não responde elogiando as habilidades de Moisés, mas garantindo a Sua presença: "Certamente eu serei contigo". Moisés então pergunta o nome de Deus, caso o povo questione. A resposta é a revelação máxima do Antigo Testamento: "EU SOU O QUE SOU" (Yahweh). Este nome denota a existência auto-existente, eterna, imutável e independente de Deus. Ele é a realidade absoluta da qual tudo o mais depende.',
    concl: 'A história da Sarça Ardente nos ensina que Deus ouve o clamor dos oprimidos e frequentemente chama pessoas comuns, quebradas ou esquecidas para propósitos extraordinários. A garantia do nosso sucesso na missão que Deus nos dá não reside em quem nós somos, nas nossas habilidades ou no nosso passado, mas exclusivamente na presença e no poder do grande "EU SOU" que nos envia.'
  },
  {
    id: 'jos_1_1_9',
    intro: 'O primeiro capítulo de Josué marca uma transição monumental na história de Israel. Moisés, o libertador e legislador gigante, está morto. O povo está acampado nas margens do rio Jordão, prestes a entrar na Terra Prometida, que está cheia de cidades fortificadas e inimigos formidáveis. O peso da liderança agora recai sobre os ombros de Josué. Neste momento de incerteza e transição, Deus não fornece a Josué um mapa militar detalhado ou novas armas, mas lhe dá uma promessa inabalável, a garantia de Sua presença e um manual de instruções baseado na Sua Palavra.',
    desc1: 'O texto começa com a realidade nua e crua: "Moisés, meu servo, é morto". Deus não permite que o luto paralise o propósito. A ordem é clara: "Levanta-te, pois, agora, passa este Jordão, tu e todo este povo, à terra que eu dou aos filhos de Israel". Deus reafirma a promessa feita aos patriarcas. A terra já foi dada por Deus (é uma herança garantida), mas o papel de Josué e do povo é marchar, lutar e tomar posse dessa herança pisando na terra. A promessa divina não anula a responsabilidade humana; ela a fundamenta.',
    desc2: 'Para enfrentar os gigantes e as muralhas de Canaã, Josué precisaria de coragem sobrenatural. Deus repete três vezes o imperativo: "Sê forte e corajoso". A base para essa coragem não era a inteligência militar de Josué, o tamanho do exército de Israel ou o enfraquecimento dos inimigos. A única base para a coragem era a promessa da presença infalível de Deus: "Como fui com Moisés, assim serei contigo; não te deixarei nem te desampararei". O medo olha para as circunstâncias; a fé olha para a presença do Senhor.',
    desc3: 'O segredo do sucesso e da prosperidade de Josué é revelado nos versículos 7 e 8. A sua prioridade máxima não deveria ser afiar espadas, mas meditar na Palavra de Deus: "Não se aparte da tua boca o livro desta lei; antes medita nele dia e noite, para que tenhas cuidado de fazer conforme a tudo quanto nele está escrito". A obediência estrita e inegociável à revelação de Deus é a bússola que garante que ele fará prosperar o seu caminho e será bem-sucedido. A vitória militar dependeria da fidelidade espiritual.',
    concl: 'A verdadeira coragem cristã não é a ausência de medo, mas a confiança absoluta na presença de Deus e a submissão incondicional à Sua Palavra diante dos maiores desafios. Assim como Josué, somos chamados a tomar posse das promessas que Cristo já conquistou para nós, avançando com fé, força e obediência.'
  },
  {
    id: 'ps_51_1_19',
    intro: 'O Salmo 51 é o mais profundo e comovente salmo penitencial da Bíblia. Ele é o raio-X de um coração verdadeiramente quebrantado. Davi escreveu este salmo após ser confrontado pelo profeta Natã sobre o seu terrível e duplo pecado: o adultério com Bate-Seba e o assassinato premeditado de seu marido, Urias. Após quase um ano de silêncio e miséria espiritual tentando esconder seu pecado, Davi finalmente é exposto. Este salmo não é uma tentativa de justificação, mas um mergulho desesperado na graça e na misericórdia restauradora de Deus.',
    desc1: 'O salmo começa com um apelo exclusivo à natureza de Deus: "Tem misericórdia de mim, ó Deus, segundo a tua benignidade; apaga as minhas transgressões, segundo a multidão das tuas misericórdias". Davi não dá desculpas, não culpa as circunstâncias nem Bate-Seba. Ele assume total responsabilidade. Ele usa três palavras para descrever seu erro: transgressão (rebelião), iniquidade (distorção moral) e pecado (errar o alvo). Mais profundamente, ele reconhece que, embora tenha ferido pessoas, o seu pecado foi fundamentalmente uma ofensa contra a santidade do próprio Deus: "Pequei contra ti, contra ti somente".',
    desc2: 'Davi não pede apenas perdão (o cancelamento da dívida); ele clama por uma purificação radical e uma renovação interna. Ele pede: "Cria em mim, ó Deus, um coração puro, e renova em mim um espírito reto". Ele reconhece que o problema não foi apenas um erro de conduta, mas uma corrupção de natureza (nascido em iniquidade). O seu maior medo não é perder o trono, mas perder a presença de Deus: "Não me lances fora da tua presença, e não retires de mim o teu Espírito Santo". Ele anseia pela restauração da "alegria da salvação".',
    desc3: 'O resultado do verdadeiro perdão é a adoração e o testemunho. Davi promete que, uma vez restaurado, ele ensinará os caminhos de Deus aos transgressores, para que outros pecadores se convertam. Ele entende que a verdadeira religião não se baseia em rituais externos para apaziguar a Deus. "Pois não desejas sacrifícios... Os sacrifícios para Deus são o espírito quebrantado; a um coração quebrantado e contrito não desprezarás, ó Deus". Deus não quer a nossa performance religiosa; Ele quer o nosso coração rendido.',
    concl: 'O verdadeiro arrependimento não foge de Deus com medo, mas corre para Ele em busca de graça. O Salmo 51 nos ensina que não importa a profundidade da nossa queda, a escuridão do nosso pecado ou o tempo que passamos fugindo, a misericórdia de Deus é profunda o suficiente para nos purificar, perdoar e restaurar completamente.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done');
