const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'psa_91_1_16',
    intro: 'O Salmo 91 é um dos textos mais conhecidos, amados e frequentemente citados de toda a Bíblia. Ele é um hino de confiança inabalável, uma declaração poética e teológica sobre a segurança absoluta daqueles que confiam em Deus. No entanto, este salmo não é um amuleto mágico para ser deixado aberto em uma mesa para afastar o mal. Ele é uma promessa condicional, dirigida àqueles que tomam uma decisão consciente e diária de fazer de Deus a sua habitação. O salmo descreve os perigos reais da vida (doenças, guerras, ataques noturnos), mas garante que, sob as asas do Altíssimo, o crente encontra um refúgio impenetrável.',
    desc1: 'O salmo começa estabelecendo a condição fundamental para todas as promessas que se seguem: "Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará". A promessa não é para quem "visita" a presença de Deus apenas nos domingos ou nos momentos de crise, mas para quem "habita" (mora, permanece) nela. O salmista usa quatro nomes para Deus nos dois primeiros versículos: Altíssimo (Elyon - o Deus que governa sobre tudo), Onipotente (Shaddai - o Deus que tem todo o poder), Senhor (Yahweh - o Deus da aliança) e Deus meu (Elohim - o Criador pessoal). Conhecer o caráter de Deus é a base para declarar: "Ele é o meu Deus, o meu refúgio, a minha fortaleza, e nele confiarei".',
    desc2: 'A partir do versículo 3, o salmista descreve os perigos dos quais Deus nos livra. Ele usa metáforas de caça ("laço do passarinheiro") e de doenças ("peste perniciosa"). Ele garante proteção contra os medos noturnos (o terror de noite) e os ataques diurnos (a seta que voa de dia). A promessa do versículo 7 é famosa: "Mil cairão ao teu lado, e dez mil à tua direita, mas não chegará a ti". Isso não significa que o crente nunca sofrerá acidentes ou doenças (a Bíblia inteira prova o contrário), mas significa que nenhum mal pode atingir o crente sem a permissão soberana de Deus, e que mesmo no meio do caos, a alma do crente está eternamente segura.',
    desc3: 'Os versículos 11 e 12 revelam a provisão angelical: "Porque aos seus anjos dará ordem a teu respeito, para te guardarem em todos os teus caminhos". Ironicamente, o diabo usou exatamente este versículo para tentar Jesus no deserto (Mateus 4), omitindo a frase "em todos os teus caminhos" (os caminhos da obediência). A proteção de Deus não é uma licença para a imprudência. O salmo conclui com o próprio Deus falando (v. 14-16), confirmando as promessas àqueles que O amam e conhecem o Seu nome: "Ele me invocará, e eu lhe responderei; estarei com ele na angústia; dela o retirarei, e o glorificarei".',
    concl: 'O Salmo 91 nos ensina que a verdadeira segurança não é a ausência de perigo, mas a presença de Deus no meio do perigo. Quando fazemos do Altíssimo a nossa morada diária, podemos enfrentar os terrores da noite e as pestes do dia com a paz inabalável de quem sabe que está guardado sob as asas do Onipotente.'
  },
  {
    id: 'isa_61_1_3',
    intro: 'O início do capítulo 61 de Isaías é uma das profecias messiânicas mais gloriosas e fundamentais do Antigo Testamento. Este texto não é apenas uma promessa poética de restauração para os exilados de Israel; é a própria "declaração de missão" do Messias. A importância desta passagem é confirmada no Novo Testamento, quando Jesus, no início do Seu ministério público, entra na sinagoga de Nazaré, lê exatamente estes versículos e declara: "Hoje se cumpriu esta Escritura em vossos ouvidos" (Lucas 4:21). Este texto descreve a unção, o propósito e o poder transformador do Ungido de Deus, que veio para trazer uma reversão radical à condição de miséria humana causada pelo pecado.',
    desc1: 'A profecia começa com a fonte da autoridade e do poder do Messias: "O Espírito do Senhor Deus está sobre mim; porque o Senhor me ungiu". A palavra "Cristo" (no grego) e "Messias" (no hebraico) significam literalmente "O Ungido". Jesus não realizou o Seu ministério na terra usando os Seus atributos divinos de forma independente, mas em total dependência e submissão ao poder do Espírito Santo. A unção não era para o Seu próprio benefício, mas para uma missão específica: "para pregar boas novas aos mansos (pobres)". O Evangelho é a boa notícia de que a salvação chegou para aqueles que reconhecem a sua pobreza e falência espiritual.',
    desc2: 'A missão do Messias é descrita em termos de libertação e cura profunda. Ele foi enviado para "restaurar os contritos de coração" (curar os corações quebrados pela dor e pelo pecado), "proclamar liberdade aos cativos, e a abertura de prisão aos presos". A humanidade sem Cristo está aprisionada por vícios, medos, culpa e pela tirania de Satanás. Jesus veio com as chaves para abrir as portas dessas prisões espirituais. Ele também veio para "apregoar o ano aceitável do Senhor" (uma referência ao Ano do Jubileu, quando todas as dívidas eram perdoadas e os escravos libertos) e "o dia da vingança do nosso Deus" (o juízo final sobre o mal).',
    desc3: 'O resultado do ministério do Messias é uma troca divina e maravilhosa (v. 3). Ele veio consolar os tristes e dar-lhes "uma coroa em vez de cinzas" (beleza em vez de luto), "óleo de alegria em vez de pranto" e "veste de louvor em vez de espírito angustiado". Jesus não apenas perdoa os nossos pecados; Ele transforma a nossa identidade e o nosso estado emocional. O objetivo final dessa transformação é a glória de Deus: "a fim de que se chamem árvores de justiça, plantações do Senhor, para que ele seja glorificado". Os corações quebrados que Jesus cura tornam-se monumentos vivos da justiça e da glória de Deus na terra.',
    concl: 'Isaías 61 nos garante que Jesus é a resposta completa para a miséria humana. Ele tem o Espírito, a unção e a autoridade para curar as nossas feridas mais profundas, quebrar as nossas correntes mais fortes e transformar as cinzas do nosso passado em uma coroa de beleza para a glória de Deus.'
  },
  {
    id: 'mat_14_13_21',
    intro: 'A multiplicação dos pães e peixes é o único milagre de Jesus (além da ressurreição) registrado nos quatro Evangelhos, o que demonstra a sua importância teológica central na igreja primitiva. O contexto deste milagre é profundamente comovente. Jesus havia acabado de receber a notícia da decapitação de João Batista (Seu primo e precursor). Buscando luto, descanso e tempo a sós com os Seus discípulos, Jesus retira-se de barco para um lugar deserto. No entanto, a multidão descobre o Seu destino e corre a pé pelas margens, chegando antes dEle. Em vez de Se irritar com a interrupção do Seu luto, a resposta de Jesus revela o coração compassivo de Deus e a Sua capacidade de prover abundantemente no "deserto".',
    desc1: 'Quando Jesus sai do barco e vê a grande multidão, a Sua reação não é de frustração por ter o Seu retiro arruinado. O texto diz: "E Jesus, saindo, viu uma grande multidão, e possuído de íntima compaixão para com ela, curou os seus enfermos". A compaixão de Cristo é mais forte do que a Sua própria dor e exaustão. Ao cair da tarde, os discípulos, agindo com uma lógica prática (e talvez querendo finalmente descansar), sugerem que Jesus despeça a multidão para que comprem comida nas aldeias. Os discípulos veem o problema (a fome), o lugar (o deserto) e a hora (tarde), e concluem que a única solução é mandar as pessoas embora.',
    desc2: 'A resposta de Jesus choca os discípulos: "Não mister que vão; dai-lhes vós de comer". Jesus os desafia a assumirem a responsabilidade, sabendo que eles não tinham os recursos. Os discípulos olham para o que têm e respondem com desespero: "Não temos aqui senão cinco pães e dois peixes". A matemática humana dizia que era impossível alimentar milhares de pessoas com o lanche de um menino (como detalhado em João 6). Mas Jesus diz: "Trazei-mos aqui". O milagre da provisão sempre começa quando entregamos a nossa insuficiência (o nosso "quase nada") nas mãos do Mestre.',
    desc3: 'Jesus ordena que a multidão se assente na relva (organizando o caos). Ele toma os cinco pães e os dois peixes, olha para o céu, abençoa, parte e dá aos discípulos para que distribuam. O milagre da multiplicação não aconteceu nas mãos dos discípulos, mas nas mãos de Jesus enquanto Ele partia o pão. O resultado é a abundância divina: "E comeram todos, e saciaram-se; e levantaram dos pedaços que sobejaram doze alcofas cheias". Havia cerca de cinco mil homens, além de mulheres e crianças (possivelmente mais de quinze mil pessoas). Deus não apenas supre a necessidade; Ele provê com sobra.',
    concl: 'A multiplicação dos pães nos ensina que, nas mãos de Jesus, o pouco é muito. Quando enfrentamos situações de escassez no "deserto" da vida, não devemos focar no que nos falta, mas entregar o pouco que temos a Cristo. Ele é o Pão da Vida, capaz de saciar a fome de uma multidão e ainda deixar sobras abundantes.'
  },
  {
    id: 'jhn_8_1_11',
    intro: 'A história da mulher pega em adultério é uma das narrativas mais dramáticas e reveladoras sobre a tensão entre a lei e a graça. Jesus estava ensinando no templo quando os escribas e fariseus interrompem a sessão arrastando uma mulher pega "no próprio ato" de adultério. Eles a colocam no meio da multidão, expondo-a à vergonha pública máxima. O objetivo deles, no entanto, não era a justiça moral, mas armar uma cilada teológica e política para Jesus. A resposta de Jesus a essa armadilha é uma obra-prima de sabedoria divina, que expõe a hipocrisia dos acusadores, cumpre as exigências da justiça e estende a graça transformadora a uma pecadora condenada.',
    desc1: 'A armadilha era perfeita. Os líderes religiosos citam a Lei de Moisés, que ordenava o apedrejamento para o adultério (embora, curiosamente, não tenham trazido o homem envolvido no ato). Eles perguntam a Jesus: "Tu, pois, que dizes?". Se Jesus dissesse para não apedrejá-la, Ele seria acusado de ser um falso profeta que desobedecia à Lei de Moisés. Se Ele dissesse para apedrejá-la, Ele perderia a Sua reputação de misericórdia e entraria em conflito com a lei romana (pois os judeus não tinham autoridade para executar a pena de morte). Jesus estava encurralado entre a lei de Deus e a lei de Roma.',
    desc2: 'Em vez de responder imediatamente, Jesus inclina-se e começa a escrever na terra com o dedo. (O que Ele escreveu é um dos maiores mistérios da Bíblia; alguns sugerem que Ele estava escrevendo os pecados dos acusadores, ou cumprindo Jeremias 17:13). Como eles insistiam na pergunta, Jesus se levanta e profere a sentença que desarma a armadilha: "Aquele que de entre vós está sem pecado seja o primeiro que atire pedra contra ela". Jesus não anula a Lei (o pecado ainda merecia a morte), mas Ele desqualifica os executores. A Lei exige juízes justos. Ao confrontar a consciência deles, Jesus expõe que todos ali eram transgressores da Lei.',
    desc3: 'A resposta de Jesus tem um efeito devastador sobre a multidão: "acusados pela consciência, saíram um a um, a começar pelos mais velhos até aos últimos". A hipocrisia não suporta a luz da santidade de Cristo. Ficam apenas Jesus e a mulher. Jesus, o único ali que realmente não tinha pecado e que tinha o direito legal e moral de atirar a primeira pedra, recusa-se a condená-la. Ele pergunta: "Mulher, onde estão aqueles teus acusadores? Ninguém te condenou?". Ela responde: "Ninguém, Senhor". Jesus então profere as palavras de graça e transformação: "Nem eu também te condeno; vai-te, e não peques mais".',
    concl: 'A história da mulher adúltera nos ensina que a graça de Jesus não minimiza o pecado, mas o perdoa. A religião sem graça usa a lei para apedrejar e destruir as pessoas; Jesus usa a graça para perdoar e restaurar. No entanto, o perdão de Cristo sempre vem acompanhado de uma ordem para a santidade: "não peques mais". A graça nos liberta da condenação para que possamos viver em obediência.'
  },
  {
    id: 'act_10_1_48',
    intro: 'O capítulo 10 de Atos é um dos momentos mais revolucionários e cruciais da história da Igreja. Até este ponto, o Cristianismo era visto essencialmente como uma seita judaica; o Evangelho havia sido pregado a judeus e samaritanos, mas a barreira de separação entre judeus e gentios (os não-judeus) permanecia intacta. A conversão de Cornélio é a história de como Deus quebrou essa barreira milenar. Para realizar isso, Deus teve que trabalhar simultaneamente em dois corações muito diferentes: no coração de um centurião romano (para prepará-lo para ouvir) e na teologia rígida do apóstolo Pedro (para prepará-lo para pregar). Esta narrativa prova que o Evangelho é universal e que a graça de Deus não faz acepção de pessoas.',
    desc1: 'A história começa em Cesareia com Cornélio, um centurião do exército romano. Apesar de ser um gentio e um oficial do império opressor, ele é descrito como "piedoso e temente a Deus", que dava esmolas e orava continuamente. A sua religiosidade, no entanto, não era suficiente para salvá-lo; ele precisava ouvir o Evangelho de Cristo. Um anjo aparece a Cornélio e lhe diz que as suas orações foram ouvidas, ordenando que ele mande buscar a Pedro, que estava na cidade de Jope. A obediência de Cornélio é imediata. Deus sempre providencia a luz do Evangelho para aqueles que buscam a verdade com um coração sincero.',
    desc2: 'Enquanto os mensageiros de Cornélio viajam, Deus começa a trabalhar na teologia de Pedro. Pedro estava orando no terraço quando tem uma visão de um grande lençol descendo do céu, cheio de animais impuros (segundo a lei levítica). Uma voz ordena: "Levanta-te, Pedro, mata e come". Pedro, preso às suas tradições religiosas, recusa: "De modo nenhum, Senhor, porque nunca comi coisa alguma comum e imunda". A voz o repreende: "Ao que Deus purificou não chames tu comum". A visão se repete três vezes. Deus não estava apenas mudando a dieta de Pedro; Ele estava destruindo o preconceito racial e religioso que impedia Pedro de entrar na casa de um gentio.',
    desc3: 'Quando os mensageiros chegam, o Espírito diz a Pedro para ir com eles sem hesitar. Pedro entra na casa de Cornélio (um ato que o tornaria cerimonialmente impuro) e encontra uma multidão reunida. Pedro confessa a sua mudança de paradigma: "Reconheço por verdade que Deus não faz acepção de pessoas". Ele prega o Evangelho da vida, morte e ressurreição de Jesus. Antes mesmo de Pedro terminar o sermão ou fazer um apelo, o Espírito Santo cai sobre todos os gentios que ouviam a palavra, e eles começam a falar em línguas, exatamente como aconteceu com os judeus no Pentecostes. Pedro, vendo a evidência inegável da aceitação de Deus, ordena que eles sejam batizados nas águas.',
    concl: 'A conversão de Cornélio nos ensina que a cruz de Cristo destruiu todas as barreiras raciais, culturais e religiosas. A graça de Deus não pode ser contida por tradições humanas ou preconceitos teológicos. Quando a Igreja se dispõe a obedecer ao Espírito Santo e a pregar a Cristo, Deus derrama o Seu poder sobre todos aqueles que creem, independentemente da sua origem.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 20');
