const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'act_8_26_40',
    intro: 'A história do encontro entre Filipe e o eunuco etíope é um dos relatos mais belos sobre a obediência radical à direção do Espírito Santo e a expansão transcultural do Evangelho. Filipe, um dos sete diáconos, estava no meio de um avivamento explosivo e bem-sucedido em Samaria, onde multidões estavam sendo curadas e salvas. No entanto, um anjo do Senhor lhe dá uma ordem que desafia a lógica humana: deixar o avivamento das multidões e ir para o sul, para uma estrada deserta que descia de Jerusalém a Gaza. Esta narrativa nos ensina que, para Deus, a salvação de uma única alma sedenta no deserto é tão importante quanto o avivamento de uma cidade inteira.',
    desc1: 'A obediência de Filipe é imediata e inquestionável: "Ele se levantou e foi". No deserto, ele encontra um homem de grande autoridade: o tesoureiro-mor da rainha de Candace, da Etiópia. Este eunuco era um prosélito ou simpatizante do judaísmo que havia viajado mais de mil quilômetros para adorar em Jerusalém. No entanto, ele voltava para casa com o coração ainda vazio, lendo o profeta Isaías em sua carruagem, mas sem compreender o significado. A religião o levou a Jerusalém, mas não lhe deu o Salvador. O Espírito Santo então diz a Filipe: "Chega-te, e ajunta-te a esse carro".',
    desc2: 'Filipe corre para a carruagem e ouve o eunuco lendo Isaías 53 (a profecia do Servo Sofredor). Filipe faz a pergunta crucial: "Entendes tu o que lês?". O eunuco, demonstrando grande humildade para um homem de sua posição, responde: "Como poderei entender, se alguém não me ensinar?". Ele convida Filipe para subir e sentar-se com ele. A passagem que ele lia descrevia um cordeiro mudo levado ao matadouro, cujo julgamento foi tirado. O eunuco pergunta se o profeta falava de si mesmo ou de outro. O texto diz que Filipe, "começando nesta Escritura, lhe anunciou a Jesus". O Antigo Testamento é a fechadura, e Jesus é a única chave que a abre.',
    desc3: 'A explicação de Filipe foi tão clara e o poder do Espírito tão convincente que, ao passarem por um lugar com água, o próprio eunuco toma a iniciativa: "Eis aqui água; que impede que eu seja batizado?". A fé genuína sempre busca a obediência pública. Filipe responde que é lícito se ele crer de todo o coração. O eunuco faz a confissão fundamental do Cristianismo: "Creio que Jesus Cristo é o Filho de Deus". Eles descem à água, Filipe o batiza e, imediatamente, o Espírito arrebata Filipe. O eunuco, embora deixado sozinho no deserto, segue o seu caminho "jubiloso", levando o Evangelho para o continente africano.',
    concl: 'A história de Filipe e do eunuco nos ensina a estarmos sempre sensíveis à voz do Espírito Santo, mesmo quando Ele nos chama para fora da nossa zona de conforto ou da nossa lógica ministerial. Deus está sempre preparando corações no "deserto" da vida, esperando apenas que um servo obediente se aproxime para lhes anunciar a Jesus.'
  },
  {
    id: 'gen_6_9_22',
    intro: 'A narrativa da Arca de Noé é muito mais do que uma história infantil sobre animais; é um dos relatos mais solenes sobre o juízo divino e a graça salvadora em toda a Bíblia. O mundo antediluviano havia chegado a um ponto de corrupção total e irreversível. O texto diz que "a maldade do homem se multiplicara sobre a terra e que toda a imaginação dos pensamentos de seu coração era só má continuamente". A terra estava cheia de violência, e Deus decidiu trazer o dilúvio para purificar a Sua criação. No meio dessa escuridão moral absoluta, a graça de Deus encontra um homem: Noé. A construção da arca torna-se o maior testemunho de fé e obediência contra a cultura da época.',
    desc1: 'O contraste entre Noé e a sua geração é absoluto. Enquanto o mundo estava corrompido, a Bíblia descreve Noé com três características fundamentais: ele era "varão justo" (tinha uma posição de retidão diante de Deus), era "perfeito em suas gerações" (tinha integridade moral em um ambiente depravado) e "andava com Deus" (tinha intimidade e comunhão diária com o Criador, assim como Enoque). A justiça de Noé não era a causa da graça de Deus, mas o fruto dela (Gênesis 6:8 diz que "Noé achou graça aos olhos do Senhor"). É possível viver uma vida santa e andar com Deus mesmo quando a sociedade inteira caminha na direção oposta.',
    desc2: 'Deus revela a Noé o Seu plano de juízo (o dilúvio) e o Seu plano de salvação (a arca). As instruções para a construção da arca são precisas e detalhadas: o tipo de madeira (gofer), as dimensões exatas (cerca de 135 metros de comprimento, 22 de largura e 13 de altura), os andares e a porta lateral. A construção da arca foi um projeto monumental que levou décadas. Durante todo esse tempo, Noé construiu um barco gigante em terra seca, longe de qualquer oceano, baseado apenas em uma palavra de Deus sobre uma chuva que nunca havia acontecido. A fé verdadeira obedece a Deus mesmo quando a obediência parece loucura para o mundo.',
    desc3: 'Além de construir a arca, Noé tinha a missão de reunir os animais e armazenar comida. O texto conclui com uma das declarações mais poderosas sobre a vida de Noé: "Assim fez Noé; consoante a tudo o que Deus lhe ordenou, assim o fez". Ele não questionou o design da arca, não reclamou do tempo que levaria e não tentou alterar o plano para acomodar os seus vizinhos. A obediência de Noé foi total, incondicional e perseverante. Através dessa obediência solitária, Deus preservou a raça humana, a vida animal e, mais importante, a linhagem através da qual o Messias viria.',
    concl: 'A arca de Noé é um tipo perfeito de Jesus Cristo. Assim como a arca foi o único refúgio seguro contra o juízo das águas, Cristo é o único refúgio contra o juízo final do pecado. A história de Noé nos desafia a andar com Deus em uma cultura corrompida e a obedecer à Sua Palavra, mesmo quando somos a minoria absoluta.'
  },
  {
    id: '1ki_17_8_16',
    intro: 'A história de Elias e a viúva de Sarepta ocorre durante os três anos e meio de seca severa que Deus enviou sobre Israel como juízo pela idolatria do rei Acabe. Quando o ribeiro de Querite seca, Deus dá a Elias uma ordem surpreendente: "Levanta-te, e vai para Sarepta, que é de Sidom, e habita ali; eis que eu ordenei ali a uma mulher viúva que te sustente". Sidom era o coração do território de Baal (o falso deus da chuva e da fertilidade) e a terra natal da perversa rainha Jezabel. Deus envia o Seu profeta não para um rei rico em Israel, mas para uma viúva pobre e gentia em território inimigo. Este milagre revela que a provisão de Deus frequentemente começa com um ato radical de fé e generosidade.',
    desc1: 'Quando Elias chega à porta da cidade, ele encontra a viúva apanhando lenha. Ele pede um pouco de água (um pedido razoável) e, em seguida, pede um bocado de pão (um pedido audacioso no meio da fome). A resposta da viúva revela o seu desespero absoluto: "Vive o Senhor teu Deus, que nem um bolo tenho, senão somente um punhado de farinha numa panela, e um pouco de azeite numa botija; e vês aqui apanhei dois cavacos, e vou prepará-lo para mim e para o meu filho, para que o comamos, e morramos". Ela estava preparando a sua última refeição. A escassez humana havia chegado ao seu limite final.',
    desc2: 'A resposta de Elias parece, à primeira vista, insensível e egoísta: "Não temas; vai, faze conforme à tua palavra; porém faze disso primeiro para mim um bolo pequeno, e traze-mo aqui; depois farás para ti e para teu filho". Elias não está sendo cruel; ele está convidando a viúva a dar um salto de fé. Ele exige que ela coloque Deus e o Seu profeta em primeiro lugar, antes da sua própria sobrevivência e da do seu filho. A verdadeira fé é testada não quando damos do que nos sobra, mas quando damos do que nos falta. A generosidade sacrificial é a chave que destranca o milagre.',
    desc3: 'O pedido de Elias vem acompanhado de uma promessa divina: "Porque assim diz o Senhor Deus de Israel: A farinha da panela não se acabará, e o azeite da botija não faltará até ao dia em que o Senhor dê chuva sobre a terra". A viúva obedece. Ela vai e faz conforme a palavra de Elias. O resultado é o milagre da provisão contínua: "E assim comeu ela, e ele, e a sua casa muitos dias. A farinha da panela não se acabou, e o azeite da botija não faltou". Deus não encheu a casa dela com sacos de farinha; Ele multiplicou o punhado diariamente. A provisão de Deus é diária e suficiente para cada dia.',
    concl: 'A história da viúva de Sarepta nos ensina que o pouco, quando colocado nas mãos de Deus com fé e prioridade, torna-se inesgotável. Quando confiamos na promessa de Deus acima das nossas circunstâncias e O colocamos em primeiro lugar, Ele sustenta a nossa vida mesmo nos tempos de maior escassez.'
  },
  {
    id: 'dan_1_8_21',
    intro: 'O primeiro capítulo de Daniel estabelece o fundamento moral e espiritual para todo o livro. O Império Babilônico, sob o rei Nabucodonosor, havia conquistado Jerusalém e levado cativos os jovens da elite judaica, incluindo Daniel, Hananias, Misael e Azarias. O objetivo da Babilônia não era apenas escravizá-los fisicamente, mas reeducá-los culturalmente. Eles receberam novos nomes (para apagar a sua identidade em Deus), nova literatura (para mudar a sua cosmovisão) e uma nova dieta (para integrá-los aos costumes pagãos). A decisão de Daniel de não se contaminar é uma aula atemporal sobre como viver em uma cultura hostil sem perder a identidade e a fidelidade a Deus.',
    desc1: 'A pressão para se conformar era imensa. Comer das iguarias do rei e beber do seu vinho era considerado um privilégio e uma honra, além de ser o caminho mais rápido para a ascensão política. No entanto, essa comida era provavelmente sacrificada aos ídolos babilônicos e violava as leis alimentares de Deus (Levítico 11). O versículo 8 é o ponto de virada: "E Daniel assentou no seu coração não se contaminar com a porção do manjar do rei, nem com o vinho que ele bebia". A santidade não acontece por acidente; ela é o resultado de uma decisão prévia e inegociável tomada no coração antes que a tentação se apresente.',
    desc2: 'A atitude de Daniel é tão importante quanto a sua decisão. Ele não faz um protesto arrogante, não organiza uma greve de fome e não insulta os babilônios. Ele age com sabedoria, respeito e submissão à autoridade. Ele "pediu ao chefe dos eunucos que lhe concedesse não se contaminar". Quando o chefe expressa medo de ser decapitado pelo rei se os jovens ficassem abatidos, Daniel propõe um teste razoável e prático de dez dias com uma dieta de legumes e água. A fé verdadeira não precisa ser beligerante; ela confia que Deus honrará a obediência e propõe soluções sábias.',
    desc3: 'Deus honra a fidelidade de Daniel de duas maneiras. Primeiro, Ele age na esfera relacional: "Ora, Deus fez com que Daniel achasse graça e misericórdia diante do chefe dos eunucos". Segundo, Ele age na esfera física e intelectual: após os dez dias, o semblante deles estava melhor e mais gordo do que o de todos os jovens que comiam as iguarias do rei. No final dos três anos de treinamento, quando foram avaliados pelo próprio Nabucodonosor, Deus lhes deu "o conhecimento e a inteligência em todas as letras, e sabedoria", sendo achados dez vezes mais sábios do que todos os magos e astrólogos do império.',
    concl: 'A decisão de Daniel nos ensina que a verdadeira influência no mundo não vem da assimilação e do compromisso com os seus valores, mas da separação santa e da fidelidade inegociável a Deus. Quando "assentamos no coração" honrar a Deus, Ele nos dá a graça, a sabedoria e a excelência necessárias para brilhar nas trevas da Babilônia.'
  },
  {
    id: 'mt_7_24_29',
    intro: 'A Parábola dos Dois Fundamentos é a grandiosa e solene conclusão do Sermão do Monte, o maior e mais profundo discurso de Jesus. Após expor a ética do Reino dos Céus, contrastar a verdadeira justiça com a hipocrisia religiosa e alertar sobre os falsos profetas, Jesus encerra com uma ilustração inesquecível sobre a construção de duas casas. O objetivo de Jesus não é apenas impressionar os Seus ouvintes com a Sua sabedoria, mas forçá-los a uma decisão radical. Esta parábola revela que a diferença entre a salvação e a ruína eterna não está na capacidade de ouvir a Palavra de Deus, mas na disposição de obedecê-la e praticá-la.',
    desc1: 'Jesus começa descrevendo o homem prudente (sábio): "Todo aquele, pois, que escuta estas minhas palavras, e as pratica, assemelhá-lo-ei ao homem prudente, que edificou a sua casa sobre a rocha". A rocha representa a própria pessoa de Cristo e a obediência aos Seus ensinamentos. Construir sobre a rocha é um trabalho árduo, invisível e demorado. Exige cavar fundo, remover a terra solta do orgulho e do pecado, e ancorar a vida na verdade imutável de Deus. A verdadeira sabedoria cristã não é o acúmulo de conhecimento teológico, mas a aplicação prática da Palavra de Deus no cotidiano.',
    desc2: 'Em seguida, Jesus descreve o homem insensato (louco): "E aquele que ouve estas minhas palavras, e não as cumpre, compará-lo-ei ao homem insensato, que edificou a sua casa sobre a areia". A areia representa a conveniência, a opinião pública, as emoções passageiras e a religiosidade superficial. Construir sobre a areia é fácil, rápido e atrai a atenção imediata. O homem insensato ouve a mesma mensagem, frequenta a mesma igreja e constrói uma casa que, por fora, pode parecer idêntica à do homem prudente. O perigo da religião superficial é que ela parece segura até que a crise chegue.',
    desc3: 'A prova final para ambas as casas é exatamente a mesma: "E desceu a chuva, e correram rios, e assopraram ventos, e combateram aquela casa". As tempestades da vida (provações, doenças, crises financeiras e, em última instância, o juízo final de Deus) são inevitáveis e atingem tanto os justos quanto os ímpios. A casa sobre a rocha "não caiu, porque estava edificada sobre a rocha". A fundação invisível garantiu a estabilidade visível. Mas a casa sobre a areia "caiu, e foi grande a sua queda". A falta de obediência prática resulta em ruína total e irreversível.',
    concl: 'Ouvir sermões, ler a Bíblia e concordar intelectualmente com Jesus não é suficiente para nos salvar das tempestades do juízo. A verdadeira segurança espiritual só é encontrada quando transformamos a escuta passiva em obediência ativa, construindo a nossa vida, caráter e esperança exclusivamente sobre a rocha inabalável que é Jesus Cristo.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 11');
