const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'gen_3_1_15',
    intro: 'O capítulo 3 de Gênesis é o eixo sobre o qual gira toda a história humana e a teologia bíblica. Ele narra a transição trágica da inocência no Éden para a rebelião, explicando a origem do mal, do sofrimento e da morte no nosso mundo. No entanto, no meio do julgamento mais severo já pronunciado, Deus não abandona a Sua criação. Este capítulo não apenas descreve a anatomia da tentação e as consequências devastadoras do pecado, mas também contém o "Protoevangelho" (o primeiro evangelho) — a promessa imutável de que Deus mesmo providenciaria um Redentor para esmagar o mal e restaurar a humanidade.',
    desc1: 'A tentação não começa com um ataque frontal, mas com uma distorção sutil da Palavra de Deus. A serpente (Satanás) aborda Eva com uma pergunta que planta a dúvida: "É assim que Deus disse?". Em seguida, o inimigo ataca o caráter de Deus, sugerindo que Ele é um ditador egoísta que está escondendo algo bom deles ("Deus sabe que... sereis como Deus"). A essência de todo pecado é a desconfiança na bondade de Deus e o desejo de autonomia — querer ser o próprio deus, definindo o que é certo e errado sem submissão ao Criador.',
    desc2: 'A queda ocorre quando Eva, e depois Adão, cedem ao desejo dos olhos e da carne. As consequências são imediatas e catastróficas. A primeira morte no Éden não foi física, mas relacional e espiritual. A intimidade é substituída pela vergonha (eles percebem que estão nus e tentam se cobrir com folhas de figueira), o amor é substituído pelo medo (eles se escondem da presença de Deus), e a responsabilidade é substituída pela transferência de culpa (Adão culpa Eva e, indiretamente, o próprio Deus que a deu; Eva culpa a serpente). O pecado sempre destrói os nossos relacionamentos com Deus, conosco mesmos e com os outros.',
    desc3: 'Deus age como um juiz justo, pronunciando as consequências do pecado sobre a serpente, a mulher e o homem (dor, suor e morte física). No entanto, no versículo 15, no meio da maldição sobre a serpente, Deus profere a maior promessa da história: "Porei inimizade entre ti e a mulher, entre a tua descendência e o seu descendente. Este te ferirá a cabeça, e tu lhe ferirás o calcanhar". Esta é a promessa da semente da mulher (Jesus Cristo). A cruz seria o calcanhar ferido de Cristo, mas a ressurreição seria a cabeça esmagada de Satanás.',
    concl: 'A história da queda nos ensina que o pecado sempre promete liberdade, mas entrega escravidão e morte. No entanto, a graça de Deus é maior do que o nosso fracasso. Antes mesmo de expulsar o homem do jardim, Deus já havia prometido o Salvador e providenciado vestes de pele (o primeiro sacrifício de sangue) para cobrir a sua vergonha, prefigurando a justiça de Cristo que nos cobre hoje.'
  },
  {
    id: '1ki_3_5_15',
    intro: 'O início do reinado de Salomão é marcado por um dos encontros mais extraordinários entre Deus e um líder humano. Em Gibeão, o principal lugar de sacrifícios antes da construção do Templo, o jovem rei Salomão oferece mil holocaustos ao Senhor. Em resposta a essa adoração extravagante, Deus lhe aparece em um sonho noturno e lhe faz uma oferta que é essencialmente um "cheque em branco" divino: "Pede-me o que queres que eu te dê". A resposta de Salomão revela as prioridades do seu coração e estabelece o padrão bíblico para a verdadeira liderança, que não busca o poder para si mesmo, mas a sabedoria para servir aos outros.',
    desc1: 'A resposta de Salomão começa com gratidão e humildade. Ele reconhece a bondade de Deus para com o seu pai, Davi, e admite a sua própria insuficiência para a tarefa que tem pela frente: "Sou ainda menino pequeno, não sei como sair, nem como entrar". A verdadeira sabedoria não começa com a autoconfiança ou com a presunção de competência, mas com o reconhecimento profundo da nossa total dependência de Deus. O maior perigo para um líder não é a falta de recursos, mas a ilusão de que ele é autossuficiente.',
    desc2: 'Diante da oferta ilimitada de Deus, Salomão não pede riqueza, vingança contra os seus inimigos políticos, longevidade ou glória pessoal. Ele pede: "Dá, pois, ao teu servo um coração compreensivo (literalmente, um coração que ouve) para julgar a teu povo, para que prudentemente discirna entre o bem e o mal". Salomão entende que o povo não pertence a ele, mas a Deus ("teu povo"), e que a sua função é ser um mordomo da justiça divina. Ele pede a capacidade de ouvir a Deus e de entender as necessidades do povo para governar com retidão.',
    desc3: 'O pedido de Salomão "pareceu bem aos olhos do Senhor". Deus se agrada quando as nossas orações refletem os Seus propósitos e não o nosso egoísmo. Como recompensa por ter pedido o que era certo e altruísta, Deus não apenas lhe concede uma sabedoria sem precedentes na história, mas também lhe dá por acréscimo tudo o que ele não pediu: riquezas, glória e a promessa de longevidade (condicionada à obediência). Deus é um Pai generoso que honra aqueles que priorizam o Seu Reino e a Sua justiça.',
    concl: 'A história do pedido de Salomão ilustra perfeitamente o princípio que Jesus ensinaria séculos depois: "Buscai primeiro o Reino de Deus e a sua justiça, e todas estas coisas vos serão acrescentadas". Quando buscamos a sabedoria de Deus para servir aos outros, Ele cuida das nossas necessidades pessoais. A humildade e um coração ensinável são os pré-requisitos para a verdadeira grandeza.'
  },
  {
    id: 'mrk_4_35_41',
    intro: 'O relato de Jesus acalmando a tempestade no Mar da Galileia é uma das demonstrações mais vívidas da Sua autoridade divina sobre a criação. Após um longo dia ensinando as multidões por meio de parábolas, Jesus instrui os Seus discípulos a passarem para a outra margem do lago. Durante a travessia noturna, uma tempestade repentina e violenta ameaça afundar o barco. Esta narrativa não é apenas um registro de um milagre físico, mas uma profunda alegoria sobre as tempestades da vida, a natureza do medo, a crise de fé e a descoberta de quem Jesus realmente é.',
    desc1: 'A tempestade surge enquanto os discípulos estão em obediência direta à palavra de Jesus ("Passemos para a outra margem"). Isso destrói a teologia popular de que as tempestades só vêm quando estamos em pecado ou fora da vontade de Deus. Muitas vezes, as maiores provações nos atingem exatamente quando estamos no centro da vontade divina. O Mar da Galileia era conhecido por essas tempestades repentinas (devido à sua geografia), mas esta era tão severa que até os pescadores experientes entraram em pânico, pois as ondas já enchiam o barco.',
    desc2: 'O contraste no barco é impressionante: enquanto os discípulos estão em pânico absoluto, Jesus está na popa, dormindo sobre um travesseiro. O sono de Jesus revela a Sua exaustão humana, mas também a Sua paz divina e confiança absoluta no Pai. Os discípulos O acordam com uma pergunta carregada de medo e acusação: "Mestre, não te importas que pereçamos?". O medo extremo frequentemente distorce a nossa visão do caráter de Deus, fazendo-nos questionar o Seu amor e o Seu cuidado por nós no meio da crise.',
    desc3: 'Jesus se levanta e não repreende os discípulos primeiro; Ele repreende a fonte do caos. Ele diz ao vento e ao mar: "Cala-te, aquieta-te". Imediatamente, o vento cessa e faz-se "grande bonança". Só então Ele se volta para os discípulos e faz a pergunta que vai ao cerne do problema: "Por que sois tão tímidos? Ainda não tendes fé?". O oposto da fé não é a dúvida, mas o medo. O milagre substitui o medo da tempestade por um temor reverente (assombro) diante do Criador: "Quem é este, que até o vento e o mar lhe obedecem?".',
    concl: 'A paz verdadeira não é a ausência de tempestades, mas a presença de Jesus no barco. Ele não prometeu uma travessia sem ventos contrários, mas garantiu que chegaríamos à outra margem. Aquele que tem o poder de silenciar os ventos e os mares com uma única palavra é perfeitamente capaz de acalmar o caos e o medo no seu coração.'
  },
  {
    id: 'luk_7_36_50',
    intro: 'O jantar na casa de Simão, o fariseu, é um dos encontros mais belos e contrastantes do ministério de Jesus. Simão convida Jesus para uma refeição, provavelmente por curiosidade teológica, mas O trata com frieza e omite as cortesias básicas de hospitalidade da época. O ambiente formal e religioso é subitamente interrompido pela entrada de uma mulher da cidade, conhecida como "pecadora" (provavelmente uma prostituta). O que se segue é uma colisão profunda entre a religiosidade orgulhosa que julga e a graça transformadora que perdoa, revelando a verdadeira essência da adoração.',
    desc1: 'A mulher entra na casa do fariseu (um ambiente hostil para ela) movida por uma necessidade desesperada de graça. Ela fica aos pés de Jesus, chorando tão intensamente que lava os Seus pés com as lágrimas, enxuga-os com os próprios cabelos (um ato de extrema humildade e quebra de decoro público), beija-os e os unge com um perfume caríssimo. A sua adoração é extravagante, silenciosa e profundamente emocional. Ela não pede nada; ela apenas derrama o seu amor e a sua gratidão diante dAquele que a aceitou.',
    desc2: 'Simão, o fariseu, observa a cena com nojo e julga silenciosamente: "Se este fora profeta, bem saberia quem e qual é a mulher que lhe tocou, pois é uma pecadora". A religião legalista sempre foca no pecado do outro e na pureza externa, sendo incapaz de compreender a graça. Jesus, lendo os pensamentos de Simão, conta a parábola de dois devedores: um devia quinhentos denários e o outro cinquenta. Como nenhum podia pagar, o credor perdoou a ambos. Jesus pergunta: "Qual deles o amará mais?". Simão responde corretamente: "Aquele a quem mais perdoou".',
    desc3: 'Jesus então aplica a parábola, contrastando a atitude de Simão com a da mulher. Simão não deu água para os pés de Jesus, não Lhe deu o beijo de saudação e não ungiu a Sua cabeça. A mulher, no entanto, não parou de lavar, beijar e ungir os Seus pés. Jesus profere o veredito da graça: "Perdoados lhe são os seus muitos pecados, porque ela muito amou; mas aquele a quem pouco se perdoa, pouco ama". O amor dela não comprou o perdão; o amor dela foi a resposta transbordante por já ter experimentado a imensidão do perdão de Cristo.',
    concl: 'A adoração verdadeira e apaixonada é o fruto direto da compreensão da nossa própria falência espiritual e da grandeza da graça de Deus. Aqueles que, como o fariseu, acham que têm poucos pecados para serem perdoados, amarão a Deus de forma fria e calculista. Mas aqueles que reconhecem a profundidade da sua dívida, derramarão tudo aos pés do Salvador.'
  },
  {
    id: 'act_12_1_19',
    intro: 'O capítulo 12 de Atos narra um dos momentos mais sombrios e, simultaneamente, mais gloriosos da Igreja Primitiva em Jerusalém. O rei Herodes Agripa I inicia uma perseguição violenta para agradar aos líderes religiosos judeus. Ele manda matar o apóstolo Tiago (irmão de João) à espada. Vendo que isso agradou à oposição, ele prende Pedro durante a Festa dos Pães Asmos, com a intenção de executá-lo publicamente após a Páscoa. A igreja parece encurralada pelo poder político e militar, mas a narrativa revela que a oração fervorosa de uma comunidade unida é uma força muito superior a qualquer exército ou prisão terrena.',
    desc1: 'A situação de Pedro era humanamente impossível. Ele estava na prisão de segurança máxima, guardado por quatro escoltas de quatro soldados cada (dezesseis soldados no total), dormindo acorrentado a dois guardas, com sentinelas nas portas. Herodes não queria correr riscos. Diante dessa demonstração de força imperial, a igreja não organiza um protesto, não tenta um resgate armado e não se entrega ao desespero. O texto diz: "Mas a igreja fazia contínua oração por ele a Deus". A oração é a resposta da igreja quando todas as portas terrenas estão trancadas.',
    desc2: 'Na noite anterior à sua execução, Pedro está dormindo profundamente. O seu sono não é de apatia, mas de uma paz sobrenatural e confiança absoluta na soberania de Deus (quer ele vivesse ou morresse). De repente, uma luz brilha na cela, e um anjo do Senhor acorda Pedro com um toque no lado. As correntes caem de suas mãos silenciosamente. O anjo lhe dá instruções simples: veste-te, calça as sandálias, põe a capa e segue-me. Eles passam pela primeira e pela segunda guarda sem serem notados, e o grande portão de ferro que dava para a cidade "se lhes abriu por si mesmo". Deus age no impossível quando a igreja ora.',
    desc3: 'Pedro, achando que era uma visão, só "cai em si" quando o anjo o deixa na rua. Ele vai para a casa de Maria (mãe de João Marcos), onde muitos estavam reunidos orando. Quando ele bate à porta, a criada Rode reconhece a sua voz e, de tanta alegria, esquece de abrir a porta e corre para avisar os outros. Ironicamente, a igreja que estava orando fervorosamente por um milagre custa a acreditar quando o milagre bate à porta, dizendo que Rode estava louca ou que era o anjo de Pedro. Deus é tão gracioso que responde às nossas orações mesmo quando a nossa fé é vacilante.',
    concl: 'A libertação de Pedro nos ensina que nenhuma prisão, corrente, guarda ou rei terreno pode resistir ao poder de Deus quando o Seu povo se une em oração fervorosa e perseverante. A oração não é o nosso último recurso; é a nossa primeira e mais poderosa arma espiritual contra as forças das trevas.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 7');
