const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'jer_18_1_10',
    intro: 'O capítulo 18 de Jeremias registra uma das lições objetivas mais famosas e poderosas do Antigo Testamento. Deus ordena ao profeta Jeremias que desça à casa do oleiro, prometendo que lá Ele lhe faria ouvir as Suas palavras. Em vez de receber uma visão celestial ou um sonho místico, Jeremias é enviado a uma oficina comum e suja para observar um artesão trabalhando com barro. A mensagem visual que Jeremias recebe ali revela a soberania absoluta de Deus sobre as nações, a fragilidade humana e a natureza condicional do juízo divino. É uma ilustração vívida de como Deus lida com o Seu povo, misturando o Seu poder soberano com a responsabilidade humana.',
    desc1: 'Jeremias desce à casa do oleiro e o observa trabalhando sobre as rodas. O texto diz: "Como o vaso, que ele fazia de barro, quebrou-se na mão do oleiro, tornou a fazer dele outro vaso, conforme o que pareceu bem aos olhos do oleiro fazer". O barro não é um material nobre como o ouro ou a prata; é terra misturada com água, sem valor intrínseco. O seu único valor está na habilidade das mãos do oleiro. O fato de o vaso se quebrar nas mãos do oleiro não significa que o oleiro falhou, mas que o barro tinha impurezas ou resistência. Em vez de jogar o barro fora, o oleiro pacientemente o amassa novamente e faz um vaso novo. Deus é o Oleiro; Israel (e a humanidade) é o barro.',
    desc2: 'A palavra do Senhor vem a Jeremias interpretando a cena: "Não poderei eu fazer de vós como fez este oleiro, ó casa de Israel? diz o Senhor. Eis que, como o barro na mão do oleiro, assim sois vós na minha mão, ó casa de Israel". Deus afirma o Seu direito soberano de moldar, quebrar e refazer as nações de acordo com o Seu propósito. O barro não tem o direito de questionar o oleiro (como Paulo argumentaria mais tarde em Romanos 9). A soberania de Deus é absoluta. No entanto, a lição da casa do oleiro não é sobre um fatalismo cego, mas sobre um relacionamento dinâmico.',
    desc3: 'Deus explica a dinâmica do Seu governo (v. 7-10). Ele diz que, se Ele decretar a destruição de uma nação, mas essa nação se arrepender da sua maldade, Ele "se arrependerá" (mudará o curso da Sua ação) do mal que intentou fazer. Da mesma forma, se Ele prometer edificar uma nação, mas ela fizer o mal e não ouvir a Sua voz, Ele "se arrependerá" do bem que prometeu. O "arrependimento" de Deus aqui não significa que Ele cometeu um erro, mas que Ele responde de forma consistente ao caráter moral das nossas escolhas. O barro tem a responsabilidade de ser maleável nas mãos de Deus através do arrependimento.',
    concl: 'A lição do oleiro nos ensina que somos apenas barro: frágeis, falhos e totalmente dependentes da graça de Deus. Quando o pecado nos "quebra" ou nos torna inúteis, Deus não nos joga no lixo. Se formos maleáveis através do arrependimento, Ele nos amassa novamente e nos refaz em um vaso novo para a Sua glória. A nossa maior segurança não está na nossa própria força, mas em permanecermos nas mãos do Oleiro.'
  },
  {
    id: 'hos_3_1_5',
    intro: 'O livro de Oseias é uma das profecias mais chocantes e emocionalmente intensas da Bíblia, porque a mensagem de Deus não é entregue apenas através de palavras, mas através do casamento trágico do próprio profeta. Deus havia ordenado que Oseias se casasse com Gômer, uma mulher que se tornaria adúltera, para ilustrar a infidelidade de Israel (a "esposa" de Deus) que havia se prostituído com ídolos. No capítulo 3, Gômer havia abandonado Oseias completamente, afundando-se tanto no pecado que acabou sendo vendida como escrava. É neste ponto de degradação total que Deus dá a Oseias uma ordem que desafia toda a lógica humana e a justiça legal: ele deve ir, comprá-la de volta e amá-la novamente. Este capítulo é o retrato definitivo da graça redentora.',
    desc1: 'A ordem divina é escandalosa (v. 1): "Vai outra vez, ama uma mulher, amada de seu amigo, e adúltera, como o Senhor ama os filhos de Israel, embora eles olhem para outros deuses, e amem os bolos de uvas". A lei de Moisés permitia o divórcio por adultério, e a sociedade exigiria que Oseias a rejeitasse. Mas Deus não lhe diz apenas para "perdoar" ou "tolerar" Gômer; Ele diz para "amá-la". O amor de Deus por Israel (e por nós) não é uma reação à nossa bondade, mas uma escolha soberana que persiste apesar da nossa traição. Os "bolos de uvas" eram iguarias usadas nos cultos pagãos de fertilidade; Israel preferia os prazeres baratos do pecado ao amor fiel de Deus.',
    desc2: 'Oseias obedece e vai ao mercado de escravos para resgatar a sua própria esposa (v. 2): "E a comprei para mim por quinze moedas de prata, e um ômer e meio de cevada". O preço pago era o valor de um escravo comum (trinta siclos de prata, metade em dinheiro e metade em grãos). Oseias não estava comprando uma mercadoria; ele estava pagando o preço do resgate (redenção) para libertar a mulher que já era legalmente sua, mas que havia se vendido à escravidão do pecado. Esta é a imagem perfeita do que Jesus fez na cruz: Ele pagou o preço do nosso resgate com o Seu próprio sangue para nos comprar de volta do mercado do pecado.',
    desc3: 'Após resgatá-la, Oseias estabelece as condições para a restauração (v. 3): "E lhe disse: Tu ficarás comigo muitos dias; não te prostituirás, nem serás de outro homem; e assim também eu serei para ti". A graça não é uma licença para continuar pecando. O resgate exige um período de purificação, isolamento e disciplina para que o relacionamento seja curado. Oseias aplica isso a Israel (v. 4-5): os israelitas ficariam "muitos dias sem rei, sem príncipe, sem sacrifício". O exílio seria o tempo de disciplina onde Deus removeria os ídolos do coração do povo. Mas o objetivo final não é a punição, é a restauração: "Depois tornarão os filhos de Israel, e buscarão ao Senhor seu Deus, e a Davi, seu rei; e temerão ao Senhor, e à sua bondade, no fim dos dias".',
    concl: 'Oseias 3 nos ensina que o amor de Deus é um amor que "compra de volta". Não importa quão longe tenhamos ido, quão sujos estejamos ou a quem nos tenhamos vendido, Deus está disposto a pagar o preço para nos resgatar. A cruz é a prova de que Deus nos ama não porque somos fiéis, mas porque Ele é fiel. A nossa resposta a esse amor escandaloso deve ser a fidelidade exclusiva a Ele.'
  },
  {
    id: 'mic_6_1_8',
    intro: 'O capítulo 6 de Miqueias é estruturado como um drama de tribunal cósmico (um "pleito" ou "controvérsia" da aliança). Deus é o Promotor e o Juiz; Israel é o réu; e os montes e os fortes alicerces da terra são convocados como o júri e as testemunhas. Deus acusa o Seu povo de ingratidão e quebra da aliança. O povo, reconhecendo a sua culpa, tenta descobrir como apaziguar a ira divina, oferecendo uma lista crescente de sacrifícios religiosos extravagantes. A resposta do profeta Miqueias (no versículo 8) corta toda a hipocrisia religiosa e resume, de forma brilhante e concisa, a essência do que Deus realmente exige do ser humano. Não é sobre rituais externos, mas sobre o caráter interno e a conduta prática.',
    desc1: 'O julgamento começa com Deus apresentando o Seu caso (v. 3-5). Ele não acusa com fúria, mas com a tristeza de um coração ferido: "Povo meu, que te tenho feito? E com que te enfadei? Testifica contra mim". Deus lembra a Israel o Seu histórico de fidelidade: Ele os libertou da escravidão no Egito, deu-lhes líderes (Moisés, Arão e Miriã) e os protegeu das maldições de Balaque e Balaão. A ingratidão de Israel era totalmente injustificável. Diante dessa acusação irrefutável, o povo (representado pelo adorador no v. 6-7) pergunta como pode se reconciliar: "Com que me apresentarei ao Senhor... ?".',
    desc2: 'A resposta do povo revela uma teologia distorcida. Eles acham que podem "comprar" o favor de Deus com rituais cada vez maiores. Eles começam com o normal: "holocaustos e bezerros de um ano". Depois, aumentam para o absurdo: "milhares de carneiros... dez mil ribeiros de azeite". Finalmente, no desespero do paganismo que os havia infectado, oferecem o sacrifício supremo e abominável: "Darei o meu primogênito pela minha transgressão, o fruto do meu ventre pelo pecado da minha alma?". Eles tratam Yahweh como uma divindade pagã que precisa ser subornada com sangue e óleo. Eles estão dispostos a dar qualquer coisa a Deus, exceto o que Ele realmente quer: o coração deles.',
    desc3: 'Miqueias interrompe a barganha religiosa com a declaração definitiva (v. 8): "Ele te declarou, ó homem, o que é bom; e que é o que o Senhor pede de ti, senão que pratiques a justiça, e ames a benignidade (misericórdia), e andes humildemente com o teu Deus?". Deus rejeita a religião divorciada da ética. Ele exige três coisas. Primeiro, "praticar a justiça": fazer o que é certo, tratar os outros com equidade e defender os oprimidos (ética social). Segundo, "amar a benignidade" (hesed): demonstrar amor leal, compaixão e graça (ética relacional). Terceiro, "andar humildemente com o teu Deus": reconhecer a nossa dependência, submeter-nos à Sua vontade e viver em comunhão diária com Ele (ética espiritual).',
    concl: 'Miqueias 6:8 nos ensina que Deus não se impressiona com o tamanho das nossas ofertas, com a emoção dos nossos cultos ou com o nosso ativismo religioso se a nossa vida diária for marcada pela injustiça, pela falta de perdão e pelo orgulho. O verdadeiro culto que agrada a Deus é uma vida transformada que reflete o Seu caráter: justa com os homens, misericordiosa com os fracos e humilde diante do Criador.'
  },
  {
    id: 'hab_3_17_19',
    intro: 'O livro de Habacuque é único entre os profetas menores porque, em vez de falar ao povo em nome de Deus, o profeta fala a Deus em nome do povo. O livro começa com Habacuque profundamente perturbado, questionando a justiça de Deus: por que Deus permite a injustiça em Judá e, pior ainda, por que Ele usaria os babilônios (uma nação ainda mais ímpia) para julgar o Seu povo? Deus responde revelando que Ele está no controle da história e que "o justo viverá pela sua fé" (2:4). O capítulo 3 é a oração final de Habacuque. Após ter uma visão aterrorizante do poder e do juízo de Deus que se aproxima, o profeta faz uma escolha consciente. Os versículos finais (17-19) são um dos maiores cânticos de fé incondicional de toda a Bíblia, declarando alegria em Deus mesmo quando todas as bênçãos terrenas desaparecem.',
    desc1: 'O versículo 17 descreve o pior cenário possível para uma sociedade agrícola antiga: o colapso total da economia e da provisão. Habacuque lista seis desastres sucessivos: "Ainda que a figueira não floresça, nem haja fruto na vide; ainda que decepcione o produto da oliveira, e os campos não produzam mantimento; ainda que as ovelhas da malhada sejam arrebatadas, e nos currais não haja gado". Ele não está descrevendo uma recessão leve, mas a fome e a devastação absolutas que acompanhariam a invasão babilônica. A figueira, a videira e a oliveira eram as bases da dieta e da economia. Sem ovelhas e gado, não havia carne, leite ou roupas. Tudo o que sustentava a vida e trazia conforto seria destruído.',
    desc2: 'A resposta natural a esse cenário seria o desespero, a amargura ou o abandono da fé. Mas a resposta de Habacuque (v. 18) é um triunfo da graça: "Todavia eu me alegrarei no Senhor; exultarei no Deus da minha salvação". A palavra "todavia" é a dobradiça da fé. A alegria de Habacuque não é um otimismo psicológico ("as coisas vão melhorar"), mas uma alegria teológica. Ele separa a sua alegria das suas circunstâncias. Ele não se alegra "nas" perdas, mas "no" Senhor. Ele descobre que, quando Deus é tudo o que lhe resta, Deus é suficiente. A sua salvação não estava nas colheitas, mas no próprio Deus.',
    desc3: 'O cântico termina com uma declaração de força e segurança (v. 19): "O Senhor Deus é a minha força, e fará os meus pés como os das cervas, e me fará andar sobre as minhas alturas". Habacuque reconhece que não tem força própria para suportar a invasão. O próprio Deus se torna a sua força. A metáfora da "cerva" (um tipo de veado) é poderosa: a cerva consegue andar com firmeza e agilidade em penhascos íngremes e perigosos sem escorregar. Deus não promete remover as "alturas" (os lugares perigosos e difíceis da vida), mas promete dar aos nossos pés a firmeza necessária para caminhar sobre elas com segurança e confiança.',
    concl: 'O final de Habacuque nos ensina que a verdadeira fé não é provada quando os celeiros estão cheios, mas quando os currais estão vazios. A adoração mais pura é aquela que diz: "Mesmo que eu perca tudo o que tenho, eu ainda tenho a Ti, e Tu és suficiente". Quando a nossa alegria está ancorada no Deus da nossa salvação, podemos caminhar com firmeza sobre as montanhas mais perigosas da vida.'
  },
  {
    id: 'exo_3_1_14',
    intro: 'O capítulo 3 de Êxodo narra um dos encontros mais cruciais e transformadores de toda a história bíblica: a revelação de Deus a Moisés na sarça ardente. Moisés, que havia sido um príncipe no Egito, estava agora com 80 anos, vivendo como um pastor de ovelhas exilado no deserto de Midiã há quatro décadas. Ele parecia ser um homem cujo propósito havia expirado, esquecido no lado oculto do deserto. No entanto, é exatamente na rotina do seu trabalho comum que Deus irrompe de forma espetacular. Este encontro não apenas comissiona Moisés para a tarefa impossível de libertar Israel da superpotência egípcia, mas também revela, pela primeira vez, o nome pessoal e o caráter eterno de Deus.',
    desc1: 'A narrativa começa com Moisés apascentando o rebanho do seu sogro perto do monte Horebe (Sinai). De repente, ele vê um fenômeno impossível: "eis que a sarça ardia no fogo, e a sarça não se consumia". A sarça (um arbusto espinhoso comum no deserto) representa a fragilidade humana e a condição humilde de Israel. O fogo representa a santidade, a presença e o juízo de Deus. O milagre não era o fogo, mas o fato de que o fogo não destruía o arbusto. Deus pode habitar no meio do Seu povo frágil sem consumi-los, por causa da Sua graça. Quando Moisés se desvia para ver a grande visão, Deus o chama pelo nome: "Moisés, Moisés!". A primeira ordem é de reverência: "Tira os sapatos de teus pés; porque o lugar em que tu estás é terra santa". A santidade não estava na terra, mas na presença do Deus que ali estava.',
    desc2: 'Deus então se identifica e revela o Seu coração (v. 6-9): "Eu sou o Deus de teu pai, o Deus de Abraão, o Deus de Isaque, e o Deus de Jacó". Ele é o Deus da aliança, que não esqueceu as Suas promessas. Deus declara que viu a aflição do Seu povo, ouviu o seu clamor e conheceu as suas dores. O sofrimento de Israel no Egito não passou despercebido. Deus diz: "Desci para livrá-lo". Mas a forma como Deus "desce" é surpreendente. Ele diz a Moisés: "Vem agora, pois, e eu te enviarei a Faraó, para que tires o meu povo... do Egito". Deus escolhe usar um pastor gago e idoso como o Seu instrumento de libertação. Moisés, sentindo a sua total inadequação, pergunta: "Quem sou eu, para que vá a Faraó?". A resposta de Deus não foca nas qualidades de Moisés, mas na Sua própria presença: "Certamente eu serei contigo".',
    desc3: 'Moisés faz uma segunda pergunta, buscando a autoridade divina para a sua missão (v. 13): "Eis que quando eu for aos filhos de Israel... e eles me disserem: Qual é o seu nome? Que lhes direi?". No mundo antigo, conhecer o nome de um deus era conhecer o seu caráter e poder. A resposta de Deus é a revelação teológica suprema do Antigo Testamento (v. 14): "EU SOU O QUE SOU (Yahweh)... Assim dirás aos filhos de Israel: EU SOU me enviou a vós". Este nome significa que Deus é autoexistente (Ele não depende de nada para existir), eterno (Ele é o mesmo ontem, hoje e sempre), imutável e totalmente presente. Ele é a realidade absoluta.',
    concl: 'O encontro na sarça ardente nos ensina que Deus frequentemente nos chama quando nos sentimos mais inadequados e esquecidos. A nossa utilidade para o Reino não depende de "quem nós somos", mas de "Quem está conosco". Quando Deus nos envia para tarefas impossíveis, Ele nos dá a única garantia de que precisamos: a presença do grande "EU SOU", o Deus que ouve o nosso clamor e tem poder para libertar.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 33');
