const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'lev_10_1_3',
    intro: 'O capítulo 10 de Levítico narra um dos eventos mais chocantes e trágicos do Antigo Testamento. O tabernáculo havia acabado de ser inaugurado com grande glória. Arão e seus filhos haviam sido consagrados como sacerdotes em uma cerimônia solene de sete dias. O fogo de Deus havia caído do céu e consumido o primeiro sacrifício, e todo o povo adorou. No entanto, no meio dessa celebração sagrada, Nadabe e Abiú, os dois filhos mais velhos de Arão, cometem um erro fatal na adoração. O julgamento de Deus é instantâneo e aterrorizante. Este texto é um lembrete severo de que Deus não pode ser adorado de qualquer maneira que o homem invente; a santidade de Deus exige obediência estrita às Suas instruções.',
    desc1: 'O Fogo Estranho. O texto diz: "E os filhos de Arão, Nadabe e Abiú, tomaram cada um o seu incensário e puseram neles fogo, e colocaram incenso sobre ele, e ofereceram fogo estranho perante a face do Senhor, o que lhes não ordenara" (v. 1). O problema não era o incenso em si, mas o "fogo estranho" (ou não autorizado). Eles ignoraram as instruções detalhadas que Deus havia dado a Moisés sobre como o incenso deveria ser oferecido (provavelmente pegando brasas de um lugar não autorizado, ou oferecendo no momento errado, ou talvez estivessem embriagados, como sugere o aviso no versículo 9). O pecado deles foi a presunção: eles acharam que podiam inovar na adoração e se aproximar de Deus nos seus próprios termos.',
    desc2: 'O Julgamento Instantâneo. A resposta de Deus à desobediência sacerdotal foi imediata e letal (v. 2): "Então saiu fogo de diante do Senhor e os consumiu; e morreram perante o Senhor". O mesmo fogo divino que havia consumido o sacrifício aceitável no capítulo anterior agora consome os sacerdotes desobedientes. Deus não permitiu que a corrupção entrasse no sacerdócio logo no seu início. O julgamento público serviu como um aviso aterrorizante para toda a nação de Israel: a proximidade com Deus é um privilégio perigoso. Quanto mais perto você está da glória de Deus, maior é a exigência de santidade e obediência.',
    desc3: 'A Santidade Vindicada e o Silêncio de Arão. Moisés explica a Arão a razão da tragédia (v. 3): "Isto é o que o Senhor falou, dizendo: Serei santificado naqueles que se chegarem a mim, e serei glorificado diante de todo o povo". Deus declara que Ele não tolerará ser tratado como comum ou profano por aqueles que O servem. A adoração deve ser feita segundo a revelação de Deus, não segundo a imaginação humana. A reação de Arão diante da morte dos seus dois filhos é uma das mais profundas demonstrações de submissão na Bíblia: "Porém Arão calou-se". Ele não argumentou, não reclamou e não acusou Deus de injustiça. Ele reconheceu a santidade e a justiça do julgamento divino.',
    concl: 'A história de Nadabe e Abiú destrói a ideia moderna de que Deus aceita qualquer tipo de adoração, desde que sejamos "sinceros". A sinceridade não substitui a obediência. Deus é um fogo consumidor, e devemos nos aproximar dEle com reverência, temor e estrita obediência à Sua Palavra, confiando unicamente no sacrifício perfeito de Cristo para a nossa aceitação.'
  },
  {
    id: '2sa_6_6_7',
    intro: 'O capítulo 6 de 2 Samuel narra a tentativa do rei Davi de trazer a Arca da Aliança (o símbolo supremo da presença de Deus) de volta para Jerusalém. A intenção de Davi era nobre e o evento começou com grande alegria, música e celebração. No entanto, a festa foi subitamente interrompida por uma tragédia aterrorizante. Quando os bois que puxavam a carroça tropeçaram, um homem chamado Uzá estendeu a mão para segurar a Arca e impedir que ela caísse. Instantaneamente, Deus o feriu de morte. Para a mente moderna, a ação de Uzá parece um reflexo natural e bem-intencionado, e a punição de Deus parece excessiva e cruel. Mas este texto nos ensina uma lição vital sobre a santidade de Deus e o perigo de tratarmos as coisas sagradas com familiaridade irreverente.',
    desc1: 'O Erro Fundamental: Ignorando a Palavra. O desastre não começou com a mão de Uzá, mas com o método de transporte. Davi colocou a Arca em um "carro novo" puxado por bois (v. 3). Esta era a maneira filisteia de transportar a Arca (1 Samuel 6). No entanto, a lei de Deus era explícita: a Arca deveria ser carregada apenas nos ombros dos sacerdotes levitas (coatitas), usando varas inseridas nas argolas, para que ninguém tocasse nela diretamente (Números 4:15; 7:9). Davi e os sacerdotes ignoraram a Palavra de Deus e adotaram um método pragmático e pagão. As boas intenções de Davi não anularam a sua desobediência à lei divina.',
    desc2: 'A Irreverência de Uzá. Quando os bois tropeçaram, a Arca balançou. Uzá, que havia crescido na casa onde a Arca esteve guardada por décadas (v. 3), estendeu a mão e a segurou. O texto diz que "a ira do Senhor se acendeu contra Uzá, e Deus o feriu ali por esta imprudência (ou irreverência)" (v. 7). O erro de Uzá foi a presunção. Ele assumiu que a sua mão (a mão de um homem pecador) era menos impura do que a terra (o chão que Deus criou). Ele tratou a santidade de Deus como algo comum que precisava da sua proteção humana. A familiaridade com o sagrado havia gerado nele uma falta de temor reverente.',
    desc3: 'A Reação de Davi: Temor e Correção. A morte de Uzá chocou Davi. Inicialmente, ele ficou "contristado" (irritado) e depois "temeu ao Senhor" (v. 8-9), perguntando: "Como virá a mim a arca do Senhor?". Davi interrompeu a viagem e deixou a Arca na casa de Obede-Edom. Durante três meses, Davi teve tempo para estudar a Lei e perceber o seu erro. Quando ele finalmente trouxe a Arca para Jerusalém (v. 12-15), ele o fez da maneira correta: os levitas a carregaram nos ombros, e Davi ofereceu sacrifícios a cada seis passos. A obediência substituiu o pragmatismo.',
    concl: 'A morte de Uzá é um aviso perene de que não podemos adorar a Deus ou fazer a Sua obra de qualquer maneira que nos pareça boa. O pragmatismo (fazer o que funciona) nunca deve substituir a obediência à revelação de Deus. A santidade de Deus não precisa da nossa proteção humana, mas exige a nossa reverência absoluta e obediência estrita.'
  },
  {
    id: '2ki_2_23_24',
    intro: 'O capítulo 2 de 2 Reis relata a transição do ministério profético de Elias para Eliseu. Após Elias ser levado ao céu em um redemoinho, Eliseu assume o manto profético e realiza o seu primeiro milagre curando as águas de Jericó. No entanto, a sua jornada para Betel é marcada por um dos incidentes mais perturbadores e frequentemente mal compreendidos do Antigo Testamento. Um grupo de "rapazes" zomba de Eliseu, e ele os amaldiçoa em nome do Senhor. Imediatamente, duas ursas saem do bosque e despedaçam quarenta e dois deles. Para entender este texto, precisamos ir além de uma leitura superficial e compreender o contexto cultural, a linguagem hebraica e o significado teológico do ministério profético.',
    desc1: 'A Natureza dos Zombadores. O texto diz que "uns rapazes pequenos saíram da cidade, e zombavam dele" (v. 23). A tradução "rapazes pequenos" ou "meninos" é enganosa. A palavra hebraica (na\'ar) é frequentemente usada para descrever jovens adultos, servos ou soldados (José aos 17 anos e os soldados de Davi são chamados de na\'ar). Eles não eram crianças inocentes brincando, mas uma gangue de jovens (mais de 42 deles) de Betel. Betel era o centro da idolatria em Israel (o bezerro de ouro de Jeroboão estava lá). Esta gangue representava a hostilidade da cidade idólatra contra o profeta do Deus verdadeiro.',
    desc2: 'O Significado da Zombaria. A zombaria deles foi específica: "Sobe, calvo; sobe, calvo!". A palavra "sobe" não era apenas um insulto geográfico; era uma referência sarcástica à ascensão de Elias. Eles estavam dizendo: "Se você é realmente o sucessor de Elias, suba ao céu como ele fez e desapareça daqui!". Chamar Eliseu de "calvo" era um insulto profundo no mundo antigo, denotando desonra e desprezo. A ofensa não era apenas contra a aparência física de Eliseu, mas uma rejeição deliberada e blasfema da autoridade profética que ele representava. Eles estavam rejeitando o próprio Deus ao rejeitar o Seu mensageiro.',
    desc3: 'O Julgamento Divino. Eliseu se vira, olha para eles e "os amaldiçoou no nome do Senhor" (v. 24). Eliseu não invocou as ursas; ele simplesmente pronunciou o julgamento divino sobre a rebelião deles. A resposta veio de Deus: "Então duas ursas saíram do bosque, e despedaçaram quarenta e dois daqueles rapazes". O julgamento severo foi um aviso nacional. Deus estava estabelecendo a autoridade de Eliseu no início do seu ministério, provando que a Palavra do Senhor não pode ser zombada impunemente. A idolatria e a rebelião de Betel não seriam toleradas.',
    concl: 'Este incidente chocante nos ensina que Deus leva a sério a honra dos Seus mensageiros e a autoridade da Sua Palavra. A zombaria contra as coisas sagradas e a rejeição deliberada da verdade divina trazem consequências severas. Deus é amoroso, mas também é o Juiz santo que não permitirá que a Sua glória seja escarnecida.'
  },
  {
    id: 'mat_12_39_40',
    intro: 'No capítulo 12 de Mateus, a oposição dos líderes religiosos contra Jesus atinge um ponto crítico. Eles já O haviam acusado de quebrar o sábado e de expulsar demônios pelo poder de Satanás. Agora, com uma hipocrisia impressionante, alguns escribas e fariseus pedem a Jesus um "sinal" (um milagre espetacular no céu) para provar a Sua autoridade messiânica. Eles ignoram os inúmeros milagres de cura e libertação que Ele já havia feito diante dos seus olhos. A resposta de Jesus é uma repreensão severa e uma profecia enigmática. Ele se recusa a fazer um truque de mágica para satisfazer a incredulidade deles, oferecendo apenas o "sinal do profeta Jonas", que aponta para o evento central da história da redenção: a Sua morte e ressurreição.',
    desc1: 'A Geração Má e Adúltera. Jesus responde ao pedido deles com uma condenação contundente: "Uma geração má e adúltera pede um sinal" (v. 39). A palavra "adúltera" aqui não se refere à imoralidade sexual, mas à infidelidade espiritual. No Antigo Testamento, Israel era frequentemente descrito como a "esposa" de Deus. Quando o povo abandonava a Deus para seguir ídolos, os profetas os chamavam de adúlteros. Jesus está dizendo que os líderes religiosos, apesar da sua aparência de piedade, eram espiritualmente infiéis. Eles não queriam a verdade; eles queriam um espetáculo que eles pudessem controlar. A incredulidade deles não era falta de evidência, mas dureza de coração.',
    desc2: 'O Sinal de Jonas. Jesus declara que nenhum sinal lhes será dado, "senão o sinal do profeta Jonas". Jonas foi o profeta rebelde do Antigo Testamento que foi engolido por um grande peixe após tentar fugir do chamado de Deus. Jesus explica o paralelo no versículo 40: "Pois, como Jonas esteve três dias e três noites no ventre da baleia, assim estará o Filho do homem três dias e três noites no seio da terra". Jesus usa a experiência histórica de Jonas como uma tipologia (uma prefiguração) da Sua própria morte, sepultamento e ressurreição. A descida de Jonas às profundezas e o seu retorno "à vida" apontavam para o triunfo final de Cristo sobre a morte.',
    desc3: 'A Ressurreição como a Prova Definitiva. O "sinal de Jonas" é a ressurreição. Jesus está dizendo que a prova definitiva da Sua identidade não seria um milagre no céu para entreter os fariseus, mas a Sua vitória sobre a morte. A ressurreição é o milagre que valida todos os outros milagres e ensinamentos de Jesus. Se os líderes religiosos rejeitassem o sinal da ressurreição (como de fato fizeram), nenhuma outra evidência os convenceria. Jesus continua nos versículos seguintes dizendo que os homens de Nínive (que se arrependeram com a pregação de Jonas) se levantarão no juízo contra aquela geração, porque "está aqui quem é maior do que Jonas".',
    concl: 'Jesus nos ensina que a fé verdadeira não é construída sobre a busca incessante por sinais e maravilhas espetaculares. A evidência suprema do amor e do poder de Deus já foi dada na história: a cruz vazia e o túmulo vazio. Se a ressurreição de Cristo não for suficiente para nos levar ao arrependimento e à fé, nenhum outro milagre o fará.'
  },
  {
    id: 'mar_11_12_14',
    intro: 'O capítulo 11 de Marcos relata os eventos da última semana do ministério terreno de Jesus (a Semana da Paixão). No dia seguinte à Sua entrada triunfal em Jerusalém, Jesus está a caminho da cidade, vindo de Betânia. Sentindo fome, Ele se aproxima de uma figueira que tinha folhas, mas, ao não encontrar frutos, Ele amaldiçoa a árvore, e ela seca desde as raízes. Este é o único milagre destrutivo de Jesus registrado nos Evangelhos, e frequentemente causa perplexidade. Por que Jesus amaldiçoaria uma árvore, especialmente quando o texto diz que "não era tempo de figos"? A resposta não está na botânica, mas na teologia. Este milagre é uma parábola em ação, um julgamento profético contra a nação de Israel e o seu sistema religioso vazio.',
    desc1: 'A Fome e a Expectativa. O texto começa notando a humanidade de Jesus: "teve fome" (v. 12). Vendo de longe uma figueira com folhas, Ele foi ver se encontraria algo nela. Na Palestina, as figueiras frequentemente produzem pequenos brotos comestíveis (chamados taqsh) antes ou junto com as folhas, mesmo antes da colheita principal dos figos. A presença de folhas em uma figueira era uma promessa visual de que haveria algum fruto. A árvore estava "anunciando" que tinha algo a oferecer.',
    desc2: 'A Decepção e a Maldição. Quando Jesus chega à árvore, Ele não encontra nada além de folhas, "porque não era tempo de figos" (a colheita principal ainda estava longe). A árvore era uma fraude: ela tinha a aparência de vida e frutificação (as folhas), mas não tinha a substância (o fruto). Jesus então profere a maldição (v. 14): "Nunca mais coma alguém fruto de ti". Os discípulos ouviram isso. No dia seguinte, eles veriam a árvore seca desde as raízes (v. 20). Jesus usou o Seu poder divino para destruir a árvore como um sinal visível e permanente.',
    desc3: 'O Significado Profético: O Julgamento de Israel. A figueira é um símbolo frequente de Israel no Antigo Testamento (Oséias 9:10; Joel 1:7). O que Jesus fez com a figueira foi uma representação visual do que Ele estava prestes a fazer com o templo em Jerusalém (que Ele purificaria logo em seguida, expulsando os cambistas). O sistema religioso de Israel, centrado no templo, era como aquela figueira: tinha muitas "folhas" (rituais, sacrifícios, multidões, pompa religiosa), mas não tinha "fruto" (arrependimento verdadeiro, justiça, amor a Deus e às nações). A maldição da figueira foi o julgamento de Jesus sobre a religião hipócrita. Deus não aceita a aparência de piedade sem a realidade da obediência.',
    concl: 'O milagre da figueira amaldiçoada é um aviso solene para a Igreja e para cada crente individualmente. Deus não se impressiona com as nossas "folhas" (frequência aos cultos, vocabulário religioso, ativismo). Ele procura "frutos" (o fruto do Espírito, santidade, amor prático). A religião sem fruto atrai o julgamento divino, não a bênção.'
  },
  {
    id: 'joh_6_53_54',
    intro: 'O capítulo 6 de João contém o longo e profundo "Discurso do Pão da Vida". No dia anterior, Jesus havia alimentado milagrosamente uma multidão de cinco mil homens com cinco pães e dois peixinhos. A multidão, maravilhada com o milagre físico, queria fazê-Lo rei à força. No dia seguinte, eles O procuram novamente, esperando mais comida grátis. Jesus confronta as motivações carnais deles e tenta elevar a visão deles do pão físico para a realidade espiritual. Ele declara ser o "Pão da Vida" que desceu do céu. Quando os judeus murmuram, Jesus intensifica a Sua linguagem, proferindo palavras que soaram chocantes e até canibais para os Seus ouvintes: Ele ordena que eles comam a Sua carne e bebam o Seu sangue para terem a vida eterna.',
    desc1: 'A Necessidade Absoluta de Cristo. Jesus declara (v. 53): "Na verdade, na verdade vos digo que, se não comerdes a carne do Filho do homem, e não beberdes o seu sangue, não tereis vida em vós mesmos". Para um judeu, a ideia de beber sangue era uma violação direta e repulsiva da Lei de Moisés (Levítico 17:10-14). Jesus está usando uma metáfora intencionalmente chocante para destruir qualquer ideia de salvação superficial. "Comer" e "beber" representam a apropriação pessoal, íntima e total. Assim como o corpo físico morre sem comida e água, a alma humana está morta e não tem vida em si mesma a menos que receba e internalize Jesus Cristo.',
    desc2: 'A Promessa da Vida Eterna e da Ressurreição. O versículo 54 traz a promessa positiva: "Quem come a minha carne e bebe o meu sangue tem a vida eterna, e eu o ressuscitarei no último dia". Jesus não está falando sobre o sacramento da Ceia do Senhor (que ainda não havia sido instituído), mas sobre a realidade espiritual que a Ceia representa: a fé na Sua obra expiatória. A Sua "carne" e o Seu "sangue" apontam diretamente para a cruz, onde o Seu corpo seria partido e o Seu sangue derramado como sacrifício pelos nossos pecados. Crer em Jesus é "alimentar-se" da Sua morte substitutiva. Aquele que faz isso recebe a vida eterna no presente e a garantia da ressurreição física no futuro.',
    desc3: 'O Escândalo do Evangelho. As palavras de Jesus foram tão ofensivas que, a partir daquele momento, "muitos dos seus discípulos tornaram para trás, e já não andavam com ele" (v. 66). Jesus não suavizou a Sua mensagem para manter a multidão. O evangelho é inerentemente escandaloso para a mente carnal. Ele exige que reconheçamos a nossa total falência espiritual e dependamos exclusivamente da morte sangrenta de um Salvador crucificado. A verdadeira fé não é apenas admirar os ensinamentos de Jesus, mas "devorar" a Sua obra redentora como a nossa única fonte de vida.',
    concl: 'Jesus nos ensina que a salvação não é um mero assentimento intelectual a um conjunto de doutrinas, mas uma união vital e orgânica com Ele. Assim como o alimento físico se torna parte do nosso corpo, Cristo deve se tornar a própria substância da nossa vida espiritual. A cruz é o único banquete que pode satisfazer a fome da alma humana.'
  },
  {
    id: 'heb_6_4_6',
    intro: 'Hebreus 6:4-6 é amplamente considerada uma das passagens mais difíceis, aterrorizantes e debatidas de todo o Novo Testamento. O autor está escrevendo a cristãos judeus que, sob intensa perseguição, estavam sendo tentados a abandonar a fé em Cristo e retornar aos rituais do judaísmo. Após exortá-los a amadurecerem na fé, o autor profere uma advertência severa sobre o perigo da apostasia (o abandono deliberado e definitivo da fé). O debate teológico central em torno deste texto é: ele ensina que um verdadeiro crente pode perder a salvação, ou ele descreve falsos convertidos que experimentaram a graça de Deus superficialmente, mas nunca foram verdadeiramente regenerados?',
    desc1: 'A Descrição da Experiência Espiritual. O autor descreve pessoas que tiveram privilégios espirituais extraordinários (v. 4-5). Eles foram "uma vez iluminados" (entenderam a verdade do evangelho), "provaram o dom celestial" (experimentaram as bênçãos da salvação), "fizeram-se participantes do Espírito Santo" (tiveram alguma comunhão ou influência do Espírito), "provaram a boa palavra de Deus" (ouviram e apreciaram a pregação) e provaram "as virtudes do século futuro" (presenciaram ou experimentaram milagres). Esta é uma descrição de pessoas que estiveram profundamente envolvidas na vida da igreja e experimentaram o poder de Deus de perto.',
    desc2: 'A Queda Irreversível. O versículo 6 apresenta a tragédia: "E recaíram (caíram, apostataram), sejam outra vez renovados para arrependimento". O autor afirma que é "impossível" que essas pessoas sejam trazidas de volta ao arrependimento. A razão é dada a seguir: "pois assim, quanto a eles, de novo crucificam o Filho de Deus, e o expõem ao vitupério (vergonha pública)". A apostasia descrita aqui não é um pecado de fraqueza, uma dúvida passageira ou um desvio moral temporário. É uma rejeição consciente, deliberada e hostil de Jesus Cristo após ter conhecido a verdade. Ao rejeitarem a Cristo e voltarem ao judaísmo, eles estavam concordando com os fariseus que O crucificaram, declarando que Ele era um impostor digno de morte.',
    desc3: 'A Interpretação Teológica. Existem duas visões principais. A visão arminiana argumenta que essas pessoas eram verdadeiros crentes que perderam a salvação através da apostasia. A visão calvinista argumenta que, embora essas pessoas tivessem grandes experiências espirituais e conhecimento (como Judas Iscariotes), elas nunca foram verdadeiramente nascidas de novo (regeneradas), pois a verdadeira fé persevera até o fim (1 João 2:19). Independentemente da visão teológica, a advertência prática é a mesma: brincar com a graça de Deus é perigoso. Se alguém rejeita a única provisão de Deus para o pecado (o sacrifício de Cristo), não resta mais nenhum outro sacrifício, apenas o juízo.',
    concl: 'Hebreus 6 não foi escrito para aterrorizar crentes sensíveis que lutam contra o pecado ou a dúvida (o verdadeiro crente se entristece com o seu pecado e busca o arrependimento). Foi escrito para alertar contra a presunção e o endurecimento do coração. A passagem nos exorta a não nos contentarmos com uma experiência religiosa superficial, mas a prosseguirmos para a maturidade, ancorando a nossa fé firmemente na obra consumada de Cristo.'
  },
  {
    id: '1jo_5_16_17',
    intro: 'No final da sua Primeira Epístola, o apóstolo João trata do tema da oração intercessória pelos irmãos na fé. Ele encoraja os crentes a orarem com confiança, sabendo que Deus ouve os pedidos feitos segundo a Sua vontade. No entanto, nos versículos 16 e 17, João introduz um conceito misterioso e perturbador que tem intrigado os estudiosos da Bíblia por séculos: o "pecado para a morte". Ele instrui os crentes a orarem pelos irmãos que cometem pecados que não são para a morte, mas diz que não ordena que se ore por aquele que comete o pecado para a morte. O que é este pecado, e por que a oração é inútil neste caso?',
    desc1: 'A Intercessão pelo Irmão que Peca. João começa com uma instrução encorajadora (v. 16a): "Se alguém vir pecar seu irmão, pecado que não é para morte, orará, e Deus dará a vida àqueles que não pecarem para morte". A vida cristã em comunidade envolve cuidar uns dos outros. Quando vemos um irmão caindo em pecado, a nossa primeira resposta não deve ser a fofoca ou o julgamento, mas a oração intercessória. João promete que Deus responderá a essa oração, restaurando a vitalidade espiritual ("dará a vida") do irmão que se desviou. A maioria dos pecados cometidos pelos crentes cai nesta categoria: pecados de fraqueza, ignorância ou falha moral que podem ser perdoados através do arrependimento.',
    desc2: 'O Pecado para a Morte. A dificuldade surge na segunda parte do versículo 16: "Há pecado para morte, e por esse não digo que ore". O que é o pecado para a morte? Existem três interpretações principais: 1) Um pecado específico e terrível (como assassinato ou adultério) punido com a morte física por Deus (como Ananias e Safira em Atos 5, ou os crentes em Corinto em 1 Coríntios 11:30). 2) A apostasia total e definitiva, a rejeição consciente de Cristo e do evangelho por alguém que antes professava a fé (semelhante ao aviso em Hebreus 6). 3) A blasfêmia contra o Espírito Santo (o endurecimento final do coração que recusa o arrependimento). A maioria dos estudiosos concorda que se refere a um estado de rebelião obstinada e final contra Deus, onde o coração se torna tão endurecido que o arrependimento se torna impossível.',
    desc3: 'A Distinção dos Pecados. João esclarece no versículo 17: "Toda a iniquidade é pecado, e há pecado que não é para morte". João não quer que os crentes pensem que alguns pecados não têm importância. Toda quebra da lei de Deus é pecado e ofende a santidade divina. No entanto, ele faz uma distinção nos resultados e na natureza da rebelião. Há pecados dos quais um crente pode se arrepender e ser restaurado, e há um nível de rebelião (o pecado para a morte) que cruza uma linha invisível da graça de Deus, resultando em julgamento definitivo (seja morte física ou condenação eterna).',
    concl: 'Esta passagem difícil nos ensina duas verdades vitais. Primeiro, a importância crucial da oração intercessória; somos chamados a lutar espiritualmente pela restauração dos nossos irmãos que caem. Segundo, a seriedade do pecado; não podemos brincar com a rebelião contra Deus, presumindo que a graça sempre estará disponível, pois existe um ponto de endurecimento do qual não há retorno.'
  },
  {
    id: 'jdg_11_30_39',
    intro: 'A história de Jefté no livro de Juízes é uma das narrativas mais trágicas e perturbadoras do Antigo Testamento. Jefté era um guerreiro valente, mas marginalizado (filho de uma prostituta), que foi chamado pelos líderes de Gileade para liderar Israel contra a ameaça dos amonitas. Antes de entrar na batalha, Jefté, impulsionado por uma mistura de zelo religioso e ignorância teológica, faz um voto precipitado a Deus. O resultado desse voto culmina no sacrifício da sua própria filha, a sua única herdeira. Este texto levanta questões profundas sobre o caráter de Deus, a natureza dos votos e as consequências desastrosas do sincretismo religioso (a mistura da fé em Yahweh com práticas pagãs).',
    desc1: 'O Voto Precipitado. O versículo 30 relata o voto de Jefté: "Se tu me deres totalmente os filhos de Amom na minha mão, aquilo que, saindo da porta de minha casa, me vier ao encontro... será do Senhor, e o oferecerei em holocausto". Jefté tentou barganhar com Deus, oferecendo um sacrifício humano (ou animal, dependendo do que saísse da casa) em troca da vitória militar. O texto anterior (v. 29) diz que "o Espírito do Senhor veio sobre Jefté", garantindo-lhe a vitória. O voto era completamente desnecessário. O erro de Jefté foi tratar Yahweh como os deuses pagãos de Canaã (como Moloque), que exigiam sacrifícios humanos para serem apaziguados. A lei de Deus proibia estritamente o sacrifício humano (Deuteronômio 12:31).',
    desc2: 'A Consequência Trágica. Deus concede a vitória a Jefté. Quando ele retorna para casa triunfante, a tragédia acontece (v. 34): "Eis que a sua filha lhe saiu ao encontro com adufes e com danças; e era ela a única filha". A alegria da vitória transforma-se em desespero absoluto. Jefté rasga as suas vestes e culpa a filha: "Ah, filha minha! muito me abateste... porque abri a minha boca ao Senhor, e não tornarei atrás". Em vez de reconhecer o seu voto como pecaminoso e buscar o perdão de Deus (a lei previa resgate para votos imprudentes em Levítico 27), o orgulho e a teologia distorcida de Jefté o levam a cumprir a promessa insana.',
    desc3: 'A Submissão da Filha e o Cumprimento do Voto. A resposta da filha de Jefté é de uma submissão heroica e trágica (v. 36): "Pai meu, se abriste a tua boca ao Senhor, faze de mim como saiu da tua boca". Ela pede apenas dois meses para chorar a sua virgindade (o fato de que ela morreria sem casar e ter filhos, o que era uma grande tragédia na cultura israelita) com as suas amigas nos montes. Após os dois meses, ela retorna, e Jefté "cumpriu nela o seu voto que tinha feito" (v. 39). A maioria dos estudiosos concorda que ele a ofereceu literalmente como sacrifício humano, um ato de abominação que reflete a escuridão moral da época dos Juízes, onde "cada um fazia o que parecia reto aos seus olhos".',
    concl: 'A história de Jefté não é um exemplo de fé a ser imitado, mas um aviso terrível. Ela nos ensina os perigos de tentar barganhar com Deus, a loucura de fazer promessas precipitadas e as consequências mortais de não conhecermos a Palavra de Deus. Deus não quer sacrifícios tolos baseados na ignorância, mas obediência baseada na verdade da Sua Palavra.'
  },
  {
    id: '1sa_16_14',
    intro: 'O versículo 14 do capítulo 16 de 1 Samuel marca um ponto de virada sombrio e trágico na história do primeiro rei de Israel. Saul havia sido escolhido por Deus, ungido por Samuel e capacitado pelo Espírito Santo para liderar a nação. No entanto, após uma série de desobediências deliberadas (culminando na recusa em destruir os amalequitas no capítulo 15), Deus rejeitou Saul como rei. O versículo 14 descreve a consequência espiritual dessa rejeição divina em duas ações simultâneas: a retirada do Espírito do Senhor e o envio de um "espírito mau da parte do Senhor". Este texto levanta questões teológicas profundas sobre a soberania de Deus, a natureza do mal e a disciplina divina.',
    desc1: 'A Retirada do Espírito do Senhor. O texto começa com uma declaração assustadora: "E o Espírito do Senhor se retirou de Saul". No Antigo Testamento, a presença do Espírito Santo sobre um líder (como um rei, juiz ou profeta) não era necessariamente uma garantia de salvação eterna, mas uma capacitação especial para o ofício e o serviço. Quando Saul persistiu na rebelião e no orgulho, Deus retirou a Sua unção, a Sua proteção e a Sua sabedoria. Saul foi deixado à sua própria sorte, governando apenas com a sua força carnal. A perda da presença capacitadora de Deus é o maior julgamento que um líder pode sofrer.',
    desc2: 'O Envio do Espírito Mau. A segunda parte do versículo é a mais difícil: "...e o assombrava um espírito mau da parte do Senhor". Como um Deus perfeitamente santo pode enviar um "espírito mau"? A teologia bíblica ensina que Deus é soberano sobre todo o universo, incluindo o reino espiritual das trevas. Satanás e os demônios não são deuses independentes; eles são criaturas rebeldes que operam sob a permissão e os limites estabelecidos por Deus (como visto no livro de Jó). Deus não é o autor do mal, mas Ele pode usar espíritos malignos como instrumentos do Seu julgamento e disciplina. Ao retirar a Sua proteção, Deus permitiu que um espírito demoníaco atormentasse a mente de Saul, causando-lhe depressão, paranoia e acessos de fúria.',
    desc3: 'O Contraste com Davi. Este versículo deve ser lido em contraste direto com o versículo anterior (v. 13), onde Davi é ungido rei e "o Espírito do Senhor se apoderou de Davi". O autor está mostrando a transferência do favor divino. Enquanto o Espírito de Deus desce sobre Davi, capacitando-o para o futuro, o Espírito se retira de Saul, deixando-o em trevas. A ironia trágica da história é que a única coisa que podia acalmar o tormento demoníaco de Saul era a música tocada por Davi (v. 23), o homem que Deus havia escolhido para substituí-lo.',
    concl: 'A tragédia de Saul é um aviso solene sobre o perigo da desobediência contínua e do orgulho. Deus é paciente, mas o Seu Espírito não contenderá para sempre com o homem rebelde. A maior tragédia na vida de um crente não é a perda de bens, posição ou saúde, mas a perda da comunhão e da presença capacitadora do Espírito Santo.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 38');
