const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'gen_18_1_15',
    intro: 'O capítulo 18 de Gênesis narra uma das teofanias (aparições de Deus) mais fascinantes do Antigo Testamento. Abraão, agora com 99 anos, estava sentado à porta da sua tenda no calor do dia, nos carvalhais de Manre. De repente, três homens aparecem diante dele. A narrativa revela rapidamente que um desses homens é o próprio Senhor (Yahweh), acompanhado por dois anjos. A hospitalidade generosa e apressada de Abraão abre caminho para uma conversa íntima onde Deus reafirma a promessa do nascimento de Isaque, confrontando a incredulidade humana com o poder ilimitado do Criador.',
    desc1: 'A reação de Abraão à chegada dos visitantes é um modelo de hospitalidade oriental e reverência espiritual. Ele não os ignora no calor do dia; ele corre ao encontro deles, prostra-se por terra e oferece água para lavar os pés e um "bocado de pão". No entanto, o "bocado de pão" transforma-se em um banquete luxuoso: ele manda Sara preparar bolos com a melhor farinha, corre ao gado para escolher um bezerro tenro e bom, e serve manteiga e leite. Abraão não sabia inicialmente que estava recebendo o Senhor, mas a sua generosidade para com os estranhos (Hebreus 13:2) criou o ambiente perfeito para a revelação divina.',
    desc2: 'Após a refeição, o Senhor vai direto ao ponto crucial da aliança: "Onde está Sara, tua mulher?". O Senhor declara: "Certamente tornarei a ti por este tempo da vida; e eis que Sara tua mulher terá um filho". Sara, que estava escutando atrás da porta da tenda, ri-se consigo mesma. O seu riso não era de alegria, mas de incredulidade cínica. Ela pensa na impossibilidade biológica: "Terei ainda deleite depois de haver envelhecido, sendo também o meu senhor já velho?". A lógica humana e a biologia diziam que a promessa de Deus era uma piada absurda. A fé frequentemente entra em conflito direto com as evidências naturais.',
    desc3: 'O Senhor, que conhece os pensamentos ocultos, confronta o riso de Sara: "Por que se riu Sara?". Em seguida, Ele faz a pergunta retórica que ecoa por toda a Bíblia e serve como âncora para a nossa fé nas situações impossíveis: "Haveria coisa alguma difícil (ou maravilhosa demais) ao Senhor?". Deus não está limitado pela biologia, pela idade ou pelas circunstâncias humanas. Ele reafirma a promessa com um prazo definido: "Ao tempo determinado tornarei a ti... e Sara terá um filho". Sara, com medo, tenta negar que riu, mas o Senhor a repreende suavemente: "Não digas isso, porque te riste". Deus expõe a nossa incredulidade não para nos condenar, mas para nos curar e nos preparar para o milagre.',
    concl: 'A visita em Manre nos ensina que Deus frequentemente nos visita nas horas mais comuns do dia. Quando respondemos com generosidade e serviço, abrimos a porta para a Sua revelação. Mais importante ainda, a história nos desafia a confrontar o nosso próprio "riso de incredulidade" diante das promessas de Deus com a verdade inabalável de que não há absolutamente nada que seja difícil demais para o Senhor.'
  },
  {
    id: 'exo_16_1_36',
    intro: 'O capítulo 16 de Êxodo ocorre exatamente um mês após a saída de Israel do Egito. O entusiasmo da libertação e o milagre do Mar Vermelho já haviam passado, e a dura realidade do deserto começou a pesar. A comida que trouxeram do Egito acabou. Diante da fome iminente de uma multidão de mais de dois milhões de pessoas, a nação entra em pânico e começa a murmurar contra Moisés e Arão. A resposta de Deus a essa rebelião não é um castigo fulminante, mas uma provisão milagrosa e diária (o maná) que serviria não apenas para alimentar os seus corpos, mas para treinar os seus corações na dependência diária do Criador.',
    desc1: 'A murmuração do povo revela a rapidez com que a memória espiritual se apaga diante do desconforto físico. Eles dizem: "Quem dera tivéssemos morrido por mão do Senhor na terra do Egito, quando estávamos sentados junto às panelas de carne... porque nos trouxestes a este deserto, para matardes de fome a toda esta multidão". O medo distorce o passado (eles esquecem a escravidão cruel e lembram apenas das panelas de carne) e acusa a liderança de intenções malignas. Moisés esclarece que a murmuração deles não era contra ele, mas contra o próprio Deus. A murmuração é, na sua essência, uma declaração de desconfiança na bondade e na provisão de Deus.',
    desc2: 'Deus responde à murmuração com graça abundante: "Eis que vos farei chover pão dos céus". No entanto, a provisão vem com regras estritas projetadas para testar a obediência do povo. Eles deveriam colher apenas a porção necessária para um dia (um ômer por pessoa). Se tentassem guardar para o dia seguinte (por medo de que Deus falhasse em prover), o maná criaria bichos e cheiraria mal. A lição era clara: a fé não pode ser armazenada; ela deve ser exercitada diariamente. Deus não lhes deu um celeiro cheio para o ano inteiro, mas o pão nosso de cada dia, forçando-os a olhar para o céu todas as manhãs.',
    desc3: 'A segunda regra envolvia o sábado. No sexto dia, eles deveriam colher o dobro, pois no sétimo dia (o sábado) não haveria maná no campo. O maná guardado para o sábado não apodrecia. Alguns desobedeceram e saíram para colher no sábado, mas não encontraram nada. Deus estava ensinando que o descanso (Sabbath) é tão sagrado quanto o trabalho, e que a obediência aos Seus mandamentos garante a provisão mesmo quando não estamos trabalhando. O povo chamou o pão de "maná" (que significa "O que é isto?"), pois não sabiam o que era. Era branco como semente de coentro e tinha sabor de bolos de mel.',
    concl: 'O maná no deserto é um tipo perfeito de Jesus Cristo, o verdadeiro Pão da Vida que desceu do céu (João 6). A história nos ensina que Deus é fiel para suprir as nossas necessidades no deserto, mas Ele o faz de uma maneira que nos mantém dependentes dEle dia após dia. A tentativa de acumular segurança fora da vontade de Deus sempre resulta em podridão, mas a obediência diária traz a doçura da provisão divina.'
  },
  {
    id: 'jos_6_1_27',
    intro: 'A queda de Jericó é a primeira e mais emblemática batalha na conquista da Terra Prometida. Jericó era uma cidade-estado poderosa, cercada por muralhas duplas e intransponíveis, controlando o acesso ao interior de Canaã. Do ponto de vista militar e humano, Israel (um povo de ex-escravos sem máquinas de cerco) não tinha a menor chance de tomar a cidade. No entanto, a estratégia que Deus entrega a Josué desafia toda a lógica militar, a tática e o bom senso humano. A vitória sobre Jericó não seria alcançada pela força das armas, mas pela obediência irracional, pela paciência e pelo poder exclusivo de Deus, estabelecendo o padrão para todas as vitórias espirituais.',
    desc1: 'A narrativa começa com uma declaração de vitória antes mesmo da batalha começar: "Então disse o Senhor a Josué: Olha, tenho dado na tua mão a Jericó, ao seu rei e aos seus homens valorosos". A fé cristã não luta para obter a vitória, mas luta a partir da vitória já garantida por Deus. A estratégia divina, no entanto, parecia uma loucura: o exército deveria marchar ao redor da cidade uma vez por dia, durante seis dias, em total silêncio. A Arca da Aliança (representando a presença de Deus) iria no meio, precedida por sete sacerdotes tocando buzinas de chifre de carneiro. O silêncio exigia disciplina e impedia a murmuração que havia destruído a geração anterior no deserto.',
    desc2: 'Marchar ao redor de uma cidade fortificada em silêncio por seis dias deve ter parecido ridículo para os soldados de Israel e provocado zombarias dos habitantes de Jericó que observavam das muralhas. A obediência a Deus frequentemente nos faz parecer tolos aos olhos do mundo (1 Coríntios 1:18). A estratégia de Deus estava testando a paciência e a submissão de Israel. Eles precisavam aprender que as muralhas não cairiam pelo seu próprio esforço, mas no tempo de Deus e pela maneira de Deus. A vitória espiritual exige que continuemos marchando em obediência, mesmo quando não vemos nenhum resultado imediato.',
    desc3: 'No sétimo dia, a instrução muda. Eles deveriam marchar ao redor da cidade sete vezes. Na sétima volta, quando os sacerdotes tocassem as buzinas longamente, Josué ordenou: "Gritai, porque o Senhor vos tem dado a cidade". O grito não era um grito de guerra para assustar o inimigo, mas um grito de fé e louvor antes da evidência visível. Quando o povo gritou, "os muros caíram abaixo", e o exército subiu e tomou a cidade. A única casa poupada foi a de Raabe, a prostituta que havia escondido os espias e demonstrado fé no Deus de Israel, provando que a graça de Deus alcança os marginalizados que creem.',
    concl: 'A queda de Jericó nos ensina que as "muralhas" intransponíveis das nossas vidas (problemas impossíveis, vícios, oposição) não caem pela nossa própria força ou inteligência. Elas caem quando obedecemos à Palavra de Deus (mesmo quando ela parece ilógica), mantemos a disciplina do silêncio (evitando a murmuração) e damos o grito de louvor crendo na vitória que Ele já nos garantiu.'
  },
  {
    id: '1sa_30_1_20',
    intro: 'O capítulo 30 de 1 Samuel narra o momento mais sombrio, desesperador e perigoso da vida de Davi antes de ele se tornar rei. Davi estava vivendo como um fugitivo na terra dos filisteus, na cidade de Ziclague, para escapar da perseguição do rei Saul. Quando Davi e os seus seiscentos homens retornam de uma campanha militar, encontram a sua cidade completamente destruída pelo fogo. Os amalequitas haviam invadido e sequestrado todas as mulheres, crianças e bens. A dor da perda transforma-se rapidamente em um motim mortal contra a liderança de Davi. Esta narrativa é uma aula magistral sobre como um líder espiritual deve reagir quando perde tudo e enfrenta a traição dos seus próprios amigos.',
    desc1: 'A cena em Ziclague é de devastação total. O texto diz que "Davi e o povo que se achava com ele alçaram a sua voz, e choraram, até que neles não houve mais força para chorar". A dor era tão profunda que esgotou a capacidade física de chorar. No entanto, a tristeza logo se transforma em raiva e busca por um bode expiatório. O versículo 6 revela a gravidade da crise: "E Davi muito se angustiou, porque o povo falava de apedrejá-lo, porque a alma de todo o povo estava em amargura". Os homens que Davi havia treinado, liderado e protegido agora queriam matá-lo. Davi perdeu a sua família, a sua cidade, os seus bens e, agora, a lealdade do seu exército.',
    desc2: 'É neste momento de isolamento absoluto que Davi toma a decisão que define o seu caráter e o separa de Saul. Em vez de se desesperar, fugir ou tentar se justificar diante dos homens furiosos, o texto diz: "todavia Davi se fortaleceu no Senhor seu Deus". Davi não buscou força nas circunstâncias, na sua espada ou na opinião pública; ele buscou força na sua aliança com Deus. Ele pede ao sacerdote Abiatar que traga o éfode (o instrumento de consulta a Deus) e pergunta: "Perseguirei eu a esta tropa? Alcançá-la-ei?". Antes de reagir à crise, Davi busca a direção de Deus. A resposta divina é clara e encorajadora: "Persegue-a, porque decerto a alcançarás e tudo libertarás".',
    desc3: 'Com a palavra de Deus, Davi e os seus homens iniciam a perseguição. Duzentos homens ficam exaustos no caminho e não conseguem continuar, mas Davi prossegue com quatrocentos. No caminho, eles encontram um escravo egípcio doente e abandonado pelos amalequitas. Em vez de ignorá-lo na sua pressa, Davi o alimenta e cuida dele. Esse ato de compaixão torna-se a chave estratégica: o escravo os guia diretamente ao acampamento inimigo. Davi ataca os amalequitas de surpresa, derrota-os completamente e recupera tudo: "E Davi salvou tudo quanto haviam tomado os amalequitas... nada lhes faltou, desde o menor até ao maior".',
    concl: 'A crise em Ziclague nos ensina que, nos momentos de perda total e traição, a nossa única esperança é nos fortalecermos no Senhor. Quando buscamos a direção de Deus antes de agir, tratamos os necessitados com compaixão no caminho e obedecemos à Sua voz, Deus é poderoso para nos fazer recuperar tudo o que o inimigo nos roubou, transformando a nossa maior derrota na nossa maior vitória.'
  },
  {
    id: 'neh_2_1_20',
    intro: 'O capítulo 2 de Neemias é um estudo de caso clássico sobre a intersecção entre a fé profunda e a ação estratégica. Neemias era o copeiro do rei Artaxerxes da Pérsia (uma posição de alta confiança e influência). Quatro meses antes, ele havia recebido a notícia devastadora de que os muros de Jerusalém estavam em ruínas e o povo em grande miséria. Durante esses quatro meses, Neemias não organizou um protesto nem tomou atitudes precipitadas; ele chorou, jejuou e orou incessantemente. O capítulo 2 narra o momento em que a oportunidade divina finalmente se apresenta. Neemias demonstra como um líder espiritual deve depender inteiramente de Deus enquanto age com coragem, planejamento meticuloso e sabedoria prática.',
    desc1: 'A oportunidade surge durante o trabalho rotineiro. O rei percebe a tristeza no rosto de Neemias (algo perigoso, pois a tristeza na presença do rei persa podia ser interpretada como insatisfação ou conspiração). O rei pergunta: "Por que está triste o teu rosto?". Neemias confessa que sentiu "grande temor", mas usa a oportunidade para explicar a situação de Jerusalém. O rei então faz a pergunta que Neemias esperava há quatro meses: "Que me pedes agora?". A reação de Neemias é o exemplo perfeito da "oração de flecha": "Então orei ao Deus dos céus". Entre a pergunta do rei e a resposta de Neemias, houve uma oração silenciosa e instantânea. A oração contínua de quatro meses o preparou para a oração de um segundo.',
    desc2: 'A resposta de Neemias ao rei revela que ele não passou os quatro meses apenas chorando, mas também planejando. Ele não pede apenas permissão para ir; ele pede cartas de salvo-conduto para os governadores além do rio e uma carta para Asafe, o guarda da floresta do rei, para fornecer madeira para a reconstrução. A fé não anula o planejamento estratégico; ela o santifica. O rei concede tudo o que Neemias pede. Neemias não atribui o sucesso à sua própria eloquência ou à bondade do rei, mas reconhece a fonte real: "E o rei mas deu, segundo a boa mão de Deus sobre mim".',
    desc3: 'Ao chegar a Jerusalém, Neemias não faz discursos imediatos. Ele passa três dias em silêncio, avaliando a situação. À noite, em segredo, ele faz uma inspeção minuciosa das ruínas dos muros. Um bom líder não baseia as suas decisões em boatos, mas na realidade dos fatos. Só depois de ter o diagnóstico completo é que ele reúne os líderes e os desafia: "Vinde, pois, e edifiquemos o muro de Jerusalém, para que não sejamos mais um opróbrio". Ele os encoraja com o testemunho da "boa mão de Deus". A oposição surge imediatamente através de Sambalate e Tobias, que zombam do projeto. A resposta de Neemias é firme e teológica: "O Deus dos céus é o que nos fará prosperar... vós, porém, não tendes parte, nem justiça, nem memória em Jerusalém".',
    concl: 'A missão de Neemias nos ensina que grandes obras para Deus requerem joelhos dobrados em oração e mentes afiadas para o planejamento. A fé verdadeira não espera passivamente que Deus faça tudo; ela ora como se tudo dependesse de Deus e planeja e trabalha como se tudo dependesse de nós, sabendo que o sucesso final vem exclusivamente da "boa mão de Deus".'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 21');
