const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: '2ki_2_1_14',
    intro: 'O capítulo 2 de 2 Reis narra a transição de liderança profética mais espetacular do Antigo Testamento: a ascensão de Elias ao céu num redemoinho e a transferência do seu manto para Eliseu. Elias sabia que o seu tempo na terra estava terminando, e Eliseu, o seu discípulo fiel, também sabia. A jornada de Gilgal até o rio Jordão é um teste final da perseverança e do compromisso de Eliseu. Elias tenta repetidamente deixar Eliseu para trás, mas o discípulo recusa-se a abandoná-lo. A história culmina com um pedido audacioso de Eliseu e uma demonstração visível do poder de Deus, garantindo que o ministério profético continuaria com a mesma autoridade na próxima geração.',
    desc1: 'A jornada começa em Gilgal, passa por Betel e chega a Jericó. Em cada cidade, Elias diz a Eliseu: "Fica-te aqui, porque o Senhor me enviou a...". E em cada cidade, Eliseu responde com um juramento solene: "Vive o Senhor, e vive a tua alma, que não te deixarei". Os filhos dos profetas (escolas de profetas) nessas cidades também sabiam o que estava para acontecer e perguntavam a Eliseu se ele sabia que o seu senhor seria levado. Eliseu os silenciava: "Também eu o sei; calai-vos". Eliseu não estava interessado em especulações teológicas ou fofocas sobre o fim de Elias; ele estava focado em permanecer perto do seu mestre até o último segundo. A verdadeira sucessão espiritual exige perseverança e lealdade inabalável.',
    desc2: 'Eles chegam ao rio Jordão. Elias tira o seu manto (o símbolo da sua autoridade profética), dobra-o e fere as águas. As águas se dividem, e os dois atravessam a seco (um milagre que ecoa Moisés no Mar Vermelho e Josué no próprio Jordão). Após a travessia, Elias faz a pergunta final: "Pede-me o que queres que te faça, antes que seja tomado de ti". Eliseu não pede riqueza, fama ou uma vida fácil. Ele faz um pedido espiritual gigantesco: "Peço-te que haja sobre mim dobrada porção de teu espírito". Ele não estava pedindo para ser duas vezes maior que Elias, mas estava usando a linguagem da herança (Deuteronômio 21:17), pedindo para ser o herdeiro legítimo e o sucessor principal do ministério de Elias.',
    desc3: 'Elias responde: "Coisa dura pediste; se me vires quando for tomado de ti, assim se te fará, porém, se não, não se fará". A concessão do Espírito não dependia de Elias, mas de Deus. A condição era que Eliseu mantivesse os olhos fixos no evento espiritual. De repente, um carro de fogo com cavalos de fogo os separa, e Elias sobe ao céu num redemoinho. Eliseu vê a cena e grita: "Meu pai, meu pai, carros de Israel e seus cavaleiros!". Ele reconhece que a verdadeira defesa de Israel não era o exército humano, mas o poder profético de Deus. O manto de Elias cai. Eliseu o pega, volta ao Jordão, fere as águas com o manto e pergunta: "Onde está o Senhor Deus de Elias?". As águas se dividem novamente, provando que o Deus de Elias agora era o Deus de Eliseu.',
    concl: 'A ascensão de Elias nos ensina que Deus não morre quando os Seus grandes líderes partem. O manto da autoridade e do poder do Espírito Santo está disponível para a próxima geração, desde que haja discípulos com a perseverança de Eliseu, que se recusam a ficar para trás, que mantêm os olhos fixos nas realidades espirituais e que ousam pedir uma porção dobrada do Espírito para continuar a obra de Deus na terra.'
  },
  {
    id: 'psa_121_1_8',
    intro: 'O Salmo 121 é o segundo dos quinze "Cânticos dos Degraus" (ou Cânticos de Romagem), que eram cantados pelos peregrinos israelitas enquanto subiam as montanhas em direção a Jerusalém para as grandes festas anuais. A jornada era perigosa, cheia de ameaças como ladrões, animais selvagens, o sol escaldante do deserto e o frio da noite. Este salmo é um diálogo interno (ou talvez um diálogo entre dois peregrinos) que começa com uma pergunta sobre a fonte de segurança diante dos perigos iminentes e termina com uma das declarações mais abrangentes e reconfortantes sobre a proteção contínua e vigilante de Deus em toda a Bíblia.',
    desc1: 'O salmo abre com uma imagem visual poderosa: "Levantarei os meus olhos para os montes, de onde vem o meu socorro". Os montes ao redor de Jerusalém podiam representar duas coisas: ou eram o lugar onde os ladrões se escondiam (a fonte do perigo), ou eram os lugares altos onde os pagãos construíam os seus altares idólatras (a falsa fonte de socorro). O salmista rejeita ambas as opções e responde à sua própria pergunta no versículo 2: "O meu socorro vem do Senhor que fez o céu e a terra". A nossa segurança não vem das circunstâncias, das defesas geográficas ou dos falsos deuses, mas exclusivamente do Criador do universo. Aquele que fez as montanhas é maior do que qualquer perigo que se esconda nelas.',
    desc2: 'A partir do versículo 3, o salmo muda para uma série de promessas diretas usando a palavra "guardar" (shamar) seis vezes. "Não deixará vacilar o teu pé; aquele que te guarda não tosquenejará (não cochilará)". Em contraste com os deuses pagãos (como Baal, que Elias zombou dizendo que talvez estivesse dormindo), o Deus de Israel é o Vigia perfeito que nunca dorme nem cochila. A proteção de Deus é contínua e ininterrupta. O salmista garante proteção contra os perigos climáticos extremos do Oriente Médio: "O Senhor é a tua sombra à tua direita. O sol não te molestará de dia nem a lua de noite". Deus é a sombra que nos protege do calor das provações diurnas e dos medos irracionais das trevas noturnas.',
    desc3: 'Os dois últimos versículos expandem a promessa de proteção para todas as áreas e todos os tempos da vida: "O Senhor te guardará de todo o mal; guardará a tua alma". Isso não significa que o crente nunca sofrerá acidentes ou doenças físicas, mas significa que nenhum mal pode destruir a sua alma ou separá-lo do amor de Deus. A promessa final é absoluta: "O Senhor guardará a tua entrada e a tua saída, desde agora e para sempre". Deus protege o início e o fim de cada jornada, cada empreendimento e, em última análise, a nossa entrada neste mundo (nascimento) e a nossa saída dele (morte), garantindo a nossa chegada segura à Jerusalém celestial.',
    concl: 'O Salmo 121 nos ensina a redirecionar o nosso olhar. Quando enfrentamos as "montanhas" de dificuldades na nossa jornada, não devemos olhar para os perigos com medo, nem para os falsos deuses do mundo em busca de socorro. Devemos levantar os olhos mais alto, para o Criador dos céus e da terra, descansando na certeza de que o nosso Vigia nunca dorme e guardará a nossa alma para sempre.'
  },
  {
    id: 'isa_40_1_11',
    intro: 'O capítulo 40 de Isaías marca uma transição dramática e gloriosa no livro. Os primeiros 39 capítulos são dominados por mensagens de juízo, advertências severas contra o pecado de Judá e profecias sobre a iminente destruição e o exílio na Babilônia. No entanto, a partir do capítulo 40, o tom muda radicalmente. Deus não abandona o Seu povo no exílio. Ele irrompe com uma mensagem de consolo, perdão e restauração. Este texto é o prólogo do "Livro da Consolação" e estabelece o fundamento para a vinda do Messias. É uma proclamação de que, apesar da fragilidade humana e do peso do pecado, a Palavra de Deus permanece eternamente e o Seu braço poderoso trará a salvação.',
    desc1: 'O capítulo começa com um imperativo divino duplo, revelando o coração de Deus para com o Seu povo sofredor: "Consolai, consolai o meu povo, diz o vosso Deus". Deus ordena aos profetas que falem "benignamente" (literalmente, "ao coração") de Jerusalém. A mensagem de consolo tem três fundamentos: o tempo da sua milícia (o sofrimento do exílio) acabou, a sua iniquidade está perdoada, e ela já recebeu em dobro pelos seus pecados (a justiça de Deus foi plenamente satisfeita). O consolo bíblico não é um tapinha nas costas dizendo que "tudo vai ficar bem"; é a declaração objetiva de que o pecado foi perdoado e a dívida foi paga.',
    desc2: 'Em seguida, uma voz clama no deserto (uma profecia cumprida diretamente por João Batista): "Preparai no deserto o caminho do Senhor; endireitai no ermo vereda a nosso Deus". A imagem é a da construção de uma estrada real para a chegada de um grande rei. Os vales (depressão, desespero) devem ser aterrados; os montes (orgulho, arrogância) devem ser nivelados; os caminhos tortuosos (engano, pecado) devem ser endireitados. A preparação para a vinda de Deus exige arrependimento e nivelamento moral. O resultado dessa preparação é a revelação universal de Deus: "E a glória do Senhor se manifestará, e toda a carne juntamente a verá".',
    desc3: 'O texto então contrasta a fragilidade humana com a eternidade da Palavra de Deus (v. 6-8). Uma voz ordena que se clame: "Toda a carne é erva e toda a sua beleza como a flor do campo... seca-se a erva, e cai a flor, porém a palavra de nosso Deus subsiste eternamente". Os impérios humanos (como a Babilônia) e os nossos próprios esforços são passageiros e murcham sob o sopro de Deus, mas as promessas divinas são o único fundamento inabalável. O texto conclui com a chegada do Senhor (v. 10-11). Ele vem com poder e autoridade ("o seu braço dominará por ele"), mas também com uma ternura infinita: "Como pastor apascentará o seu rebanho; entre os seus braços recolherá os cordeirinhos, e os levará no seu regaço".',
    concl: 'Isaías 40 nos ensina que o juízo de Deus nunca é a Sua última palavra para o Seu povo. A Sua última palavra é sempre graça, perdão e consolo. Quando nos sentimos no "deserto" do sofrimento ou da culpa, somos chamados a preparar o caminho do Senhor através do arrependimento, confiando não na nossa própria força (que murcha como a erva), mas na Palavra eterna do nosso Deus, que vem até nós com o poder de um Rei e a ternura de um Pastor.'
  },
  {
    id: 'mat_18_21_35',
    intro: 'A Parábola do Credor Incompassivo (ou do Servo Impiedoso) é a resposta contundente de Jesus a uma pergunta de Pedro sobre os limites do perdão. Pedro, achando-se muito generoso, pergunta: "Senhor, até quantas vezes pecará meu irmão contra mim, e eu lhe perdoarei? Até sete?". A tradição rabínica ensinava que se devia perdoar três vezes. Pedro dobrou o número e acrescentou um, esperando ser elogiado. A resposta de Jesus destrói a matemática humana do perdão: "Não te digo que até sete; mas, até setenta vezes sete". O perdão no Reino de Deus não tem limites contáveis. Para ilustrar a razão teológica dessa exigência radical, Jesus conta a história de um rei que decide acertar as contas com os seus servos.',
    desc1: 'A parábola começa com uma dívida astronômica e impagável. Um servo é trazido diante do rei devendo "dez mil talentos". Um talento era equivalente a cerca de vinte anos de salário de um trabalhador comum. Dez mil talentos era uma quantia absurda (mais do que o orçamento anual de várias províncias romanas juntas), representando uma dívida que o servo jamais poderia pagar, mesmo que vivesse mil vidas. O rei ordena que ele, a sua mulher, os seus filhos e tudo o que ele tem sejam vendidos para pagar a dívida. O servo prostra-se e implora: "Senhor, sê generoso para comigo, e tudo te pagarei". O pedido dele era ridículo (ele nunca poderia pagar), mas o rei, movido de íntima compaixão, faz o impensável: ele perdoa a dívida inteira. A graça cancela o que o esforço humano nunca poderia resolver.',
    desc2: 'O choque da parábola ocorre na cena seguinte. O servo que acabou de ser perdoado de uma dívida bilionária sai e encontra um conservo que lhe devia "cem dinheiros" (cerca de cem dias de salário). Era uma dívida real, mas insignificante comparada à que lhe fora perdoada. O servo agarra o companheiro pelo pescoço, sufocando-o, e exige: "Paga-me o que me deves". O conservo usa exatamente as mesmas palavras de súplica: "Sê generoso para comigo, e tudo te pagarei". Mas o servo perdoado recusa-se a mostrar misericórdia e lança o companheiro na prisão. A falha em perdoar os outros revela uma falha profunda em compreender e internalizar o perdão que recebemos de Deus.',
    desc3: 'Os outros servos veem a injustiça e relatam tudo ao rei. O rei chama o servo impiedoso e profere a sentença: "Servo malvado, perdoei-te toda aquela dívida, porque me suplicaste. Não devias tu, igualmente, ter compaixão do teu companheiro, como eu também tive misericórdia de ti?". O rei, indignado, entrega-o aos atormentadores até que pague toda a dívida (o que significa tormento eterno, pois a dívida era impagável). Jesus conclui a parábola com um aviso aterrorizante: "Assim vos fará, também, meu Pai celestial, se do coração não perdoardes, cada um a seu irmão, as suas ofensas". O perdão não é uma opção terapêutica; é uma exigência de salvação.',
    concl: 'A parábola do credor incompassivo nos ensina que a nossa capacidade de perdoar os outros é a prova definitiva de que realmente experimentamos o perdão de Deus. O pecado de qualquer pessoa contra nós (os cem dinheiros) é minúsculo comparado ao nosso pecado contra o Deus Santo (os dez mil talentos). Recusar-se a perdoar é uma hipocrisia arrogante que nos coloca de volta sob o juízo de Deus.'
  },
  {
    id: 'luk_22_39_46',
    intro: 'A agonia no Getsêmani é o momento de maior vulnerabilidade, pavor e batalha espiritual da vida terrena de Jesus. Na noite antes da Sua crucificação, após a Última Ceia, Jesus retira-se para o Monte das Oliveiras, como era o Seu costume. Ele sabe que a traição de Judas é iminente e que a cruz O aguarda na manhã seguinte. O Getsêmani (que significa "prensa de azeite") torna-se o lugar onde a alma de Jesus é esmagada sob o peso antecipado do pecado do mundo e da ira de Deus. É neste jardim, na escuridão da noite e na solidão da oração, que a verdadeira batalha pela nossa salvação é travada e vencida, antes mesmo do primeiro prego ser cravado no Calvário.',
    desc1: 'Jesus chega ao local e dá uma instrução crucial aos Seus discípulos: "Orai, para que não entreis em tentação". A tentação não era apenas o sono, mas a negação e o abandono que ocorreriam nas próximas horas. Jesus então se afasta deles a uma distância de um tiro de pedra, ajoelha-se e começa a orar. A oração de Jesus revela a intensidade do Seu conflito interno: "Pai, se queres, passa de mim este cálice; todavia não se faça a minha vontade, mas a tua". O "cálice" no Antigo Testamento é frequentemente uma metáfora para a ira e o juízo de Deus contra o pecado (Isaías 51:17). Jesus não estava com medo da dor física da cruz ou dos romanos; Ele estava aterrorizado com a perspectiva de se tornar pecado e experimentar o abandono do Pai (a separação espiritual).',
    desc2: 'A agonia de Jesus atinge um nível físico extremo. Lucas, o médico, registra um detalhe único: "E, posto em agonia, orava mais intensamente. E o seu suor tornou-se em grandes gotas de sangue, que corriam até ao chão". Essa condição médica rara (hematidrose) ocorre sob estresse psicológico extremo, quando os vasos capilares se rompem e o sangue se mistura com o suor. A pressão sobre Jesus era tão grande que um anjo do céu aparece para confortá-Lo e fortalecê-Lo. Jesus estava suportando o peso da condenação eterna de toda a humanidade. A Sua submissão ("não se faça a minha vontade, mas a tua") reverte a rebelião de Adão no primeiro jardim (o Éden). No Éden, Adão disse a Deus: "A minha vontade seja feita", e trouxe a morte. No Getsêmani, Jesus diz: "A Tua vontade seja feita", e traz a vida.',
    desc3: 'Enquanto Jesus trava a maior batalha da história em oração, os discípulos falham miseravelmente. Quando Jesus se levanta da oração e vai ter com eles, os encontra "dormindo de tristeza". A tristeza e a exaustão emocional os dominaram. Jesus os repreende suavemente, mas com urgência: "Por que dormis? Levantai-vos, e orai, para que não entreis em tentação". A falha dos discípulos em vigiar e orar no Getsêmani resultou na sua dispersão e na negação de Pedro poucas horas depois. A vitória espiritual de Jesus na cruz foi garantida pela Sua vitória na oração no jardim.',
    concl: 'A agonia no Getsêmani nos ensina o custo infinito da nossa salvação. Jesus bebeu o cálice da ira de Deus até a última gota para que nós pudéssemos beber o cálice da salvação. A história também nos adverte sobre o perigo da negligência espiritual: quando enfrentamos a tentação e a crise, a nossa única defesa é a oração vigilante e a submissão total à vontade do Pai.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 25');
