const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'luk_5_1_11',
    intro: 'O relato da pesca maravilhosa no Evangelho de Lucas é o momento decisivo em que Jesus chama os Seus primeiros discípulos (Pedro, Tiago e João) para um compromisso em tempo integral. A narrativa começa com uma cena de frustração profunda: pescadores experientes que trabalharam arduamente durante toda a noite (o melhor horário para a pesca no Mar da Galileia) e não apanharam absolutamente nada. Jesus entra nesse cenário de fracasso profissional e exaustão física não apenas para realizar um milagre de provisão, mas para transformar radicalmente a identidade e o propósito de vida daqueles homens.',
    desc1: 'A multidão apertava Jesus para ouvir a Palavra de Deus à beira do lago de Genesaré. Jesus vê dois barcos vazios e pede a Simão Pedro para afastar um pouco o barco da terra, transformando-o em um púlpito flutuante. Pedro, mesmo exausto após uma noite de fracasso, obedece e cede o seu barco (o seu instrumento de trabalho) para o uso do Mestre. Quando entregamos a Jesus o controle das nossas ferramentas, do nosso tempo e do nosso trabalho, Ele os usa para a glória de Deus e, em seguida, nos abençoa de forma surpreendente.',
    desc2: 'Após terminar de ensinar, Jesus dá uma ordem que desafia a lógica profissional de Pedro: "Faze-te ao mar alto, e lançai as vossas redes para pescar". Pedro era o pescador experiente; Jesus era um carpinteiro. Além disso, pescar de dia e em águas profundas era contra todas as regras da pesca local. Pedro expressa a sua frustração ("Mestre, havendo trabalhado toda a noite, nada apanhamos"), mas toma a decisão que muda a sua vida: "mas, sobre a tua palavra, lançarei a rede". O milagre sempre acontece quando a obediência à Palavra de Cristo supera a nossa experiência, a nossa lógica e o nosso cansaço.',
    desc3: 'O resultado da obediência é uma abundância esmagadora. Eles apanham uma quantidade tão grande de peixes que as redes começam a romper e os dois barcos quase afundam. Diante da manifestação do poder divino, a reação de Pedro não é de alegria pela riqueza repentina, mas de convicção de pecado. Ele cai aos pés de Jesus e diz: "Senhor, ausenta-te de mim, por que sou um homem pecador". O milagre revelou a santidade de Cristo e a impureza de Pedro. Jesus responde com graça e um novo chamado: "Não temas; de agora em diante serás pescador de homens". Eles deixam a maior pesca de suas vidas para trás e O seguem.',
    concl: 'A pesca maravilhosa nos ensina que o fracasso humano é frequentemente o palco para o milagre divino. Quando obedecemos à Palavra de Jesus, mesmo quando ela contraria a nossa lógica, experimentamos a Sua provisão abundante. Mas o maior milagre não é a rede cheia de peixes; é quando deixamos tudo para trás para nos tornarmos pescadores de homens.'
  },
  {
    id: 'jhn_5_1_15',
    intro: 'A cura do paralítico no tanque de Betesda é o terceiro "sinal" no Evangelho de João e marca o início do conflito aberto entre Jesus e os líderes religiosos judaicos em Jerusalém. O tanque de Betesda (que significa "Casa de Misericórdia") era um lugar de desespero e superstição, cercado por cinco alpendres cheios de doentes, cegos, coxos e paralíticos que esperavam pelo movimento das águas para serem curados. No meio dessa multidão de sofredores, Jesus escolhe um homem que estava paralisado há trinta e oito anos. Esta narrativa revela a soberania da graça de Cristo, que ignora as regras religiosas humanas (o sábado) para trazer restauração imediata a quem não tem esperança.',
    desc1: 'A condição do homem era de total impotência e isolamento. Trinta e oito anos de paralisia significavam uma vida inteira de dependência, decepção e marginalização. Quando Jesus o vê e sabe do seu longo sofrimento, Ele faz uma pergunta surpreendente e penetrante: "Queres ficar são?". A pergunta parece óbvia, mas Jesus estava sondando a vontade do homem. Depois de tanto tempo na mesma condição, a doença pode se tornar uma identidade e uma zona de conforto. O homem não responde com um "sim", mas com uma desculpa baseada na sua solidão e no sistema competitivo do tanque: "Senhor, não tenho homem algum que... me ponha no tanque".',
    desc2: 'Jesus ignora a superstição do tanque e a desculpa do homem. Ele não o ajuda a entrar na água; Ele traz a cura diretamente através da Sua Palavra. Jesus dá três ordens impossíveis para um paralítico: "Levanta-te, toma o teu leito, e anda". A palavra de Cristo carrega em si mesma o poder para realizar o que ordena. Imediatamente, o homem fica são, pega o seu leito e começa a andar. A graça de Deus não depende dos nossos rituais, do nosso tempo de espera ou da ajuda de outros homens; ela opera soberanamente pelo poder da Palavra de Jesus.',
    desc3: 'O milagre, no entanto, gera um conflito imediato, pois "aquele dia era sábado". Os líderes religiosos judeus, cegos pelo legalismo, não se alegram com a cura de um homem paralisado há quase quatro décadas; eles o acusam de quebrar a lei por carregar o seu leito no sábado. A religião morta valoriza mais as regras e as tradições do que a restauração humana. Mais tarde, Jesus encontra o homem no templo e lhe dá uma advertência severa: "Eis que já estás são; não peques mais, para que não te suceda alguma coisa pior". A cura física é um chamado à santidade; o pecado não perdoado é uma paralisia muito pior do que a doença física.',
    concl: 'A cura em Betesda nos ensina que Jesus é a verdadeira Casa de Misericórdia. Ele nos encontra na nossa paralisia espiritual, quando não temos ninguém para nos ajudar, e nos restaura com a Sua Palavra. No entanto, a Sua graça nos chama a abandonar o pecado e a vivermos para a Sua glória, mesmo que isso enfureça a religiosidade ao nosso redor.'
  },
  {
    id: 'act_27_13_26',
    intro: 'O capítulo 27 de Atos narra a dramática viagem de Paulo a Roma como prisioneiro. O navio, ignorando os avisos proféticos de Paulo, parte de Creta e é rapidamente apanhado por um furacão devastador conhecido como Euroaquilão. Durante quatorze dias, o navio é açoitado pela tempestade, sem ver o sol ou as estrelas, levando toda a tripulação (composta por marinheiros experientes, soldados romanos e prisioneiros) ao desespero absoluto. Esta narrativa não é apenas um relato histórico de um naufrágio, mas uma poderosa lição sobre liderança espiritual, a paz de Deus no meio do caos e como a presença de um único crente fiel pode trazer salvação para todos ao seu redor.',
    desc1: 'A crise começa com uma falsa sensação de segurança. O vento sul soprava suavemente, e os marinheiros acharam que tinham o controle da situação. No entanto, a calmaria rapidamente se transforma em um furacão incontrolável. A tempestade é tão violenta que eles perdem o controle do navio, começam a jogar a carga e a própria armação do navio ao mar para tentar não afundar. O versículo 20 resume a situação humana sem Deus: "não aparecendo, havendo já muitos dias, nem sol nem estrelas... dissipou-se-nos afinal toda a esperança de sermos salvos". Quando os nossos recursos naturais falham e a escuridão permanece, o desespero é inevitável.',
    desc2: 'No meio do pânico total, Paulo, um prisioneiro acorrentado, levanta-se e assume a liderança moral e espiritual do navio. Ele não os condena com um "eu avisei", mas traz uma mensagem de esperança baseada na revelação divina. Ele diz: "Exorto-vos a que tenhais bom ânimo, porque não se perderá a vida de nenhum de vós, mas somente o navio". A paz de Paulo não vinha da negação da tempestade, mas da certeza da presença de Deus. Ele declara com convicção: "Porque esta mesma noite o anjo de Deus, de quem eu sou e a quem sirvo, esteve comigo". A identidade de Paulo ("de quem eu sou") e o seu propósito ("a quem sirvo") eram a âncora da sua alma.',
    desc3: 'A mensagem do anjo a Paulo era dupla: "Não temas, Paulo, importa que sejas apresentado a César; e eis que Deus te deu todos quantos navegam contigo". O propósito de Deus para a vida de Paulo (pregar em Roma) era a garantia da sua sobrevivência e, por extensão, da sobrevivência de todos os que estavam com ele. Paulo encoraja a tripulação com uma declaração de fé inabalável: "Portanto, ó senhores, tende bom ânimo; porque creio em Deus, que há de acontecer assim como a mim me foi dito". A fé verdadeira confia na Palavra de Deus mesmo quando as circunstâncias externas gritam o contrário.',
    concl: 'A tempestade e o naufrágio nos ensinam que a presença de Deus não nos isenta das tormentas da vida, mas nos dá paz e propósito no meio delas. Quando sabemos a quem pertencemos e a quem servimos, podemos ser faróis de esperança e liderança para um mundo que está em pânico e sem direção.'
  },
  {
    id: 'eph_2_1_10',
    intro: 'Os primeiros dez versículos do capítulo 2 de Efésios formam um dos resumos mais magistrais, profundos e belos de todo o Evangelho na Bíblia. O apóstolo Paulo leva os leitores a uma jornada que começa nas profundezas do desespero humano e termina nas alturas da glória divina. Ele descreve o que nós éramos por natureza (mortos no pecado), o que Deus fez por nós (nos vivificou com Cristo) e o que nós nos tornamos pela graça (feitura Sua, criados para boas obras). Este texto é o retrato definitivo da graça imerecida, destruindo qualquer ilusão de mérito humano e exaltando a soberania do amor de Deus.',
    desc1: 'Paulo começa com o diagnóstico mais sombrio e realista da condição humana: "E vos vivificou, estando vós mortos em ofensas e pecados". A humanidade sem Cristo não está apenas doente, confusa ou precisando de um guia moral; ela está espiritualmente morta. Um morto não pode responder a estímulos, não pode se curar e não pode buscar a Deus. Paulo explica que andávamos segundo o curso deste mundo, sob a influência de Satanás (o príncipe das potestades do ar) e éramos escravos dos desejos da nossa carne. A conclusão é aterrorizante: éramos "por natureza filhos da ira", merecedores do juízo de Deus.',
    desc2: 'A virada do texto ocorre no versículo 4, com duas das palavras mais gloriosas da Escritura: "Mas Deus". A intervenção divina muda tudo. Deus não nos salvou porque éramos amáveis ou porque tínhamos algum mérito, mas "sendo rico em misericórdia, pelo seu muito amor com que nos amou". Mesmo quando estávamos mortos e apodrecendo em nossos pecados, Deus nos vivificou juntamente com Cristo, nos ressuscitou e nos fez assentar nos lugares celestiais. A salvação é uma obra de ressurreição espiritual operada exclusivamente pelo poder de Deus. Paulo enfatiza repetidamente: "Pela graça sois salvos".',
    desc3: 'Para eliminar qualquer possibilidade de orgulho humano, Paulo declara a fórmula definitiva da salvação: "Porque pela graça sois salvos, por meio da fé; e isto não vem de vós, é dom de Deus. Não vem das obras, para que ninguém se glorie". A fé é apenas a mão vazia que recebe o presente (dom) da salvação. No entanto, a salvação pela graça não leva à inércia. Paulo conclui no versículo 10: "Porque somos feitura sua (obra-prima de Deus), criados em Cristo Jesus para as boas obras, as quais Deus preparou para que andássemos nelas". As boas obras não são a raiz da nossa salvação, mas são o fruto inevitável dela.',
    concl: 'Efésios 2 nos humilha ao mostrar a nossa total incapacidade espiritual, mas nos exalta ao revelar a imensidão do amor e da graça de Deus. A salvação é do início ao fim uma obra divina, transformando mortos espirituais em obras-primas vivas, destinadas a refletir a glória de Deus através de uma vida de boas obras.'
  },
  {
    id: 'php_4_4_13',
    intro: 'O capítulo 4 da Epístola aos Filipenses contém alguns dos versículos mais amados e citados do Novo Testamento sobre a alegria, a paz e o contentamento. O que torna essas exortações tão extraordinárias é o contexto em que foram escritas: o apóstolo Paulo não estava em um retiro de férias ou em um palácio confortável, mas acorrentado em uma prisão romana, aguardando um julgamento que poderia resultar em sua execução. A partir desse cenário de sofrimento e incerteza, Paulo ensina à igreja o segredo da verdadeira alegria e do contentamento inabalável, provando que a paz de Deus não depende das circunstâncias externas, mas da presença interna de Cristo.',
    desc1: 'A exortação de Paulo começa com um imperativo que parece impossível: "Regozijai-vos sempre no Senhor; outra vez digo, regozijai-vos". A alegria cristã não é um sentimento superficial baseado em circunstâncias favoráveis (felicidade), mas uma escolha profunda e contínua baseada na pessoa e na obra de Cristo ("no Senhor"). Em seguida, Paulo ataca o maior inimigo da paz: a ansiedade. "Não andeis ansiosos por coisa alguma". A cura para a ansiedade não é a negação do problema, mas a oração com gratidão: "em tudo, pela oração e súplicas, e com ação de graças, apresentai as vossas petições a Deus". A gratidão muda o nosso foco do problema para o Provedor.',
    desc2: 'O resultado de entregar as nossas ansiedades a Deus é a promessa de uma paz sobrenatural: "E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos sentimentos em Cristo Jesus". Esta paz não faz sentido para a lógica humana (excede o entendimento), mas atua como uma guarnição militar (guardará) protegendo a nossa mente e as nossas emoções contra o desespero. Para manter essa paz, Paulo instrui os crentes a disciplinarem os seus pensamentos (v. 8), focando em tudo o que é verdadeiro, honesto, justo, puro, amável e de boa fama. A nossa paz é diretamente afetada pela dieta da nossa mente.',
    desc3: 'Paulo conclui revelando o seu próprio testemunho de maturidade espiritual: "Já aprendi a contentar-me com o que tenho". O contentamento não é natural; é algo que precisa ser aprendido na escola da vida. Paulo aprendeu a viver na humilhação e na abundância, na fome e na fartura. O seu segredo não era o estoicismo ou a força de vontade, mas a dependência absoluta de Cristo. É neste contexto que ele declara o famoso versículo 13: "Posso todas as coisas em Cristo que me fortalece". Este versículo não é uma promessa de superpoderes para realizar os nossos desejos egoístas, mas a garantia de que Cristo nos dará força para suportar qualquer circunstância (fome, prisão ou morte) com alegria e fidelidade.',
    concl: 'A verdadeira alegria e o contentamento cristão são à prova de prisões e tempestades. Quando aprendemos a entregar as nossas ansiedades a Deus em oração, a disciplinar a nossa mente com a verdade e a depender da força de Cristo em todas as situações, experimentamos uma paz que o mundo não pode dar e nem pode tirar.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 12');
