const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: '1ki_19_1_18',
    intro: 'A história de Elias na caverna é um dos relatos mais honestos e reconfortantes da Bíblia sobre a fragilidade humana e o cuidado de Deus. Logo após a sua maior vitória espiritual no Monte Carmelo (onde ele derrotou 450 profetas de Baal e fez chover fogo do céu), Elias entra em um colapso físico, emocional e espiritual. Ameaçado de morte pela rainha Jezabel, o grande profeta foge para o deserto, senta-se debaixo de um zimbro e pede para morrer. Esta narrativa nos ensina que grandes vitórias espirituais são frequentemente seguidas por grande vulnerabilidade, e revela como Deus trata os Seus servos quando eles estão completamente esgotados.',
    desc1: 'O esgotamento de Elias é profundo e multifacetado. Ele está fisicamente exausto (após correr quilômetros), emocionalmente drenado (pela tensão do Carmelo) e espiritualmente decepcionado (pois o avivamento nacional que ele esperava não aconteceu; Jezabel continuava no poder). Ele ora: "Basta; toma agora, ó Senhor, a minha alma, pois não sou melhor do que meus pais". A depressão frequentemente distorce a nossa visão da realidade e nos faz focar apenas no negativo. A resposta de Deus ao desespero de Elias não é um sermão de repreensão, mas provisão prática: um anjo o toca e lhe dá pão cozido sobre as brasas e um cântaro de água. Deus respeita e cuida da nossa humanidade.',
    desc2: 'Sustentado por aquela comida, Elias caminha quarenta dias até Horebe (o Monte Sinai), o lugar onde Deus havia feito a aliança com Israel. Ele entra em uma caverna (um lugar de isolamento e escuridão). Deus pergunta: "Que fazes aqui, Elias?". Elias responde com uma mistura de autopiedade e orgulho: "Tenho sido muito zeloso... e só fiquei eu". Deus então manda Elias sair da caverna para ver a Sua manifestação. Passa um vento forte que fende os montes, depois um terremoto, e depois um fogo, mas "o Senhor não estava" neles. Deus não estava no espetáculo.',
    desc3: 'Após o fogo, vem "uma voz mansa e delicada" (um murmúrio suave). É nessa quietude que Deus se revela e fala com Elias. Deus corrige a visão distorcida do profeta: ele não estava sozinho, pois Deus havia reservado sete mil em Israel que não haviam dobrado os joelhos a Baal. Em vez de descartar o profeta esgotado, Deus o restaura dando-lhe uma nova missão (ungir novos reis e um sucessor, Eliseu) e novos companheiros. A cura para o isolamento e a depressão espiritual frequentemente envolve voltar ao trabalho do Reino, mas com uma nova perspectiva e em comunidade.',
    concl: 'Deus é infinitamente gentil com a nossa fragilidade. Ele não nos descarta quando estamos esgotados, deprimidos ou com medo. Ele nos restaura não com condenação, mas com a Sua presença suave, com suprimento prático para as nossas necessidades físicas e com um novo propósito para as nossas vidas.'
  },
  {
    id: 'mt_14_22_33',
    intro: 'O episódio de Jesus andando sobre as águas ocorre imediatamente após a multiplicação dos pães. Jesus "obriga" os Seus discípulos a entrarem no barco e irem para o outro lado do Mar da Galileia, enquanto Ele sobe ao monte para orar sozinho. O que se segue é uma das tempestades mais aterrorizantes que os discípulos (muitos deles pescadores experientes) já enfrentaram. Esta narrativa não é apenas sobre o poder de Jesus sobre as leis da natureza, mas uma profunda lição sobre a natureza da fé, o perigo da distração e a prontidão da graça de Deus para nos resgatar quando afundamos.',
    desc1: 'Os discípulos estão no meio do mar, na quarta vigília da noite (entre 3 e 6 da manhã), exaustos de remar contra o vento contrário e açoitados pelas ondas. Eles estavam exatamente onde Jesus havia mandado, provando que a obediência não nos isenta de tempestades. De repente, Jesus vem andando sobre as águas. Em vez de se alegrarem, os discípulos gritam de terror, achando que é um fantasma. O medo frequentemente nos cega para a presença de Deus nas nossas crises. A resposta de Jesus é imediata e traz a paz que acalma a tempestade interna antes de acalmar a externa: "Tende bom ânimo, sou eu, não temais".',
    desc2: 'Pedro, impulsivo e ousado, responde: "Senhor, se és tu, manda-me ir ter contigo por cima das águas". Jesus diz apenas uma palavra: "Vem". A fé verdadeira exige que saiamos da nossa zona de conforto (o barco) e pisemos no impossível, confiando unicamente na palavra de Cristo. Enquanto Pedro manteve os olhos fixos em Jesus, ele experimentou o milagre e andou sobre as águas. A fé nos sustenta acima das circunstâncias que deveriam nos afogar.',
    desc3: 'No entanto, o milagre é interrompido pela distração. "Mas, sentindo o vento forte, teve medo; e, começando a ir para o fundo, clamou, dizendo: Senhor, salva-me!". Quando Pedro tirou os olhos de Jesus e olhou para a força da tempestade, a gravidade e o medo assumiram o controle. A dúvida sempre nos faz afundar. A resposta de Jesus é a essência da graça: Ele não espera Pedro se afogar para dar uma lição; "logo Jesus, estendendo a mão, segurou-o", repreendendo suavemente a sua pequena fé. Quando eles entram no barco, o vento cessa, e a reação final de todos é a adoração: "És verdadeiramente o Filho de Deus".',
    concl: 'A vida cristã é uma caminhada sobre as águas da adversidade. Enquanto mantivermos o nosso foco em Cristo, seremos sustentados pelo Seu poder. E mesmo quando a nossa fé vacila, olhamos para a tempestade e começamos a afundar, a mão do Salvador está sempre estendida e pronta para nos resgatar ao primeiro clamor.'
  },
  {
    id: 'lk_15_1_10',
    intro: 'O capítulo 15 de Lucas é frequentemente chamado de "O Evangelho dentro do Evangelho". Ele começa com uma murmuração dos fariseus e escribas: "Este recebe pecadores, e come com eles". A religião legalista se escandalizava com a graça de Jesus. Em resposta, Jesus conta três parábolas (a ovelha perdida, a moeda perdida e o filho pródigo) para revelar o coração de Deus. As duas primeiras parábolas (a ovelha e a moeda) focam na iniciativa divina: Deus não é um juiz distante esperando que os pecadores se consertem, mas um buscador apaixonado e incansável daquilo que se perdeu.',
    desc1: 'A primeira parábola é a da Ovelha Perdida. Um pastor tem cem ovelhas e perde uma. A lógica humana e econômica diria para focar nas noventa e nove que estão seguras, mas a lógica do Reino é diferente. O pastor deixa as noventa e nove no deserto e vai em busca daquela que se perdeu "até encontrá-la". A ovelha perdida não pode salvar a si mesma; ela depende inteiramente da busca do pastor. Quando a encontra, ele não a castiga, mas a coloca alegremente sobre os ombros e a traz para casa. Deus vai aos lugares mais difíceis e perigosos para nos resgatar.',
    desc2: 'A segunda parábola é a da Moeda Perdida (uma dracma). Uma mulher tem dez moedas de prata (provavelmente parte do seu dote de casamento, tendo grande valor sentimental e financeiro) e perde uma dentro de casa. Ela não aceita a perda. Ela acende a candeia (a luz do Espírito Santo), varre a casa (a ação purificadora da Palavra) e busca diligentemente até encontrá-la. A moeda estava perdida dentro de casa, assim como muitas pessoas estão perdidas dentro das igrejas, cobertas pela poeira da religiosidade, precisando ser encontradas pela luz do Evangelho.',
    desc3: 'O clímax de ambas as parábolas é a celebração. O pastor chama os amigos e vizinhos: "Alegrai-vos comigo, porque já achei a minha ovelha perdida". A mulher faz o mesmo: "Alegrai-vos comigo, porque já achei a dracma perdida". Jesus conclui revelando uma verdade teológica maravilhosa: "Assim vos digo que há alegria diante dos anjos de Deus por um pecador que se arrepende". O céu não faz festa quando os fariseus se orgulham de sua justiça própria, mas o céu entra em júbilo quando um único pecador quebrado é encontrado e trazido de volta para casa pela graça de Deus.',
    concl: 'Você tem um valor inestimável para Deus. Ele não espera que o perdido encontre o caminho de volta sozinho; Ele toma a iniciativa da busca. A salvação não é apenas a nossa alegria por termos sido encontrados, mas é, acima de tudo, a alegria do próprio Deus em nos resgatar.'
  },
  {
    id: 'act_3_1_10',
    intro: 'A cura do coxo na Porta Formosa é o primeiro milagre registrado após o Pentecostes e serve como um poderoso paradigma para a missão da Igreja. Pedro e João estão subindo ao Templo para a oração da tarde (hora nona). Na porta chamada Formosa (uma entrada magnífica de bronze), eles encontram um homem que era coxo desde o ventre de sua mãe. Ele era colocado ali todos os dias para pedir esmolas. Este homem representa a humanidade caída: tão perto da presença de Deus (o Templo), mas excluída de entrar, paralisada desde o nascimento e dependendo de migalhas para sobreviver.',
    desc1: 'O encontro começa com uma expectativa frustrada. O coxo vê Pedro e João e pede uma esmola, esperando receber algumas moedas de cobre para sobreviver mais um dia. Pedro fixa os olhos nele e diz: "Olha para nós". O homem olha com expectativa financeira. A religião sem o poder do Espírito Santo frequentemente se limita a dar "esmolas" – alívio temporário, conselhos morais ou ajuda social – que podem aliviar o sofrimento imediato, mas mantêm as pessoas paralisadas na porta, sem nunca experimentarem a verdadeira transformação.',
    desc2: 'A resposta de Pedro é uma das declarações mais famosas da Igreja Primitiva: "Não tenho prata nem ouro; mas o que tenho, isso te dou. Em nome de Jesus Cristo, o Nazareno, levanta-te e anda". Pedro reconhece a sua própria pobreza material, mas tem plena consciência da sua riqueza espiritual. A Igreja não pode dar ao mundo o que não tem, mas tem a obrigação de dar o que recebeu: a autoridade e o poder do Nome de Jesus. Pedro não ora pedindo que Deus cure; ele age com a autoridade delegada por Cristo, toma o homem pela mão direita e o levanta.',
    desc3: 'O milagre é instantâneo e completo. Os pés e os tornozelos do homem se firmam. Ele não apenas se levanta, mas dá um salto, começa a andar e entra no Templo com eles, "andando, saltando e louvando a Deus". A cura física foi apenas o meio para a restauração espiritual e social. O homem que passou a vida inteira do lado de fora agora entra no santuário como um adorador. Todo o povo o vê e fica cheio de pasmo e assombro, o que abre a porta para o poderoso sermão evangelístico de Pedro que se segue.',
    concl: 'A missão da Igreja não é apenas oferecer alívio temporário para as consequências do pecado, mas trazer a cura radical e a transformação eterna através do poder do Nome de Jesus. Quando a Igreja caminha na autoridade de Cristo, os paralisados são levantados e transformados em adoradores.'
  },
  {
    id: 'gen_50_15_21',
    intro: 'O capítulo 50 de Gênesis é o desfecho magnífico da longa e dolorosa saga de José e seus irmãos. Após a morte do patriarca Jacó, os irmãos de José são tomados pelo pânico. Eles projetam a sua própria culpa em José, acreditando que o perdão que haviam recebido anos antes era apenas uma trégua temporária por respeito ao pai idoso. Eles temem que, agora que Jacó está morto, José finalmente usará o seu poder absoluto como governador do Egito para se vingar de tê-lo vendido como escravo. Este texto é a maior aula do Antigo Testamento sobre a soberania de Deus, a providência divina e o poder libertador do perdão genuíno.',
    desc1: 'O medo dos irmãos os leva a enviar um mensageiro a José com uma história (provavelmente inventada) de que Jacó, antes de morrer, havia ordenado que José os perdoasse. Em seguida, eles mesmos vêm, prostram-se diante dele (cumprindo mais uma vez os sonhos proféticos da juventude de José) e se oferecem como escravos. O pecado não resolvido e a culpa sempre nos mantêm prisioneiros do medo, fazendo-nos duvidar da graça que já recebemos. Ao ouvir as palavras deles, José chora. Ele chora porque percebe que, mesmo após tantos anos de amor e provisão, os seus irmãos ainda não haviam compreendido a profundidade do seu perdão.',
    desc2: 'A resposta de José é um dos picos teológicos da Bíblia. Ele os tranquiliza com uma pergunta retórica: "Não temais; porventura estou eu em lugar de Deus?". José recusa-se a assumir o papel de juiz e vingador. O perdão genuíno liberta o ofendido da necessidade de retaliação, entregando a justiça nas mãos de Deus. Em seguida, ele profere a declaração que resume toda a sua vida: "Vós bem intentastes mal contra mim; porém Deus o intentou para bem, para fazer como se vê neste dia, para conservar muita gente com vida".',
    desc3: 'José não minimiza o pecado dos irmãos ("vós intentastes mal"), nem chama o mal de bem. A venda para a escravidão, a falsa acusação de Potifar e os anos na prisão foram reais e dolorosos. No entanto, ele reconhece que, por trás da maldade humana, havia uma mão invisível e soberana orquestrando tudo para um propósito maior de salvação. A providência de Deus não anula a responsabilidade humana, mas a sobrepuja. José termina prometendo sustentá-los e aos seus filhos, falando-lhes "ao coração". O perdão não apenas cancela a dívida, mas abençoa o ofensor.',
    concl: 'A história de José nos ensina que o perdão só é plenamente possível quando confiamos na soberania de Deus. Quando entendemos que Deus governa até mesmo sobre as injustiças que sofremos, usando-as para forjar o nosso caráter e para a salvação de outros, somos libertos da amargura e capacitados a amar aqueles que nos feriram.'
  },
  {
    id: '2sam_12_1_13',
    intro: 'O capítulo 12 de 2 Samuel é o momento do acerto de contas. O rei Davi, o "homem segundo o coração de Deus", havia cometido os pecados mais terríveis de sua vida: adulterou com Bate-Seba e, para encobrir a gravidez, planejou o assassinato do marido dela, Urias, um de seus soldados mais leais. Durante meses, Davi viveu na mentira, achando que havia escondido o seu pecado com sucesso. Mas "a coisa que Davi fez pareceu mal aos olhos do Senhor". Deus, em Sua misericórdia confrontadora, envia o profeta Natã. Esta narrativa é uma obra-prima sobre como a Palavra de Deus desmascara a hipocrisia e como o arrependimento genuíno atrai a graça imediata.',
    desc1: 'Natã não entra no palácio com acusações diretas (o que poderia fazer o rei se defender ou mandar matá-lo). Ele usa uma parábola brilhante: a história de um homem muito rico, com muitas ovelhas, que rouba a única e amada ovelhinha de um homem pobre para preparar um banquete para um visitante. O pecado frequentemente nos cega para as nossas próprias falhas, mas nos deixa com a visão aguçada para julgar os erros dos outros. Ao ouvir a história, a ira de Davi se acende grandemente contra o homem rico, e ele declara a sentença: "O homem que fez isso é digno de morte". Davi, sem saber, condenou a si mesmo.',
    desc2: 'É então que Natã dispara a flecha da verdade que atravessa as defesas do rei: "Tu és este homem!". A Palavra de Deus funciona como um espelho que revela quem realmente somos. Natã passa a listar tudo o que Deus havia feito por Davi (livramento, unção, reino) e expõe a raiz do pecado: "Por que, pois, desprezaste a palavra do Senhor, fazendo o mal diante de seus olhos?". O pecado de Davi não foi apenas contra Urias ou Bate-Seba; foi um desprezo direto contra o próprio Deus e a Sua bondade. Natã então pronuncia as graves consequências que viriam sobre a casa de Davi (a espada nunca se apartaria da sua família).',
    desc3: 'A grandeza de Davi não estava na sua perfeição, mas na sua capacidade de se arrepender. Diante da exposição total, ele não dá desculpas, não culpa Bate-Seba por tomar banho no terraço, não culpa a pressão do reinado e não tenta justificar suas ações. Ele profere apenas quatro palavras no hebraico: "Pequei contra o Senhor". É um arrependimento total, incondicional e quebrantado (que mais tarde geraria o Salmo 51). A resposta de Deus através de Natã é imediata e maravilhosa: "Também o Senhor perdoou o teu pecado; não morrerás". A graça de Deus é maior do que o nosso pior pecado.',
    concl: 'Não podemos esconder os nossos pecados de Deus, e a tentativa de fazê-lo só traz miséria espiritual. O caminho para a restauração não é o encobrimento, mas a confissão honesta e quebrantada. Quando assumimos a nossa culpa diante de Deus, encontramos a Sua maravilhosa e imediata graça perdoadora.'
  },
  {
    id: 'luk_10_38_42',
    intro: 'O breve relato da visita de Jesus à casa de Marta e Maria em Betânia é uma das passagens mais instrutivas do Novo Testamento sobre as prioridades da vida cristã. Jesus e Seus discípulos são recebidos na casa de Marta. O cenário que se desenrola apresenta um contraste clássico entre duas atitudes diante do Mestre: o ativismo ansioso e a adoração contemplativa. Esta história não é uma condenação do trabalho ou do serviço prático (que são essenciais), mas um alerta severo sobre o perigo de permitir que o serviço para Jesus substitua a intimidade com Jesus.',
    desc1: 'O texto começa descrevendo as posturas das duas irmãs. Maria "assentando-se também aos pés de Jesus, ouvia a sua palavra". Sentar aos pés de um rabino era a posição de um discípulo, uma atitude de submissão, fome espiritual e adoração. Marta, por outro lado, "andava distraída em muitos serviços". O serviço de Marta era legítimo, nobre e necessário (afinal, ela estava hospedando o Filho de Deus e Seus discípulos). O problema não era o serviço em si, mas o fato de que ela estava "distraída" (literalmente, puxada em várias direções) por ele. É perfeitamente possível estar tão ocupado trabalhando para o Senhor que nos esquecemos do Senhor do trabalho.',
    desc2: 'A distração de Marta logo se transforma em frustração, ansiedade e, finalmente, em cobrança. Ela interrompe Jesus e diz: "Senhor, não te importas de que minha irmã me deixe servir só? Dize-lhe que me ajude". O ativismo religioso frequentemente gera amargura e um espírito de julgamento. Marta não apenas critica a sua irmã, mas repreende o próprio Jesus, acusando-O de não se importar com o seu esforço. Quando o nosso serviço não flui da adoração, ele se torna um fardo pesado que nos faz murmurar contra os outros e contra Deus.',
    desc3: 'Jesus responde com profunda ternura e firmeza: "Marta, Marta, estás ansiosa e afadigada com muitas coisas, mas uma só é necessária". Jesus diagnostica a doença da alma de Marta: a ansiedade gerada pela multiplicidade de tarefas. Ele então estabelece a prioridade absoluta do Reino: apenas uma coisa é verdadeiramente necessária. "E Maria escolheu a boa parte, a qual não lhe será tirada". A "boa parte" é a comunhão com Cristo, a escuta atenta da Sua Palavra. O serviço terminará, as refeições acabarão, mas a Palavra de Deus e a intimidade com Ele permanecem para a eternidade.',
    concl: 'O serviço cristão é vital, mas ele deve ser sempre o fruto da nossa intimidade com Cristo, e nunca o substituto dela. A nossa maior prioridade não é o que podemos fazer por Jesus, mas estar aos Seus pés, ouvindo a Sua voz e recebendo a Sua graça. Essa é a única coisa que não nos pode ser tirada.'
  },
  {
    id: 'jhn_2_1_11',
    intro: 'O milagre da transformação da água em vinho nas Bodas de Caná da Galileia é o primeiro dos sete "sinais" registrados no Evangelho de João. É significativo que Jesus não tenha iniciado o Seu ministério público curando um leproso, ressuscitando um morto ou pregando no Templo, mas salvando uma festa de casamento em uma pequena aldeia. Este milagre não é apenas uma demonstração de poder sobre a natureza, mas um sinal teológico profundo que revela a glória de Cristo e a natureza do Seu Reino: um Reino que traz alegria abundante, purificação e a transformação da velha religião em uma nova e vibrante aliança.',
    desc1: 'O cenário é uma festa de casamento que enfrenta uma crise social e cultural devastadora: "Faltou vinho". No antigo Oriente Médio, a falta de vinho em um casamento não era apenas um inconveniente, mas uma quebra grave de hospitalidade que traria vergonha duradoura para a família. A falta de vinho simboliza o esgotamento dos recursos humanos. A alegria humana, as tradições e os prazeres deste mundo sempre têm um limite; eles inevitavelmente acabam e deixam um vazio. Maria, mãe de Jesus, percebe a crise e leva o problema à pessoa certa: "Eles não têm vinho".',
    desc2: 'A resposta de Jesus a Maria parece distante ("Mulher, que tenho eu contigo? Ainda não é chegada a minha hora"), indicando que Ele agora age não sob a autoridade materna, mas sob o cronograma do Pai celestial. No entanto, Maria demonstra uma fé e submissão perfeitas ao orientar os servos: "Fazei tudo quanto ele vos disser". Esta é a regra de ouro para qualquer milagre. Jesus ordena que encham de água seis talhas de pedra, que eram usadas para a purificação ritual dos judeus. A velha religião (representada pelas talhas de pedra e pela água da purificação) era pesada, externa e incapaz de trazer verdadeira alegria.',
    desc3: 'Os servos enchem as talhas até em cima, tiram a água e a levam ao mestre-sala. O milagre acontece silenciosamente. A água da purificação religiosa é transformada no melhor vinho da festa. O mestre-sala fica impressionado, pois o costume era servir o vinho inferior no final, mas o noivo havia guardado "o bom vinho até agora". Jesus não apenas restaura o que foi perdido, Ele traz algo infinitamente superior e em uma quantidade extravagante (cerca de 600 litros de vinho). João conclui: "Jesus principiou assim os seus sinais... e manifestou a sua glória; e os seus discípulos creram nele".',
    concl: 'O milagre de Caná nos ensina que a religião sem Cristo é como água em talhas de pedra: fria, ritualística e incapaz de saciar. Mas quando convidamos Jesus para as nossas crises e obedecemos à Sua Palavra, Ele transforma a nossa escassez, a nossa vergonha e a nossa religiosidade vazia na alegria abundante e inesgotável do Seu Reino.'
  },
  {
    id: 'act_10_1_16',
    intro: 'O capítulo 10 de Atos é um dos momentos mais revolucionários da história da Igreja. Até este ponto, o Cristianismo era visto essencialmente como uma seita judaica; o Evangelho era pregado quase exclusivamente aos judeus, e a ideia de aceitar gentios (não-judeus) sem que eles primeiro se submetessem à Lei de Moisés era impensável. Para que o Evangelho alcançasse os confins da terra, Deus precisava realizar dois milagres simultâneos: preparar o coração de um gentio para receber a Palavra e, mais difícil ainda, quebrar os preconceitos teológicos e culturais arraigados no coração do apóstolo Pedro. A visão do lençol é o momento em que Deus derruba o muro de separação.',
    desc1: 'A narrativa começa em Cesareia com Cornélio, um centurião romano. Ele é descrito como "piedoso e temente a Deus", que dava muitas esmolas e orava continuamente. No entanto, a sua religiosidade, moralidade e boas obras não eram suficientes para salvá-lo; ele precisava ouvir o Evangelho de Jesus Cristo. Deus envia um anjo a Cornélio, instruindo-o a mandar buscar a Pedro em Jope. A salvação não vem pelas nossas boas obras, mas pela fé na mensagem do Evangelho que Deus providenciou.',
    desc2: 'Enquanto os mensageiros de Cornélio se aproximam de Jope, Deus começa a trabalhar no coração de Pedro. Ao meio-dia, com fome, Pedro sobe ao terraço para orar e cai em êxtase. Ele vê o céu aberto e um grande lençol descendo, cheio de todos os tipos de animais, répteis e aves (muitos deles considerados "impuros" e proibidos pela lei alimentar judaica de Levítico 11). Uma voz do céu ordena: "Levanta-te, Pedro, mata e come". A fome física de Pedro é usada por Deus para ensinar uma lição espiritual profunda sobre a pureza e a graça.',
    desc3: 'A resposta de Pedro é um paradoxo religioso: "De modo nenhum, Senhor! Porque nunca comi coisa alguma comum e imunda". Ele chama Deus de "Senhor", mas diz "não" à Sua ordem, apegando-se à sua tradição teológica. A voz divina o repreende com uma declaração que muda a história da redenção: "Não chames tu comum (impuro) ao que Deus purificou". Isso acontece três vezes para confirmar a mensagem. Deus não estava apenas mudando a dieta de Pedro; Ele estava declarando que, através do sacrifício de Cristo, a distinção cerimonial entre judeus (puros) e gentios (impuros) havia sido abolida. A graça de Deus é para todas as nações.',
    concl: 'Deus frequentemente precisa desconstruir os nossos preconceitos religiosos, culturais e raciais para que possamos ser instrumentos úteis nas Suas mãos. A visão de Pedro nos ensina que não há pessoas "impuras" ou indignas de ouvir o Evangelho. A cruz de Cristo purificou o caminho para que toda a humanidade tenha acesso ao Pai.'
  },
  {
    id: 'rut_1_1_18',
    intro: 'O livro de Rute é uma joia literária e teológica que brilha no meio da escuridão do período dos Juízes. A história começa com uma série de tragédias devastadoras: fome, exílio, viuvez e luto profundo. No entanto, através da lealdade extraordinária de uma jovem viúva estrangeira e da providência invisível de Deus, o que começa como um funeral termina como um casamento que altera a genealogia do Messias. O capítulo 1 estabelece o cenário de dor e o teste definitivo de fidelidade que define o caráter de Rute e o futuro da redenção.',
    desc1: 'A narrativa começa com Elimeleque, que, diante de uma fome em Belém (ironicamente, a "Casa do Pão"), decide abandonar a Terra Prometida e levar sua esposa Noemi e seus dois filhos para os campos de Moabe (uma nação idólatra e inimiga histórica de Israel). A busca por sobrevivência fora da vontade de Deus resulta em tragédia total: Elimeleque morre, os filhos se casam com mulheres moabitas (Orfa e Rute) e, dez anos depois, ambos os filhos também morrem. Noemi fica completamente desamparada, sem marido, sem filhos, sem netos e em terra estrangeira. O pecado e a fuga de Deus sempre cobram um preço alto.',
    desc2: 'Ao ouvir que Deus havia visitado o Seu povo dando-lhes pão, Noemi decide voltar para Belém. No caminho, amargurada e sem esperança, ela tenta persuadir suas noras a voltarem para as casas de suas mães e para os seus deuses, pois ela não tinha mais nada a oferecer-lhes. É o teste definitivo da lealdade. Orfa chora, beija a sogra e volta para o seu povo e para a sua idolatria. A lealdade de Orfa era baseada na conveniência e no afeto natural, que não suportam a prova do sofrimento. Mas Rute "se apegou a ela". A verdadeira fidelidade é revelada quando não há nada a ganhar.',
    desc3: 'A resposta de Rute a Noemi é uma das declarações de amor e conversão mais belas de toda a Bíblia: "Não me instes para que te abandone... porque aonde quer que tu fores irei eu, e onde quer que pousares, ali pousarei eu; o teu povo é o meu povo, o teu Deus é o meu Deus". Rute não apenas escolhe ficar com a sogra idosa e amargurada; ela faz uma renúncia radical do seu passado, da sua cultura e dos seus deuses, para abraçar o Deus de Israel e o Seu povo, aceitando a pobreza e a condição de estrangeira. É um salto de fé absoluto na providência do Deus de Noemi.',
    concl: 'A verdadeira lealdade e o amor sacrificial se revelam nos momentos de maior perda e dificuldade. A decisão de Rute de abandonar tudo por amor e fé não apenas salvou Noemi da amargura, mas inseriu uma estrangeira moabita na linhagem real do rei Davi e, em última instância, do próprio Jesus Cristo. A providência de Deus usa a fidelidade nas pequenas coisas para realizar os Seus grandes propósitos redentores.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done');
