const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'luk_18_9_14',
    intro: 'A Parábola do Fariseu e do Publicano é contada por Jesus com um alvo específico e contundente: "alguns que confiavam em si mesmos, crendo que eram justos, e desprezavam os outros". A parábola contrasta dois homens que sobem ao templo para orar. Aos olhos da sociedade judaica da época, o fariseu era o modelo de virtude, piedade e ortodoxia, enquanto o publicano (cobrador de impostos para Roma) era o símbolo da traição, da corrupção e do pecado. No entanto, Jesus inverte completamente a expectativa da audiência, revelando que a justificação diante de Deus não depende da nossa performance moral, mas da nossa postura de quebrantamento e dependência da Sua misericórdia.',
    desc1: 'O fariseu sobe ao templo e ora "consigo mesmo". A sua oração não é uma petição a Deus, mas um currículo de autoexaltação. Ele começa agradecendo a Deus, mas o motivo da sua gratidão é o seu próprio orgulho: "Ó Deus, graças te dou porque não sou como os demais homens, roubadores, injustos e adúlteros; nem ainda como este publicano". A falsa justiça sempre precisa de alguém pior para se comparar e se sentir superior. Em seguida, ele lista os seus méritos religiosos: "Jejuo duas vezes na semana, e dou os dízimos de tudo quanto possuo". Ele confiava na sua própria obediência à lei para exigir a aceitação de Deus.',
    desc2: 'O publicano, por outro lado, reconhece a sua total indignidade. A sua postura física reflete a sua condição espiritual: "estando em pé, de longe, nem ainda queria levantar os olhos ao céu". Ele não se atreve a se aproximar do altar e não tem nenhum mérito para apresentar. Em vez de listar as suas boas obras, ele "batia no peito" (um sinal de profunda angústia e luto pelo próprio pecado) e faz a oração mais curta e eficaz da Bíblia: "Ó Deus, tem misericórdia de mim, pecador". A palavra usada para "misericórdia" aqui (hilaskomai) significa literalmente "sê propício a mim", um apelo ao sacrifício expiatório no altar. Ele pede que a ira de Deus seja desviada pela graça.',
    desc3: 'O veredito de Jesus choca a audiência religiosa: "Digo-vos que este (o publicano) desceu justificado para sua casa, e não aquele (o fariseu)". A justificação (ser declarado justo por Deus) não foi concedida ao homem que tinha a melhor moralidade, mas ao homem que reconheceu a sua falência espiritual e clamou pela misericórdia divina. O fariseu pediu justiça e recebeu exatamente o que merecia (nada, pois a sua justiça era como trapo da imundícia). O publicano pediu misericórdia e recebeu a justificação. Jesus conclui com o princípio do Reino: "qualquer que a si mesmo se exalta será humilhado, e qualquer que a si mesmo se humilha será exaltado".',
    concl: 'A parábola nos adverte contra o perigo letal da religiosidade moralista. Quando confiamos na nossa própria justiça, tornamo-nos cegos para o nosso pecado e cruéis para com os outros. A porta da graça só se abre para aqueles que, como o publicano, batem no peito, reconhecem a sua total falência e dependem exclusivamente da misericórdia de Deus.'
  },
  {
    id: 'gen_45_1_15',
    intro: 'O capítulo 45 de Gênesis é o clímax emocional e teológico da longa saga de José. Mais de vinte anos haviam se passado desde que os seus irmãos o venderam como escravo por inveja. Após passar pela cisterna, pela escravidão na casa de Potifar, pela prisão injusta e, finalmente, pela exaltação como governador de todo o Egito (segundo apenas a Faraó), José agora tem os seus irmãos ajoelhados diante dele, implorando por comida durante a fome global. Ele havia testado os seus irmãos (através do incidente com o copo de prata na saca de Benjamim) para ver se eles haviam mudado. Ao ouvir o apelo sacrificial de Judá (que se ofereceu para ser escravo no lugar de Benjamim), José não consegue mais conter a emoção. A sua revelação é uma das maiores demonstrações de perdão e de compreensão da soberania de Deus em toda a Escritura.',
    desc1: 'A tensão atinge o limite. José ordena que todos os egípcios saiam da sala. Ele chora tão alto que os egípcios e a casa de Faraó o ouvem. Então, ele pronuncia as palavras que aterrorizam os seus irmãos: "Eu sou José; vive ainda meu pai?". Os irmãos ficam "pasmos" (literalmente, aterrorizados e paralisados). Eles estão diante do homem mais poderoso do mundo, que tem o poder de vida e morte sobre eles, e percebem que é o mesmo irmão que eles haviam traído e vendido. A culpa do passado encontra o poder do presente. A expectativa natural seria a vingança imediata e implacável.',
    desc2: 'Em vez de vingança, José oferece graça e uma perspectiva teológica revolucionária. Ele pede que eles se aproximem e diz: "Eu sou José, vosso irmão, a quem vendestes para o Egito. Agora, pois, não vos entristeçais, nem vos pese aos vossos olhos por me haverdes vendido para cá; porque para conservação da vida, Deus me enviou adiante de vós". José não nega o pecado deles ("a quem vendestes"), mas ele se recusa a ser definido como uma vítima. Ele enxerga a mão invisível da providência de Deus operando através da maldade humana. O perdão de José é possível porque ele entende que Deus estava no controle de cada detalhe da sua dor.',
    desc3: 'José repete a sua conclusão teológica três vezes para garantir que eles entendam: "Assim não fostes vós que me enviastes para cá, senão Deus" (v. 8). Deus usou a inveja dos irmãos para posicionar José no Egito, a fim de salvar a própria família (a linhagem da aliança) e muitas nações da fome severa. José então ordena que eles voltem rapidamente a Canaã, busquem o seu pai Jacó e tragam toda a família para habitar na terra de Gósen, onde ele os sustentaria. A cena termina com José beijando todos os seus irmãos e chorando sobre eles. O perdão restaura a comunhão que o pecado havia destruído.',
    concl: 'A história da revelação de José nos ensina que o perdão verdadeiro só é possível quando paramos de focar na maldade das pessoas que nos feriram e começamos a focar na soberania de Deus, que é capaz de transformar as nossas maiores tragédias em instrumentos de salvação. Como José diria mais tarde: "Vós intentastes o mal contra mim, mas Deus o tornou em bem".'
  },
  {
    id: 'exo_32_1_14',
    intro: 'O capítulo 32 de Êxodo narra a mais rápida e trágica apostasia da história de Israel. Apenas algumas semanas antes, o povo havia ouvido a voz de Deus no Monte Sinai, tremido de medo e prometido obedecer a todos os mandamentos (incluindo "Não farás para ti imagem de escultura"). Enquanto Moisés estava no cume do monte por quarenta dias recebendo as tábuas da Lei, o povo no acampamento perde a paciência. A demora de Deus frequentemente revela a verdadeira condição do coração humano. Incapazes de lidar com a invisibilidade de Deus e com a ausência do seu líder humano, eles exigem um ídolo tangível. A narrativa do bezerro de ouro é um aviso contundente sobre a nossa tendência inata para a idolatria e a necessidade desesperada de intercessão.',
    desc1: 'A crise começa com a impaciência: "Mas vendo o povo que Moisés tardava em descer do monte...". O povo se reúne contra Arão e faz uma exigência absurda: "Levanta-te, faze-nos deuses, que vão adiante de nós; porque quanto a este Moisés... não sabemos o que lhe sucedeu". Eles queriam um deus que pudessem ver, controlar e carregar. Arão, cedendo covardemente à pressão popular, pede as argolas de ouro das mulheres e filhos, funde o ouro e molda um bezerro. O bezerro (provavelmente inspirado no deus egípcio Ápis) era um símbolo de força e fertilidade. O povo declara: "Estes são os teus deuses, ó Israel, que te tiraram da terra do Egito". A idolatria é a tentativa de reduzir o Deus infinito a uma imagem manipulável.',
    desc2: 'No dia seguinte, eles oferecem holocaustos, comem, bebem e "levantam-se para folgar" (uma expressão que implica orgias e rituais pagãos). Enquanto o povo festejava o seu falso deus no vale, o verdadeiro Deus falava com Moisés no monte. Deus diz a Moisés: "Vai, desce; porque o teu povo, que fizeste subir do Egito, se corrompeu". Deus repudia a nação ("teu povo") e declara a Sua ira justa: "Agora, pois, deixa-me, para que o meu furor se acenda contra eles, e os consuma; e eu farei de ti uma grande nação". Deus oferece a Moisés a oportunidade de ser o novo Abraão, começando tudo de novo.',
    desc3: 'A resposta de Moisés é uma das maiores intercessões da Bíblia. Ele recusa a oferta de grandeza pessoal e implora a favor do povo rebelde. Moisés usa três argumentos poderosos. Primeiro, ele lembra a Deus que o povo pertence a Ele ("o teu povo, que tiraste da terra do Egito com grande força"). Segundo, ele apela para a glória e a reputação de Deus entre as nações ("Por que hão de falar os egípcios, dizendo: Para mal os tirou, para matá-los nos montes?"). Terceiro, ele apela para a fidelidade de Deus à Sua própria aliança e promessas feitas a Abraão, Isaque e Israel. O resultado da intercessão é imediato: "Então o Senhor arrependeu-se do mal que dissera que havia de fazer ao seu povo".',
    concl: 'A história do bezerro de ouro expõe a fragilidade da nossa fé quando Deus parece demorar. Somos rápidos em fabricar "deuses" (sucesso, dinheiro, relacionamentos) para preencher o vazio da espera. No entanto, a história também revela o poder da intercessão. Assim como Moisés ficou na brecha para salvar Israel da ira de Deus, Jesus Cristo, o nosso mediador perfeito, intercede continuamente por nós, garantindo a nossa salvação apesar das nossas falhas.'
  },
  {
    id: '1sa_16_1_13',
    intro: 'O capítulo 16 de 1 Samuel marca uma transição crucial na história de Israel: a rejeição definitiva do rei Saul e a escolha do rei Davi. Saul havia sido escolhido de acordo com os critérios humanos (ele era o homem mais alto e bonito de Israel), mas o seu coração era rebelde e desobediente. Deus então envia o profeta Samuel à cidade de Belém, à casa de Jessé, com a missão de ungir um novo rei entre os seus filhos. O processo de seleção divina que se segue é uma das lições mais profundas da Bíblia sobre como Deus avalia a liderança e o valor humano, destruindo completamente os nossos padrões de aparência e status.',
    desc1: 'Samuel chega a Belém e convida Jessé e os seus filhos para o sacrifício. Quando o filho mais velho, Eliabe, se apresenta, Samuel comete o mesmo erro que Israel havia cometido com Saul. Ao ver a altura e a aparência impressionante de Eliabe, o profeta pensa imediatamente: "Certamente está perante o Senhor o seu ungido". Samuel estava julgando pelo exterior. A nossa tendência natural é sempre avaliar o potencial de liderança, o sucesso e o valor de uma pessoa pela sua aparência física, carisma, currículo ou posição social.',
    desc2: 'Deus interrompe o pensamento de Samuel com um princípio teológico fundamental: "Não atentes para a sua aparência, nem para a grandeza da sua estatura, porque o tenho rejeitado; porque o Senhor não vê como vê o homem, pois o homem vê o que está diante dos olhos, porém o Senhor olha para o coração". Deus rejeita Eliabe e os outros seis filhos de Jessé que passam diante de Samuel. Nenhum deles era o escolhido. O coração (o centro da vontade, do caráter, da fé e das motivações) é o único critério que importa para Deus. A verdadeira qualificação para o serviço divino é invisível aos olhos humanos.',
    desc3: 'Após os sete filhos passarem, Samuel pergunta a Jessé: "Acabaram-se os mancebos?". Jessé responde que ainda faltava o menor (o mais jovem), que estava apascentando as ovelhas. Davi era tão insignificante aos olhos da sua própria família que nem sequer foi convidado para o sacrifício com o profeta. Samuel exige que o tragam. Quando Davi chega, Deus diz a Samuel: "Levanta-te, e unge-o, porque é este mesmo". Samuel toma o vaso de azeite e o unge no meio dos seus irmãos. A partir daquele dia, "o Espírito do Senhor se apoderou de Davi". O jovem pastor esquecido no campo foi escolhido para ser o maior rei de Israel.',
    concl: 'A unção de Davi nos ensina que Deus não é impressionado pelos nossos currículos, pela nossa aparência ou pela nossa popularidade. Ele procura corações que sejam fiéis a Ele na obscuridade (como Davi cuidando das ovelhas). Quando Deus encontra um coração segundo o Seu próprio coração, Ele o capacita com o Seu Espírito e o exalta no tempo certo, provando que os últimos serão os primeiros.'
  },
  {
    id: '2ki_4_1_7',
    intro: 'A história da viúva e do azeite é um dos milagres mais tocantes e práticos do ministério do profeta Eliseu. A narrativa começa com um grito de desespero. Uma mulher, viúva de um dos discípulos dos profetas (um homem que temia ao Senhor), encontra-se em uma crise financeira devastadora. Na cultura do antigo Oriente Médio, a dívida não paga resultava em escravidão. O credor estava batendo à porta para levar os seus dois filhos como escravos para pagar a dívida do marido falecido. Ela havia perdido o marido, estava perdendo os bens e agora estava prestes a perder os filhos. É nesse cenário de falência total que ela clama ao profeta, e Deus responde com um milagre de provisão abundante que exige fé e obediência prática.',
    desc1: 'Quando a viúva clama a Eliseu, a resposta do profeta é surpreendente. Ele não lhe dá dinheiro nem faz uma oração mágica para que a dívida desapareça. Ele faz duas perguntas: "Que te hei de fazer? Dize-me que é o que tens em casa?". Deus frequentemente começa o milagre a partir daquilo que já temos, por menor que seja. A mulher responde com a perspectiva da sua escassez: "Tua serva não tem nada em casa, senão uma botija de azeite". Aos olhos dela, um pouco de azeite era "nada" diante do tamanho da dívida. Mas nas mãos de Deus, o pouco que entregamos é a semente para o milagre.',
    desc2: 'Eliseu dá uma instrução que desafia a lógica: "Vai, pede emprestadas, de todos os teus vizinhos, vasilhas vazias, não poucas". Em seguida, ela deveria entrar em casa, fechar a porta atrás de si e dos seus filhos, e começar a derramar o seu único azeite nas vasilhas vazias. O milagre exigia três coisas: fé (para pedir vasilhas vazias aos vizinhos sem ter o que colocar nelas), privacidade (fechar a porta, pois o milagre acontece na intimidade com Deus, longe da incredulidade do mundo) e ação (ela tinha que começar a derramar o azeite antes de ver a multiplicação).',
    desc3: 'A viúva obedece. Ela fecha a porta e, com a ajuda dos filhos, começa a derramar. O azeite flui continuamente, enchendo vasilha após vasilha. O milagre não parou porque o poder de Deus acabou, mas porque a capacidade de receber da viúva chegou ao fim. Quando ela pede mais uma vasilha e o filho diz que não há mais nenhuma, o texto diz: "Então o azeite parou". A provisão de Deus foi exatamente proporcional à fé e à preparação da viúva (o número de vasilhas que ela recolheu). Ela vai a Eliseu, que lhe diz: "Vai, vende o azeite, e paga a tua dívida; e tu e teus filhos vivei do resto".',
    concl: 'A história da viúva e do azeite nos ensina que Deus se importa com as nossas crises financeiras e familiares. Quando entregamos o nosso "nada" (o pouco que temos) a Deus com fé e obediência, Ele o multiplica para pagar as nossas dívidas e sustentar o nosso futuro. O limite do milagre de Deus na nossa vida é frequentemente determinado pelo tamanho das "vasilhas vazias" da nossa fé.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 19');
