const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'gen_22_1_19',
    intro: 'O capítulo 22 de Gênesis, conhecido na tradição judaica como a "Akedah" (A Amarração de Isaque), é uma das narrativas mais tensas, profundas e teologicamente ricas de toda a Escritura. Após décadas de espera, Abraão finalmente tem o filho da promessa, Isaque. No entanto, Deus o submete ao teste supremo, pedindo que ele sacrifique exatamente aquilo que ele mais ama e que representa o cumprimento de todas as promessas divinas. Este teste não foi desenhado para destruir Abraão, mas para revelar a prioridade absoluta do seu coração e para prefigurar, com detalhes impressionantes, o sacrifício definitivo que o próprio Deus faria no Calvário.',
    desc1: 'O teste começa com um chamado claro e doloroso: "Toma agora o teu filho, o teu único filho, Isaque, a quem amas, e vai-te à terra de Moriá, e oferece-o ali em holocausto". O pedido ataca a lógica humana e a própria promessa de Deus (pois a descendência viria por Isaque). O teste revela se Abraão amava mais a dádiva (o filho) ou o Doador (Deus). A fé verdadeira é provada quando Deus nos pede para entregar o nosso "Isaque" – aquilo que consideramos essencial para a nossa felicidade e futuro.',
    desc2: 'A resposta de Abraão é um monumento à fé obediente. Ele "levantou-se de madrugada", não argumentou, não pediu explicações e não adiou a obediência. A viagem durou três dias (três dias em que Isaque esteve "morto" na mente de Abraão). Ao chegarem ao pé do monte, Abraão diz aos servos: "Ficai-vos aqui... eu e o moço iremos até ali; e havendo adorado, tornaremos a vós". Ele acreditava tão firmemente no caráter e na promessa de Deus que, como Hebreus 11:19 explica, ele confiava que Deus era poderoso para ressuscitar Isaque dentre os mortos.',
    desc3: 'No topo do monte (o mesmo monte onde mais tarde seria construído o Templo em Jerusalém), Isaque faz a pergunta cortante: "Onde está o cordeiro?". Abraão profetiza: "Deus proverá para si o cordeiro". Quando Abraão levanta o cutelo, o Anjo do Senhor intervém. Deus não queria a morte de Isaque; Ele queria a rendição do coração de Abraão. Imediatamente, Abraão vê um carneiro preso pelos chifres em um arbusto e o oferece em sacrifício substitutivo. O lugar é chamado de "Jeová-Jireh" (O Senhor Proverá). O carneiro substituiu Isaque, assim como Cristo nos substituiu na cruz.',
    concl: 'A verdadeira adoração custa tudo, mas a obediência radical sempre resulta em provisão divina. A história de Isaque aponta diretamente para a cruz: séculos depois, no mesmo monte Moriá, o próprio Deus Pai entregaria o Seu único Filho, a quem amava. Mas dessa vez, não haveria um anjo para interromper o sacrifício, nem um carneiro para substituir, porque Jesus era o Cordeiro definitivo que Deus proveu para a nossa salvação.'
  },
  {
    id: '1sa_1_1_20',
    intro: 'O primeiro livro de Samuel começa não com o relato de reis ou exércitos, mas com a dor silenciosa de uma mulher estéril em uma família disfuncional. Ana era uma das duas esposas de Elcana. Enquanto Penina tinha filhos e a provocava cruelmente, Ana carregava o estigma e a vergonha da esterilidade em uma cultura que via a falta de filhos como um sinal de desfavor divino. A história de Ana é um testemunho poderoso de como Deus usa a nossa dor mais profunda para nos levar a uma dependência radical dEle, transformando a nossa aflição no berço de um propósito que mudará a história.',
    desc1: 'A dor de Ana era multiplicada a cada ano durante as viagens a Siló para adoração. Penina a irritava excessivamente para a entristecer, e o amor de Elcana (que lhe dava porção dupla) não era suficiente para preencher o vazio do seu ventre e da sua alma. Ana chorava e não comia. O consolo humano, por mais bem-intencionado que seja, frequentemente falha em alcançar as profundezas da nossa angústia. A dor de Ana a levou a um ponto de ruptura, mas em vez de se render à amargura contra Deus ou à vingança contra Penina, ela escolheu o caminho da oração.',
    desc2: 'No templo, com amargura de alma, Ana chora abundantemente e faz um voto ao Senhor. Ela não pede um filho apenas para satisfazer o seu desejo materno ou para calar a sua rival. Ela consagra a criança a Deus antes mesmo de concebê-la: "Se... me deres um filho varão, ao Senhor o darei por todos os dias da sua vida". Ana alinha o seu desejo mais profundo com o propósito de Deus (que precisava de um profeta fiel para substituir a linhagem corrupta de Eli). A oração que move o céu é aquela que busca não apenas o nosso alívio, mas a glória de Deus.',
    desc3: 'Enquanto Ana orava silenciosamente (movendo apenas os lábios), o sacerdote Eli a confunde com uma mulher embriagada e a repreende. Mesmo diante dessa injustiça pastoral, Ana responde com mansidão e respeito, explicando que estava derramando a sua alma perante o Senhor. Eli então a abençoa: "Vai em paz; e o Deus de Israel te conceda a petição que lhe fizeste". O milagre da oração de Ana é visto antes mesmo da gravidez: "A mulher seguiu o seu caminho, e comeu, e o seu semblante já não era triste". A paz de Deus inunda o coração que entrega os seus fardos no altar.',
    concl: 'Deus frequentemente permite o fechamento de certas portas em nossas vidas para nos levar a um nível de oração e consagração que nunca alcançaríamos no conforto. Quando entregamos os nossos "Isaques" e "Samuéis" no altar antes mesmo de recebê-los, Deus transforma a nossa esterilidade em frutos que abençoarão gerações.'
  },
  {
    id: 'mt_13_1_23',
    intro: 'A Parábola do Semeador é a primeira e a mais fundamental das parábolas de Jesus no Evangelho de Mateus. Jesus a conta para uma grande multidão à beira-mar e, mais tarde, a explica em particular aos Seus discípulos. O propósito desta parábola é responder a uma pergunta crucial: se a mensagem do Reino (a semente) é tão poderosa e divina, por que ela produz resultados tão diferentes nas pessoas que a ouvem? Jesus revela que o problema nunca está na qualidade da semente ou na habilidade do Semeador, mas exclusivamente na condição do "solo" — o coração humano.',
    desc1: 'O primeiro solo é a "beira do caminho", que representa o coração endurecido. A semente cai, mas não consegue penetrar porque a terra foi pisada e compactada pela rotina, pelo cinismo ou pelo pecado. Jesus explica que este é aquele que ouve a Palavra do Reino, mas não a compreende (não a internaliza). Como a semente fica exposta na superfície, "vem o Maligno e arrebata o que foi semeado no seu coração". O inimigo tem pressa em roubar a Palavra antes que ela possa gerar fé e arrependimento.',
    desc2: 'Os dois solos seguintes representam corações que recebem a Palavra, mas falham em frutificar. O "solo rochoso" é o coração superficial: ouve a Palavra e a recebe logo com alegria, mas não tem raiz profunda. Quando surge a tribulação ou a perseguição por causa da Palavra, a pessoa logo se escandaliza e desiste. A fé baseada apenas em emoções não suporta o calor da provação. O "solo espinhoso" é o coração dividido: a semente cresce, mas os espinhos (os cuidados deste mundo, a sedução das riquezas e as ambições) crescem junto e sufocam a Palavra, tornando-a infrutífera. É a tragédia de tentar amar a Deus e ao mundo ao mesmo tempo.',
    desc3: 'O quarto e último solo é a "boa terra", que representa o coração receptivo, ensinável e focado. Jesus diz que este é o que "ouve e compreende a palavra". A verdadeira compreensão bíblica não é apenas intelectual, mas envolve submissão e obediência. Neste solo, a semente cria raízes profundas, não é sufocada pelos espinhos e, inevitavelmente, "dá fruto, e um produz cem, outro sessenta, e outro trinta por um". A marca inegável da verdadeira conversão e da recepção da Palavra de Deus não é a emoção inicial, mas a frutificação perseverante a longo prazo.',
    concl: 'A eficácia da Palavra de Deus em nossas vidas depende inteiramente da condição do nosso coração. Devemos orar constantemente para que o Espírito Santo quebre a dureza do nosso coração, aprofunde as nossas raízes na verdade e arranque os espinhos da ansiedade e do materialismo, para que possamos produzir uma colheita abundante para a glória de Deus.'
  },
  {
    id: 'luk_2_1_20',
    intro: 'O relato do nascimento de Jesus no Evangelho de Lucas é uma obra-prima de contrastes. O evento mais importante e transformador da história humana — a encarnação do Filho de Deus — não ocorreu nos corredores do poder em Roma, nem nos recintos sagrados do Templo em Jerusalém, mas em um estábulo humilde na pequena vila de Belém. Lucas justapõe o decreto arrogante do imperador romano com a fragilidade de um bebê em uma manjedoura, revelando que a verdadeira glória de Deus se manifesta na simplicidade, na pobreza e na identificação com os marginalizados.',
    desc1: 'A narrativa começa com a macro-história: César Augusto, o homem mais poderoso do mundo, emite um decreto para recensear todo o império, visando a cobrança de impostos e o controle militar. No entanto, Deus usa a arrogância do império para cumprir a profecia de Miqueias 5:2, movendo José e Maria de Nazaré para Belém. A micro-história revela a humildade da encarnação: Maria dá à luz o seu filho primogênito, envolve-o em panos e o deita em uma manjedoura (um cocho de alimentação de animais), "porque não havia lugar para eles na estalagem". O Rei do universo nasce na pobreza e na rejeição.',
    desc2: 'O anúncio do nascimento não é feito aos nobres ou aos sacerdotes, mas a um grupo de pastores que guardavam os seus rebanhos durante a noite. Os pastores eram frequentemente considerados impuros e marginalizados pela sociedade religiosa da época. É a eles que a glória do Senhor brilha e o anjo traz as "boas novas de grande alegria, que o será para todo o povo". O anjo anuncia o nascimento do "Salvador, que é Cristo, o Senhor", e dá um sinal surpreendente: não uma coroa ou um palácio, mas "um menino envolto em panos, e deitado numa manjedoura".',
    desc3: 'Após o anúncio, uma multidão dos exércitos celestiais irrompe em louvor: "Glória a Deus nas alturas, Paz na terra, boa vontade para com os homens". Os pastores não duvidam; eles dizem: "Vamos, pois, até Belém, e vejamos isso que aconteceu". Eles vão apressadamente, encontram a família e o bebê exatamente como o anjo havia dito, e tornam-se os primeiros evangelistas, divulgando a palavra a todos. Maria, em contraste com a agitação dos pastores, "guardava todas estas coisas, conferindo-as (meditando) em seu coração".',
    concl: 'O mistério do Natal é que o Deus Todo-Poderoso escolheu esvaziar-se da Sua glória celestial para nascer na sujeira de uma manjedoura, a fim de nos salvar. O verdadeiro sentido do Natal nos convida a responder como os pastores (com obediência apressada, adoração e testemunho) e como Maria (com contemplação profunda e silenciosa do mistério da graça).'
  },
  {
    id: 'exo_3_1_12',
    intro: 'O encontro de Moisés com Deus na sarça ardente é um dos momentos mais definidores da história da redenção. Moisés, que havia sido criado como príncipe no Egito, passou os últimos 40 anos no deserto de Midiã como um pastor de ovelhas fugitivo. Aos 80 anos de idade, ele provavelmente achava que a sua vida havia terminado em fracasso e obscuridade. No entanto, é no meio da rotina diária e no lugar mais improvável que Deus o encontra para lhe dar o maior chamado de sua vida. Esta narrativa revela como Deus chama, capacita e envia aqueles que se sentem inadequados para os Seus propósitos.',
    desc1: 'O encontro começa com uma visão intrigante: uma sarça (um arbusto comum e espinhoso do deserto) que ardia no fogo, mas não se consumia. Deus frequentemente usa o comum para revelar o extraordinário e atrai a nossa atenção antes de falar conosco. Quando Moisés se desvia para ver a "grande visão", Deus o chama pelo nome: "Moisés, Moisés!". A primeira ordem de Deus é um chamado à reverência: "Não te chegues para cá; tira os sapatos de teus pés; porque o lugar em que tu estás é terra santa". A santidade não estava na areia do deserto, mas na presença do Deus Santo que transforma qualquer lugar em solo sagrado.',
    desc2: 'Deus então revela a Sua identidade ("Eu sou o Deus de teu pai, o Deus de Abraão, de Isaque e de Jacó") e o Seu coração compassivo. Ele diz: "Tenho visto atentamente a aflição do meu povo... tenho ouvido o seu clamor... e conheci as suas dores". Deus não é um observador distante do sofrimento humano; Ele vê, ouve, conhece e desce para livrar. O choque para Moisés vem no versículo 10, quando Deus diz: "Vem agora, pois, e eu te enviarei a Faraó, para que tires o meu povo... do Egito". Deus desce para salvar, mas Ele escolhe usar um homem quebrado como Seu instrumento.',
    desc3: 'A resposta de Moisés é cheia de insegurança e medo: "Quem sou eu, para que vá a Faraó e tire do Egito os filhos de Israel?". Moisés foca na sua própria fraqueza, no seu passado de fracasso e na impossibilidade da tarefa. A resposta de Deus não é uma lista de elogios para melhorar a autoestima de Moisés. Deus não diz "Você é capaz", mas diz a única coisa que realmente importa: "Certamente eu serei contigo". A garantia do sucesso na obra de Deus não é a nossa competência, mas a presença e o poder dAquele que nos envia.',
    concl: 'O nosso passado de fracassos, a nossa idade ou as nossas limitações não anulam o chamado de Deus. Quando Ele nos chama para uma tarefa impossível, Ele não espera que tenhamos os recursos em nós mesmos. A Sua presença conosco é a nossa maior capacitação e a garantia absoluta da vitória.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 8');
