const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: '1pe_1_3_12',
    intro: 'A Primeira Epístola de Pedro foi escrita para cristãos que viviam como "estrangeiros e peregrinos" nas províncias da Ásia Menor, enfrentando oposição social e a ameaça crescente de perseguição oficial pelo Império Romano. Para encorajar crentes que estavam sofrendo, Pedro não oferece falsas promessas de alívio imediato ou prosperidade terrena. Em vez disso, ele eleva os olhos deles para a eternidade. Os versículos 3 a 12 formam, no grego original, uma única e majestosa frase de louvor, uma explosão de adoração pela "viva esperança" que temos em Cristo. Pedro argumenta que a grandeza da nossa salvação futura é a única âncora capaz de sustentar a nossa alegria no meio do sofrimento presente.',
    desc1: 'Pedro começa bendizendo a Deus Pai, que "segundo a sua grande misericórdia, nos gerou de novo para uma viva esperança, pela ressurreição de Jesus Cristo dentre os mortos". A nossa esperança não é um otimismo cego ou um desejo vago ("espero que tudo dê certo"); é uma esperança "viva" porque está ancorada em um evento histórico inegável: um túmulo vazio. O objeto dessa esperança é "uma herança incorruptível, incontaminável, e que não se pode murchar, guardada nos céus para vós". Diferente das heranças terrenas (que apodrecem, são roubadas ou perdem o valor), a nossa herança celestial é absolutamente segura. E não apenas a herança está guardada para nós, mas nós somos "guardados pelo poder de Deus, mediante a fé", até o dia da salvação final.',
    desc2: 'É com base nessa segurança eterna que Pedro introduz o paradoxo da vida cristã (v. 6): "Em que vós grandemente vos alegrais, ainda que agora importa, sendo necessário, que estejais por um pouco contristados com várias tentações (provações)". A alegria profunda e a tristeza circunstancial podem coexistir no coração do crente. Pedro explica o propósito do sofrimento: "Para que a prova da vossa fé, muito mais preciosa do que o ouro que perece e é provado pelo fogo, se ache em louvor, e honra, e glória, na revelação de Jesus Cristo". O fogo da provação não destrói a fé verdadeira; ele a purifica, queima as impurezas (orgulho, autossuficiência) e prova a sua autenticidade. O sofrimento temporal produz glória eterna.',
    desc3: 'Pedro destaca a natureza extraordinária da fé desses crentes (v. 8): "Ao qual, não o havendo visto, amais; no qual, não o vendo agora, mas crendo, vos alegrais com gozo inefável e glorioso". Eles não tiveram o privilégio de Pedro de andar fisicamente com Jesus, mas o amor e a alegria deles eram reais e indescritíveis. Pedro conclui (v. 10-12) lembrando-os do privilégio histórico que possuem. Os profetas do Antigo Testamento indagaram e investigaram sobre a graça e os sofrimentos do Messias, mas não viram o cumprimento. Até mesmo os anjos "desejam atentar" para os mistérios da salvação. Nós vivemos no tempo do cumprimento, desfrutando de uma revelação que os profetas apenas previram.',
    concl: 'A mensagem de Pedro nos ensina que a perspectiva eterna muda tudo. Quando o sofrimento bater à nossa porta, não devemos focar no fogo da provação, mas no Ouro que ele está purificando. A nossa herança está segura nos céus, e nós estamos seguros nas mãos de Deus. Essa é a viva esperança que nos permite chorar as nossas dores presentes enquanto nos alegramos com um gozo inefável e glorioso.'
  },
  {
    id: '1jn_1_1_10',
    intro: 'A Primeira Epístola de João foi escrita no final do primeiro século, quando a igreja enfrentava uma ameaça interna perigosa: o proto-gnosticismo. Esses falsos mestres ensinavam que a matéria era má e o espírito era bom, concluindo que Deus nunca poderia ter assumido um corpo físico real. Eles negavam a encarnação e afirmavam ter um conhecimento espiritual superior que os isentava do pecado. O apóstolo João, o último apóstolo vivo, escreve esta carta com a autoridade de uma testemunha ocular para destruir essas heresias. O capítulo 1 estabelece os dois pilares da fé cristã: a realidade histórica da encarnação (Jesus é Deus em carne) e a necessidade absoluta de lidar honestamente com o nosso pecado para termos comunhão com Deus.',
    desc1: 'João começa com uma defesa apaixonada e sensorial da encarnação: "O que era desde o princípio, o que ouvimos, o que vimos com os nossos olhos, o que temos contemplado, e as nossas mãos tocaram da Palavra da vida". Ele ataca a ideia de que Jesus era apenas um espírito ou uma ilusão. João diz: "Nós O ouvimos, vimos e tocamos". O cristianismo não é uma filosofia mística baseada em ideias abstratas; é uma fé histórica baseada na realidade de que o Deus eterno ("a vida eterna que estava com o Pai") entrou no tempo e no espaço, assumindo carne humana. O propósito dessa proclamação é a comunhão (koinonia): "para que também tenhais comunhão conosco; e a nossa comunhão é com o Pai, e com seu Filho Jesus Cristo".',
    desc2: 'Tendo estabelecido quem é Cristo, João passa para a natureza de Deus e as suas implicações morais (v. 5): "Deus é luz, e não há nele trevas nenhumas". A luz representa a santidade absoluta e a verdade revelada. Se Deus é luz, a comunhão com Ele exige que andemos na luz. João expõe a hipocrisia dos falsos mestres: "Se dissermos que temos comunhão com ele, e andarmos em trevas, mentimos, e não praticamos a verdade". A verdadeira espiritualidade não é o que dizemos ter, mas como vivemos. No entanto, andar na luz não significa perfeição sem pecado; significa viver em transparência diante de Deus, onde "o sangue de Jesus Cristo, seu Filho, nos purifica de todo o pecado".',
    desc3: 'João confronta diretamente a negação do pecado (v. 8-10). Os gnósticos diziam que não tinham pecado. João é contundente: "Se dissermos que não temos pecado, enganamo-nos a nós mesmos, e não há verdade em nós". Pior ainda, "se dissermos que não pecamos, fazemo-lo mentiroso". A negação do pecado é o maior obstáculo para a graça. A solução não é esconder o pecado, mas expô-lo à luz: "Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados, e nos purificar de toda a injustiça". A confissão (homologeo, dizer a mesma coisa) é concordar com Deus sobre a gravidade do nosso pecado. O perdão é garantido não porque merecemos, mas porque Deus é fiel (às Suas promessas) e justo (porque Cristo já pagou a pena).',
    concl: '1 João 1 nos ensina que não podemos ter comunhão com Deus se negarmos a encarnação de Cristo ou se escondermos os nossos pecados. A verdadeira vida cristã é vivida na luz da santidade de Deus, onde a nossa constante falha humana encontra a purificação contínua e perfeita do sangue de Jesus através da confissão honesta e humilde.'
  },
  {
    id: 'rev_2_1_7',
    intro: 'O capítulo 2 de Apocalipse inicia a seção das cartas ditadas pelo próprio Jesus Cristo glorificado às sete igrejas da província romana da Ásia. A primeira carta é endereçada à igreja de Éfeso. Éfeso era a cidade mais importante da região, um centro comercial, político e religioso (lar do famoso Templo de Diana/Ártemis). A igreja ali havia sido fundada por Paulo e pastoreada por Timóteo e pelo próprio apóstolo João. Era uma igreja madura, com uma herança teológica riquíssima. No entanto, a avaliação de Jesus revela um perigo sutil e letal que frequentemente atinge igrejas e crentes maduros: a ortodoxia fria. Eles tinham a doutrina certa e o trabalho árduo, mas haviam perdido o coração.',
    desc1: 'Jesus se apresenta à igreja de Éfeso como aquele "que tem na sua destra as sete estrelas (os pastores/anjos das igrejas), que anda no meio dos sete castiçais de ouro (as igrejas)". Ele não é um observador distante; Ele está ativamente presente e conhece intimamente a Sua igreja. Jesus começa com um elogio impressionante (v. 2-3): "Conheço as tuas obras, e o teu trabalho, e a tua paciência, e que não podes sofrer os maus; e puseste à prova os que dizem ser apóstolos, e o não são, e tu os achaste mentirosos". A igreja de Éfeso era trabalhadora, perseverante sob perseguição e teologicamente rigorosa. Eles odiavam a heresia (como as obras dos nicolaítas) e protegiam o rebanho dos falsos mestres. Aos olhos humanos, era a igreja perfeita.',
    desc2: 'No entanto, o olhar penetrante de Cristo vê além do ativismo e da ortodoxia (v. 4): "Tenho, porém, contra ti que deixaste o teu primeiro amor". A palavra "deixaste" (aphiemi) implica um abandono gradual, não uma perda acidental. No meio da batalha pela verdade doutrinária e do cansaço do trabalho ministerial, o amor apaixonado, devotado e íntimo por Jesus (e possivelmente uns pelos outros) havia esfriado. A igreja havia se tornado uma máquina de fazer coisas certas com a motivação errada. Jesus deixa claro que o trabalho árduo e a teologia correta, embora essenciais, nunca podem substituir o amor a Ele. A ortodoxia sem amor é um cadáver teológico.',
    desc3: 'O remédio que Jesus prescreve para a restauração do primeiro amor é triplo e urgente (v. 5): "Lembra-te, pois, de onde caíste, e arrepende-te, e pratica as primeiras obras". Primeiro, "lembra-te": olhar para trás e recordar a paixão e a alegria do início da salvação. Segundo, "arrepende-te": tratar a falta de amor não como uma fase natural da maturidade, mas como um pecado grave que exige mudança de mente e de direção. Terceiro, "pratica as primeiras obras": o amor não é apenas um sentimento a ser recuperado, mas uma ação a ser repetida. A advertência é severa: "quando não, em breve virei a ti, e tirarei do seu lugar o teu castiçal, se não te arrependeres". Uma igreja sem amor perde o direito de ser luz no mundo.',
    concl: 'A carta a Éfeso é um aviso solene para todos os que estão envolvidos no serviço cristão e na defesa da verdade. É possível estar tão ocupado trabalhando para o Senhor e defendendo a doutrina do Senhor que nos esquecemos de amar o Senhor. Jesus nos chama a voltar ao básico: lembrar, arrepender-se e reacender a chama do primeiro amor, pois Ele deseja o nosso coração antes das nossas obras.'
  },
  {
    id: 'rom_12_1_8',
    intro: 'O capítulo 12 de Romanos marca a grande transição da epístola. Nos primeiros onze capítulos, o apóstolo Paulo construiu o argumento teológico mais profundo e abrangente da Bíblia sobre a salvação. Ele demonstrou a condenação universal da humanidade, a justificação pela graça através da fé em Cristo, a santificação pelo Espírito Santo e a soberania de Deus na história. Agora, no capítulo 12, Paulo muda da teologia (o que Deus fez) para a ética (como devemos viver). O cristianismo bíblico nunca separa a doutrina da prática. A palavra "Rogo-vos, pois" (ou "Portanto") é a ponte: toda a obediência cristã não é uma tentativa de ganhar a salvação, mas a única resposta lógica e grata às "misericórdias de Deus" que já recebemos.',
    desc1: 'Paulo define a essência da adoração cristã (v. 1): "que apresenteis os vossos corpos em sacrifício vivo, santo e agradável a Deus, que é o vosso culto racional". No Antigo Testamento, a adoração envolvia trazer animais mortos ao altar. No Novo Testamento, Deus não quer animais mortos; Ele quer crentes vivos. A adoração não se limita a cantar no domingo, mas envolve oferecer o nosso "corpo" (a totalidade da nossa vida prática, tempo, energia e pureza) a Deus todos os dias. Paulo chama isso de "culto racional" (logikos), significando que, à luz de tudo o que Deus fez por nós (capítulos 1-11), entregar a vida a Ele é a única atitude lógica, inteligente e razoável.',
    desc2: 'Para que esse sacrifício vivo seja possível, Paulo dá um mandamento negativo e um positivo (v. 2): "E não sede conformados com este mundo, mas sede transformados pela renovação do vosso entendimento". O "mundo" (aion, a era presente) tem um sistema de valores, prioridades e pressões que tenta nos espremer no seu molde. A resistência não vem do isolamento físico, mas da "transformação" (metamorphoo, a mesma palavra usada para a transfiguração de Jesus). Essa metamorfose interna acontece pela "renovação do entendimento" (a mente). A mudança de comportamento começa com a mudança de pensamento através da Palavra de Deus. O resultado é a capacidade de "experimentar qual seja a boa, agradável, e perfeita vontade de Deus".',
    desc3: 'Após estabelecer a base da consagração pessoal, Paulo aplica essa transformação à vida em comunidade (v. 3-8). O primeiro sinal de uma mente renovada é a humildade: "que não pense de si mesmo além do que convém; antes, pense com moderação". O orgulho destrói a igreja. Paulo usa a metáfora do corpo humano para ilustrar a igreja: "Assim nós, que somos muitos, somos um só corpo em Cristo, mas individualmente somos membros uns dos outros". A unidade não significa uniformidade. Deus distribuiu dons diferentes (profecia, ministério, ensino, exortação, contribuição, liderança, misericórdia) segundo a Sua graça. Cada membro deve exercer o seu dom com dedicação, alegria e simplicidade para a edificação do corpo, não para a promoção pessoal.',
    concl: 'Romanos 12 nos ensina que a verdadeira teologia sempre leva à transformação. Quando compreendemos a profundidade da misericórdia de Deus, a nossa única resposta racional é colocar a nossa vida no altar como um sacrifício vivo, recusar o molde do mundo, renovar a nossa mente na Palavra e servir aos nossos irmãos com humildade e amor através dos dons que Deus nos deu.'
  },
  {
    id: 'col_3_1_17',
    intro: 'O capítulo 3 de Colossenses é um dos textos mais práticos e diretos do apóstolo Paulo sobre a santificação e a vida cristã diária. A igreja em Colossos estava sendo ameaçada por falsos mestres que ensinavam que a salvação exigia a observância de regras rigorosas, ascetismo (punição do corpo) e adoração de anjos. Paulo destrói essa heresia nos capítulos anteriores, afirmando a supremacia e a suficiência absolutas de Cristo. No capítulo 3, Paulo explica que a verdadeira vitória sobre o pecado não vem de regras religiosas ("não toques, não proves"), mas da nossa união mística com Cristo na Sua morte e ressurreição. A vida cristã é o processo de nos tornarmos na prática aquilo que já somos em Cristo.',
    desc1: 'Paulo estabelece o fundamento teológico da santificação (v. 1-4): "Portanto, se já ressuscitastes com Cristo, buscai as coisas que são de cima... Pensai nas coisas que são de cima, e não nas que são da terra". A nossa união com Cristo é tão real que a Sua morte foi a nossa morte para o pecado, e a Sua ressurreição é a nossa nova vida. Paulo diz: "Porque já estais mortos, e a vossa vida está escondida com Cristo em Deus". A nossa identidade mais profunda não é definida pelo nosso passado, pelo nosso trabalho ou pelas nossas falhas, mas por Cristo. Como a nossa vida está "escondida" nEle, o nosso foco mental e os nossos desejos devem estar alinhados com as realidades celestiais, aguardando o dia em que Ele se manifestará em glória.',
    desc2: 'Com base nessa nova identidade, Paulo dá ordens radicais de "mortificação" (v. 5-9). Ele diz: "Mortificai (fazei morrer), pois, os vossos membros, que estão sobre a terra". Não devemos negociar ou domesticar o pecado; devemos matá-lo. Ele lista os pecados sexuais (prostituição, impureza, paixão lasciva) e a avareza (que ele chama de idolatria). Em seguida, ele lista os pecados sociais e de linguagem (ira, cólera, malícia, maledicência, palavras torpes, mentira). Esses pecados pertencem ao "velho homem" que já foi despido. A ira de Deus virá sobre essas coisas. O cristão não pode continuar vivendo nas práticas que crucificaram o seu Salvador.',
    desc3: 'A santificação não é apenas tirar a roupa suja; é vestir a roupa nova (v. 10-17). Paulo ordena: "Revesti-vos, pois, como eleitos de Deus... de entranhas de misericórdia, de benignidade, humildade, mansidão, longanimidade". O novo homem é criado à imagem de Cristo, onde todas as barreiras raciais, culturais e sociais (grego e judeu, circuncisão e incircuncisão, bárbaro, cita, servo, livre) são destruídas, pois "Cristo é tudo em todos". O cimento que une todas essas virtudes é o amor. Paulo conclui com três marcas de uma comunidade transformada: a paz de Cristo dominando os corações, a Palavra de Cristo habitando ricamente (através do ensino e do louvor com salmos, hinos e cânticos espirituais) e a gratidão contínua, fazendo tudo em nome do Senhor Jesus.',
    concl: 'Colossenses 3 nos ensina que a santidade não é alcançada por esforço religioso ou regras humanas, mas por vivermos à luz da nossa ressurreição com Cristo. Porque morremos com Ele, devemos matar o pecado em nós. Porque ressuscitamos com Ele, devemos nos revestir do Seu caráter, permitindo que a Sua paz, a Sua Palavra e o Seu amor governem os nossos relacionamentos e as nossas ações diárias.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 30');
