const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'neh_2_1_8',
    intro: 'O capítulo 2 de Neemias é um estudo de caso clássico sobre a intersecção entre a fé profunda e a ação estratégica. Neemias era o copeiro do rei Artaxerxes da Pérsia (uma posição de alta confiança e influência). Quatro meses antes, ele havia recebido a notícia devastadora de que os muros de Jerusalém estavam em ruínas e o povo em grande miséria. Durante esses quatro meses, Neemias não organizou um protesto nem tomou atitudes precipitadas; ele chorou, jejuou e orou incessantemente. O capítulo 2 narra o momento em que a oportunidade divina finalmente se apresenta. Neemias demonstra como um líder espiritual deve depender inteiramente de Deus enquanto age com coragem, planejamento meticuloso e sabedoria prática.',
    desc1: 'A oportunidade surge durante o trabalho rotineiro. O rei percebe a tristeza no rosto de Neemias (algo perigoso, pois a tristeza na presença do rei persa podia ser interpretada como insatisfação ou conspiração). O rei pergunta: "Por que está triste o teu rosto?". Neemias confessa que sentiu "grande temor", mas usa a oportunidade para explicar a situação de Jerusalém. O rei então faz a pergunta que Neemias esperava há quatro meses: "Que me pedes agora?". A reação de Neemias é o exemplo perfeito da "oração de flecha": "Então orei ao Deus dos céus". Entre a pergunta do rei e a resposta de Neemias, houve uma oração silenciosa e instantânea. A oração contínua de quatro meses o preparou para a oração de um segundo.',
    desc2: 'A resposta de Neemias ao rei revela que ele não passou os quatro meses apenas chorando, mas também planejando. Ele não pede apenas permissão para ir; ele pede cartas de salvo-conduto para os governadores além do rio e uma carta para Asafe, o guarda da floresta do rei, para fornecer madeira para a reconstrução. A fé não anula o planejamento estratégico; ela o santifica. O rei concede tudo o que Neemias pede. Neemias não atribui o sucesso à sua própria eloquência ou à bondade do rei, mas reconhece a fonte real: "E o rei mas deu, segundo a boa mão de Deus sobre mim".',
    desc3: 'Ao chegar a Jerusalém, Neemias não faz discursos imediatos. Ele passa três dias em silêncio, avaliando a situação. À noite, em segredo, ele faz uma inspeção minuciosa das ruínas dos muros. Um bom líder não baseia as suas decisões em boatos, mas na realidade dos fatos. Só depois de ter o diagnóstico completo é que ele reúne os líderes e os desafia: "Vinde, pois, e edifiquemos o muro de Jerusalém, para que não sejamos mais um opróbrio". Ele os encoraja com o testemunho da "boa mão de Deus". A oposição surge imediatamente através de Sambalate e Tobias, que zombam do projeto. A resposta de Neemias é firme e teológica: "O Deus dos céus é o que nos fará prosperar... vós, porém, não tendes parte, nem justiça, nem memória em Jerusalém".',
    concl: 'A missão de Neemias nos ensina que grandes obras para Deus requerem joelhos dobrados em oração e mentes afiadas para o planejamento. A fé verdadeira não espera passivamente que Deus faça tudo; ela ora como se tudo dependesse de Deus e planeja e trabalha como se tudo dependesse de nós, sabendo que o sucesso final vem exclusivamente da "boa mão de Deus".'
  },
  {
    id: 'ps_91_1_16',
    intro: 'O Salmo 91 é um dos textos mais conhecidos, amados e frequentemente citados de toda a Bíblia. Ele é um hino de confiança inabalável, uma declaração poética e teológica sobre a segurança absoluta daqueles que confiam em Deus. No entanto, este salmo não é um amuleto mágico para ser deixado aberto em uma mesa para afastar o mal. Ele é uma promessa condicional, dirigida àqueles que tomam uma decisão consciente e diária de fazer de Deus a sua habitação. O salmo descreve os perigos reais da vida (doenças, guerras, ataques noturnos), mas garante que, sob as asas do Altíssimo, o crente encontra um refúgio impenetrável.',
    desc1: 'O salmo começa estabelecendo a condição fundamental para todas as promessas que se seguem: "Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará". A promessa não é para quem "visita" a presença de Deus apenas nos domingos ou nos momentos de crise, mas para quem "habita" (mora, permanece) nela. O salmista usa quatro nomes para Deus nos dois primeiros versículos: Altíssimo (Elyon - o Deus que governa sobre tudo), Onipotente (Shaddai - o Deus que tem todo o poder), Senhor (Yahweh - o Deus da aliança) e Deus meu (Elohim - o Criador pessoal). Conhecer o caráter de Deus é a base para declarar: "Ele é o meu Deus, o meu refúgio, a minha fortaleza, e nele confiarei".',
    desc2: 'A partir do versículo 3, o salmista descreve os perigos dos quais Deus nos livra. Ele usa metáforas de caça ("laço do passarinheiro") e de doenças ("peste perniciosa"). Ele garante proteção contra os medos noturnos (o terror de noite) e os ataques diurnos (a seta que voa de dia). A promessa do versículo 7 é famosa: "Mil cairão ao teu lado, e dez mil à tua direita, mas não chegará a ti". Isso não significa que o crente nunca sofrerá acidentes ou doenças (a Bíblia inteira prova o contrário), mas significa que nenhum mal pode atingir o crente sem a permissão soberana de Deus, e que mesmo no meio do caos, a alma do crente está eternamente segura.',
    desc3: 'Os versículos 11 e 12 revelam a provisão angelical: "Porque aos seus anjos dará ordem a teu respeito, para te guardarem em todos os teus caminhos". Ironicamente, o diabo usou exatamente este versículo para tentar Jesus no deserto (Mateus 4), omitindo a frase "em todos os teus caminhos" (os caminhos da obediência). A proteção de Deus não é uma licença para a imprudência. O salmo conclui com o próprio Deus falando (v. 14-16), confirmando as promessas àqueles que O amam e conhecem o Seu nome: "Ele me invocará, e eu lhe responderei; estarei com ele na angústia; dela o retirarei, e o glorificarei".',
    concl: 'O Salmo 91 nos ensina que a verdadeira segurança não é a ausência de perigo, mas a presença de Deus no meio do perigo. Quando fazemos do Altíssimo a nossa morada diária, podemos enfrentar os terrores da noite e as pestes do dia com a paz inabalável de quem sabe que está guardado sob as asas do Onipotente.'
  },
  {
    id: 'eze_37_1_14',
    intro: 'A visão do vale de ossos secos no capítulo 37 de Ezequiel é uma das imagens proféticas mais poderosas e inesquecíveis da Bíblia. O profeta Ezequiel estava ministrando aos exilados judeus na Babilônia. A nação de Israel havia sido destruída, o templo queimado e o povo deportado. O sentimento geral era de desespero absoluto; eles diziam: "Os nossos ossos se secaram, e pereceu a nossa esperança; nós mesmos estamos cortados". Para responder a esse desespero, o Espírito do Senhor leva Ezequiel a um vale cheio de ossos humanos secos e desarticulados, representando a morte espiritual e nacional de Israel. O que se segue é uma demonstração espetacular de que o Deus que criou a vida a partir do pó em Gênesis é o mesmo Deus que pode ressuscitar uma nação morta através da Sua Palavra e do Seu Espírito.',
    desc1: 'A visão começa com um diagnóstico brutal da realidade. O Espírito faz Ezequiel andar ao redor do vale para ver a extensão da tragédia: "eis que eram mui numerosos sobre a face do vale, e eis que estavam sequíssimos". Os ossos não eram apenas de pessoas mortas recentemente; eram ossos branqueados pelo sol, indicando que a morte havia ocorrido há muito tempo e que qualquer esperança natural de vida havia desaparecido. Deus então faz a Ezequiel a pergunta impossível: "Filho do homem, porventura viverão estes ossos?". A resposta de Ezequiel é um modelo de humildade teológica e submissão à soberania divina: "Senhor Deus, tu o sabes". A lógica humana diria "não", mas a fé deixa a porta aberta para o poder de Deus.',
    desc2: 'Deus não ressuscita os ossos com um estalar de dedos; Ele escolhe usar a parceria humana através da pregação. Ele ordena a Ezequiel: "Profetiza sobre estes ossos, e dize-lhes: Ossos secos, ouvi a palavra do Senhor". Pregar para ossos secos parece a tarefa mais inútil e ridícula do mundo. É uma metáfora perfeita para a pregação do Evangelho a corações espiritualmente mortos. Ezequiel obedece, e enquanto ele profetiza, ocorre um milagre barulhento: "houve um ruído, e eis que se fez um rebuliço, e os ossos se achegaram, cada osso ao seu osso". Nervos, carne e pele cobrem os ossos, formando corpos completos. No entanto, o milagre estava incompleto: "mas não havia neles espírito (fôlego de vida)". A estrutura religiosa e moral havia sido restaurada, mas a vida espiritual ainda faltava.',
    desc3: 'Deus dá a segunda ordem: "Profetiza ao espírito... e dize ao espírito: Assim diz o Senhor Deus: Vem dos quatro ventos, ó espírito, e assopra sobre estes mortos, para que vivam". Ezequiel profetiza novamente, e o Espírito (Ruach, que também significa vento ou fôlego) entra nos corpos. Eles vivem e se colocam em pé, formando "um exército grande em extremo". Deus então interpreta a visão: os ossos são a casa de Israel. Deus promete abrir as sepulturas do exílio, colocar o Seu Espírito dentro deles e trazê-los de volta à sua própria terra. A restauração nacional seria inseparável da regeneração espiritual.',
    concl: 'A visão do vale de ossos secos nos ensina que não existe situação, igreja, família ou vida tão morta, seca e desarticulada que o poder de Deus não possa ressuscitar. A ressurreição espiritual sempre acontece através da combinação de dois elementos essenciais: a pregação fiel da Palavra de Deus (mesmo quando parece inútil) e o sopro vivificador do Espírito Santo.'
  },
  {
    id: 'dan_3_16_30',
    intro: 'A história da fornalha de fogo ardente no capítulo 3 de Daniel é um dos relatos mais dramáticos de coragem civil, fidelidade religiosa e livramento divino no Antigo Testamento. O rei Nabucodonosor da Babilônia, o monarca mais poderoso do mundo na época, ergue uma estátua de ouro colossal na planície de Dura e emite um decreto exigindo que todos os oficiais do império se prostrem e a adorem ao som da música. A recusa significava a morte imediata em uma fornalha. Três jovens judeus exilados (Sadraque, Mesaque e Abede-Nego), que haviam sido promovidos na administração babilônica, enfrentam a escolha suprema: comprometer a sua fé para salvar as suas vidas e carreiras, ou permanecer fiéis ao Deus de Israel e enfrentar uma morte terrível.',
    desc1: 'A cerimônia de dedicação da estátua é um espetáculo de poder e intimidação. Quando a música toca, todos os povos e nações se prostram. A pressão para o conformismo era absoluta. No entanto, alguns caldeus (provavelmente movidos por inveja política) denunciam os três jovens judeus ao rei: "não fizeram caso de ti; a teus deuses não servem, nem a estátua de ouro, que levantaste, adoraram". Nabucodonosor, furioso, manda chamá-los e oferece uma segunda chance, acompanhada de uma ameaça arrogante: "se não a adorardes, sereis lançados... numa fornalha de fogo ardente; e quem é o Deus que vos poderá livrar das minhas mãos?". O rei desafia diretamente o poder de Yahweh.',
    desc2: 'A resposta dos três jovens (v. 16-18) é uma das maiores declarações de fé incondicional da Bíblia. Eles não pedem tempo para pensar, não tentam negociar um acordo e não dão desculpas teológicas (como "vamos nos curvar fisicamente, mas adorar a Deus no coração"). Eles dizem: "Não necessitamos de te responder sobre este negócio. Eis que o nosso Deus, a quem nós servimos, é que nos pode livrar... e nos livrará das tuas mãos, ó rei". Eles afirmam o poder absoluto de Deus para salvá-los. Mas a grandeza da sua fé está na frase seguinte: "E, se não, fica sabendo ó rei, que não serviremos a teus deuses nem adoraremos a estátua de ouro que levantaste". A fé deles não dependia do livramento. Eles preferiam morrer queimados a cometer idolatria.',
    desc3: 'Nabucodonosor, cheio de fúria, manda aquecer a fornalha sete vezes mais do que o normal e ordena que os seus soldados mais fortes amarrem e lancem os jovens no fogo. O fogo era tão intenso que matou os soldados que os lançaram. Mas, quando o rei olha para dentro da fornalha, ele fica espantado: "Eu, porém, vejo quatro homens soltos, que andam passeando dentro do fogo, sem sofrer nenhum dano; e o aspecto do quarto é semelhante ao Filho de Deus". Deus não apagou o fogo nem impediu que eles fossem lançados nele; Ele desceu na fornalha e caminhou com eles no meio do fogo. A única coisa que o fogo queimou foram as cordas que os prendiam. Quando eles saem, nem sequer o cheiro de fumaça estava nas suas roupas.',
    concl: 'A fornalha de fogo ardente nos ensina que a verdadeira fé não é a garantia de que Deus nos livrará de todas as provações, mas a convicção de que Ele é digno de obediência, independentemente das consequências ("e, se não"). Quando nos recusamos a nos curvar aos ídolos do mundo, podemos ser lançados no fogo da perseguição, mas é exatamente lá que experimentaremos a presença mais íntima e libertadora do Filho de Deus.'
  },
  {
    id: 'ps_139_1_24',
    intro: 'O Salmo 139 é, sem dúvida, a mais bela, profunda e poética exploração dos atributos de Deus em toda a Escritura. Escrito por Davi, este salmo não é um tratado teológico frio e abstrato sobre a onisciência (Deus sabe tudo), a onipresença (Deus está em todo lugar) e a onipotência (Deus pode tudo) do Criador. Em vez disso, é uma meditação intensamente pessoal e relacional sobre como esses atributos divinos afetam a vida do crente. Davi celebra o fato de que o Deus infinito do universo nos conhece intimamente, nos cerca constantemente e nos formou com um propósito específico. Longe de ser uma verdade aterrorizante, o conhecimento absoluto de Deus torna-se a base da nossa maior segurança e conforto.',
    desc1: 'Nos primeiros seis versículos, Davi medita sobre a onisciência de Deus: "Senhor, tu me sondaste, e me conheces". Deus não tem um conhecimento superficial sobre nós; Ele conhece os nossos movimentos (o assentar e o levantar), entende os nossos pensamentos de longe e esquadrinha os nossos caminhos. Antes mesmo que a palavra chegue à nossa língua, Deus já a conhece inteiramente. Davi não se sente invadido por esse conhecimento absoluto, mas protegido: "Tu me cercaste por detrás e por diante, e puseste sobre mim a tua mão". O conhecimento de Deus é tão maravilhoso que excede a capacidade de compreensão humana.',
    desc2: 'A partir do versículo 7, Davi explora a onipresença de Deus: "Para onde me irei do teu espírito, ou para onde fugirei da tua face?". Ele imagina tentar escapar de Deus subindo aos céus, descendo ao mais profundo abismo (Seol), ou voando para as extremidades do mar. A conclusão é que não há lugar no universo, físico ou espiritual, onde Deus não esteja presente. Mesmo se a escuridão mais densa tentar nos esconder, "as trevas e a luz são para ti a mesma coisa". Para o ímpio, a onipresença de Deus é um terror (não há onde se esconder do Juiz); mas para o crente, é o maior consolo (não há lugar de dor ou isolamento onde o Pai não possa nos alcançar e guiar).',
    desc3: 'Nos versículos 13 a 16, Davi volta-se para a onipotência de Deus na criação humana: "Pois possuíste os meus rins; cobriste-me (teceste-me) no ventre de minha mãe". Davi louva a Deus porque foi feito de modo "assombroso e maravilhoso". A vida humana não é um acidente biológico; é uma obra de arte tecida pelas mãos do Criador no lugar mais oculto. Além de formar o nosso corpo, Deus também planejou os nossos dias: "os teus olhos viram o meu corpo ainda informe; e no teu livro todas estas coisas foram escritas; as quais em continuação foram formadas, quando nem ainda uma delas havia". O nosso futuro está seguro nas mãos dAquele que nos desenhou.',
    concl: 'O Salmo 139 destrói a ilusão de que podemos esconder alguma coisa de Deus ou de que a nossa vida é um acidente sem sentido. O salmo termina com uma oração corajosa de submissão (v. 23-24): "Sonda-me, ó Deus, e conhece o meu coração... e vê se há em mim algum caminho mau, e guia-me pelo caminho eterno". Quando entendemos que Deus nos conhece perfeitamente e nos ama infinitamente, podemos abrir o nosso coração para a Sua purificação e direção.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 32');
