const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'isa_45_7',
    intro: 'O capítulo 45 de Isaías contém uma das profecias mais impressionantes da Bíblia. Deus chama Ciro, o rei da Pérsia, pelo nome, mais de um século antes do seu nascimento, e o designa como o Seu "ungido" (instrumento) para derrotar a Babilônia e libertar os judeus do exílio. No contexto desta profecia, Deus faz uma declaração teológica radical sobre a Sua própria soberania absoluta no versículo 7. Esta declaração foi dada especificamente para refutar o dualismo persa (a religião de Ciro, o zoroastrismo), que ensinava que havia dois deuses iguais em conflito: um deus bom (da luz) e um deus mau (das trevas). Deus declara categoricamente que Ele é o único Senhor e que não há outro poder no universo que opere fora do Seu controle.',
    desc1: 'A Soberania sobre a Luz e as Trevas. Deus declara: "Eu formo a luz, e crio as trevas". No dualismo persa, a luz e as trevas eram forças cósmicas opostas e independentes. Deus corrige essa teologia afirmando que Ele é o Criador de ambas. A luz e as trevas (tanto no sentido físico quanto no sentido metafórico de prosperidade e adversidade) não são deuses rivais; são realidades criadas que estão sob o comando absoluto do único Deus verdadeiro. Ele governa sobre os ciclos da natureza e sobre os ciclos da história humana.',
    desc2: 'A Soberania sobre a Paz e o Mal. A segunda parte do versículo é a que causa mais dificuldade: "Eu faço a paz, e crio o mal, eu, o Senhor, faço todas estas coisas". A palavra hebraica traduzida como "mal" (ra) tem uma ampla gama de significados. Neste contexto (em contraste com a palavra "paz" ou "bem-estar", shalom), "ra" não significa o mal moral (o pecado), mas a calamidade, o desastre, o julgamento ou a adversidade. Deus não é o autor do pecado (Tiago 1:13), mas Ele é o autor soberano dos julgamentos e das calamidades que vêm sobre as nações (como o exílio babilônico ou a destruição que Ciro traria).',
    desc3: 'O Conforto da Soberania Absoluta. A declaração "eu, o Senhor, faço todas estas coisas" não tem o objetivo de assustar o povo de Deus, mas de confortá-lo. Se houvesse um deus mau independente causando calamidades no mundo, os crentes viveriam em terror constante, sem saber quem venceria no final. Mas, como Deus é soberano até mesmo sobre os desastres e as nações pagãs (como a Babilônia e a Pérsia), o Seu povo pode ter certeza de que a história não está fora de controle. Deus usa até mesmo a adversidade ("o mal") para cumprir os Seus propósitos redentores e justos.',
    concl: 'Isaías 45:7 nos ensina que não há dualismo no universo. Satanás não é o igual oposto de Deus; ele é uma criatura rebelde com uma coleira curta. Quando passamos por tempos de paz ou por tempos de calamidade, podemos descansar na certeza de que o nosso Deus soberano está no controle de todas as coisas, orquestrando a história para a Sua glória e para o bem do Seu povo.'
  },
  {
    id: 'mat_24_36',
    intro: 'O capítulo 24 de Mateus contém o "Sermão Profético" (ou Sermão do Monte das Oliveiras), onde Jesus responde às perguntas dos Seus discípulos sobre a destruição do templo e os sinais da Sua vinda e do fim do mundo. Jesus descreve uma série de eventos catastróficos, perseguições, falsos profetas e tribulações que precederão o Seu retorno glorioso. No entanto, após dar todos esses sinais, Jesus faz uma declaração surpreendente no versículo 36 que serve como um freio absoluto para qualquer tentativa humana de marcar datas para o fim do mundo. Ele afirma a ignorância humana e angélica sobre o momento exato, e levanta uma profunda questão teológica sobre o Seu próprio conhecimento durante a encarnação.',
    desc1: 'A Ignorância Humana e Angélica. Jesus declara: "Mas daquele dia e hora ninguém sabe, nem os anjos do céu". Apesar de todos os sinais que Ele acabou de descrever, o momento exato do Seu retorno permanece um segredo divino. Os anjos, que habitam na presença de Deus e são os executores dos Seus julgamentos, não têm acesso a essa informação. Se os seres celestiais não sabem, é o cúmulo da arrogância humana (e a marca de falsos profetas) tentar calcular datas, anos ou épocas para a segunda vinda. A história da igreja está cheia de seitas que marcaram datas e terminaram em vergonha e desilusão.',
    desc2: 'A Ignorância do Filho (A Kenosis). A parte mais teologicamente complexa do versículo é a frase (encontrada em alguns manuscritos de Mateus e claramente em Marcos 13:32): "nem o Filho, mas unicamente meu Pai". Como Jesus, sendo Deus (onisciente), poderia não saber o dia da Sua própria vinda? A resposta encontra-se na doutrina da Encarnação (Filipenses 2:7). Quando o Filho de Deus se tornou homem, Ele não deixou de ser Deus, mas Ele voluntariamente limitou o uso independente dos Seus atributos divinos. Durante o Seu ministério terreno, Jesus viveu em submissão total ao Pai, sabendo apenas o que o Pai Lhe revelava. A Sua ignorância sobre a data não era uma falha, mas uma prova da Sua verdadeira humanidade e submissão.',
    desc3: 'O Propósito do Segredo: A Vigilância. A razão pela qual o Pai manteve a data em segredo é revelada nos versículos seguintes (v. 42-44): "Vigiai, pois, porque não sabeis a que hora há de vir o vosso Senhor". Se soubéssemos a data exata, a tendência humana seria viver em pecado e negligência até o último momento, e então tentar um arrependimento de última hora. O segredo da data cria a necessidade de vigilância constante. O crente deve viver todos os dias com a expectativa de que Cristo pode voltar hoje, e com o planejamento de que Ele pode demorar gerações.',
    concl: 'A declaração de Jesus sobre o dia e a hora desconhecidos nos liberta da obsessão doentia por marcar datas escatológicas e nos chama para a responsabilidade prática. A nossa tarefa não é adivinhar quando o Mestre voltará, mas sermos encontrados fiéis, trabalhando e vigiando, para que, quando Ele vier, nos encontre fazendo a Sua vontade.'
  },
  {
    id: 'mar_4_11_12',
    intro: 'No capítulo 4 de Marcos, Jesus começa a ensinar as multidões usando parábolas (histórias terrenas com significados espirituais). A primeira e mais fundamental é a Parábola do Semeador. Após contar a história para a multidão, Jesus se retira com os Seus discípulos mais próximos. Eles Lhe perguntam por que Ele ensina por parábolas. A resposta de Jesus nos versículos 11 e 12 é uma das mais difíceis e teologicamente densas dos Evangelhos. Em vez de dizer que as parábolas são ilustrações simples para facilitar o entendimento de todos, Jesus declara que elas têm um duplo propósito: revelar a verdade aos discípulos e ocultar a verdade daqueles que têm o coração endurecido, cumprindo a profecia de Isaías.',
    desc1: 'O Mistério Revelado aos Discípulos. Jesus diz aos Seus seguidores: "A vós vos é dado saber os mistérios do reino de Deus". Na Bíblia, um "mistério" não é um enigma a ser resolvido pela inteligência humana, mas uma verdade divina que estava oculta e agora é revelada por Deus. O conhecimento do Reino de Deus (a salvação, a graça, a pessoa de Cristo) não é uma conquista intelectual, mas um dom ("vos é dado"). Os discípulos não entenderam as parábolas porque eram mais espertos que a multidão, mas porque Jesus, pela Sua graça, lhes deu a revelação e a explicação.',
    desc2: 'O Julgamento sobre os de Fora. O contraste é severo: "mas aos que estão de fora todas estas coisas se dizem por parábolas". Para a multidão descrente, as parábolas permaneciam apenas como histórias sobre agricultura. Jesus então cita Isaías 6:9-10 para explicar o motivo (v. 12): "Para que, vendo, vejam, e não percebam; e, ouvindo, ouçam, e não entendam; para que não se convertam, e lhes sejam perdoados os pecados". Isso soa como se Jesus não quisesse que eles fossem salvos. No entanto, o contexto de Isaías e do ministério de Jesus mostra que este é um julgamento judicial sobre pessoas que já haviam endurecido os seus corações e rejeitado a verdade clara (como os fariseus no capítulo 3).',
    desc3: 'A Parábola como Misericórdia e Juízo. As parábolas funcionam como um filtro espiritual. Para o coração faminto e humilde (os discípulos), a parábola atrai a pessoa a Jesus para pedir a explicação, resultando em revelação. Para o coração orgulhoso e endurecido (os fariseus e a multidão superficial), a parábola oculta a verdade, confirmando-os na sua cegueira. De certa forma, ocultar a verdade profunda daqueles que a zombariam é um ato de misericórdia, pois quanto mais luz alguém rejeita, maior será a sua condenação (aumentar a revelação para um coração rebelde apenas aumentaria a sua culpa).',
    concl: 'A resposta de Jesus sobre as parábolas nos ensina que a revelação espiritual não é um direito humano, mas um presente da graça de Deus. A Palavra de Deus nunca é neutra; ela sempre produz um efeito. Para aqueles que buscam a Cristo com humildade, ela traz luz e salvação. Para aqueles que O rejeitam com orgulho, ela se torna um instrumento de cegueira e julgamento.'
  },
  {
    id: 'luk_16_1_9',
    intro: 'A Parábola do Administrador Infiel (ou Mordomo Desonesto) em Lucas 16 é amplamente considerada a parábola mais difícil e desconcertante contada por Jesus. Nela, um administrador que está prestes a ser demitido por má gestão de fundos decide falsificar as dívidas dos clientes do seu patrão, reduzindo o valor que eles devem, para garantir que esses clientes o recebam em suas casas quando ele ficar desempregado. O choque da parábola vem no versículo 8, onde o patrão (e, por implicação, Jesus) elogia o administrador desonesto. Como Jesus pode elogiar um fraudador? Para entender esta parábola, devemos focar no ponto principal da comparação (a prudência e a visão de futuro) e não nos detalhes imorais da história.',
    desc1: 'A Crise e a Resolução do Administrador. O administrador é pego desperdiçando os bens do seu senhor e recebe o aviso de demissão. Ele entra em pânico: ele não tem força para o trabalho braçal e tem vergonha de mendigar. Ele precisa de um plano para o seu futuro iminente. A sua solução é brilhante, embora corrupta: ele chama os devedores do seu senhor e reduz as suas dívidas (por exemplo, de 100 medidas de azeite para 50). Ao fazer isso, ele cria uma dívida de gratidão enorme com esses homens. Quando ele for expulso da casa do seu senhor, esses devedores se sentirão obrigados a abrigá-lo.',
    desc2: 'O Elogio da Prudência, não da Desonestidade. O versículo 8 diz: "E louvou aquele senhor o injusto mordomo por haver procedido prudentemente". O patrão não elogiou a desonestidade do administrador (ele ainda o chama de "injusto"), mas admirou a sua astúcia, sagacidade e capacidade de usar os recursos presentes para garantir o seu futuro. Jesus então faz a aplicação: "porque os filhos deste mundo são mais prudentes na sua geração do que os filhos da luz". Jesus está lamentando que os incrédulos frequentemente demonstram mais inteligência, dedicação e visão de futuro para garantir a sua segurança terrena do que os cristãos demonstram para investir na sua eternidade.',
    desc3: 'A Aplicação: Investindo na Eternidade. O versículo 9 contém a ordem de Jesus: "E eu vos digo: Granjeai amigos com as riquezas da injustiça; para que, quando estas vos faltarem, vos recebam eles nos tabernáculos eternos". As "riquezas da injustiça" (ou "dinheiro injusto") referem-se ao dinheiro terreno, que pertence a este mundo caído. Jesus está dizendo aos Seus discípulos para imitarem a prudência do administrador, mas com um objetivo eterno. Devemos usar o nosso dinheiro terreno (que inevitavelmente nos "faltará" quando morrermos) para abençoar pessoas, apoiar missões e ganhar almas para o Reino. Quando chegarmos ao céu ("tabernáculos eternos"), essas pessoas que foram abençoadas ou salvas através da nossa generosidade estarão lá para nos receber e nos agradecer.',
    concl: 'A Parábola do Administrador Infiel nos ensina que o dinheiro é uma ferramenta temporária que deve ser usada com visão eterna. Não podemos levar o nosso dinheiro para o céu, mas podemos enviá-lo adiante, investindo-o em pessoas e na obra do evangelho. A verdadeira sabedoria financeira não é acumular riquezas na terra, mas usar os recursos terrenos para garantir um impacto eterno.'
  },
  {
    id: '1co_15_29',
    intro: 'O capítulo 15 de 1 Coríntios é a defesa mais extensa e gloriosa da doutrina da ressurreição corporal em toda a Bíblia. Paulo está combatendo a heresia de alguns em Corinto que diziam que "não há ressurreição de mortos". Ele argumenta que, se não há ressurreição, Cristo não ressuscitou, e a nossa fé é vã. No meio desta argumentação lógica e teológica, Paulo lança uma pergunta no versículo 29 que se tornou um dos textos mais obscuros e debatidos do Novo Testamento: "Doutra maneira, que farão os que se batizam pelos mortos, se absolutamente os mortos não ressuscitam? Por que se batizam eles então pelos mortos?". O que significa ser batizado pelos mortos?',
    desc1: 'O Contexto do Argumento. É crucial entender que Paulo não está introduzindo uma nova doutrina ou ordenando uma prática. Ele está usando um argumento ad hominem (apelando à prática dos seus oponentes ou da cultura) para provar a inconsistência deles. O argumento de Paulo é simples: "Vocês dizem que não há ressurreição, mas a prática de vocês (ou de alguns entre vocês) de se batizarem pelos mortos pressupõe que os mortos viverão novamente. Se os mortos não ressuscitam, essa prática é completamente absurda". Paulo está apontando a contradição lógica deles, não endossando a teologia da prática.',
    desc2: 'As Teorias sobre a Prática. Existem dezenas de interpretações para este versículo. A interpretação herética (adotada pelos mórmons) é o batismo vicário (uma pessoa viva é batizada em favor de uma pessoa morta não batizada para garantir a sua salvação). Isso contradiz toda a teologia bíblica, que ensina que a salvação é pela fé pessoal durante a vida (Hebreus 9:27). Outra teoria sugere que novos convertidos estavam sendo batizados "para preencher o lugar" dos crentes que haviam morrido (martirizados). Uma terceira teoria (mais provável) é que alguns crentes em Corinto, influenciados por superstições pagãs, começaram uma prática aberrante de se batizarem por parentes que morreram antes de serem batizados. Paulo cita a prática deles para mostrar a inconsistência deles, sem aprovar a prática em si.',
    desc3: 'A Interpretação Alternativa (Gramatical). Alguns estudiosos sugerem uma tradução diferente baseada na preposição grega "hyper" (por, em favor de, por causa de). Eles traduzem: "O que farão os que se batizam por causa dos mortos?". Ou seja, pessoas que se convertem e são batizadas por causa do testemunho fiel de crentes que já morreram (como mártires ou parentes piedosos), com a esperança de se reunirem com eles na ressurreição. Se não há ressurreição, ser batizado com a esperança de rever os entes queridos mortos é inútil. Esta interpretação elimina a ideia de um batismo vicário e se encaixa perfeitamente na teologia cristã ortodoxa.',
    concl: 'Embora o significado exato da prática em Corinto permaneça um mistério, o ponto principal de Paulo é cristalino: a negação da ressurreição corporal torna toda a vida cristã, o sofrimento, o batismo e a esperança completamente absurdos. A nossa fé não é uma filosofia para esta vida apenas; ela está inseparavelmente ancorada na promessa de que, assim como Cristo ressuscitou, nós também ressuscitaremos.'
  },
  {
    id: '1pe_3_18_20',
    intro: 'A Primeira Epístola de Pedro foi escrita para encorajar cristãos que estavam sofrendo perseguição injusta. No capítulo 3, Pedro aponta para o exemplo supremo de sofrimento injusto: Jesus Cristo. Ao descrever a morte e a vitória de Cristo, Pedro introduz nos versículos 18 a 20 uma das passagens mais enigmáticas e difíceis de interpretar em toda a Bíblia. Ele fala sobre Cristo sendo vivificado no Espírito, e então indo "pregar aos espíritos em prisão", que foram desobedientes nos dias de Noé. Quem são esses espíritos? O que Cristo pregou a eles? E quando isso aconteceu? As respostas a essas perguntas têm gerado debates teológicos por séculos.',
    desc1: 'O Sofrimento e a Vitória de Cristo. O versículo 18 estabelece o fundamento do evangelho: "Porque também Cristo padeceu uma vez pelos pecados, o justo pelos injustos, para levar-nos a Deus". A morte de Cristo foi substitutiva e definitiva. A frase seguinte é a chave para o mistério: "morto, sim, na carne, mas vivificado no Espírito" (ou pelo Espírito). Isso não significa que Cristo se tornou um fantasma, mas que, após a Sua morte física (na carne), Ele foi ressuscitado para uma nova ordem de vida pelo poder do Espírito Santo (ou na esfera do Espírito). A Sua ressurreição é a prova da Sua vitória total sobre o pecado e a morte.',
    desc2: 'A Pregação aos Espíritos em Prisão (Visão 1: A Descida ao Inferno). A interpretação tradicional (frequentemente associada ao Credo dos Apóstolos) sugere que, entre a Sua morte e ressurreição, o espírito de Jesus desceu ao Hades (o mundo dos mortos). Lá, Ele pregou aos "espíritos em prisão" (as almas dos seres humanos que morreram no dilúvio). Ele não pregou o evangelho para dar-lhes uma segunda chance de salvação (a Bíblia rejeita o purgatório ou a salvação após a morte), mas proclamou a Sua vitória e o julgamento definitivo sobre eles. Esta visão enfatiza o triunfo cósmico de Cristo sobre todos os reinos.',
    desc3: 'A Pregação aos Espíritos em Prisão (Visão 2: A Pregação através de Noé). Uma interpretação alternativa (defendida por Agostinho e muitos reformadores) argumenta que Cristo não desceu ao inferno para pregar. Em vez disso, o "Espírito" mencionado no versículo 18 é o Espírito de Cristo que, nos dias do Antigo Testamento, inspirou Noé (o "pregoeiro da justiça", 2 Pedro 2:5) a pregar aos seus contemporâneos ímpios enquanto a arca estava sendo construída. Aquelas pessoas rejeitaram a mensagem de Cristo (através de Noé) e agora, no tempo em que Pedro escreve, os seus espíritos estão "em prisão" (no inferno) aguardando o julgamento final. O ponto de Pedro é encorajar a igreja: assim como a minoria (oito pessoas) foi salva na arca enquanto a maioria zombava, a igreja perseguida será salva por Cristo, mesmo sendo uma minoria rejeitada pelo mundo.',
    concl: 'Independentemente da interpretação exata dos "espíritos em prisão", o propósito de Pedro é claro: encorajar os crentes que sofrem. A morte de Cristo parecia uma derrota, mas resultou na Sua ressurreição gloriosa e na proclamação da Sua vitória sobre todos os poderes da rebelião. Assim como Deus vindicou Cristo e salvou Noé, Ele vindicará e salvará aqueles que permanecem fiéis a Ele em meio à hostilidade do mundo.'
  },
  {
    id: '1jo_3_9',
    intro: 'A Primeira Epístola de João foi escrita para dar aos crentes a certeza da sua salvação e para combater falsos mestres que afirmavam ter comunhão com Deus enquanto viviam na escuridão moral. João estabelece uma série de "testes" (obediência, amor e verdade) para distinguir os verdadeiros filhos de Deus dos falsos. No capítulo 3, versículo 9, João faz uma declaração absoluta e aparentemente aterrorizante: "Qualquer que é nascido de Deus não comete pecado; porque a sua semente permanece nele; e não pode pecar, porque é nascido de Deus". Lida isoladamente, esta frase parece ensinar o perfeccionismo sem pecado (a ideia de que um verdadeiro cristão nunca mais peca). No entanto, isso contradiria o próprio João no capítulo 1. Como reconciliar esta aparente contradição?',
    desc1: 'A Contradição Aparente. Se interpretarmos 1 João 3:9 como significando que um cristão nunca comete um único ato de pecado, temos um problema teológico massivo. No mesmo livro (1 João 1:8), João escreveu: "Se dissermos que não temos pecado, enganamo-nos a nós mesmos, e não há verdade em nós". E no versículo 10: "Se dissermos que não pecamos, fazemo-lo mentiroso". João reconhece claramente que os crentes ainda lutam contra o pecado e precisam de confissão contínua e da purificação do sangue de Cristo. Portanto, 1 João 3:9 não pode estar ensinando a perfeição absoluta e impecável nesta vida.',
    desc2: 'A Gramática e o Estilo de Vida (A Prática do Pecado). A chave para entender este versículo está na gramática grega. O verbo traduzido como "não comete pecado" (poiei hamartian) está no tempo presente contínuo. Uma tradução mais precisa seria: "não vive na prática habitual do pecado" ou "não continua pecando como um estilo de vida". João não está falando sobre um ato isolado de pecado (no qual um crente pode cair e se arrepender), mas sobre uma vida caracterizada pela rebelião contínua, impenitente e habitual contra Deus. O falso convertido vive confortavelmente no pecado; o verdadeiro crente pode cair no pecado, mas não pode viver confortavelmente nele.',
    desc3: 'A Razão Teológica: A Semente Divina. João explica por que o verdadeiro crente não pode viver na prática habitual do pecado: "porque a sua semente permanece nele; e não pode pecar, porque é nascido de Deus". A "semente" (sperma) de Deus refere-se ao princípio da nova vida implantado no crente na regeneração (o novo nascimento) através da Palavra e do Espírito Santo. Quando alguém nasce de Deus, ele recebe uma nova natureza que ama a justiça e odeia o pecado. É ontologicamente impossível para alguém que possui a natureza santa de Deus viver feliz e continuamente na lama do pecado. A nova natureza inevitavelmente produzirá uma nova maneira de viver.',
    concl: '1 João 3:9 não foi escrito para nos levar ao desespero quando falhamos, mas para nos dar uma ferramenta de discernimento. A prova do novo nascimento não é a ausência total de pecado, mas uma guerra constante contra o pecado. Se alguém afirma ser cristão, mas vive em pecado habitual, sem convicção, sem arrependimento e sem desejo de santidade, essa pessoa prova que a "semente de Deus" não está nela.'
  },
  {
    id: 'rev_3_15_16',
    intro: 'O capítulo 3 de Apocalipse contém a carta de Jesus à igreja de Laodiceia, a sétima e última das cartas às igrejas da Ásia Menor. Laodiceia era uma cidade extremamente rica, famosa pelo seu centro bancário, pela sua indústria de lã negra e pela sua escola de medicina (que produzia um colírio famoso). A igreja local havia absorvido a cultura da cidade: eles eram ricos, autossuficientes e orgulhosos, dizendo: "Rico sou, e estou enriquecido, e de nada tenho falta" (v. 17). Jesus profere contra esta igreja a repreensão mais severa de todas as sete cartas. Nos versículos 15 e 16, Ele usa a metáfora da temperatura da água para descrever o estado espiritual nauseante da congregação, ameaçando vomitá-los da Sua boca.',
    desc1: 'O Contexto Geográfico e a Metáfora da Água. Jesus diz: "Conheço as tuas obras, que nem és frio nem quente; quem dera foras frio ou quente!". Para entender a metáfora, precisamos conhecer a geografia de Laodiceia. A cidade não tinha um suprimento de água próprio. Eles recebiam água por aquedutos de duas cidades vizinhas: Hierápolis (famosa por suas fontes de águas termais quentes, usadas para cura) e Colossos (famosa por suas águas frias e refrescantes). Quando a água chegava a Laodiceia, ela já não era nem quente (curativa) nem fria (refrescante); era morna, estagnada e cheia de minerais com gosto ruim.',
    desc2: 'O Significado de "Frio" e "Quente". A interpretação popular frequentemente diz que "quente" significa zelo espiritual e "frio" significa hostilidade aberta a Deus, concluindo que Jesus prefere um ateu declarado a um cristão hipócrita. No entanto, no contexto das águas de Hierápolis e Colossos, tanto a água quente quanto a fria eram úteis e boas. Jesus está dizendo: "Quem dera vocês fossem úteis! Quem dera vocês trouxessem cura (como a água quente) ou refrigério espiritual (como a água fria) para a cidade". Em vez disso, a igreja de Laodiceia não servia para nada. Eles não tinham impacto espiritual; eles eram inúteis para o Reino de Deus.',
    desc3: 'A Rejeição da Água Morna. O julgamento de Jesus é visceral (v. 16): "Assim, porque és morno, e não és frio nem quente, vomitar-te-ei da minha boca". A água morna e rica em minerais de Laodiceia literalmente causava náuseas em quem a bebesse. Jesus está dizendo que a religião autossuficiente, confortável, sem sacrifício e sem paixão daquela igreja Lhe causava repulsa espiritual. Eles afirmavam o nome de Cristo, mas viviam como o mundo. Eles não eram hereges declarados, mas a sua apatia complacente era mais ofensiva a Cristo do que a rejeição aberta. A igreja morna é o maior obstáculo para o evangelho, pois apresenta ao mundo uma caricatura morta do cristianismo.',
    concl: 'A carta a Laodiceia é um alerta aterrorizante para a igreja moderna, especialmente em contextos de prosperidade material. A riqueza e o conforto frequentemente produzem a ilusão de independência espiritual. Jesus nos chama ao arrependimento, exigindo que abandonemos a nossa mornidão inútil e busquemos nEle o verdadeiro ouro provado no fogo, para que possamos ser instrumentos de cura e refrigério em um mundo doente.'
  },
  {
    id: 'mat_10_34',
    intro: 'No capítulo 10 de Mateus, Jesus envia os Seus doze apóstolos para a sua primeira missão de pregação. As Suas instruções não são um discurso motivacional cheio de promessas de sucesso fácil e aceitação universal. Pelo contrário, Jesus os prepara para a rejeição, a perseguição e o conflito. O versículo 34 é uma das declarações mais chocantes e paradoxais do ministério de Jesus, onde Ele destrói a ilusão de que o evangelho trará paz imediata a todos os relacionamentos e estabelece o custo absoluto do discipulado.',
    desc1: 'A Espada da Divisão. Jesus choca os Seus ouvintes: "Não cuideis que vim trazer a paz à terra; não vim trazer paz, mas espada". Como o "Príncipe da Paz" (Isaías 9:6) pode dizer isso? Jesus está falando sobre o efeito inevitável do evangelho em um mundo caído. A verdade de Cristo força uma decisão. A luz inevitavelmente entra em conflito com as trevas. A "espada" aqui não é uma arma militar para promover a fé pela força (Jesus proibiu isso), mas uma metáfora para a divisão afiada que o evangelho causa nas relações humanas.',
    desc2: 'O Conflito Familiar. Nos versículos seguintes, Jesus explica a natureza dessa espada: ela dividirá as famílias. "Porque eu vim pôr em dissensão o homem contra seu pai, e a filha contra sua mãe... e os inimigos do homem serão os seus familiares". Quando alguém em uma família decide seguir a Jesus de forma radical, abandonando tradições falsas ou pecados de estimação, isso frequentemente causa ofensa, hostilidade e rejeição por parte daqueles que rejeitam o evangelho. A lealdade a Cristo frequentemente custa a paz doméstica.',
    desc3: 'A Supremacia de Cristo. O propósito desta declaração não é promover a rebelião familiar, mas estabelecer a hierarquia absoluta do amor e da lealdade. Jesus exige uma devoção que supera os laços de sangue mais fortes. Se a família nos pedir para desobedecer a Cristo, ou se tivermos que escolher entre a aprovação da família e a obediência ao evangelho, devemos escolher Cristo. Ele exige a devoção que pertence apenas a Deus.',
    concl: 'O evangelho de Jesus Cristo não é um complemento para tornar a nossa vida mais confortável. É uma chamada radical para a rendição total. Jesus nos avisa que segui-Lo pode nos custar a paz na família e a aprovação do mundo. A verdadeira paz que Cristo traz é a paz com Deus, que frequentemente resulta em conflito com um mundo que rejeita a Deus.'
  },
  {
    id: 'mar_10_18',
    intro: 'No capítulo 10 de Marcos, um homem rico e influente (frequentemente chamado de "Jovem Rico") corre até Jesus, ajoelha-se diante dEle e faz a pergunta mais importante da vida: "Bom Mestre, que farei para herdar a vida eterna?". Antes de responder à pergunta sobre a salvação, Jesus interrompe o homem e questiona a sua premissa inicial com uma resposta surpreendente (v. 18): "Por que me chamas bom? Ninguém há bom senão um, que é Deus". Esta resposta tem sido usada por críticos para argumentar que Jesus negou a Sua própria divindade e a Sua própria bondade perfeita. No entanto, uma análise cuidadosa revela que Jesus estava fazendo exatamente o oposto: Ele estava forçando o jovem a reconhecer quem Ele realmente era.',
    desc1: 'O Uso Superficial da Palavra "Bom". O jovem rico usou o título "Bom Mestre" como um elogio lisonjeiro. Na cultura rabínica da época, os professores da lei raramente eram chamados de "bons", pois esse título era reservado a Deus. O jovem estava tratando Jesus como um mero professor humano excepcional, um guia moral que poderia lhe dar uma lista de tarefas para alcançar o céu. A sua visão da "bondade" era superficial, baseada no esforço humano e na obediência externa à lei (como ele mesmo afirma no v. 20: "tudo isso guardei desde a minha mocidade").',
    desc2: 'O Dilema Lógico de Jesus. Jesus não está negando ser bom, nem está negando ser Deus. Ele está apresentando ao jovem um dilema lógico (um silogismo). A premissa de Jesus é: "Somente Deus é verdadeiramente e perfeitamente bom". Se o jovem acredita que Jesus é apenas um mestre humano, ele não tem o direito de chamá-Lo de "bom" (pois todos os homens são pecadores). Se o jovem insiste em chamar Jesus de "bom", ele deve estar preparado para reconhecer que Jesus é mais do que um mestre; Ele é o próprio Deus encarnado. Jesus está dizendo: "Você entende as implicações do título que está me dando?".',
    desc3: 'A Preparação para o Teste Final. Ao redefinir a "bondade" como um atributo exclusivo de Deus, Jesus está preparando o terreno para expor a falência moral do jovem. O jovem achava que era "bom" porque guardava os mandamentos externos. Mas Jesus, o Deus perfeitamente bom, vê o coração. Jesus testa o jovem pedindo que ele venda tudo o que tem e O siga. O jovem vai embora triste, provando que ele amava o seu dinheiro mais do que a Deus (quebrando o primeiro mandamento). Ele não era "bom" afinal; ele era um idólatra que precisava da graça, não de mais tarefas religiosas.',
    concl: 'A resposta de Jesus ao Jovem Rico nos ensina que não podemos nos aproximar de Cristo apenas como um bom professor de moral. Se Ele é apenas um homem, Ele não pode nos salvar. Devemos reconhecer a nossa própria falta de bondade e nos prostrar diante dEle não apenas como Mestre, mas como o Deus perfeitamente bom que exige a nossa rendição total.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 39');
