const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'gen_32_22_32',
    intro: 'A luta de Jacó no vau de Jaboque é um dos encontros mais misteriosos e transformadores do Antigo Testamento. Jacó estava retornando para a Terra Prometida após vinte anos de exílio. No entanto, ele estava aterrorizado, pois sabia que no dia seguinte encontraria o seu irmão Esaú, a quem havia enganado e que agora vinha ao seu encontro com quatrocentos homens armados. Jacó envia a sua família, os seus servos e todos os seus bens para o outro lado do rio, ficando completamente sozinho na escuridão da noite. É nesse momento de isolamento e medo extremo que ele tem um encontro físico e espiritual com o próprio Deus, uma luta que mudaria para sempre a sua identidade e o seu destino.',
    desc1: 'A narrativa diz que "lutou com ele um homem, até que a alva subiu". A identidade desse "homem" é revelada mais tarde como uma teofania (uma manifestação visível de Deus, possivelmente o Cristo pré-encarnado). A luta durou a noite inteira. Jacó, que passou a vida inteira lutando contra os homens (enganando o seu pai, o seu irmão e o seu sogro Labão) usando a sua própria astúcia e força, agora se vê lutando contra o próprio Deus. Deus desce ao nível de Jacó para confrontá-lo não com palavras, mas com um combate corpo a corpo. A verdadeira transformação espiritual frequentemente requer que lutemos com Deus até que a nossa autossuficiência seja quebrada.',
    desc2: 'Vendo que não prevalecia contra a teimosia e a força natural de Jacó, o "homem" toca na articulação da coxa de Jacó, deslocando-a. Em um instante, a força de Jacó é destruída. Ele não pode mais lutar nem fugir; ele só pode se agarrar. A quebra física de Jacó representa a quebra do seu orgulho e da sua dependência da própria força. Mesmo manco e derrotado, Jacó se agarra ao seu oponente e declara: "Não te deixarei ir, se me não abençoares". A verdadeira fé não é a ausência de luta, mas a recusa em soltar Deus mesmo quando estamos feridos e quebrados.',
    desc3: 'Antes de abençoá-lo, o "homem" faz uma pergunta crucial: "Qual é o teu nome?". Anos antes, quando o seu pai cego lhe fez a mesma pergunta, Jacó mentiu dizendo: "Eu sou Esaú". Agora, na escuridão, ele é forçado a confessar a sua verdadeira identidade: "Jacó" (que significa enganador, usurpador). A confissão da nossa verdadeira natureza é o pré-requisito para a transformação. Deus então muda o seu nome: "Não te chamarás mais Jacó, mas Israel (aquele que luta com Deus); pois como príncipe lutaste com Deus e com os homens, e prevaleceste". A bênção de Deus não foi a remoção do problema (Esaú ainda estava vindo), mas a transformação da identidade de Jacó.',
    concl: 'A história de Jaboque nos ensina que Deus frequentemente nos leva ao isolamento e quebra a nossa autossuficiência para nos transformar. Saímos da presença de Deus mancando (com a marca da nossa fraqueza), mas com um novo nome e uma nova identidade. A maior vitória na vida cristã não é quando derrotamos os nossos inimigos, mas quando somos derrotados por Deus e passamos a depender exclusivamente da Sua graça.'
  },
  {
    id: 'exo_33_12_23',
    intro: 'O capítulo 33 de Êxodo ocorre no rescaldo da maior crise espiritual de Israel: o pecado do bezerro de ouro. A nação havia quebrado a aliança semanas após tê-la feito. Como consequência, Deus diz a Moisés que cumprirá a promessa de dar a terra de Canaã e enviará um anjo para expulsar os inimigos, mas declara: "Eu não subirei no meio de ti, porque és povo de dura cerviz, para que te não consuma eu no caminho". Deus estava oferecendo o sucesso (a terra, a vitória, a prosperidade), mas retirando a Sua presença íntima. A resposta de Moisés a essa oferta é uma das intercessões mais apaixonadas e teologicamente profundas da Bíblia, revelando o coração de um líder que valoriza a presença de Deus acima de qualquer bênção terrena.',
    desc1: 'Moisés rejeita categoricamente a oferta de sucesso sem a presença de Deus. Ele argumenta com o Senhor na Tenda da Congregação: "Se a tua presença não for conosco, não nos faças subir daqui". Para Moisés, a Terra Prometida sem Deus seria apenas mais um deserto. Ele entende que a verdadeira herança de Israel não era o território de Canaã, o leite ou o mel, mas o próprio Yahweh. A religião que busca as bênçãos de Deus (saúde, prosperidade, sucesso) mas não se importa com a presença de Deus é uma forma sutil de idolatria. Moisés prefere morrer no deserto com Deus do que viver no paraíso sem Ele.',
    desc2: 'Moisés continua o seu argumento, apelando para a identidade e o testemunho da nação: "Como, pois, se saberá agora que tenho achado graça aos teus olhos, eu e o teu povo? Acaso não é por andares tu conosco, de modo a sermos separados, eu e o teu povo, de todos os povos que há sobre a face da terra?". O que distinguia Israel das outras nações não era a sua moralidade superior, o seu poder militar ou a sua cultura, mas exclusivamente a presença manifesta do Deus vivo no meio deles. A presença de Deus é a única marca inegável da verdadeira Igreja; sem ela, somos apenas mais uma organização humana.',
    desc3: 'Deus responde à intercessão de Moisés com graça: "A minha presença irá contigo, e eu te darei descanso". Mas Moisés, encorajado pela intimidade, faz um pedido ainda mais audacioso: "Rogo-te que me mostres a tua glória". Ele não quer apenas a presença que guia; ele quer ver a essência de quem Deus é. Deus responde que nenhum homem pode ver a Sua face e viver (devido à santidade consumidora de Deus), mas Ele faz uma concessão maravilhosa. Deus coloca Moisés na fenda de uma rocha, cobre-o com a Sua mão enquanto passa, e permite que Moisés veja as Suas "costas" (o rastro da Sua bondade e glória).',
    concl: 'A intercessão de Moisés nos desafia a examinar os nossos próprios desejos. Estamos satisfeitos com a proteção (o anjo) e a provisão (a terra), ou estamos desesperados pela presença do próprio Deus? A verdadeira maturidade espiritual é alcançada quando podemos dizer a Deus: "Se a Tua presença não for comigo, eu não quero ir a lugar nenhum".'
  },
  {
    id: 'psa_139_1_24',
    intro: 'O Salmo 139 é, sem dúvida, a mais bela, profunda e poética exploração dos atributos de Deus em toda a Escritura. Escrito por Davi, este salmo não é um tratado teológico frio e abstrato sobre a onisciência (Deus sabe tudo), a onipresença (Deus está em todo lugar) e a onipotência (Deus pode tudo) do Criador. Em vez disso, é uma meditação intensamente pessoal e relacional sobre como esses atributos divinos afetam a vida do crente. Davi celebra o fato de que o Deus infinito do universo nos conhece intimamente, nos cerca constantemente e nos formou com um propósito específico. Longe de ser uma verdade aterrorizante, o conhecimento absoluto de Deus torna-se a base da nossa maior segurança e conforto.',
    desc1: 'Nos primeiros seis versículos, Davi medita sobre a onisciência de Deus: "Senhor, tu me sondaste, e me conheces". Deus não tem um conhecimento superficial sobre nós; Ele conhece os nossos movimentos (o assentar e o levantar), entende os nossos pensamentos de longe e esquadrinha os nossos caminhos. Antes mesmo que a palavra chegue à nossa língua, Deus já a conhece inteiramente. Davi não se sente invadido por esse conhecimento absoluto, mas protegido: "Tu me cercaste por detrás e por diante, e puseste sobre mim a tua mão". O conhecimento de Deus é tão maravilhoso que excede a capacidade de compreensão humana.',
    desc2: 'A partir do versículo 7, Davi explora a onipresença de Deus: "Para onde me irei do teu espírito, ou para onde fugirei da tua face?". Ele imagina tentar escapar de Deus subindo aos céus, descendo ao mais profundo abismo (Seol), ou voando para as extremidades do mar. A conclusão é que não há lugar no universo, físico ou espiritual, onde Deus não esteja presente. Mesmo se a escuridão mais densa tentar nos esconder, "as trevas e a luz são para ti a mesma coisa". Para o ímpio, a onipresença de Deus é um terror (não há onde se esconder do Juiz); mas para o crente, é o maior consolo (não há lugar de dor ou isolamento onde o Pai não possa nos alcançar e guiar).',
    desc3: 'Nos versículos 13 a 16, Davi volta-se para a onipotência de Deus na criação humana: "Pois possuíste os meus rins; cobriste-me (teceste-me) no ventre de minha mãe". Davi louva a Deus porque foi feito de modo "assombroso e maravilhoso". A vida humana não é um acidente biológico; é uma obra de arte tecida pelas mãos do Criador no lugar mais oculto. Além de formar o nosso corpo, Deus também planejou os nossos dias: "os teus olhos viram o meu corpo ainda informe; e no teu livro todas estas coisas foram escritas; as quais em continuação foram formadas, quando nem ainda uma delas havia". O nosso futuro está seguro nas mãos dAquele que nos desenhou.',
    concl: 'O Salmo 139 destrói a ilusão de que podemos esconder alguma coisa de Deus ou de que a nossa vida é um acidente sem sentido. O salmo termina com uma oração corajosa de submissão (v. 23-24): "Sonda-me, ó Deus, e conhece o meu coração... e vê se há em mim algum caminho mau, e guia-me pelo caminho eterno". Quando entendemos que Deus nos conhece perfeitamente e nos ama infinitamente, podemos abrir o nosso coração para a Sua purificação e direção.'
  },
  {
    id: 'isa_55_1_13',
    intro: 'O capítulo 55 de Isaías é o clímax do "Livro da Consolação" (a segunda metade de Isaías) e apresenta o convite mais apaixonado, universal e gracioso do Antigo Testamento. Escrito para um povo que estava no exílio, gastando as suas energias e recursos na Babilônia para tentar encontrar satisfação em coisas que não podiam preencher o vazio da alma, Deus irrompe com um apelo urgente. Ele convida todos os sedentos a virem e desfrutarem da Sua provisão espiritual abundante e gratuita. Este texto é uma antecipação gloriosa do Evangelho da graça, revelando que a salvação não pode ser comprada com o esforço humano, mas deve ser recebida como um dom gratuito através do arrependimento e da fé na Palavra de Deus.',
    desc1: 'O convite começa com um grito de urgência: "Ó vós, todos os que tendes sede, vinde às águas, e os que não tendes dinheiro, vinde, comprai, e comei; sim, vinde, comprai, sem dinheiro e sem preço, vinho e leite". O pré-requisito para a salvação não é a dignidade moral ou a riqueza espiritual, mas a sede (o reconhecimento da própria necessidade) e a falência (não ter dinheiro). Deus oferece água (para a sobrevivência), vinho (para a alegria) e leite (para a nutrição). Em seguida, Ele confronta a futilidade do esforço humano: "Por que gastais o dinheiro naquilo que não é pão? E o produto do vosso trabalho naquilo que não pode satisfazer?". O mundo oferece substitutos vazios, mas só Deus oferece a verdadeira satisfação para a alma.',
    desc2: 'O convite à graça é acompanhado por um chamado urgente ao arrependimento (v. 6-7): "Buscai ao Senhor enquanto se pode achar, invocai-o enquanto está perto". A graça é gratuita, mas a janela de oportunidade não ficará aberta para sempre; há uma urgência escatológica na salvação. O arrependimento é descrito de forma prática: "Deixe o ímpio o seu caminho (as suas ações pecaminosas), e o homem maligno os seus pensamentos (a raiz do pecado na mente), e se converta ao Senhor". A promessa para o que se arrepende é absoluta: Deus "se compadecerá dele" e "grandioso é em perdoar". O perdão de Deus não é relutante, mas abundante e transbordante.',
    desc3: 'Para garantir ao povo que essa promessa de perdão abundante é real (pois a lógica humana tem dificuldade em aceitar a graça gratuita), Deus declara a superioridade dos Seus caminhos (v. 8-9): "Porque os meus pensamentos não são os vossos pensamentos, nem os vossos caminhos os meus caminhos". A graça de Deus não opera segundo a lógica da retribuição humana. Por fim, Deus garante a eficácia da Sua Palavra (v. 10-11). Assim como a chuva e a neve descem do céu e não voltam sem regar a terra e fazê-la produzir, a Palavra de Deus não voltará vazia, mas cumprirá infalivelmente o propósito para o qual foi enviada. A nossa salvação está ancorada na Palavra inquebrável de Deus.',
    concl: 'Isaías 55 nos convida a parar de tentar comprar a nossa salvação com os nossos próprios méritos e a parar de buscar satisfação nas cisternas rotas deste mundo. O banquete da graça está preparado e é totalmente gratuito. A única resposta exigida é que venhamos com sede, abandonemos os nossos caminhos pecaminosos e confiemos na Palavra e no perdão grandioso do nosso Deus.'
  },
  {
    id: 'mat_16_13_28',
    intro: 'O encontro em Cesareia de Filipe (Mateus 16) é o divisor de águas no ministério de Jesus e o ponto central do Evangelho de Mateus. Jesus leva os Seus discípulos para longe da multidão e da oposição religiosa, para uma região pagã conhecida pela adoração ao deus Pã e ao imperador romano. É nesse cenário de pluralismo religioso que Jesus faz a pergunta mais importante da história humana, forçando os Seus discípulos a definirem a Sua identidade. A resposta a essa pergunta não apenas estabelece a fundação da Igreja, mas também introduz a revelação chocante de que o caminho do Messias (e dos Seus seguidores) passa inevitavelmente pela cruz.',
    desc1: 'Jesus começa com uma pesquisa de opinião pública: "Quem dizem os homens ser o Filho do homem?". Os discípulos relatam as opiniões populares: João Batista ressuscitado, Elias, Jeremias ou um dos profetas. A multidão respeitava Jesus como um grande mestre ou um profeta poderoso, mas O via apenas como um homem. A religião popular sempre tenta reduzir Jesus a um bom exemplo moral ou a um líder revolucionário. No entanto, Jesus estreita o foco e faz a pergunta pessoal e inadiável: "E vós, quem dizeis que eu sou?". A salvação não depende do que a multidão pensa sobre Jesus, mas da nossa confissão pessoal e revelada sobre a Sua identidade.',
    desc2: 'Simão Pedro, agindo como porta-voz do grupo, faz a confissão definitiva: "Tu és o Cristo (o Messias prometido), o Filho do Deus vivo". Jesus responde afirmando que essa compreensão não veio de dedução humana ("carne e sangue não to revelou"), mas de uma revelação direta de Deus Pai. Jesus então muda o nome de Simão para Pedro (Petros, pedra) e declara: "Sobre esta pedra (petra, a rocha da confissão de Pedro sobre a identidade de Cristo) edificarei a minha igreja, e as portas do inferno não prevalecerão contra ela". A Igreja não é construída sobre a fragilidade de um homem, mas sobre a verdade inabalável de que Jesus é o Filho de Deus.',
    desc3: 'Imediatamente após essa revelação gloriosa, Jesus muda o tom e "começou a mostrar aos seus discípulos que convinha ir a Jerusalém, e padecer muito... e ser morto, e ressuscitar ao terceiro dia". Pedro, chocado com a ideia de um Messias sofredor, repreende Jesus: "Senhor, tem compaixão de ti; de modo nenhum te acontecerá isso". Jesus o repreende severamente: "Para trás de mim, Satanás... não compreendes as coisas que são de Deus, mas só as que são dos homens". Jesus então estabelece a condição para o discipulado: "Se alguém quiser vir após mim, renuncie-se a si mesmo, tome sobre si a sua cruz, e siga-me". Não há cristianismo sem cruz.',
    concl: 'A confissão de Cesareia de Filipe nos ensina que reconhecer Jesus como o Filho de Deus é apenas o primeiro passo. A verdadeira fé exige que aceitemos não apenas a Sua identidade divina, mas também o Seu método de salvação (a cruz) e a Sua exigência de discipulado (a nossa própria cruz). A Igreja que confessa a Cristo e abraça a cruz é a única força na terra contra a qual as portas do inferno não podem prevalecer.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 18');
