const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'psa_19_1_14',
    intro: 'O Salmo 19, escrito por Davi, é considerado por muitos (incluindo C.S. Lewis) como um dos maiores poemas líricos do mundo. O salmo é uma meditação profunda sobre as duas formas pelas quais Deus se revela à humanidade: a revelação geral (através da criação) e a revelação especial (através da Sua Palavra escrita). Davi começa olhando para a vastidão do céu estrelado e termina olhando para as profundezas do seu próprio coração. O salmo nos ensina que a mesma voz que ordenou o universo e estabeleceu as leis da natureza também nos deu a lei moral, e que o objetivo final de ambas as revelações é nos levar à humildade, à purificação e a um relacionamento redentor com o Criador.',
    desc1: 'A primeira parte do salmo (v. 1-6) foca na revelação geral. Davi declara: "Os céus declaram a glória de Deus e o firmamento anuncia a obra das suas mãos". A criação não é silenciosa; ela é um pregador contínuo. "Um dia faz declaração a outro dia, e uma noite mostra sabedoria a outra noite". A mensagem do universo sobre o poder, a ordem e a majestade do Criador é universal, não dependendo de linguagem humana: "Sem linguagem, sem fala, ouvem-se as suas vozes". Davi usa a imagem do sol, que cruza o céu como um noivo saindo do seu aposento ou um herói correndo a sua carreira, para ilustrar que nada pode se esconder do calor e da evidência da presença de Deus na natureza. A criação nos deixa sem desculpas (Romanos 1:20).',
    desc2: 'A segunda parte (v. 7-11) muda abruptamente da glória do universo para a perfeição da Palavra de Deus (a revelação especial). Enquanto a criação nos mostra que Deus existe e é poderoso, a Palavra nos mostra quem Ele é, o que Ele exige e como podemos ser salvos. Davi usa seis títulos para a Palavra (lei, testemunho, preceitos, mandamento, temor, juízos) e descreve os seus efeitos transformadores: ela refrigera a alma, dá sabedoria aos símplices, alegra o coração e ilumina os olhos. A Palavra de Deus é mais valiosa do que o ouro fino e mais doce do que o mel. Ela não é um fardo, mas a fonte da verdadeira alegria e do discernimento moral.',
    desc3: 'A terceira parte (v. 12-14) é a resposta pessoal de Davi a essas duas grandes revelações. Diante da majestade do universo e da pureza absoluta da Lei, Davi percebe a sua própria pecaminosidade. Ele pergunta: "Quem pode entender os seus erros?". Ele clama por purificação dos "pecados ocultos" (aqueles que ele comete sem perceber) e pede para ser guardado dos "pecados intencionais" (a rebelião deliberada), para que eles não dominem sobre ele. O salmo termina com uma das orações mais belas da Bíblia: "Sejam agradáveis as palavras da minha boca e a meditação do meu coração perante a tua face, Senhor, Rocha minha e Redentor meu!".',
    concl: 'O Salmo 19 nos ensina que não podemos conhecer a Deus plenamente apenas admirando um pôr do sol; precisamos abrir as Escrituras. Quando a glória de Deus na criação e a pureza de Deus na Sua Palavra colidem com a nossa vida, o resultado deve ser um coração quebrantado que clama por purificação e deseja viver de forma agradável diante do seu Redentor.'
  },
  {
    id: 'jer_18_1_6',
    intro: 'O capítulo 18 de Jeremias registra uma das lições objetivas mais famosas e poderosas do Antigo Testamento. Deus ordena ao profeta Jeremias que desça à casa do oleiro, prometendo que lá Ele lhe faria ouvir as Suas palavras. Em vez de receber uma visão celestial ou um sonho místico, Jeremias é enviado a uma oficina comum e suja para observar um artesão trabalhando com barro. A mensagem visual que Jeremias recebe ali revela a soberania absoluta de Deus sobre as nações, a fragilidade humana e a natureza condicional do juízo divino. É uma ilustração vívida de como Deus lida com o Seu povo, misturando o Seu poder soberano com a responsabilidade humana.',
    desc1: 'Jeremias desce à casa do oleiro e o observa trabalhando sobre as rodas. O texto diz: "Como o vaso, que ele fazia de barro, quebrou-se na mão do oleiro, tornou a fazer dele outro vaso, conforme o que pareceu bem aos olhos do oleiro fazer". O barro não é um material nobre como o ouro ou a prata; é terra misturada com água, sem valor intrínseco. O seu único valor está na habilidade das mãos do oleiro. O fato de o vaso se quebrar nas mãos do oleiro não significa que o oleiro falhou, mas que o barro tinha impurezas ou resistência. Em vez de jogar o barro fora, o oleiro pacientemente o amassa novamente e faz um vaso novo. Deus é o Oleiro; Israel (e a humanidade) é o barro.',
    desc2: 'A palavra do Senhor vem a Jeremias interpretando a cena: "Não poderei eu fazer de vós como fez este oleiro, ó casa de Israel? diz o Senhor. Eis que, como o barro na mão do oleiro, assim sois vós na minha mão, ó casa de Israel". Deus afirma o Seu direito soberano de moldar, quebrar e refazer as nações de acordo com o Seu propósito. O barro não tem o direito de questionar o oleiro (como Paulo argumentaria mais tarde em Romanos 9). A soberania de Deus é absoluta. No entanto, a lição da casa do oleiro não é sobre um fatalismo cego, mas sobre um relacionamento dinâmico.',
    desc3: 'Deus explica a dinâmica do Seu governo (v. 7-10). Ele diz que, se Ele decretar a destruição de uma nação, mas essa nação se arrepender da sua maldade, Ele "se arrependerá" (mudará o curso da Sua ação) do mal que intentou fazer. Da mesma forma, se Ele prometer edificar uma nação, mas ela fizer o mal e não ouvir a Sua voz, Ele "se arrependerá" do bem que prometeu. O "arrependimento" de Deus aqui não significa que Ele cometeu um erro, mas que Ele responde de forma consistente ao caráter moral das nossas escolhas. O barro tem a responsabilidade de ser maleável nas mãos de Deus através do arrependimento.',
    concl: 'A lição do oleiro nos ensina que somos apenas barro: frágeis, falhos e totalmente dependentes da graça de Deus. Quando o pecado nos "quebra" ou nos torna inúteis, Deus não nos joga no lixo. Se formos maleáveis através do arrependimento, Ele nos amassa novamente e nos refaz em um vaso novo para a Sua glória. A nossa maior segurança não está na nossa própria força, mas em permanecermos nas mãos do Oleiro.'
  },
  {
    id: 'mat_13_1_23',
    intro: 'A Parábola do Semeador é a primeira e a mais fundamental de todas as parábolas de Jesus (Marcos 4:13 diz que se não entendermos esta, não entenderemos as outras). Jesus estava ensinando uma grande multidão à beira do Mar da Galileia, sentado em um barco. Ele usa uma cena agrícola comum para explicar um dos maiores mistérios do Seu ministério: por que a mesma mensagem do Evangelho, pregada pelo mesmo pregador (o próprio Jesus), produz resultados tão radicalmente diferentes nas pessoas que a ouvem. A parábola revela que a eficácia da Palavra de Deus não depende da qualidade da semente (que é sempre perfeita), mas da condição do "solo" (o coração humano) que a recebe.',
    desc1: 'Jesus descreve o semeador lançando a semente, que cai em quatro tipos diferentes de solo. O primeiro solo é "ao pé do caminho" (a beira da estrada). Este solo é duro e compactado pelos passos das pessoas. A semente não consegue penetrar, fica exposta, e as aves vêm e a comem. Jesus explica que este é o coração endurecido pela incredulidade, pelo orgulho ou pelo cinismo. A pessoa ouve a Palavra do Reino, mas não a entende (não a internaliza). O diabo (as aves) vem imediatamente e arrebata o que foi semeado, impedindo qualquer chance de salvação. A Palavra não tem impacto porque o coração está fechado.',
    desc2: 'O segundo solo é "pedregoso", onde não há muita terra. A semente brota rapidamente, mas como não tem profundidade (raiz), quando o sol esquenta, a planta seca e morre. Jesus explica que este é o coração emocional e superficial. A pessoa ouve a Palavra e a recebe imediatamente com alegria (entusiasmo religioso). No entanto, a sua fé é baseada em sentimentos e na busca por bênçãos, não em convicção profunda. Quando surge a "angústia ou a perseguição por causa da palavra" (o sol escaldante), essa pessoa se ofende e abandona a fé. O cristianismo sem raízes não sobrevive ao sofrimento.',
    desc3: 'O terceiro solo é "entre espinhos". A semente brota e cresce, mas os espinhos crescem junto e a sufocam, impedindo-a de dar fruto. Jesus explica que este é o coração dividido. A pessoa ouve a Palavra, mas "os cuidados deste mundo (ansiedade) e a sedução das riquezas (materialismo)" sufocam a Palavra. A fé não é destruída pela perseguição, mas pela prosperidade e pelas distrações. O quarto solo é a "boa terra". A semente cai, penetra, cria raízes e dá fruto (a cem, a sessenta e a trinta por um). Este é o coração que ouve, entende e obedece à Palavra. A marca da verdadeira salvação não é apenas o entusiasmo inicial, mas a produção de frutos a longo prazo.',
    concl: 'A Parábola do Semeador nos desafia a examinar a condição do nosso próprio coração. A Palavra de Deus está sendo semeada continuamente. A questão não é se a semente é boa, mas que tipo de solo nós somos. Estamos endurecidos pelo orgulho, somos superficiais diante do sofrimento, estamos sufocados pelo materialismo, ou somos a boa terra que recebe a Palavra com humildade e produz os frutos do Espírito?'
  },
  {
    id: 'luk_15_1_10',
    intro: 'O capítulo 15 de Lucas é frequentemente chamado de "O Coração do Evangelho". Ele contém três parábolas (a ovelha perdida, a moeda perdida e o filho pródigo) contadas em resposta a uma crítica específica. Os publicanos e os pecadores (os marginalizados morais da sociedade) estavam se aproximando para ouvir Jesus. Os fariseus e escribas (a elite religiosa) murmuravam, dizendo: "Este recebe pecadores, e come com eles". Para a religião farisaica, Deus amava os justos e odiava os pecadores; a santidade exigia separação. Jesus conta essas parábolas para destruir essa teologia distorcida e revelar o verdadeiro coração de Deus: um Deus que não apenas recebe os pecadores que vêm a Ele, mas que os busca ativamente e se alegra extravagantemente quando são encontrados.',
    desc1: 'A primeira parábola é a da Ovelha Perdida. Jesus pergunta aos fariseus: "Que homem dentre vós, tendo cem ovelhas, e perdendo uma delas, não deixa no deserto as noventa e nove, e vai após a perdida até que venha a achá-la?". A lógica econômica humana diria para focar nas 99 que estão seguras, mas a lógica do amor divino busca a única que está em perigo. A ovelha perdida representa o pecador que se desviou por tolice ou distração e não consegue voltar sozinho. O pastor não espera que a ovelha encontre o caminho de volta; ele vai atrás dela. Quando a encontra, ele não a castiga com o cajado; ele a coloca sobre os ombros com alegria e a carrega de volta para casa.',
    desc2: 'A segunda parábola é a da Moeda Perdida (Dracma). Uma mulher tem dez dracmas (moedas de prata, possivelmente parte do seu dote de casamento, tendo grande valor financeiro e sentimental) e perde uma dentro de casa. A moeda perdida representa o pecador que está perdido "dentro de casa" (talvez uma referência àqueles que estão perdidos dentro da própria religião, sem perceberem a sua condição). A moeda não tem vontade própria; ela está inerte na escuridão e na sujeira. A mulher acende a candeia, varre a casa e busca diligentemente até encontrá-la. Deus acende a luz da Sua Palavra e varre a nossa vida com o Espírito Santo para nos encontrar.',
    desc3: 'O clímax de ambas as parábolas é a celebração. Quando o pastor encontra a ovelha e a mulher encontra a moeda, eles não celebram sozinhos. Eles convocam os amigos e vizinhos: "Alegrai-vos comigo, porque já achei a minha ovelha (ou dracma) perdida". Jesus aplica a lição diretamente aos fariseus: "Digo-vos que assim haverá alegria no céu por um pecador que se arrepende, mais do que por noventa e nove justos que não necessitam de arrependimento". Os fariseus achavam que Deus se alegrava com a sua justiça própria. Jesus revela que o céu entra em festa não por causa do moralismo dos que se acham justos, mas por causa do arrependimento dos que se sabem perdidos.',
    concl: 'As parábolas da ovelha e da moeda perdidas nos ensinam que o nosso valor não diminui quando nos perdemos no pecado; nós continuamos sendo o tesouro procurado por Deus. A salvação não é a história do nosso esforço para encontrar a Deus, mas a história da busca incansável, amorosa e diligente de Deus para nos encontrar e nos trazer de volta para casa com alegria.'
  },
  {
    id: 'act_16_6_15',
    intro: 'O capítulo 16 de Atos narra um dos momentos mais cruciais de redirecionamento divino na história das missões cristãs. O apóstolo Paulo e a sua equipe (Silas e Timóteo) estavam na sua segunda viagem missionária, viajando pela Ásia Menor (atual Turquia). Eles tinham planos estratégicos claros sobre onde pregar o Evangelho, mas o Espírito Santo intervém de forma surpreendente, fechando portas lógicas e abrindo uma porta inesperada. O resultado dessa obediência à direção do Espírito é a chegada do Evangelho ao continente europeu e a conversão de Lídia, a primeira cristã europeia registrada. Esta narrativa é uma aula sobre como Deus guia os Seus servos através de portas fechadas e visões claras.',
    desc1: 'A narrativa começa com uma série de portas fechadas: "E, passando pela Frígia e pela província da Galácia, foram impedidos pelo Espírito Santo de anunciar a palavra na Ásia". Eles tentam ir para a Bitínia, "mas o Espírito de Jesus não lho permitiu". Paulo estava tentando fazer algo bom (pregar o Evangelho), mas não era o tempo nem o lugar de Deus. O texto não explica como o Espírito os impediu (se por circunstâncias, profecia ou convicção interna), mas a lição é clara: Deus guia o Seu povo tanto pelo que Ele impede quanto pelo que Ele permite. Um "não" de Deus não é uma rejeição, mas um redirecionamento para um propósito maior.',
    desc2: 'Sem opções na Ásia, eles descem para a cidade costeira de Trôade. É lá, durante a noite, que Paulo tem uma visão: "um varão da Macedônia estava em pé, e lhe rogava, dizendo: Passa à Macedônia, e ajuda-nos". A Macedônia ficava do outro lado do Mar Egeu, na Europa. A resposta da equipe é imediata e unânime (Lucas, o autor de Atos, junta-se à equipe aqui, usando o pronome "nós"): "E, logo depois desta visão, procuramos partir para a Macedônia, concluindo que o Senhor nos chamava para lhes anunciarmos o evangelho". Eles não hesitam. A verdadeira fé exige que abandonemos os nossos planos lógicos quando recebemos a direção clara de Deus.',
    desc3: 'Eles atravessam o mar e chegam a Filipos, a principal cidade da Macedônia e uma colônia romana. No sábado, em vez de encontrarem o "varão" da visão, eles vão para a beira do rio, onde algumas mulheres estavam reunidas para orar (não havia homens judeus suficientes para formar uma sinagoga). Paulo prega para elas. Entre elas estava Lídia, uma vendedora de púrpura (um artigo de luxo) da cidade de Tiatira. O texto descreve a sua conversão com uma precisão teológica profunda: "O Senhor lhe abriu o coração para que estivesse atenta ao que Paulo dizia". A salvação é uma obra de Deus; o pregador fala aos ouvidos, mas só o Senhor pode abrir o coração. Lídia crê, é batizada com a sua casa e insiste em hospedar os missionários.',
    concl: 'A história do chamado macedônio nos ensina que os planos de Deus são sempre maiores do que a nossa estratégia. Quando Deus fecha portas que parecem boas, Ele está nos preparando para abrir portas que são essenciais. A conversão de Lídia prova que, quando obedecemos à direção do Espírito, Deus já preparou os corações (mesmo nos lugares mais improváveis) para receberem a semente do Evangelho.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 27');
