const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: '1sa_15_1_3',
    intro: 'O capítulo 15 de 1 Samuel contém uma das ordens divinas mais difíceis e controversas de toda a Bíblia. O profeta Samuel entrega a Saul, o primeiro rei de Israel, uma missão militar que não é uma guerra comum, mas um ato de "herém" (o anátema, ou a destruição total consagrada a Deus). Deus ordena a Saul que ataque a nação dos amalequitas e destrua absolutamente tudo: homens, mulheres, crianças e animais. Para o leitor moderno, esta ordem parece um genocídio cruel, incompatível com o Deus de amor. No entanto, para entender este texto, é necessário compreendê-lo dentro do contexto da justiça divina, da história da redenção e da natureza do juízo de Deus no Antigo Testamento.',
    desc1: 'A Memória da Justiça Divina. O versículo 2 estabelece a base legal e moral para a ordem: "Assim diz o Senhor dos Exércitos: Lembrei-me do que Amaleque fez a Israel; como se lhe opôs no caminho, quando subia do Egito". Os amalequitas não eram vítimas inocentes. Centenas de anos antes, quando Israel era um povo vulnerável de ex-escravos fugindo do Egito, os amalequitas os atacaram covardemente pela retaguarda, matando os fracos e cansados (Deuteronômio 25:17-19). Deus havia prometido julgar Amaleque por essa atrocidade. A ordem a Saul não é um capricho sanguinário, mas a execução de uma sentença judicial divina que havia sido adiada por séculos, demonstrando a paciência de Deus, mas também a certeza da Sua justiça.',
    desc2: 'O Princípio do Herém (Anátema). A ordem no versículo 3 é absoluta: "Vai, pois, agora e fere a Amaleque; e destrói totalmente a tudo o que tiver, e não lhe perdoes; porém matarás desde o homem até à mulher, desde os meninos até aos de peito, desde os bois até às ovelhas, e desde os camelos até aos jumentos". O "herém" era uma prática onde uma nação ou cidade era tão profundamente corrupta e dedicada ao mal que Deus a consagrava para a destruição total, removendo-a da terra como um cirurgião remove um câncer. A inclusão de crianças e animais mostra que o julgamento era corporativo e absoluto; nada do que pertencia a Amaleque deveria ser aproveitado por Israel (para evitar o saque e a cobiça).',
    desc3: 'A Soberania de Deus sobre a Vida. A maior dificuldade do texto é a ordem para matar crianças. A Bíblia ensina que Deus é o Criador e o Doador da vida, e Ele tem o direito soberano de tirá-la quando e como decidir, seja através de causas naturais, desastres ou, neste caso específico e único da história bíblica, através do exército de Israel. O julgamento dos amalequitas é uma prefiguração do julgamento final, onde o mal será erradicado completamente. É crucial notar que Deus não dá essa ordem de "guerra santa" à Igreja no Novo Testamento; a nossa guerra é espiritual, não carnal.',
    concl: 'A ordem para destruir os amalequitas é um lembrete sombrio de que Deus é um Juiz perfeitamente justo que não deixará o mal impune para sempre. O texto nos confronta com a severidade da ira de Deus contra o pecado e nos faz valorizar ainda mais a cruz de Cristo, onde a ira que nós merecíamos caiu sobre o Filho de Deus para que pudéssemos ser poupados.'
  },
  {
    id: 'psa_137_7_9',
    intro: 'O Salmo 137 é um dos textos mais crus, dolorosos e perturbadores do saltério. É um "salmo imprecatório" (uma oração que pede o julgamento e a maldição de Deus sobre os inimigos). O salmo foi escrito por exilados judeus na Babilônia, que choravam junto aos rios enquanto os seus captores zombavam deles, pedindo que cantassem as canções de Sião. Os versículos finais (7-9) mudam da tristeza profunda para uma fúria ardente contra Edom e a Babilônia, culminando em uma das imagens mais chocantes da Bíblia: uma bênção sobre aquele que esmagar os bebês babilônios contra as pedras. Como podemos entender essa linguagem violenta na Palavra de Deus?',
    desc1: 'O Clamor por Justiça contra Edom. O versículo 7 pede a Deus que se lembre dos edomitas (descendentes de Esaú, irmãos de Israel). Quando os babilônios destruíram Jerusalém, os edomitas não apenas ficaram de braços cruzados, mas celebraram a carnificina e encorajaram a destruição total: "Arrasai-a, arrasai-a, até aos seus alicerces". O salmista está pedindo a Deus que aplique a justiça retributiva contra a traição e a crueldade de Edom. Não é um pedido de vingança pessoal, mas um apelo ao Juiz do universo para que o mal não fique impune.',
    desc2: 'A Lei de Talião e a Queda da Babilônia. O versículo 8 dirige-se à Babilônia, a nação que massacrou os judeus e destruiu o templo: "Ah! filha de Babilônia, que vais ser assolada; feliz aquele que te retribuir o pago que tu nos pagaste a nós". O salmista está invocando a Lei de Talião (olho por olho, dente por dente), que era a base da justiça no mundo antigo. Ele está pedindo que a Babilônia sofra exatamente o mesmo terror e destruição que ela infligiu a Jerusalém. Ele reconhece que a Babilônia já está destinada à destruição pelas profecias divinas.',
    desc3: 'A Imagem Chocante do Julgamento. O versículo 9 é o mais difícil: "Feliz aquele que pegar em teus filhos e der com eles nas pedras". Esta não é uma ordem de Deus para que os crentes matem crianças, mas a expressão honesta da dor e da raiva de uma vítima de atrocidades. Os babilônios haviam feito exatamente isso com os bebês judeus durante o cerco de Jerusalém. O salmista está entregando o seu desejo de vingança a Deus, em vez de agir com as próprias mãos. Ele está pedindo que o julgamento de Deus sobre a Babilônia seja tão completo que a sua futura geração (os "filhos") seja cortada, impedindo que o império do mal ressurja.',
    concl: 'Os salmos imprecatórios nos ensinam que podemos levar a nossa raiva, dor e desejo de justiça mais profundos e sombrios a Deus em oração. Em vez de reprimir a nossa fúria diante da injustiça, devemos entregá-la ao Juiz Supremo. Para o cristão, a resposta final a este salmo encontra-se na cruz, onde a justiça implacável de Deus e o Seu amor perdoador se encontraram.'
  },
  {
    id: 'mat_5_29_30',
    intro: 'No Sermão do Monte, Jesus eleva o padrão da moralidade muito além da obediência externa exigida pelos fariseus, atingindo o nível dos pensamentos e intenções do coração. Ao falar sobre o adultério, Jesus declara que olhar para uma mulher com intenção impura já é cometer adultério no coração. Imediatamente a seguir (versículos 29 e 30), Ele usa uma linguagem chocante e hiperbólica (exagero intencional) sobre arrancar o olho e cortar a mão. O objetivo de Jesus não é promover a automutilação física, mas ensinar a seriedade absoluta do pecado e a necessidade de uma ação radical e dolorosa para mortificar a carne e evitar a condenação eterna.',
    desc1: 'A Metáfora do Olho Direito. Jesus diz: "Portanto, se o teu olho direito te escandalizar (fizer tropeçar), arranca-o e atira-o para longe de ti". O olho é o portão da mente; é através do olhar que a cobiça frequentemente entra no coração (como aconteceu com o rei Davi). O "olho direito" representava o melhor olho, a visão mais valiosa. Jesus está dizendo que, se algo na sua vida (mesmo algo valioso, prazeroso ou aparentemente inofensivo) está levando você a pecar, você deve eliminá-lo impiedosamente. A automutilação física não resolveria o problema (um homem cego ainda pode cobiçar na mente); a mutilação deve ser espiritual e prática (cortar o acesso à tentação).',
    desc2: 'A Metáfora da Mão Direita. Jesus continua: "E, se a tua mão direita te escandalizar, corta-a e atira-a para longe de ti". A mão direita representa a ação, a habilidade, o trabalho e os relacionamentos. Se uma carreira, um relacionamento, um hábito ou um ambiente está fazendo você tropeçar no pecado, você deve cortá-lo da sua vida, não importa o quão doloroso ou limitante isso pareça. A palavra "atira-o para longe" indica uma separação violenta e definitiva, sem espaço para negociação com o pecado.',
    desc3: 'A Matemática da Eternidade. A razão para essa ação radical é baseada em um cálculo de custo-benefício eterno: "Pois te é melhor que se perca um dos teus membros do que seja todo o teu corpo lançado no inferno (Geena)". Jesus ensina que o pecado não mortificado leva à condenação eterna. É infinitamente melhor viver nesta vida com "limitações" (sem certos prazeres, relacionamentos ou status que levam ao pecado) e entrar na vida eterna, do que desfrutar de todos os membros e prazeres aqui e perecer no inferno. O inferno é uma realidade tão terrível que qualquer sacrifício terreno para evitá-lo é um preço pequeno a pagar.',
    concl: 'Jesus nos ensina que não podemos tratar o pecado como um animal de estimação inofensivo. O pecado é um câncer espiritual. A verdadeira santificação exige amputações dolorosas: cancelar assinaturas, terminar relacionamentos tóxicos, mudar de emprego ou abandonar hábitos. A graça de Deus não nos isenta da luta radical contra o pecado; ela nos dá o poder para fazer os cortes necessários.'
  },
  {
    id: 'mat_10_34_39',
    intro: 'No capítulo 10 de Mateus, Jesus envia os Seus doze apóstolos para a sua primeira missão de pregação. As Suas instruções não são um discurso motivacional cheio de promessas de sucesso fácil e aceitação universal. Pelo contrário, Jesus os prepara para a rejeição, a perseguição e o conflito. Nos versículos 34 a 39, Jesus profere algumas das palavras mais difíceis e paradoxais do Seu ministério. Ele destrói a ilusão de que o evangelho trará paz imediata a todos os relacionamentos e estabelece o custo absoluto do discipulado: a lealdade a Cristo deve superar o amor à própria família e à própria vida.',
    desc1: 'A Espada da Divisão. Jesus choca os Seus ouvintes: "Não cuideis que vim trazer a paz à terra; não vim trazer paz, mas espada". Como o "Príncipe da Paz" pode dizer isso? Jesus está falando sobre o efeito inevitável do evangelho em um mundo caído. A verdade de Cristo força uma decisão. Quando alguém na família decide seguir a Jesus de forma radical, isso frequentemente causa divisão, ofensa e hostilidade por parte daqueles que rejeitam o evangelho. Jesus cita o profeta Miqueias para mostrar que o evangelho dividirá as casas: "o filho contra o pai, e a filha contra a mãe... e os inimigos do homem serão os seus familiares".',
    desc2: 'A Supremacia do Amor a Cristo. Jesus estabelece a hierarquia absoluta do amor (v. 37): "Quem ama o pai ou a mãe mais do que a mim não é digno de mim; e quem ama o filho ou a filha mais do que a mim não é digno de mim". Jesus não está ensinando a odiar a família (Ele mesmo mandou honrar pai e mãe), mas está exigindo que o nosso amor e lealdade a Ele sejam tão supremos que qualquer outro amor pareça menor em comparação. Se a família nos pedir para desobedecer a Cristo, devemos escolher Cristo. Ele exige a devoção que pertence apenas a Deus.',
    desc3: 'A Cruz e o Paradoxo da Vida. O custo do discipulado vai além da família; exige a própria vida (v. 38): "E quem não toma a sua cruz, e não segue após mim, não é digno de mim". No primeiro século, a cruz não era uma joia, mas um instrumento de tortura e execução pública. Tomar a cruz significava marchar para a morte, renunciando a todos os direitos e ambições pessoais. Jesus conclui com o grande paradoxo da vida cristã (v. 39): "Quem achar a sua vida perdê-la-á; e quem perder a sua vida, por amor de mim, achá-la-á". Quem tenta salvar a sua vida vivendo para si mesmo, perderá a vida eterna. Quem entrega a sua vida a Cristo, encontrará a verdadeira vida.',
    concl: 'O evangelho de Jesus Cristo não é um complemento para tornar a nossa vida mais confortável. É uma chamada radical para a rendição total. Jesus nos avisa que segui-Lo pode nos custar a paz na família, a aprovação do mundo e até a nossa própria vida. Mas Ele também promete que o que perdemos por amor a Ele é infinitamente menor do que a vida eterna que encontramos nEle.'
  },
  {
    id: 'mar_3_28_30',
    intro: 'O capítulo 3 de Marcos relata um momento de intensa oposição ao ministério de Jesus. Os escribas que desceram de Jerusalém, incapazes de negar os milagres óbvios de Jesus (especialmente a expulsão de demônios), decidem atacar a fonte do Seu poder. Eles O acusam de estar possuído por Belzebu (o príncipe dos demônios) e de expulsar demônios pelo poder de Satanás. Jesus primeiro refuta a lógica absurda deles (Satanás não expulsaria Satanás), e então profere a advertência mais aterrorizante de todo o Novo Testamento: a declaração sobre o "pecado imperdoável" ou a "blasfêmia contra o Espírito Santo".',
    desc1: 'A Extensão da Graça. Antes de falar sobre o pecado imperdoável, Jesus faz uma declaração impressionante sobre a vastidão da graça de Deus (v. 28): "Na verdade vos digo que todos os pecados serão perdoados aos filhos dos homens, e toda a sorte de blasfêmias, com que blasfemarem". Esta é uma promessa extraordinária. Assassinato, adultério, roubo, mentira e até mesmo blasfêmias verbais contra Deus podem ser perdoados através do arrependimento e da fé em Cristo. A graça de Deus é maior do que a maioria dos pecados humanos.',
    desc2: 'A Exceção Aterrorizante. No entanto, Jesus estabelece uma única exceção absoluta (v. 29): "Qualquer, porém, que blasfemar contra o Espírito Santo, nunca obterá perdão, mas será réu do eterno juízo". O que é esta blasfêmia? O contexto (v. 30) nos dá a resposta: "Porque diziam: Tem espírito imundo". Os escribas estavam vendo a obra clara, inegável e libertadora do Espírito Santo através de Jesus, e, com corações endurecidos, chamaram o Espírito Santo de demônio. Eles não estavam confusos; eles estavam em um estado de rebelião consciente, deliberada e maliciosa contra a luz de Deus.',
    desc3: 'A Natureza do Pecado Imperdoável. A blasfêmia contra o Espírito Santo não é um palavrão dito em um momento de raiva, nem uma dúvida passageira. É a rejeição final, obstinada e contínua da obra do Espírito Santo, que é o único que pode nos convencer do pecado e nos levar ao arrependimento. Se alguém chama a única força que pode salvá-lo de "demoníaca", essa pessoa cortou a única ponte para a salvação. O pecado é imperdoável não porque Deus se recusa a perdoar quem se arrepende, mas porque a pessoa que comete esse pecado destruiu a sua própria capacidade de se arrepender. O seu coração tornou-se pedra.',
    concl: 'A advertência sobre o pecado imperdoável não deve aterrorizar o crente sensível (o fato de você ter medo de tê-lo cometido é a prova de que você não o cometeu, pois o seu coração ainda é sensível a Deus). Em vez disso, é um aviso solene contra o endurecimento do coração. Nunca devemos zombar, resistir ou atribuir ao mal a obra clara do Espírito Santo, pois é Ele quem nos atrai para a graça salvadora de Cristo.'
  },
  {
    id: 'luk_14_26_27',
    intro: 'No capítulo 14 de Lucas, Jesus está cercado por "grandes multidões" que O acompanhavam. Muitas dessas pessoas provavelmente O seguiam pelos motivos errados: fascínio pelos milagres, esperança de pão grátis ou expectativa de uma revolução política contra Roma. Jesus, que nunca se impressionou com números e nunca diluiu a Sua mensagem para atrair multidões, vira-se para eles e profere palavras chocantes para filtrar os verdadeiros discípulos dos meros simpatizantes. Ele estabelece os termos inegociáveis do discipulado, usando uma linguagem tão forte que ofenderia qualquer pessoa que não estivesse disposta a uma rendição total.',
    desc1: 'O Paradoxo do "Ódio" à Família. Jesus diz (v. 26): "Se alguém vier a mim, e não aborrecer (odiar) a seu pai, e mãe, e mulher, e filhos, e irmãos, e irmãs... não pode ser meu discípulo". Esta é uma das frases mais difíceis de Jesus. Ele não está anulando o mandamento de amar o próximo ou honrar os pais. No idioma semítico, "odiar" frequentemente significa "amar menos" ou "escolher um em detrimento do outro" (como em "Amei a Jacó, e odiei a Esaú"). Jesus está exigindo que o nosso amor e lealdade a Ele sejam tão absolutos e supremos que, em comparação, o nosso amor pela nossa família mais próxima pareça ódio. Se a vontade da família entrar em conflito com a vontade de Cristo, o discípulo deve escolher Cristo sem hesitação.',
    desc2: 'A Renúncia da Própria Vida. A exigência de Jesus vai além da família e atinge o núcleo do ego humano: "...e ainda também a sua própria vida, não pode ser meu discípulo". O verdadeiro discipulado exige o fim da autonomia. Não podemos seguir a Jesus e, ao mesmo tempo, insistir em ser os senhores do nosso próprio destino, carreira, desejos e segurança. Seguir a Cristo significa entregar a Ele a escritura de propriedade da nossa vida. Quem ama a sua própria vida mais do que a Cristo não é digno dEle.',
    desc3: 'A Cruz como Estilo de Vida. Jesus conclui com a metáfora definitiva do sacrifício (v. 27): "E qualquer que não levar a sua cruz, e não vier após mim, não pode ser meu discípulo". Para a multidão do primeiro século, a cruz não era um símbolo religioso de ouro usado no pescoço; era o instrumento romano de tortura, humilhação e morte. Ver alguém carregando uma cruz significava ver um homem condenado caminhando para a sua execução, sem direitos e sem futuro terreno. Jesus está dizendo que o discípulo deve considerar-se morto para o mundo e para o pecado, disposto a sofrer rejeição e perseguição por causa do evangelho.',
    concl: 'Jesus não oferece um evangelho barato. Ele não nos chama para adicioná-Lo à nossa vida como um acessório para nos fazer felizes. Ele nos chama para morrermos para nós mesmos. O verdadeiro discipulado custa tudo o que temos e tudo o que somos. Mas a promessa implícita do evangelho é que Aquele que nos pede tudo é o único que é digno de receber tudo.'
  },
  {
    id: 'rom_9_10_18',
    intro: 'O capítulo 9 de Romanos é um dos textos mais profundos, complexos e debatidos de toda a Bíblia. O apóstolo Paulo está lidando com uma questão teológica angustiante: se o evangelho é verdadeiro, por que a maioria dos judeus (o povo escolhido de Deus) rejeitou o Messias? A promessa de Deus falhou? Paulo responde que não. Ele mergulha no mistério da eleição soberana de Deus, argumentando que pertencer ao povo de Deus nunca foi uma questão de descendência física ou de obras humanas, mas exclusivamente da escolha livre, soberana e incondicional da graça de Deus. Para provar isso, ele usa exemplos da história dos patriarcas.',
    desc1: 'A Eleição Incondicional (Jacó e Esaú). Paulo usa o exemplo dos filhos gêmeos de Isaque e Rebeca (v. 10-13). Antes mesmo de os meninos nascerem, antes de fazerem qualquer bem ou mal, Deus disse a Rebeca: "O maior servirá o menor". Paulo explica o motivo dessa escolha antecipada: "para que o propósito de Deus, segundo a eleição, ficasse firme, não por causa das obras, mas por aquele que chama". A salvação não é baseada no mérito humano previsto, mas na escolha soberana de Deus. Paulo cita Malaquias para confirmar: "Amei a Jacó, e aborreci a Esaú". Deus escolheu Jacó para ser o herdeiro da promessa puramente por Sua graça.',
    desc2: 'A Defesa da Justiça de Deus. Paulo antecipa a objeção humana natural (v. 14): "Que diremos pois? que há injustiça da parte de Deus?". Se Deus escolhe um e rejeita outro antes de nascerem, isso não é injusto? Paulo responde com um enfático "De modo nenhum!". Ele cita a declaração de Deus a Moisés (v. 15): "Compadecer-me-ei de quem me compadecer, e terei misericórdia de quem eu tiver misericórdia". A justiça de Deus exigiria que todos fossem condenados, pois todos pecaram. A misericórdia, por definição, não é um direito que pode ser exigido; é um presente livre. Deus não é injusto por salvar alguns; Ele é infinitamente gracioso por não condenar todos.',
    desc3: 'A Soberania sobre o Coração (Faraó). Paulo conclui o seu argumento (v. 16): "Assim, pois, isto não depende do que quer, nem do que corre, mas de Deus, que se compadece". A salvação não depende da vontade humana ou do esforço humano. Para provar a soberania absoluta de Deus, Paulo usa o exemplo de Faraó (v. 17). Deus levantou Faraó exatamente para mostrar o Seu poder e proclamar o Seu nome. O versículo 18 resume o mistério: "Logo, pois, compadece-se de quem quer, e endurece a quem quer". Deus é soberano tanto na distribuição da Sua misericórdia quanto na aplicação da Sua justiça.',
    concl: 'Romanos 9 destrói o orgulho humano. Ensina-nos que não contribuímos com nada para a nossa salvação, exceto com o pecado que a tornou necessária. A doutrina da eleição soberana não deve nos levar ao fatalismo, mas à mais profunda gratidão e humildade, sabendo que, se fomos salvos, foi unicamente porque Deus, na Sua misericórdia insondável, escolheu nos amar.'
  },
  {
    id: '1ti_2_11_15',
    intro: 'O capítulo 2 de 1 Timóteo contém algumas das instruções mais debatidas e controversas do apóstolo Paulo sobre a ordem na igreja, especificamente em relação ao papel das mulheres no culto público. Paulo estava escrevendo a Timóteo, que pastoreava a igreja em Éfeso, uma cidade dominada pelo culto à deusa Diana (Ártemis), onde as mulheres exerciam forte liderança religiosa. Além disso, falsos mestres estavam se infiltrando na igreja, e algumas mulheres parecem ter sido influenciadas por eles. Neste contexto, Paulo estabelece diretrizes sobre o ensino e a autoridade na congregação, baseando os seus argumentos não na cultura local, mas na ordem da criação e na queda.',
    desc1: 'A Instrução sobre o Aprendizado e a Submissão. Paulo começa (v. 11): "A mulher aprenda em silêncio, com toda a subjeição". No mundo antigo, onde as mulheres frequentemente eram excluídas da educação teológica, a ordem para que a mulher "aprenda" era radical e libertadora. No entanto, o modo de aprendizado no culto público deveria ser em "silêncio" (hesychia, que significa quietude, tranquilidade, ausência de perturbação) e "subjeição" (reconhecendo a ordem de autoridade estabelecida por Deus na igreja).',
    desc2: 'A Restrição ao Ensino e à Autoridade. O versículo 12 é o centro do debate: "Não permito, porém, que a mulher ensine, nem use de autoridade sobre o marido (ou homem), mas que esteja em silêncio". Paulo não está dizendo que as mulheres não podem ensinar em nenhum contexto (Priscila ensinou Apolo, e mulheres mais velhas devem ensinar as mais novas). A restrição refere-se especificamente ao ofício de ensino doutrinário autoritativo sobre a congregação reunida (o papel do presbítero/pastor). Paulo estabelece que a liderança espiritual principal e o ensino autoritativo na igreja local foram confiados por Deus aos homens qualificados.',
    desc3: 'O Fundamento Teológico: Criação e Queda. Paulo não baseia esta restrição na cultura de Éfeso ou na suposta inferioridade intelectual das mulheres, mas na história de Gênesis (v. 13-14). Primeiro, a ordem da criação: "Porque primeiro foi formado Adão, depois Eva". Deus estabeleceu uma ordem de liderança antes mesmo da entrada do pecado. Segundo, a dinâmica da queda: "E Adão não foi enganado, mas a mulher, sendo enganada, caiu em transgressão". Paulo aponta que a inversão da ordem divina (Eva tomando a liderança e Adão falhando em proteger e liderar) resultou no desastre da queda. O versículo 15 ("salvar-se-á, porém, dando à luz filhos") é difícil, mas geralmente é entendido como a promessa de que as mulheres encontrarão significado e salvação vivendo o seu papel ordenado por Deus (como a maternidade) com fé, amor e santidade, em vez de usurparem a autoridade.',
    concl: 'Este texto nos ensina que Deus é um Deus de ordem. Ele estabeleceu papéis distintos e complementares para homens e mulheres na família e na igreja. A restrição de Paulo não é sobre valor ou dignidade (homens e mulheres são iguais em Cristo), mas sobre a função e a ordem estabelecidas pelo Criador para o florescimento da Sua igreja.'
  },
  {
    id: 'gen_6_5_7',
    intro: 'O capítulo 6 de Gênesis descreve o estado moral da humanidade nos dias que antecederam o grande Dilúvio. Após a queda de Adão e Eva e o assassinato de Abel por Caim, o pecado não apenas permaneceu no mundo, mas multiplicou-se e intensificou-se como um vírus descontrolado. Os versículos 5 a 7 oferecem o diagnóstico mais sombrio e absoluto da depravação humana em toda a Escritura. Eles revelam como Deus vê o coração humano não regenerado e a profunda tristeza divina diante da corrupção da Sua criação, culminando na decisão do juízo.',
    desc1: 'A Totalidade da Depravação Humana. O versículo 5 é um raio-X divino da alma humana: "E viu o Senhor que a maldade do homem se multiplicara sobre a terra e que toda a imaginação dos pensamentos de seu coração era só má continuamente". O texto usa palavras absolutas para descrever a extensão do pecado: "toda" a imaginação, "só" má, "continuamente". O pecado não era apenas um ato ocasional ou externo; ele havia corrompido a fonte da vida humana (o coração e os pensamentos). Não havia nenhuma área da vida humana que não estivesse infectada pela rebelião contra Deus. Esta é a base bíblica para a doutrina da depravação total.',
    desc2: 'A Dor e o "Arrependimento" de Deus. A resposta de Deus ao pecado humano é profundamente emocional (v. 6): "Então arrependeu-se o Senhor de haver feito o homem sobre a terra e pesou-lhe em seu coração". A palavra "arrependeu-se" (nacham) não significa que Deus cometeu um erro ou foi pego de surpresa (Deus é onisciente). É um antropopatismo (atribuir emoções humanas a Deus) para expressar a profunda dor, tristeza e repulsa de Deus diante da ruína moral da Sua criação. O pecado humano não apenas quebra as leis de Deus; ele fere o coração de Deus.',
    desc3: 'A Decisão do Juízo. A santidade e a justiça de Deus não podem tolerar o mal indefinidamente. O versículo 7 declara a sentença: "E disse o Senhor: Destruirei o homem que criei de sobre a face da terra, desde o homem até ao animal, até ao réptil, e até à ave dos céus; porque me arrependo de os haver feito". A corrupção humana foi tão profunda que afetou toda a criação (Romanos 8:20-22). A única solução para um mundo totalmente corrompido era a destruição total (uma "des-criação") através das águas do dilúvio, para que Deus pudesse recomeçar com Noé, que "achou graça aos olhos do Senhor" (v. 8).',
    concl: 'Gênesis 6 nos confronta com a realidade terrível do pecado humano e a santidade inflexível de Deus. O coração humano, deixado à sua própria sorte, produz apenas o mal continuamente. O dilúvio é um lembrete histórico de que o juízo de Deus é real e inevitável para o pecado não arrependido, apontando para a nossa necessidade desesperada da graça salvadora que hoje encontramos em Cristo, a nossa verdadeira Arca.'
  },
  {
    id: 'exo_21_20_21',
    intro: 'O capítulo 21 de Êxodo faz parte do "Livro da Aliança", uma série de leis civis e criminais dadas a Israel logo após os Dez Mandamentos. Estas leis aplicavam os princípios morais de Deus à sociedade antiga do Oriente Médio. Os versículos 20 e 21 tratam de um tema muito difícil para o leitor moderno: a escravidão e o castigo físico de servos. Para entender este texto, é crucial reconhecer que a "escravidão" em Israel era frequentemente uma servidão por dívida (um sistema econômico de sobrevivência), muito diferente do tráfico de escravos baseado em raça dos séculos recentes. Além disso, a lei de Deus aqui não está instituindo o ideal moral, mas regulando e limitando a crueldade em uma sociedade dura e caída.',
    desc1: 'A Proteção da Vida do Servo. O versículo 20 estabelece uma lei revolucionária para o mundo antigo: "Se alguém ferir a seu servo, ou a sua serva, com pau, e morrer debaixo da sua mão, certamente será castigado (vingado)". Nas nações vizinhas (como Babilônia ou Egito), o escravo era considerado propriedade absoluta do senhor, e o senhor podia matá-lo sem sofrer consequências legais. A lei de Deus em Israel muda isso radicalmente. O servo é reconhecido como um ser humano feito à imagem de Deus. Se o senhor matar o servo, o senhor será julgado como um assassino. A vida do servo tem valor legal e proteção divina.',
    desc2: 'A Regulação do Castigo e a "Propriedade". O versículo 21 apresenta a dificuldade: "Porém, se sobreviver por um ou dois dias, não será castigado, porque é dinheiro seu (sua propriedade)". No mundo antigo, o castigo físico era o método padrão de disciplina. A lei não proíbe a disciplina física, mas estabelece um limite estrito: a intenção. Se o servo sobrevive por um ou dois dias após o espancamento, isso prova legalmente que o senhor não tinha a intenção de matá-lo (foi disciplina que deu errado, não assassinato premeditado). A frase "é dinheiro seu" não significa que o servo não é humano, mas reconhece a realidade econômica da época: o senhor já sofreu uma perda financeira pela incapacidade ou morte do servo, o que serve como punição econômica.',
    desc3: 'O Princípio da Redução de Danos. Ao ler leis como esta, devemos lembrar o princípio ensinado por Jesus em Mateus 19:8 sobre o divórcio: "Por causa da dureza do vosso coração vos permitiu Moisés... mas ao princípio não foi assim". A lei mosaica frequentemente operava com o princípio de "redução de danos". Deus não aboliu imediatamente todas as estruturas sociais caídas (como a servidão e a poligamia), mas introduziu leis que limitavam o abuso, protegiam os vulneráveis e preparavam o caminho para a ética superior do Novo Testamento, onde em Cristo "não há servo nem livre" (Gálatas 3:28).',
    concl: 'Embora as leis civis do Antigo Testamento reflitam a dura realidade do mundo antigo, elas revelam um Deus que se importa com a justiça e que intervém para proteger os mais vulneráveis da sociedade. O valor da vida humana, mesmo a de um servo, é estabelecido pela lei divina, apontando para a dignidade igual que todos temos diante do Criador.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 37');
