const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: '1sa_15_10_23',
    intro: 'O capítulo 15 de 1 Samuel marca o ponto de não retorno para o reinado de Saul. Deus, através do profeta Samuel, havia dado a Saul uma ordem explícita e severa: destruir totalmente os amalequitas (um juízo divino pendente desde os dias de Moisés) e não poupar nada, nem pessoas nem animais. Saul vai à guerra e vence, mas decide obedecer apenas parcialmente. Ele destrói o que era vil e desprezível, mas poupa o rei Agague (como um troféu de guerra) e o melhor das ovelhas e dos bois. Quando confrontado, Saul tenta justificar a sua desobediência com motivos religiosos, revelando um coração que valorizava mais a própria imagem e a conveniência do que a submissão a Deus.',
    desc1: 'A palavra do Senhor vem a Samuel com uma declaração dolorosa: "Arrependo-me de haver posto a Saul rei, porquanto deixou de me seguir, e não cumpriu as minhas palavras". Samuel passa a noite clamando a Deus, mas na manhã seguinte vai confrontar o rei. Quando Samuel chega, Saul o recebe com uma mentira piedosa e excesso de confiança: "Bendito sejas tu do Senhor; cumpri a palavra do Senhor". Saul havia se enganado a ponto de acreditar que a obediência parcial era aceitável. Samuel, no entanto, não se deixa enganar pela retórica religiosa e faz a pergunta que expõe a hipocrisia: "Que balido, pois, de ovelhas é este nos meus ouvidos, e o mugido de vacas que ouço?". O pecado sempre deixa evidências barulhentas.',
    desc2: 'Confrontado com a evidência, Saul tenta transferir a culpa e espiritualizar o seu pecado: "O povo os trouxe dos amalequitas... para os sacrificar ao Senhor teu Deus". Saul culpa os seus soldados (falta de liderança) e afirma que a desobediência tinha um propósito nobre (sacrifícios a Deus). Ele tenta usar a religião para encobrir a rebelião. Samuel o interrompe e o lembra de onde ele veio: "Porventura, sendo tu pequeno aos teus próprios olhos, não foste feito cabeça das tribos de Israel?". O orgulho havia substituído a humildade inicial de Saul. Ele agora se achava no direito de editar os mandamentos de Deus de acordo com a sua própria sabedoria.',
    desc3: 'Samuel profere então uma das declarações teológicas mais importantes do Antigo Testamento: "Tem porventura o Senhor tanto prazer em holocaustos e sacrifícios, como em que se obedeça à palavra do Senhor? Eis que o obedecer é melhor do que o sacrificar; e o atender melhor é do que a gordura de carneiros". Deus não precisa dos nossos sacrifícios, do nosso dinheiro ou do nosso ativismo religioso se o nosso coração estiver em rebelião. Samuel conclui com o veredito final: "Porque a rebelião é como o pecado de feitiçaria, e o porfiar é como iniquidade e idolatria. Porquanto tu rejeitaste a palavra do Senhor, ele também te rejeitou a ti, para que não sejas rei".',
    concl: 'A rejeição de Saul nos ensina que a obediência parcial é, na verdade, desobediência total. Não podemos escolher quais partes da Palavra de Deus vamos obedecer e tentar compensar as nossas falhas com ativismo religioso. Para Deus, a obediência humilde e incondicional é sempre superior a qualquer sacrifício que possamos oferecer.'
  },
  {
    id: '2ki_6_8_23',
    intro: 'A história de Eliseu e os carros de fogo em Dotã é uma das narrativas mais espetaculares sobre a realidade do mundo espiritual e a proteção invisível de Deus. O rei da Síria estava em guerra contra Israel, mas todas as suas emboscadas secretas falhavam. Frustrado, ele descobre que o profeta Eliseu estava revelando os seus planos militares ao rei de Israel (através de revelação divina). O rei sírio decide então enviar um grande exército, com cavalos e carros de guerra, para cercar a pequena cidade de Dotã durante a noite, com o único objetivo de prender um homem desarmado. Esta história contrasta o pânico da visão natural com a paz inabalável da visão espiritual.',
    desc1: 'Na manhã seguinte, o servo de Eliseu (provavelmente um jovem inexperiente) levanta-se cedo, sai e vê a cidade completamente cercada pelo exército sírio. O pânico toma conta dele. Ele corre para Eliseu e grita: "Ai, meu senhor! Que faremos?". O servo estava olhando para a realidade através das lentes da visão natural. Ele viu o problema (o exército inimigo), viu os seus próprios recursos (ele e um velho profeta) e concluiu corretamente, segundo a lógica humana, que a situação era desesperadora e sem saída. O medo é a resposta natural quando focamos apenas no que os nossos olhos físicos podem ver.',
    desc2: 'A resposta de Eliseu é de uma calma sobrenatural: "Não temas; porque mais são os que estão conosco do que os que estão com eles". Para o servo, essa afirmação devia parecer loucura. Onde estava esse exército maior? Eliseu não tenta explicar a situação com lógica militar; ele faz uma oração simples, mas profunda: "Senhor, peço-te que lhe abras os olhos, para que veja". Eliseu não orou para que Deus enviasse um exército (o exército já estava lá); ele orou para que o servo pudesse ver a realidade espiritual que já existia. Quando o Senhor abre os olhos do jovem, ele vê o monte "cheio de cavalos e carros de fogo, em redor de Eliseu". A proteção de Deus era infinitamente superior à ameaça síria.',
    desc3: 'Quando os sírios descem para atacar, Eliseu ora novamente, pedindo que Deus os fira de cegueira (uma confusão mental, não cegueira física total). Eliseu então guia o exército inimigo cego até Samaria, a capital de Israel, entregando-os nas mãos do rei israelita. O rei de Israel, vendo os inimigos vulneráveis, pergunta se deve matá-los. Eliseu proíbe a matança e ordena: "Põe-lhes diante pão e água, para que comam e bebam, e se vão para seu senhor". O profeta vence a guerra não com a espada, mas com um banquete de graça. Os sírios voltam para casa humilhados pela misericórdia, e as incursões cessam.',
    concl: 'A história de Dotã nos ensina que a realidade espiritual é muito maior e mais poderosa do que a realidade física que nos assusta. Quando nos sentimos cercados por problemas, inimigos ou crises, não precisamos entrar em pânico. Precisamos orar para que Deus abra os nossos olhos espirituais, para vermos que os "carros de fogo" do Senhor estão sempre ao redor daqueles que O temem.'
  },
  {
    id: 'psa_103_1_22',
    intro: 'O Salmo 103, escrito por Davi, é um dos hinos de louvor mais puros, abrangentes e apaixonados de toda a Bíblia. Diferente de muitos outros salmos, este não contém nenhuma petição, nenhum lamento e nenhuma menção a inimigos. É uma explosão ininterrupta de gratidão e adoração. Davi começa pregando para si mesmo, convocando a sua própria alma a não sofrer de amnésia espiritual, mas a lembrar ativamente de todos os benefícios de Deus. O salmo é um catálogo teológico da graça, listando a compaixão inesgotável, o perdão total e o amor paternal de Deus para com a humanidade frágil e pecadora.',
    desc1: 'O salmo começa com um auto-comando: "Bendize, ó minha alma, ao Senhor, e tudo o que há em mim bendiga o seu santo nome". A adoração verdadeira não é apenas um exercício labial, mas exige o envolvimento de "tudo o que há em mim" (intelecto, emoções, vontade). Davi adverte contra o maior perigo da vida cristã: "e não te esqueças de nenhum de seus benefícios". O esquecimento gera murmuração; a lembrança gera louvor. Ele então lista os benefícios pessoais: Ele perdoa todas as iniquidades, sara todas as enfermidades, redime a vida da perdição, coroa com benignidade e misericórdia, e farta a boca de bens, renovando a juventude como a da águia.',
    desc2: 'A partir do versículo 6, Davi expande o foco da sua experiência pessoal para o caráter de Deus revelado na história de Israel (especialmente a Moisés). Ele descreve Deus como "misericordioso e piedoso, tardio em irar-se e grande em benignidade". Deus não lida conosco segundo os nossos pecados, nem nos retribui segundo as nossas iniquidades. Para ilustrar a magnitude do perdão divino, Davi usa as maiores distâncias concebíveis no universo físico: "Pois quanto o céu está elevado acima da terra, assim é grande a sua misericórdia... Quanto está longe o oriente do ocidente, assim afasta de nós as nossas transgressões". O perdão de Deus é infinito e definitivo.',
    desc3: 'Davi então usa a metáfora mais terna do salmo: "Como um pai se compadece de seus filhos, assim o Senhor se compadece daqueles que o temem". A compaixão de Deus não é baseada na nossa força, mas na nossa fraqueza: "Pois ele conhece a nossa estrutura; lembra-se de que somos pó". A vida humana é frágil e passageira como a erva e a flor do campo, que o vento sopra e desaparece. Mas, em contraste com a nossa fragilidade temporal, "a misericórdia do Senhor é desde a eternidade e até a eternidade sobre aqueles que o temem". O salmo termina convocando todo o universo (anjos, exércitos celestiais e todas as obras da criação) a se juntarem a ele em um grande coro de louvor.',
    concl: 'O Salmo 103 é o antídoto perfeito para a depressão espiritual e a ingratidão. Quando a nossa alma estiver abatida, devemos pregar para nós mesmos, lembrando intencionalmente do perdão infinito, da cura, da redenção e do amor paternal de Deus, que nos trata não como merecemos, mas segundo a grandeza da Sua misericórdia.'
  },
  {
    id: 'isa_43_1_7',
    intro: 'O início do capítulo 43 de Isaías contém uma das promessas de proteção e pertencimento mais reconfortantes, pessoais e poderosas de todo o Antigo Testamento. O povo de Israel estava enfrentando a perspectiva aterrorizante do exílio na Babilônia, sentindo-se abandonado, destruído e sem valor. É nesse contexto de medo e incerteza que Deus fala através do profeta, não para prometer que o sofrimento não viria, mas para garantir a Sua presença inabalável no meio do sofrimento. Este texto revela o coração de um Deus redentor que conhece o Seu povo pelo nome, que pagou um alto preço por eles e que os protegerá através dos elementos mais destrutivos da natureza.',
    desc1: 'A passagem começa com uma declaração de propriedade baseada na criação e na redenção: "Mas agora, assim diz o Senhor que te criou, ó Jacó, e que te formou, ó Israel: Não temas, porque eu te remi; chamei-te pelo teu nome, tu és meu". O antídoto para o medo ("não temas") não é a autoconfiança, mas a certeza de pertencimento ("tu és meu"). Deus não nos vê como uma massa anônima; Ele nos chama pelo nome. A palavra "remi" (redimir) significa comprar de volta, pagar um resgate. Nós pertencemos a Deus duas vezes: porque Ele nos fez (criação) e porque Ele nos comprou de volta do pecado (redenção).',
    desc2: 'O versículo 2 é o coração da promessa: "Quando passares pelas águas estarei contigo, e quando pelos rios, eles não te submergirão; quando passares pelo fogo, não te queimarás, nem a chama arderá em ti". Deus não promete um desvio ao redor das águas profundas ou um escudo contra o fogo das provações. A promessa não é a isenção do sofrimento, mas a preservação dentro dele. As águas (símbolo de caos e afogamento) e o fogo (símbolo de destruição e purificação) são inevitáveis na vida cristã. No entanto, a presença de Deus ("estarei contigo") garante que as provações não terão a palavra final; elas não nos submergirão nem nos consumirão.',
    desc3: 'Deus fundamenta essa promessa de proteção no Seu próprio caráter e no valor que Ele atribui ao Seu povo: "Porque eu sou o Senhor teu Deus, o Santo de Israel, o teu Salvador". Ele declara que deu o Egito, a Etiópia e Sebá como resgate por Israel. O versículo 4 contém uma das declarações de amor mais impressionantes da Bíblia: "Visto que foste precioso aos meus olhos, também foste honrado, e eu te amei". Aos olhos do mundo, Israel era uma nação derrotada e escravizada, mas aos olhos de Deus, eles eram preciosos e honrados. Deus conclui prometendo reunir os Seus filhos de todos os cantos da terra (oriente, ocidente, norte e sul), garantindo que nenhum daqueles que foram criados para a Sua glória será perdido.',
    concl: 'Isaías 43 nos garante que a nossa segurança não reside na ausência de tempestades ou fornalhas, mas na presença do nosso Redentor. Quando sabemos que fomos comprados por um alto preço, chamados pelo nome e amados profundamente por Deus, podemos atravessar qualquer rio de dificuldade e qualquer fogo de provação com a certeza de que não seremos destruídos.'
  },
  {
    id: 'mat_25_14_30',
    intro: 'A Parábola dos Talentos, contada por Jesus no Seu discurso escatológico no Monte das Oliveiras, é uma das ilustrações mais claras sobre a mordomia cristã e a responsabilidade que temos diante de Deus. Jesus compara o Reino dos Céus a um homem rico que, prestes a viajar para longe, confia os seus bens aos seus servos. A parábola não é sobre como ganhar a salvação (que é pela graça), mas sobre como devemos viver e administrar os recursos que Deus nos deu enquanto aguardamos o retorno do Rei. Ela destrói a ideia de que a vida cristã é apenas esperar passivamente pelo céu, ensinando que somos chamados a ser investidores ativos e produtivos no Reino de Deus.',
    desc1: 'O senhor distribui os seus bens de forma desigual, mas justa: "A um deu cinco talentos, a outro dois, e a outro um, a cada um segundo a sua capacidade". Um "talento" não era uma moeda pequena, mas uma medida de peso (geralmente de prata ou ouro) equivalente a cerca de vinte anos de salário de um trabalhador comum. Deus nos confia recursos imensos (tempo, dinheiro, habilidades, dons espirituais, o Evangelho). A distribuição desigual não é injustiça, mas sabedoria divina baseada na capacidade de cada um. Deus não exige que produzamos o que não nos foi dado, mas exige fidelidade com o que temos.',
    desc2: 'Os dois primeiros servos agem imediatamente: "E, tendo ele partido, o que recebera cinco talentos negociou com eles, e granjeou outros cinco talentos. Da mesma sorte, o que recebera dois, granjeou também outros dois". Eles entenderam que o dinheiro não era deles, mas do senhor, e assumiram o risco de investir para o crescimento do reino do seu mestre. O terceiro servo, no entanto, dominado pelo medo e por uma visão distorcida do seu senhor, "cavou na terra e escondeu o dinheiro do seu senhor". Ele não roubou nem desperdiçou o talento em vícios (como o filho pródigo); o seu pecado foi a omissão, a inércia e a recusa em usar o dom para o propósito a que se destinava.',
    desc3: 'Após muito tempo, o senhor retorna para o acerto de contas. Os dois primeiros servos apresentam o lucro e recebem exatamente o mesmo elogio e recompensa: "Bem está, servo bom e fiel. Sobre o pouco foste fiel, sobre muito te colocarei; entra no gozo do teu senhor". A recompensa pela fidelidade não é a aposentadoria, mas maior responsabilidade e intimidade com o mestre. O terceiro servo tenta se justificar culpando o caráter do senhor ("conhecendo que és homem duro... tive medo"). O senhor o condena não por ter apenas um talento, mas por ser "mau e negligente". Ele perde o que tinha, que é dado ao que tem dez, e é lançado nas trevas exteriores. A inércia espiritual é tratada como rebelião.',
    concl: 'A parábola dos talentos nos adverte que não somos donos de nada, mas administradores de tudo o que Deus nos deu. O maior risco na vida cristã não é tentar fazer algo para Deus e falhar, mas ter tanto medo de falhar que acabamos enterrando os nossos dons e não fazendo nada. Um dia prestaremos contas, e o nosso maior desejo deve ser ouvir: "Bem está, servo bom e fiel".'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 23');
