const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'psa_46_1_11',
    intro: 'O Salmo 46 é um hino majestoso de confiança inabalável na soberania e na proteção de Deus. Ele foi a inspiração direta para Martinho Lutero compor o famoso hino "Castelo Forte é o Nosso Deus", que se tornou o hino de batalha da Reforma Protestante. O salmo é estruturado em três estrofes, cada uma descrevendo um cenário de caos crescente: o caos na natureza (terremotos e tsunamis), o caos nas nações (guerras e tumultos políticos) e a resposta final de Deus a todo esse caos. A mensagem central é que, mesmo quando os fundamentos do mundo visível parecem estar desmoronando, o povo de Deus tem uma segurança invisível e indestrutível no próprio Criador.',
    desc1: 'A primeira estrofe (v. 1-3) estabelece a tese do salmo: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia". Deus não é um refúgio distante ou teórico, mas "bem presente" (literalmente, "abundantemente encontrado") no momento exato da crise. Por causa dessa realidade, o salmista faz uma declaração de coragem radical: "Portanto não temeremos, ainda que a terra se mude, e ainda que os montes se transportem para o meio dos mares". A terra e os montes representam as coisas mais estáveis e permanentes da criação. O salmista diz que, mesmo que o mundo natural entre em colapso total (terremotos, tsunamis, águas que rugem), o crente não precisa entrar em pânico, pois a sua segurança não está na estabilidade da terra, mas na estabilidade do Criador.',
    desc2: 'A segunda estrofe (v. 4-7) muda o cenário do mar revolto para uma cidade pacífica: "Há um rio cujas correntes alegram a cidade de Deus, o santuário das moradas do Altíssimo". Jerusalém não tinha um rio natural (apenas a fonte de Giom), mas o "rio" aqui é uma metáfora da presença contínua, silenciosa e vivificadora de Deus (em contraste com as águas barulhentas e destrutivas do mar). A segurança da cidade não está nas suas muralhas, mas no seu Hóspede: "Deus está no meio dela; não se abalará". Enquanto as nações se enfurecem e os reinos se movem (caos político e militar), Deus apenas "levanta a sua voz, e a terra se derrete". Uma única palavra de Deus é suficiente para dissolver a fúria dos impérios.',
    desc3: 'A terceira estrofe (v. 8-11) é um convite para contemplar a vitória final de Deus: "Vinde, contemplai as obras do Senhor; que desolações tem feito na terra". Deus é o Senhor da guerra e da paz. Ele "faz cessar as guerras até ao fim da terra; quebra o arco e corta a lança; queima os carros no fogo". O clímax do salmo é o imperativo divino no versículo 10: "Aquietai-vos, e sabei que eu sou Deus". A palavra "aquietai-vos" (raphah) significa literalmente "soltar, relaxar, parar de lutar". Em meio ao pânico global, Deus ordena que o Seu povo pare de tentar controlar o incontrolável e reconheça a Sua exaltação soberana sobre todas as nações.',
    concl: 'O Salmo 46 nos ensina que a paz verdadeira não é a ausência de tempestades naturais ou de crises políticas, mas a presença do "Senhor dos Exércitos" conosco. Quando o mundo ao nosso redor treme, somos chamados a soltar as nossas ansiedades e a descansar na certeza de que o nosso Deus é um castelo forte que jamais será abalado.'
  },
  {
    id: 'isa_6_1_13',
    intro: 'O capítulo 6 de Isaías narra a visão e o chamado do profeta em um momento de profunda crise nacional. O texto começa com um marcador histórico significativo: "No ano em que morreu o rei Uzias". Uzias havia reinado por 52 anos, trazendo estabilidade, prosperidade e poder militar a Judá. Para a maioria dos israelitas, Uzias era o único rei que eles haviam conhecido. A sua morte repentina (após ser ferido com lepra por orgulho) deixou a nação em um estado de choque, luto e incerteza política, com a ameaça do Império Assírio crescendo no horizonte. É exatamente quando o trono terreno fica vazio que Deus abre os olhos de Isaías para ver o verdadeiro Rei, cujo trono nunca fica vazio e cujo reinado nunca tem fim.',
    desc1: 'A visão de Isaías é de uma majestade esmagadora: "eu vi também ao Senhor assentado sobre um alto e sublime trono; e o seu séquito (a orla do seu manto) enchia o templo". O trono de Deus não estava abalado pela crise em Judá. Acima do trono, serafins (anjos cujo nome significa "os ardentes") voavam. Eles tinham seis asas: com duas cobriam o rosto (reverência diante da glória de Deus), com duas cobriam os pés (humildade) e com duas voavam (prontidão para o serviço). Eles clamavam uns aos outros: "Santo, Santo, Santo é o Senhor dos Exércitos; toda a terra está cheia da sua glória". A santidade de Deus (a Sua total separação do pecado e a Sua perfeição moral absoluta) é o atributo mais enfatizado na visão, fazendo tremer os umbrais do templo.',
    desc2: 'A reação de Isaías diante da santidade de Deus não é de fascínio, mas de terror moral. Ele não diz "Que visão linda!", mas grita: "Ai de mim! Pois estou perdido; porque sou um homem de lábios impuros, e habito no meio de um povo de impuros lábios; os meus olhos viram o Rei, o Senhor dos Exércitos". A visão da santidade de Deus sempre expõe a nossa própria corrupção. Isaías, o profeta, percebe que os seus lábios (o seu instrumento de trabalho) estão contaminados. Imediatamente, um dos serafins voa com uma brasa viva tirada do altar (o lugar do sacrifício) e toca a boca de Isaías, declarando: "a tua iniquidade foi tirada, e expiado o teu pecado". A purificação não vem do esforço humano, mas do fogo do altar de Deus.',
    desc3: 'Somente após a purificação é que Isaías ouve a voz de Deus perguntando: "A quem enviarei, e quem há de ir por nós?". A Trindade delibera sobre a missão. A resposta de Isaías é imediata e incondicional: "Eis-me aqui, envia-me a mim". Ele não pergunta o salário, as condições de trabalho ou o destino; a graça purificadora produz obediência voluntária. A missão que Deus lhe dá, no entanto, é dura: pregar a um povo que ouvirá, mas não entenderá; que verá, mas não perceberá. O ministério de Isaías endureceria o coração do povo para o juízo (o exílio), mas Deus promete que um "santo germe" (um remanescente fiel) sobreviveria como o toco de uma árvore cortada.',
    concl: 'A visão de Isaías nos ensina que não podemos servir a Deus adequadamente até que vejamos a Sua santidade, reconheçamos a nossa própria impureza e experimentemos o fogo purificador do Seu perdão. Quando os nossos "reis Uzias" (as nossas seguranças terrenas) morrem, Deus nos convida a olhar para cima e ver que o Senhor dos Exércitos continua no controle absoluto do universo.'
  },
  {
    id: 'mat_8_5_13',
    intro: 'A cura do servo do centurião em Cafarnaum é um dos episódios mais surpreendentes do ministério de Jesus, pois quebra todas as barreiras culturais, religiosas e raciais da época. Um centurião era um oficial do exército romano, comandando cerca de cem soldados. Para os judeus, ele era o símbolo vivo da opressão imperial, um gentio impuro e um inimigo da nação. No entanto, este homem aproxima-se de Jesus não com a arrogância de um conquistador, mas com a humildade de um suplicante, intercedendo não por um filho ou um superior, mas por um simples escravo. A atitude deste soldado romano não apenas resulta em um milagre à distância, mas arranca de Jesus a maior declaração de admiração registrada nos Evangelhos.',
    desc1: 'O centurião roga a Jesus dizendo: "Senhor, o meu criado jaz em casa, paralítico, e violentamente atormentado". A compaixão do centurião pelo seu escravo já era algo incomum no Império Romano (onde escravos doentes eram frequentemente descartados). Jesus responde imediatamente: "Eu irei, e lhe darei saúde". A disposição de Jesus de entrar na casa de um gentio (o que O tornaria cerimonialmente impuro segundo a tradição judaica) demonstra que a graça de Deus não conhece fronteiras. No entanto, a resposta do centurião interrompe Jesus e revela uma compreensão teológica profunda: "Senhor, não sou digno de que entres debaixo do meu telhado". Ele reconhece a sua própria indignidade diante da santidade de Cristo.',
    desc2: 'O centurião então apresenta a sua lógica militar aplicada à fé: "mas dize somente uma palavra, e o meu criado há de sarar". Ele explica: "Pois também eu sou homem sob autoridade, e tenho soldados às minhas ordens; e digo a este: Vai, e ele vai... e ao meu criado: Faze isto, e ele o faz". O centurião entende perfeitamente o conceito de autoridade delegada. Ele sabe que a sua palavra tem poder porque ele está sob a autoridade de Roma. Ele reconhece que Jesus está sob a autoridade do Deus Altíssimo e, portanto, o poder de Jesus sobre a doença não depende da Sua presença física. Uma única palavra de Jesus, emitida com autoridade divina, era suficiente para curar à distância.',
    desc3: 'A reação de Jesus é extraordinária: "E maravilhou-se Jesus". Em todos os Evangelhos, Jesus só se maravilha duas vezes: com a incredulidade dos judeus em Nazaré (Marcos 6:6) e com a fé deste gentio em Cafarnaum. Jesus declara à multidão: "Em verdade vos digo que nem mesmo em Israel encontrei tanta fé". Jesus usa a fé do centurião para profetizar a entrada dos gentios no Reino de Deus: muitos virão do Oriente e do Ocidente para se assentarem à mesa com Abraão, Isaque e Jacó, enquanto os "filhos do reino" (os judeus incrédulos) serão lançados nas trevas exteriores. Jesus então diz ao centurião: "Vai, e como creste te seja feito". E na mesma hora o servo foi curado.',
    concl: 'A fé do centurião nos ensina que a verdadeira fé não exige sinais visíveis, rituais ou a presença física de Deus. A verdadeira fé é a confiança absoluta na autoridade e no poder da Palavra de Cristo. Quando reconhecemos a nossa indignidade e confiamos que uma única palavra dEle é suficiente para resolver a nossa crise, nós maravilhamos o coração de Deus.'
  },
  {
    id: 'exo_20_1_17',
    intro: 'O capítulo 20 de Êxodo registra a entrega dos Dez Mandamentos (o Decálogo) no Monte Sinai, o documento fundacional da aliança entre Deus e Israel. Frequentemente, os Dez Mandamentos são mal compreendidos como um conjunto de regras opressivas e arbitrárias criadas para limitar a liberdade humana. No entanto, o contexto histórico prova exatamente o contrário. Deus não deu a Lei a um povo livre para escravizá-lo; Ele deu a Lei a um povo recém-liberto da escravidão para ensiná-lo a viver em liberdade. Os Dez Mandamentos são o "manual do fabricante" para a vida humana, revelando o caráter santo de Deus e estabelecendo os limites necessários para que o amor a Deus e ao próximo floresçam em uma sociedade justa.',
    desc1: 'O prefácio do Decálogo (v. 2) é a chave hermenêutica para entender todos os mandamentos: "Eu sou o Senhor teu Deus, que te tirei da terra do Egito, da casa da servidão". A graça e a redenção precedem a Lei. Deus não diz: "Obedeçam a estas regras e eu os libertarei". Ele diz: "Eu já os libertei pela minha graça; agora, vivam desta maneira". A obediência bíblica nunca é a raiz da salvação, mas sempre o fruto da gratidão pela salvação já recebida. Os primeiros quatro mandamentos focam no nosso relacionamento vertical com Deus: exclusividade (não ter outros deuses), adoração correta (não fazer imagens de escultura, pois Deus não pode ser reduzido à criação), reverência (não tomar o nome do Senhor em vão) e tempo sagrado (lembrar o dia de sábado para santificá-lo, reconhecendo Deus como Criador e Provedor).',
    desc2: 'Os últimos seis mandamentos focam no nosso relacionamento horizontal com o próximo. Eles formam a base dos direitos humanos e da justiça social. O quinto mandamento (honrar pai e mãe) é a ponte entre os deveres para com Deus e os deveres para com os homens, estabelecendo o respeito à autoridade delegada e à família. Os mandamentos seguintes protegem a vida ("Não matarás"), o casamento e a pureza sexual ("Não adulterarás"), a propriedade ("Não furtarás") e a verdade e a reputação do próximo ("Não dirás falso testemunho"). A quebra de qualquer um desses mandamentos destrói o tecido da sociedade e causa dor profunda.',
    desc3: 'O décimo mandamento é único e revolucionário: "Não cobiçarás". Enquanto os outros nove mandamentos lidam principalmente com ações e palavras externas (que podem ser julgadas por tribunais humanos), o décimo mandamento atinge o coração, os desejos e as motivações invisíveis. A cobiça (o desejo insaciável pelo que pertence a outro) é a raiz invisível que produz o furto, o adultério e o assassinato. A Lei de Deus não se contenta com a conformidade externa; ela exige a pureza interna. O apóstolo Paulo usou exatamente este mandamento para perceber a sua própria pecaminosidade (Romanos 7:7), provando que a Lei serve como um espelho que revela o nosso pecado e nos conduz à necessidade da graça de Cristo.',
    concl: 'Os Dez Mandamentos não são uma escada pela qual subimos para alcançar o céu, mas os trilhos sobre os quais o trem da nossa vida deve correr para não descarrilar. Eles revelam a santidade de Deus, expõem a nossa incapacidade de sermos perfeitos e nos apontam para Jesus Cristo, o único que cumpriu a Lei perfeitamente em nosso lugar.'
  },
  {
    id: 'num_13_25_33',
    intro: 'O relato dos doze espias em Números 13 é uma das histórias mais trágicas sobre as consequências da incredulidade. Israel estava em Cades-Barneia, na fronteira sul da Terra Prometida. Deus ordena a Moisés que envie doze líderes (um de cada tribo) para espiar a terra de Canaã. Após quarenta dias de exploração, eles retornam com os frutos da terra (um cacho de uvas tão grande que precisou ser carregado por dois homens). No entanto, o relatório que eles apresentam divide a nação e sela o destino de toda uma geração. A história revela que a fé e a incredulidade podem olhar para a mesma realidade, os mesmos fatos e os mesmos obstáculos, mas chegar a conclusões completamente opostas.',
    desc1: 'O relatório começa com um consenso sobre os fatos: "Fomos à terra a que nos enviaste; e verdadeiramente mana leite e mel, e este é o seu fruto". Todos os doze espias concordam que a promessa de Deus sobre a bondade da terra era absolutamente verdadeira. No entanto, dez dos espias introduzem a palavra que destrói a fé: "O povo, porém, que habita nessa terra é poderoso, e as cidades fortificadas e mui grandes; e também ali vimos os filhos de Anaque (gigantes)". Eles viram os gigantes e as muralhas, e permitiram que os obstáculos ofuscassem a promessa. A incredulidade não nega os fatos, mas os interpreta sem levar Deus em consideração.',
    desc2: 'Calebe, um dos dois espias fiéis (junto com Josué), tenta acalmar o povo e apresenta a perspectiva da fé: "Subamos animosamente, e possuamo-la em herança; porque certamente prevaleceremos contra ela". Calebe não nega a existência dos gigantes, mas ele mede os gigantes em relação ao tamanho de Deus, não em relação ao seu próprio tamanho. A fé não é cegueira para as dificuldades; é a convicção de que Deus é maior do que qualquer dificuldade. Mas os dez espias incrédulos rebatem com pânico e exagero: "Não poderemos subir contra aquele povo, porque é mais forte do que nós". Eles espalham um "infame relatório" (fake news espiritual), dizendo que a terra devorava os seus moradores.',
    desc3: 'O clímax da incredulidade dos dez espias é revelado na sua autoimagem distorcida: "Também vimos ali gigantes... e éramos aos nossos olhos como gafanhotos, e assim também éramos aos seus olhos". O medo sempre distorce a nossa visão. Quando tiramos os olhos de Deus, os nossos problemas se tornam gigantes e nós nos sentimos como insetos esmagáveis. A tragédia é que os dez espias convenceram toda a congregação. O povo chorou a noite toda, rebelou-se contra Moisés e tentou eleger um novo líder para voltar para a escravidão no Egito. Como resultado desse pecado de incredulidade, Deus sentenciou toda aquela geração a vagar e morrer no deserto por quarenta anos.',
    concl: 'A história dos doze espias nos adverte que a maioria nem sempre tem razão, especialmente em questões espirituais. Quando enfrentamos os "gigantes" da vida, temos uma escolha: podemos olhar para eles através das lentes do medo e nos sentirmos como gafanhotos, ou podemos olhar para eles através das lentes das promessas de Deus e dizer com Calebe: "Certamente prevaleceremos".'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 22');
