const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'mt_6_25_34',
    intro: 'No coração do Sermão do Monte, Jesus aborda a ansiedade, uma das doenças mais antigas e universais da alma humana. A ansiedade não é apenas um problema psicológico; para Jesus, é fundamentalmente um problema teológico. Ela revela uma crise de fé e uma visão distorcida do caráter de Deus. Jesus nos ensina que a preocupação com o futuro (o que comeremos, o que beberemos, com que nos vestiremos) é uma característica dos gentios (aqueles que não conhecem a Deus). A cura para a ansiedade não é a apatia ou a irresponsabilidade, mas a substituição do medo pela confiança absoluta no cuidado de um Pai celestial amoroso e soberano.',
    desc1: 'Jesus começa com um imperativo claro: "Não andeis cuidadosos (ansiosos) quanto à vossa vida". Ele usa dois argumentos da natureza para provar a irracionalidade da ansiedade. Primeiro, Ele aponta para as aves do céu: elas não semeiam, não colhem e não armazenam em celeiros, mas o Pai celestial as alimenta. Segundo, Ele aponta para os lírios do campo: eles não trabalham nem fiam, mas nem Salomão em toda a sua glória se vestiu como eles. O argumento é do menor para o maior: se Deus cuida com tanto zelo das aves e das flores (que são temporárias e não têm alma), "não vos vestirá muito mais a vós, homens de pouca fé?". A ansiedade é essencialmente uma amnésia sobre o valor que temos para Deus.',
    desc2: 'Jesus expõe a total inutilidade da ansiedade: "E qual de vós poderá, com todos os seus cuidados, acrescentar um côvado à sua estatura (ou um momento à sua vida)?". A preocupação não pode mudar o passado nem controlar o futuro; ela apenas rouba a paz do presente. A ansiedade é tentar carregar o fardo do amanhã com a força de hoje. Jesus diz que o nosso Pai celestial "bem sabe" que precisamos de todas essas coisas. A paz não vem da ausência de necessidades, mas da certeza de que o nosso Pai conhece cada uma delas e tem o poder para supri-las no tempo certo.',
    desc3: 'A solução de Jesus para a ansiedade é uma mudança radical de prioridades: "Mas, buscai primeiro o reino de Deus, e a sua justiça, e todas estas coisas vos serão acrescentadas". A ansiedade surge quando colocamos as "coisas" (sobrevivência, conforto, status) no centro da nossa vida. Quando o Reino de Deus se torna a nossa obsessão e a nossa prioridade absoluta, as outras coisas assumem o seu lugar correto como acréscimos divinos. Jesus conclui com um conselho prático: "Não vos inquieteis, pois, pelo dia de amanhã... Basta a cada dia o seu mal". Deus nos dá graça diária para os problemas diários.',
    concl: 'A ansiedade é o resultado de tentarmos ser os deuses das nossas próprias vidas, controlando o incontrolável. A liberdade vem quando abdicamos do controle, buscamos o Reino de Deus acima de tudo e descansamos na promessa de que o nosso Pai celestial cuidará de todas as nossas necessidades.'
  },
  {
    id: 'luk_15_11_32',
    intro: 'A Parábola do Filho Pródigo (ou dos Dois Filhos Perdidos) é a mais longa, famosa e profunda das parábolas de Jesus. Ela é o clímax do capítulo 15 de Lucas, contada em resposta à murmuração dos fariseus e escribas contra Jesus por Ele receber e comer com pecadores. Esta parábola não é apenas sobre o arrependimento de um pecador rebelde; é uma revelação chocante sobre o coração extravagante, escandaloso e perdoador de Deus Pai. A história expõe as duas maneiras pelas quais a humanidade se afasta de Deus: através da rebelião escancarada (o filho mais novo) e através da religiosidade orgulhosa e moralista (o filho mais velho).',
    desc1: 'A história começa com a rebelião do filho mais novo, que pede a sua parte da herança enquanto o pai ainda está vivo (o equivalente a dizer: "Pai, eu quero o seu dinheiro, mas desejo que você estivesse morto"). O pai, respeitando a liberdade do filho, divide os bens. O filho parte para uma província distante e desperdício tudo vivendo dissolutamente. A ilusão do pecado é que ele promete liberdade, mas sempre entrega escravidão. Quando os recursos acabam e uma grande fome atinge a terra, ele acaba apascentando porcos (a maior degradação para um judeu) e desejando comer as bolotas dos animais. O pecado nos leva mais longe do que queríamos ir e nos custa mais do que queríamos pagar.',
    desc2: 'No fundo do poço, o filho "cai em si". O arrependimento começa com a lembrança da bondade do pai: "Quantos jornaleiros de meu pai têm abundância de pão, e eu aqui pereço de fome!". Ele ensaia um discurso de arrependimento, pedindo para ser tratado como um servo. Mas a reação do pai quebra todos os protocolos culturais. O pai o vê de longe (provando que o esperava todos os dias), enche-se de íntima compaixão, corre (um ato humilhante para um patriarca oriental), lança-se ao seu pescoço e o beija. O pai não o deixa terminar o discurso de servo; ele ordena que lhe tragam a melhor veste (justiça), o anel (autoridade) e as alparcas (filiação), e prepara um banquete. A graça de Deus não nos restaura à condição de escravos, mas à dignidade de filhos.',
    desc3: 'A parábola, no entanto, não termina com a festa, mas com a tragédia do filho mais velho. Ao ouvir a música, ele se recusa a entrar. O pai sai para implorar a ele também. A resposta do filho mais velho revela o seu coração: "Eis que te sirvo há tantos anos, sem nunca transgredir o teu mandamento, e nunca me deste um cabrito para alegrar-me com os meus amigos". Ele era obediente por fora, mas o seu coração estava tão longe do pai quanto o do irmão mais novo. Ele via o pai como um patrão a ser aplacado pelas suas boas obras, não como um pai a ser amado. A religiosidade moralista nos cega para a graça e nos enche de ressentimento contra a misericórdia de Deus para com os outros.',
    concl: 'A parábola nos ensina que podemos estar perdidos tanto na "província distante" do pecado escancarado quanto dentro da "casa do pai" através da religiosidade orgulhosa. O coração de Deus, no entanto, sai ao encontro de ambos, oferecendo a festa da graça para o rebelde arrependido e implorando ao religioso que abandone o seu orgulho e entre na alegria do perdão.'
  },
  {
    id: 'jhn_15_1_11',
    intro: 'O discurso da Videira Verdadeira ocorre nas horas finais de Jesus com os Seus discípulos, pouco antes da Sua prisão e crucificação. Caminhando talvez pelos vinhedos ao redor de Jerusalém, Jesus usa uma das metáforas mais ricas do Antigo Testamento (Israel era frequentemente comparado a uma videira que falhou em dar bons frutos) para revelar o segredo da vida cristã autêntica. Jesus declara: "Eu sou a videira verdadeira, e meu Pai é o lavrador". Esta passagem destrói a ilusão do esforço humano independente e estabelece que a santificação, a alegria e a frutificação espiritual são resultados exclusivos de uma conexão vital, contínua e íntima com Cristo.',
    desc1: 'A metáfora estabelece três papéis claros: Jesus é a videira (a fonte de vida), o Pai é o lavrador (aquele que cuida e disciplina) e nós somos as varas (os ramos). O objetivo do lavrador é que a videira dê fruto. Para isso, Ele realiza duas ações: "Toda a vara em mim, que não dá fruto, a tira; e limpa (poda) toda aquela que dá fruto, para que dê mais fruto". A poda é dolorosa, mas é a prova do amor e do cuidado do Pai. Deus frequentemente corta da nossa vida os excessos, as distrações, os pecados de estimação e até coisas boas, para que possamos focar a nossa energia espiritual em produzir o fruto que permanece.',
    desc2: 'O imperativo central do texto é repetido várias vezes: "Estai em mim, e eu em vós". A palavra "estar" (ou permanecer) significa manter uma comunhão constante e ininterrupta com Cristo através da oração, da obediência e da meditação na Sua Palavra. Jesus é categórico sobre a nossa incapacidade: "Como a vara de si mesma não pode dar fruto, se não estiver na videira, assim também vós, se não estiverdes em mim... porque sem mim nada podeis fazer". O ativismo religioso sem intimidade com Cristo é estéril. Não fomos chamados para produzir frutos pelo nosso próprio esforço, mas para permanecer na videira e deixar que a seiva do Espírito Santo produza o fruto através de nós.',
    desc3: 'Os resultados de permanecer na videira são extraordinários. Primeiro, a oração respondida: "Se vós estiverdes em mim, e as minhas palavras estiverem em vós, pedireis tudo o que quiserdes, e vos será feito" (porque os nossos desejos estarão alinhados com a vontade dEle). Segundo, a glória de Deus: "Nisto é glorificado meu Pai, que deis muito fruto". Terceiro, a alegria transbordante: "Tenho-vos dito isto, para que o meu gozo permaneça em vós, e o vosso gozo seja completo". A verdadeira alegria não é encontrada na busca pelo sucesso ou no ativismo exaustivo, mas na intimidade profunda com o Salvador.',
    concl: 'A vida cristã não é uma lista de regras a serem cumpridas com a nossa própria força, mas um relacionamento vital a ser cultivado. Quando aceitamos a poda do Pai e escolhemos permanecer diariamente em Cristo, a frutificação e a alegria tornam-se as consequências naturais e inevitáveis da nossa união com Ele.'
  },
  {
    id: '1co_13_1_13',
    intro: 'O capítulo 13 de 1 Coríntios, conhecido como o "Hino ao Amor", é um dos textos mais belos e profundos de toda a literatura mundial. No entanto, ele não foi escrito como um poema romântico para ser lido em casamentos, mas como uma repreensão cirúrgica a uma igreja dividida, carnal e orgulhosa. A igreja de Corinto era rica em dons espirituais (línguas, profecias, curas), mas era pobre em caráter. Eles usavam os dons para competir e se exaltar. Paulo interrompe a sua discussão sobre os dons espirituais (capítulos 12 e 14) para mostrar "um caminho ainda mais excelente". Ele prova que qualquer dom, ministério, conhecimento ou sacrifício, se não for motivado e governado pelo amor (ágape), é absolutamente inútil diante de Deus.',
    desc1: 'Paulo começa com uma série de hipóteses extremas para demonstrar a supremacia do amor. Ele diz que mesmo que falasse as línguas dos homens e dos anjos, se não tivesse amor, seria apenas um barulho irritante (o metal que soa ou o sino que tine). Mesmo que tivesse o dom de profecia, conhecesse todos os mistérios e tivesse uma fé capaz de mover montanhas, sem amor, ele "nada seria". O golpe final atinge o sacrifício extremo: mesmo que ele desse todos os seus bens aos pobres e entregasse o seu corpo para ser queimado (martírio), sem amor, isso "nada me aproveitaria". Deus não mede o nosso valor pelo tamanho do nosso ministério, mas pela pureza da nossa motivação.',
    desc2: 'Em seguida, Paulo personifica o amor, descrevendo-o não como um sentimento passivo, mas como uma série de ações e escolhas. O amor ágape é paciente e benigno (bondoso). Ele não é invejoso, não se vangloria, não se ensoberbece, não se porta com indecência, não busca os seus próprios interesses, não se irrita facilmente e não suspeita mal. O amor não se alegra com a injustiça (mesmo quando ela atinge um inimigo), mas folga com a verdade. O amor "tudo sofre, tudo crê, tudo espera, tudo suporta". Esta é a descrição exata do caráter de Jesus Cristo. O amor é a santidade em ação nos relacionamentos.',
    desc3: 'Paulo conclui contrastando a temporalidade dos dons com a eternidade do amor. "O amor nunca falha". As profecias serão aniquiladas, as línguas cessarão e o conhecimento desaparecerá, porque eles são apenas ferramentas temporárias para a nossa condição imperfeita ("porque em parte conhecemos"). Quando vier o que é perfeito (a eternidade com Cristo), os dons não serão mais necessários. Paulo compara o nosso estado atual com a infância e a visão embaçada de um espelho de bronze. Na eternidade, veremos face a face. "Agora, pois, permanecem a fé, a esperança e o amor, estes três, mas o maior destes é o amor".',
    concl: 'Os dons espirituais são ferramentas temporárias dadas por Deus para edificar a igreja, mas o amor é a própria essência do caráter de Deus que permanecerá para sempre. O nosso maior objetivo não deve ser a busca por poder ou reconhecimento ministerial, mas a busca incansável por amar a Deus e ao próximo com o mesmo amor sacrificial com que fomos amados por Cristo.'
  },
  {
    id: 'jos_24_14_24',
    intro: 'O capítulo 24 de Josué é o grande discurso de despedida do líder que introduziu Israel na Terra Prometida. Aos 110 anos de idade, Josué reúne todas as tribos, os anciãos e os juízes em Siquém (um lugar de profundo significado histórico, onde Abraão construiu o seu primeiro altar). Após recontar a história da fidelidade de Deus desde o chamado de Abraão até a conquista de Canaã, Josué lança um ultimato espiritual à nação. Ele sabe que a maior ameaça a Israel não são os exércitos inimigos, mas a idolatria e o sincretismo religioso. Este texto é um chamado radical a uma decisão inadiável: a fé verdadeira não admite neutralidade ou corações divididos.',
    desc1: 'O apelo de Josué começa com uma exigência de integridade: "Agora, pois, temei ao Senhor, e servi-o com sinceridade e com verdade; e deitai fora os deuses aos quais serviram vossos pais dalém do rio e no Egito, e servi ao Senhor". A idolatria não era apenas um problema das nações vizinhas; Israel ainda guardava secretamente os deuses do Egito e da Mesopotâmia. Josué deixa claro que é impossível servir a Yahweh enquanto se mantém ídolos escondidos no coração ou na tenda. A verdadeira adoração exige exclusividade e arrependimento prático (deitar fora os ídolos).',
    desc2: 'Josué então apresenta a escolha mais famosa do Antigo Testamento: "Porém, se vos parece mal aos vossos olhos servir ao Senhor, escolhei hoje a quem sirvais... porém eu e a minha casa serviremos ao Senhor". Josué não está sugerindo que a idolatria seja uma opção válida, mas está usando sarcasmo para forçá-los a sair da neutralidade. A indecisão espiritual é, na verdade, uma decisão contra Deus. Josué não espera a decisão da maioria para definir a sua própria fé; ele assume a liderança espiritual do seu lar e declara que, independentemente do que a nação escolha, a sua casa pertencerá exclusivamente ao Senhor.',
    desc3: 'O povo responde rapidamente e com excesso de confiança: "Nunca nos aconteça que deixemos ao Senhor para servirmos a outros deuses". Eles recitam a história do Êxodo e prometem obediência. No entanto, Josué, conhecendo a superficialidade do coração humano, os confronta duramente: "Não podereis servir ao Senhor, porquanto é Deus santo, é Deus zeloso, que não perdoará a vossa transgressão nem os vossos pecados". Josué não está tentando desencorajá-los, mas quer destruir a ilusão de que servir a Deus é algo fácil ou casual. A aliança com um Deus santo e zeloso exige um compromisso total, e a quebra dessa aliança trará juízo severo. O povo insiste: "Não, antes ao Senhor serviremos", e Josué os faz testemunhas contra si mesmos.',
    concl: 'O desafio de Josué ecoa através das gerações: "Escolhei hoje a quem sirvais". Não podemos viver no meio-termo, tentando desfrutar das bênçãos de Deus enquanto mantemos os ídolos do mundo (dinheiro, prazer, aprovação humana). A verdadeira fé exige uma decisão consciente, pública e inegociável de servir exclusivamente ao Senhor, custe o que custar.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 15');
