const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'mat_14_22_33',
    intro: 'A narrativa de Jesus andando sobre as águas ocorre imediatamente após o milagre da multiplicação dos pães. A multidão, impressionada com a provisão milagrosa, queria forçar Jesus a ser rei (João 6:15). Para evitar essa falsa expectativa messiânica e proteger os Seus discípulos dessa influência política, Jesus os "obriga" a entrar no barco e atravessar o Mar da Galileia, enquanto Ele despede a multidão e sobe ao monte para orar sozinho. O que se segue é uma das tempestades mais aterrorizantes e reveladoras do Novo Testamento. Esta história não é apenas sobre o poder de Jesus sobre a natureza, mas sobre a natureza da fé, do medo e da nossa dependência absoluta do Salvador quando as tempestades da vida nos cercam.',
    desc1: 'Enquanto Jesus orava no monte, os discípulos estavam no meio do mar, "açoitados pelas ondas; porque o vento era contrário". Eles estavam remando com dificuldade há horas, exaustos e aterrorizados. É importante notar que eles estavam naquela tempestade não por desobediência (como Jonas), mas por obediência direta à ordem de Jesus. A obediência a Cristo não nos isenta das tempestades da vida. Na "quarta vigília da noite" (entre as 3 e as 6 da manhã, a hora mais escura), Jesus vai ter com eles, andando sobre o mar. Quando os discípulos O veem, o medo deles aumenta: "É um fantasma! E gritaram com medo". Eles não reconheceram o Salvador porque estavam focados no terror da tempestade.',
    desc2: 'Jesus imediatamente acalma o pânico deles com a Sua palavra: "Tende bom ânimo, sou eu, não temais". A frase "sou eu" (ego eimi) é a mesma expressão usada para o nome divino "EU SOU" no Antigo Testamento. Pedro, impulsivo e corajoso, responde com um desafio de fé: "Senhor, se és tu, manda-me ir ter contigo por cima das águas". Pedro não queria apenas ver o milagre; ele queria participar dele. Jesus diz uma única palavra: "Vem". Pedro desce do barco e, milagrosamente, começa a andar sobre as águas em direção a Jesus. A fé verdadeira exige que saiamos da falsa segurança do nosso "barco" e confiemos exclusivamente na palavra de Cristo.',
    desc3: 'O milagre de Pedro dura pouco. O texto diz: "Mas, sentindo o vento forte, teve medo; e, começando a ir para o fundo, clamou, dizendo: Senhor, salva-me!". Pedro tirou os olhos de Jesus e olhou para a fúria do vento e das ondas. Quando o nosso foco muda do Salvador para as circunstâncias, a fé afunda e o medo assume o controle. Imediatamente, Jesus estende a mão, segura-o e repreende-o suavemente: "Homem de pouca fé, por que duvidaste?". Quando eles sobem para o barco, o vento cessa instantaneamente. Os discípulos, maravilhados, prostram-se e adoram Jesus, confessando: "És verdadeiramente o Filho de Deus". A tempestade serviu para revelar a glória de Cristo e aprofundar a fé dos discípulos.',
    concl: 'A história de Jesus andando sobre as águas nos ensina que as tempestades da vida são inevitáveis, mesmo quando estamos no centro da vontade de Deus. Quando o vento for contrário, não devemos focar no tamanho das ondas, mas manter os olhos fixos no "EU SOU" que caminha sobre elas. E mesmo quando a nossa fé vacilar e começarmos a afundar, a mão estendida de Cristo está sempre pronta para nos salvar quando clamamos a Ele.'
  },
  {
    id: 'mrk_5_21_43',
    intro: 'O capítulo 5 de Marcos apresenta uma das narrativas mais belas e complexas dos Evangelhos, onde duas histórias de desespero e cura se entrelaçam perfeitamente. Jairo, um dos principais da sinagoga (um homem de alto status religioso e social), aproxima-se de Jesus com um pedido urgente: a sua filha de doze anos está à beira da morte. Enquanto Jesus caminha com Jairo em direção à sua casa, a multidão O aperta. No meio dessa multidão, há uma mulher anônima, sofrendo de uma hemorragia há doze anos (o mesmo tempo de vida da filha de Jairo). Ela era impura, pobre e marginalizada. Jesus interrompe a missão urgente do homem importante para atender à fé silenciosa da mulher invisível, demonstrando que a Sua graça não faz acepção de pessoas e que o Seu poder é suficiente para ambas as crises.',
    desc1: 'A mulher do fluxo de sangue havia gastado tudo o que tinha com médicos e só piorava. Pela lei levítica, ela era cerimonialmente impura; qualquer pessoa que ela tocasse também se tornaria impura. Ela não podia ir ao templo nem ter contato social normal. Desesperada, ela pensa: "Se eu tão-somente tocar nas suas vestes, sararei". Ela se esgueira por trás de Jesus e toca a orla do Seu manto. Imediatamente, a fonte do seu sangue seca. Jesus, sentindo que "virtude (poder) saíra dele", para e pergunta: "Quem tocou nas minhas vestes?". Os discípulos acham a pergunta absurda devido à multidão que O apertava. Mas Jesus não queria apenas curá-la fisicamente; Ele queria restaurá-la publicamente e relacionar-se com ela.',
    desc2: 'A mulher, tremendo de medo (pois havia quebrado a lei ao tocar em um rabino), prostra-se e conta toda a verdade. Jesus não a repreende pela sua impureza; Ele a chama pelo título mais afetuoso: "Filha, a tua fé te salvou; vai em paz, e sê curada deste teu mal". Enquanto Jesus falava com ela, chegam mensageiros da casa de Jairo com a pior notícia possível: "A tua filha está morta; para que enfadas mais o Mestre?". A demora de Jesus para curar a mulher parece ter custado a vida da menina. A esperança de Jairo é destruída. Mas Jesus, ignorando a notícia de morte, diz a Jairo a frase que sustenta a fé no meio do caos: "Não temas, crê somente".',
    desc3: 'Jesus chega à casa de Jairo, que já estava cheia de pranteadores profissionais fazendo alvoroço. Jesus diz: "A menina não está morta, mas dorme". A multidão ri dEle com escárnio, pois conheciam a realidade da morte. Jesus expulsa os incrédulos, entra no quarto apenas com os pais da menina e três discípulos (Pedro, Tiago e João). Ele toma a mão da menina morta (outro ato que O tornaria cerimonialmente impuro) e diz em aramaico: "Talita cumi" (Menina, a ti te digo, levanta-te). Imediatamente a menina se levanta e anda. O poder de Jesus sobre a morte é tão absoluto que Ele a trata como um simples sono do qual Ele pode nos despertar com uma palavra.',
    concl: 'A história entrelaçada de Jairo e da mulher do fluxo de sangue nos ensina que Jesus nunca está ocupado demais para atender ao nosso clamor, seja ele o grito público de um líder ou o toque silencioso de um marginalizado. A demora de Deus não é a negação de Deus. Quando as circunstâncias dizem que "já é tarde demais" e a morte parece ter vencido, Jesus nos chama a ignorar o desespero e a confiar na Sua palavra: "Não temas, crê somente".'
  },
  {
    id: 'jhn_4_1_42',
    intro: 'O encontro de Jesus com a mulher samaritana no poço de Jacó é uma das conversas mais longas, teologicamente ricas e culturalmente subversivas registradas nos Evangelhos. Jesus estava viajando da Judeia para a Galileia e o texto diz que "era-lhe necessário passar por Samaria". Essa "necessidade" não era geográfica (os judeus rigorosos frequentemente contornavam Samaria para evitar contato com os samaritanos, a quem consideravam mestiços impuros e hereges), mas uma necessidade divina e missional. Ao meio-dia (a hora mais quente, quando as mulheres respeitáveis não iam ao poço), Jesus, cansado da viagem, senta-se junto ao poço e inicia uma conversa que quebra barreiras seculares de raça, gênero e religião, oferecendo a "água viva" a uma mulher sedenta e marginalizada.',
    desc1: 'Jesus quebra o gelo com um pedido simples: "Dá-me de beber". A mulher fica chocada: "Como, sendo tu judeu, me pedes de beber a mim, que sou mulher samaritana?". Jesus ignora o preconceito cultural e eleva a conversa para o nível espiritual: "Se tu conheceras o dom de Deus, e quem é o que te diz: Dá-me de beber, tu lhe pedirias, e ele te daria água viva". A mulher, pensando apenas em água física, questiona como Ele poderia tirar água daquele poço fundo sem um cântaro. Jesus explica a diferença entre as águas: "Qualquer que beber desta água tornará a ter sede; mas aquele que beber da água que eu lhe der nunca mais terá sede... se fará nele uma fonte de água que salte para a vida eterna".',
    desc2: 'A mulher, ainda focada na conveniência física, pede dessa água. É então que Jesus faz o diagnóstico espiritual necessário antes de oferecer a cura: "Vai, chama o teu marido, e vem cá". A mulher responde com uma meia-verdade: "Não tenho marido". Jesus expõe a sua vida com precisão profética e graça: "Tiveste cinco maridos, e o que agora tens não é teu marido". A sede daquela mulher não era apenas física; era uma sede emocional e relacional que ela tentava saciar pulando de relacionamento em relacionamento. Jesus não a condena, mas expõe a sua ferida para que ela possa receber a verdadeira "água viva" que satisfaz a alma.',
    desc3: 'Percebendo que Jesus é um profeta, a mulher tenta mudar de assunto para um debate teológico seguro sobre o local correto de adoração (o monte Gerizim dos samaritanos ou Jerusalém dos judeus). Jesus responde com a maior definição de adoração do Novo Testamento: "Deus é Espírito, e importa que os que o adoram o adorem em espírito e em verdade". A adoração verdadeira não depende de geografia ou rituais, mas de um coração transformado pelo Espírito e alinhado com a Verdade (Cristo). A mulher menciona a esperança do Messias, e Jesus faz a Sua primeira declaração messiânica explícita: "Eu o sou, eu que falo contigo". A mulher deixa o seu cântaro (o símbolo da sua velha vida), corre para a cidade e se torna a primeira evangelista, trazendo toda a cidade para conhecer Jesus.',
    concl: 'O encontro no poço de Jacó nos ensina que Jesus busca intencionalmente aqueles que a sociedade rejeita. Ele conhece a nossa sede mais profunda e os "cântaros" quebrados que usamos para tentar nos satisfazer. A verdadeira adoração e a satisfação eterna só são encontradas quando bebemos da "água viva" que Cristo oferece, permitindo que Ele exponha os nossos pecados com graça e nos transforme em fontes a jorrar para a vida eterna.'
  },
  {
    id: 'php_2_1_11',
    intro: 'O capítulo 2 da Epístola aos Filipenses contém um dos textos cristológicos mais profundos, belos e teologicamente densos de todo o Novo Testamento, frequentemente chamado de "Hino de Kenosis" (esvaziamento). O apóstolo Paulo não escreveu este hino apenas para dar uma aula de teologia sistemática sobre a encarnação; ele o escreveu com um propósito pastoral muito prático. A igreja de Filipos estava enfrentando problemas de desunião, rivalidade e orgulho. Para exortá-los à humildade e a considerarem os outros superiores a si mesmos, Paulo não lhes dá um conjunto de regras morais, mas apresenta o exemplo supremo: a jornada de Jesus Cristo da glória eterna à humilhação da cruz, e da cruz à exaltação suprema.',
    desc1: 'Paulo começa ordenando: "Haja em vós o mesmo sentimento que houve também em Cristo Jesus". Ele então descreve a preexistência gloriosa de Cristo: "Sendo em forma de Deus, não teve por usurpação (não considerou como algo a ser agarrado ou retido a qualquer custo) ser igual a Deus". Jesus possuía a própria essência e natureza de Deus desde a eternidade. No entanto, Ele não usou os Seus privilégios divinos para o Seu próprio benefício ou conforto. Em vez de se apegar à Sua glória, Ele "esvaziou-se a si mesmo" (kenosis). Esse esvaziamento não significa que Ele deixou de ser Deus, mas que Ele abriu mão do uso independente dos Seus atributos divinos e da glória que tinha com o Pai.',
    desc2: 'O esvaziamento de Cristo é descrito em uma série de degraus descendentes de humilhação. Primeiro, Ele tomou a "forma de servo" (a essência da submissão). Segundo, Ele se fez "semelhante aos homens" (a encarnação, assumindo a fragilidade humana). Terceiro, "achado na forma de homem, humilhou-se a si mesmo, sendo obediente até à morte". A morte já seria uma humilhação infinita para o Autor da vida, mas Ele desceu ao degrau mais baixo possível: "e morte de cruz". A crucificação era a forma de execução mais vergonhosa, dolorosa e maldita do Império Romano, reservada para escravos e rebeldes. O Rei do universo permitiu ser despido, torturado e executado como um criminoso para nos salvar.',
    desc3: 'Por causa dessa obediência e humilhação absolutas, Deus Pai reverte a trajetória: "Por isso, também Deus o exaltou soberanamente, e lhe deu um nome que é sobre todo o nome". A exaltação de Cristo é a resposta do Pai à submissão do Filho. O propósito dessa exaltação é universal e inegável: "Para que ao nome de Jesus se dobre todo o joelho dos que estão nos céus, e na terra, e debaixo da terra, e toda a língua confesse que Jesus Cristo é o Senhor, para glória de Deus Pai". Um dia, todo ser no universo (anjos, humanos salvos, demônios e rebeldes) reconhecerá a soberania de Jesus. A única diferença é se dobraremos os joelhos agora com alegria e salvação, ou no juízo final com terror e condenação.',
    concl: 'Filipenses 2 destrói a lógica do mundo, que diz que o caminho para a grandeza é a autoexaltação e o poder sobre os outros. O Evangelho nos ensina que o caminho para a verdadeira glória é a cruz. Se queremos ter o "sentimento de Cristo", devemos estar dispostos a abrir mão dos nossos direitos, a servir aos outros com humildade e a confiar que Deus nos exaltará no tempo certo.'
  },
  {
    id: 'heb_11_1_40',
    intro: 'O capítulo 11 de Hebreus é universalmente conhecido como a "Galeria dos Heróis da Fé" ou o "Hall da Fama do Antigo Testamento". O autor da epístola estava escrevendo para cristãos judeus que estavam enfrentando perseguição severa e estavam tentados a abandonar a fé em Cristo e voltar para a segurança do judaísmo tradicional. Para encorajá-los a perseverar, o autor não oferece uma nova teoria filosófica, mas faz um apelo à história. Ele define o que é a verdadeira fé e, em seguida, faz um desfile magnífico de homens e mulheres do passado que viveram, sofreram e morreram confiando nas promessas invisíveis de Deus. Este capítulo prova que a fé não é um salto no escuro, mas uma âncora firme na fidelidade do Criador.',
    desc1: 'O capítulo começa com a definição clássica: "Ora, a fé é o firme fundamento das coisas que se esperam, e a prova das coisas que se não veem". A fé não é um sentimento vago ou um pensamento positivo; é uma convicção (hupostasis, a substância ou o título de propriedade) sobre realidades futuras e invisíveis baseadas na Palavra de Deus. O autor afirma que foi por essa fé que os antigos "alcançaram testemunho" (foram aprovados por Deus). A fé é o único meio pelo qual podemos agradar a Deus (v. 6): "Ora, sem fé é impossível agradar-lhe; porque é necessário que aquele que se aproxima de Deus creia que ele existe, e que é galardoador dos que o buscam".',
    desc2: 'O autor então lista os exemplos práticos. Ele menciona Abel (que ofereceu um sacrifício melhor), Enoque (que andou com Deus e foi transladado) e Noé (que construiu uma arca para um dilúvio que nunca tinha visto). O maior espaço é dedicado a Abraão, que obedeceu ao chamado para ir a um lugar desconhecido, viveu em tendas como estrangeiro na Terra Prometida e esteve disposto a sacrificar o seu filho Isaque, crendo que Deus era poderoso para ressuscitá-lo. O autor também destaca Sara, Isaque, Jacó, José e Moisés, que "teve por maiores riquezas o vitupério de Cristo do que os tesouros do Egito; porque tinha em vista a recompensa" e "ficou firme, como vendo o invisível". A fé sempre exige que escolhamos a recompensa eterna em vez do conforto temporal.',
    desc3: 'A parte final do capítulo (v. 32-40) é um resumo rápido e emocionante. O autor menciona juízes, reis e profetas que, pela fé, "venceram reinos, praticaram a justiça, alcançaram promessas, fecharam as bocas dos leões, apagaram a força do fogo". Mas a fé não garante apenas vitórias espetaculares; ela também sustenta no sofrimento extremo. O autor lista aqueles que foram torturados, apedrejados, serrados ao meio e mortos à espada, "dos quais o mundo não era digno". O clímax teológico é que todos esses heróis morreram sem receber a plenitude da promessa (a vinda do Messias), "provendo Deus alguma coisa melhor a nosso respeito, para que eles, sem nós, não fossem aperfeiçoados". Nós, a Igreja, somos o cumprimento da esperança deles.',
    concl: 'Hebreus 11 nos ensina que a fé não é a garantia de uma vida fácil, mas a força para perseverar até o fim. Os heróis do passado não eram super-homens perfeitos (muitos tinham falhas graves), mas eram homens e mulheres que decidiram confiar que Deus é fiel para cumprir o que prometeu. A vida deles nos desafia a olhar além do visível e a vivermos hoje à luz da eternidade.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 29');
