const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'jdg_6_11_24',
    intro: 'A história do chamado de Gideão ocorre durante um dos períodos mais sombrios do livro de Juízes. Por causa da desobediência de Israel, Deus os entregou nas mãos dos midianitas, que invadiam a terra como gafanhotos na época da colheita, destruindo o sustento e levando o povo à fome e ao desespero. O medo era tão grande que os israelitas viviam escondidos em cavernas. É nesse cenário de opressão nacional e covardia pessoal que o Anjo do Senhor aparece a Gideão. A narrativa revela como Deus enxerga o nosso potencial através da Sua graça, mesmo quando nós só conseguimos ver a nossa própria fraqueza e os nossos medos.',
    desc1: 'Quando o Anjo do Senhor aparece, Gideão não está liderando um exército ou orando no templo; ele está "malhando o trigo no lagar, para o salvar dos midianitas". O lagar era um buraco no chão usado para pisar uvas, não o lugar alto e ventilado (eira) onde o trigo deveria ser malhado. Gideão estava escondido, dominado pelo medo. No entanto, a saudação do Anjo é surpreendente: "O Senhor é contigo, homem valoroso". Deus não chama Gideão pelo que ele era naquele momento (um fazendeiro assustado), mas pelo que ele se tornaria pelo poder de Deus (um herói valoroso). A graça de Deus nos define pelo nosso destino nEle, não pelo nosso passado ou pelos nossos medos presentes.',
    desc2: 'A resposta de Gideão é cheia de cinismo e dor acumulada: "Ai, Senhor meu, se o Senhor é conosco, por que tudo isto nos sobreveio? E que é feito de todas as suas maravilhas que nossos pais nos contaram?". Gideão questiona a presença e o poder de Deus diante do sofrimento de Israel. O Senhor não entra em um debate teológico para Se justificar; Ele simplesmente dá a Gideão uma missão: "Vai nesta tua força, e livrarás a Israel das mãos dos midianitas; porventura não te enviei eu?". A resposta para a crise de Israel não seria um milagre caindo do céu, mas um homem comum enviado e capacitado por Deus.',
    desc3: 'Gideão, ainda focado nas suas limitações, apresenta as suas desculpas: "Eis que a minha família é a mais pobre em Manassés, e eu o menor na casa de meu pai". Ele se via como o menor do menor. A garantia de Deus é a mesma que Ele deu a Moisés: "Porquanto eu hei de ser contigo, tu ferirás aos midianitas como se fossem um só homem". Gideão pede um sinal, prepara uma oferta (cabrito e pães asmos) e o Anjo a consome com fogo que sobe da penha, desaparecendo em seguida. Gideão percebe que viu o Anjo do Senhor face a face e teme morrer, mas Deus lhe dá paz. Gideão então constrói um altar e o chama de "Jeová-Shalom" (O Senhor é Paz).',
    concl: 'O chamado de Gideão nos ensina que Deus não procura pessoas perfeitas, corajosas ou com grandes currículos para realizar a Sua obra. Ele procura pessoas comuns, muitas vezes escondidas e cheias de dúvidas, para que, quando a vitória for alcançada, fique claro que o poder e a glória pertencem exclusivamente a Ele. A nossa fraqueza é o palco perfeito para o "homem valoroso" que Deus quer forjar em nós.'
  },
  {
    id: '1sa_1_9_20',
    intro: 'O primeiro capítulo de 1 Samuel nos apresenta a dor profunda de Ana, uma mulher estéril em uma cultura que via a falta de filhos como um sinal de desfavor divino. Ela era uma das duas esposas de Elcana. Enquanto Penina tinha filhos e a provocava cruelmente, Ana carregava o estigma e a vergonha. A dor de Ana era multiplicada a cada ano durante as viagens a Siló para adoração. A história de Ana é um testemunho poderoso de como Deus usa a nossa dor mais profunda para nos levar a uma dependência radical dEle, transformando a nossa aflição no berço de um propósito que mudará a história de uma nação.',
    desc1: 'A dor de Ana a levou a um ponto de ruptura. O consolo humano, por mais bem-intencionado que seja (como o de Elcana, que lhe dava porção dupla e tentava ser melhor que dez filhos), frequentemente falha em alcançar as profundezas da nossa angústia. Em vez de se render à amargura contra Deus ou à vingança contra Penina, Ana escolheu o caminho da oração. No templo, com amargura de alma, ela chora abundantemente e faz um voto ao Senhor. Ela não pede um filho apenas para satisfazer o seu desejo materno; ela consagra a criança a Deus antes mesmo de concebê-la: "Se... me deres um filho varão, ao Senhor o darei por todos os dias da sua vida".',
    desc2: 'Enquanto Ana orava silenciosamente (movendo apenas os lábios), o sacerdote Eli a confunde com uma mulher embriagada e a repreende. Mesmo diante dessa injustiça pastoral, Ana responde com mansidão e respeito, explicando que estava derramando a sua alma perante o Senhor. Eli então a abençoa: "Vai em paz; e o Deus de Israel te conceda a petição que lhe fizeste". O milagre da oração de Ana é visto antes mesmo da gravidez: "A mulher seguiu o seu caminho, e comeu, e o seu semblante já não era triste". A paz de Deus inunda o coração que entrega os seus fardos no altar.',
    desc3: 'O texto diz que "Elcana conheceu a Ana sua mulher, e o Senhor se lembrou dela". O verbo "lembrar" na Bíblia não significa que Deus havia esquecido e de repente recordou, mas que Ele agiu em favor dela no tempo determinado. Ana concebeu e deu à luz um filho, e chamou o seu nome Samuel (que significa "Do Senhor o pedi"). Ana cumpriu o seu voto, entregando Samuel para servir no templo assim que foi desmamado. O menino que nasceu da dor e da oração de uma mulher estéril tornou-se o grande profeta, sacerdote e juiz que guiaria Israel na transição para a monarquia.',
    concl: 'Deus frequentemente permite o fechamento de certas portas em nossas vidas para nos levar a um nível de oração e consagração que nunca alcançaríamos no conforto. Quando entregamos os nossos "Isaques" e "Samuéis" no altar antes mesmo de recebê-los, Deus transforma a nossa esterilidade em frutos que abençoarão gerações.'
  },
  {
    id: 'psa_51_1_12',
    intro: 'O Salmo 51 é o mais profundo e famoso dos salmos penitenciais. Ele foi escrito por Davi após o momento mais sombrio e vergonhoso da sua vida: o seu adultério com Bate-Seba e o subsequente assassinato do marido dela, Urias, para encobrir o pecado. Durante quase um ano, Davi viveu em hipocrisia, escondendo o seu crime, até ser confrontado pelo profeta Natã com a parábola da ovelhinha (2 Samuel 12). Quando a máscara de Davi cai, ele não dá desculpas, não culpa as circunstâncias e não apela para os seus privilégios reais. O Salmo 51 é o modelo bíblico definitivo de como um coração quebrantado busca a restauração divina, revelando a anatomia do verdadeiro arrependimento.',
    desc1: 'Davi começa o salmo não apelando para as suas boas obras passadas, mas exclusivamente para o caráter de Deus: "Tem misericórdia de mim, ó Deus, segundo a tua benignidade; apaga as minhas transgressões, segundo a multidão das tuas misericórdias". Ele reconhece que a sua única esperança é a graça imerecida de Deus. Davi usa três palavras diferentes para descrever a sua falha: transgressão (rebelião deliberada contra a lei de Deus), iniquidade (a corrupção interna e a natureza torta do coração) e pecado (errar o alvo do padrão divino). Ele pede para ser lavado e purificado, reconhecendo que o pecado é uma sujeira profunda que só Deus pode remover.',
    desc2: 'A marca do verdadeiro arrependimento é a confissão sem desculpas. Davi declara: "Porque eu conheço as minhas transgressões, e o meu pecado está sempre diante de mim". Ele não tenta minimizar a sua culpa. O versículo 4 contém a declaração mais chocante: "Contra ti, contra ti somente pequei, e fiz o que é mal à tua vista". Embora Davi tenha destruído a vida de Urias, Bate-Seba e a sua própria família, ele entende que todo pecado, em sua essência, é uma ofensa cósmica e uma traição contra o próprio Deus. Ele reconhece que Deus é absolutamente justo em julgar e condenar o seu ato.',
    desc3: 'Davi não pede apenas perdão pelos atos cometidos; ele pede uma transformação radical da sua natureza. Ele reconhece que nasceu em iniquidade (v. 5) e clama: "Cria em mim, ó Deus, um coração puro, e renova em mim um espírito reto" (v. 10). O verbo "criar" (bara) é o mesmo usado em Gênesis 1 para a criação do universo do nada; Davi sabe que o seu coração não precisa de uma reforma, mas de uma nova criação. O seu maior medo não é perder o trono, mas perder a presença de Deus: "Não me lances fora da tua presença, e não retires de mim o teu Espírito Santo". Ele clama pela restauração da "alegria da tua salvação".',
    concl: 'O Salmo 51 nos ensina que não há pecado tão grande que a misericórdia de Deus não possa perdoar, desde que haja um arrependimento genuíno. O verdadeiro arrependimento não é apenas o remorso pelas consequências do pecado, mas a dor profunda por ter ofendido a Deus, acompanhada de um clamor desesperado por um coração puro e pela restauração da comunhão com o Criador.'
  },
  {
    id: 'mt_11_25_30',
    intro: 'O final do capítulo 11 de Mateus apresenta um dos contrastes mais belos do ministério de Jesus. Nos versículos anteriores, Jesus havia pronunciado duros "ais" (juízos) sobre as cidades da Galileia (Corazim, Betsaida e Cafarnaum) que testemunharam a maioria dos Seus milagres, mas se recusaram a se arrepender. A rejeição estava crescendo. No entanto, em vez de Se frustrar, Jesus irrompe em uma oração de gratidão ao Pai pela soberania da graça. Em seguida, Ele estende um dos convites mais universais, amorosos e reconfortantes de toda a Bíblia. Este texto revela o coração de Cristo para com aqueles que estão esmagados pelo peso da religiosidade e das lutas da vida.',
    desc1: 'A oração de Jesus revela o mistério da revelação divina: "Graças te dou, ó Pai, Senhor do céu e da terra, que ocultaste estas coisas aos sábios e entendidos, e as revelaste aos pequeninos". A salvação não é uma conquista intelectual para os orgulhosos, mas um presente revelado aos humildes ("pequeninos"). Os líderes religiosos (sábios aos seus próprios olhos) rejeitaram Jesus porque Ele não se encaixava nas suas expectativas teológicas, mas os simples e quebrantados O receberam. Jesus afirma a Sua autoridade exclusiva: "Ninguém conhece o Filho, senão o Pai; e ninguém conhece o Pai, senão o Filho, e aquele a quem o Filho o quiser revelar".',
    desc2: 'Com base nessa autoridade suprema, Jesus faz o grande convite: "Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei". O convite não é para uma nova religião, um novo conjunto de regras ou uma filosofia, mas para uma pessoa: "Vinde a mim". O público-alvo são os "cansados" (aqueles que estão exaustos pelo próprio esforço) e "oprimidos" (aqueles que carregam fardos pesados colocados por outros, especialmente o fardo do legalismo farisaico que exigia perfeição para a salvação). A promessa de Jesus é o "alívio" (descanso), não a isenção de problemas, mas a paz profunda da alma justificada.',
    desc3: 'Jesus explica como esse descanso é alcançado: "Tomai sobre vós o meu jugo, e aprendei de mim, que sou manso e humilde de coração; e encontrareis descanso para as vossas almas". O jugo era uma peça de madeira colocada sobre dois bois para que puxassem o arado juntos; representava submissão e trabalho. Jesus não nos oferece uma vida sem jugo (sem compromisso), mas oferece o Seu próprio jugo. A diferença é que o Mestre que coloca o jugo é "manso e humilde", não um tirano exigente. Ele conclui: "Porque o meu jugo é suave e o meu fardo é leve". Quando nos submetemos a Cristo, descobrimos que Ele carrega o peso maior conosco.',
    concl: 'A religião humana diz: "Trabalhe duro para alcançar a Deus e talvez você encontre descanso". O Evangelho de Jesus diz: "Venha a mim com a sua exaustão, receba o meu descanso pela graça, e então trabalhemos juntos". O verdadeiro descanso para a alma não é encontrado na ausência de responsabilidades, mas na submissão alegre ao jugo suave do Salvador.'
  },
  {
    id: 'jhn_21_1_19',
    intro: 'O capítulo 21 de João é o epílogo do Evangelho e narra uma das cenas mais comoventes de restauração em toda a Bíblia. Após a ressurreição, Jesus já havia aparecido aos discípulos, mas a questão do fracasso de Pedro ainda pairava no ar. Pedro havia negado Jesus três vezes publicamente antes da crucificação. Sentindo-se indigno e sem direção, Pedro decide voltar à sua antiga vida: "Vou pescar". Sete discípulos o seguem. Eles passam a noite inteira no Mar de Tiberíades e não apanham nada. É nesse cenário de fracasso profissional e culpa espiritual que Jesus aparece na praia, não para condenar Pedro, mas para restaurá-lo comissioná-lo novamente para o ministério.',
    desc1: 'A cena na praia é um "déjà vu" intencional orquestrado por Jesus. Ao amanhecer, Jesus (ainda não reconhecido) diz para lançarem a rede para o lado direito do barco. A obediência resulta em uma pesca milagrosa de 153 grandes peixes. João reconhece o padrão (lembrando-se de Lucas 5) e diz a Pedro: "É o Senhor!". Pedro, impetuoso como sempre, veste a túnica e lança-se ao mar para chegar a Jesus. Quando chegam à praia, encontram brasas acesas com peixe e pão. Jesus os convida: "Vinde, comei". O Senhor ressurreto, o Rei do universo, serve o café da manhã aos Seus discípulos exaustos. A restauração começa com a comunhão e o cuidado prático.',
    desc2: 'Após a refeição, Jesus confronta o elefante na sala. Ele se dirige a Pedro usando o seu nome antigo (Simão, filho de Jonas) e faz a pergunta mais penetrante: "Amas-me mais do que estes?". Jesus pergunta isso três vezes, correspondendo exatamente às três negações de Pedro. A repetição entristece Pedro, pois o força a encarar a profundidade do seu fracasso. Pedro não responde com a arrogância do passado ("ainda que todos te abandonem, eu não"), mas com a humildade de quem conhece a própria fraqueza: "Senhor, tu sabes tudo; tu sabes que eu te amo". A verdadeira restauração exige que enfrentemos a verdade sobre nós mesmos diante do Senhor.',
    desc3: 'A cada afirmação de amor de Pedro, Jesus responde com uma comissão: "Apascenta os meus cordeiros", "Apascenta as minhas ovelhas". Jesus não exige que Pedro faça penitência ou cumpra um período de provação. O perdão de Cristo é tão completo que Ele confia o Seu bem mais precioso (a Sua igreja) nas mãos do homem que O havia negado dias antes. A qualificação principal para o ministério pastoral não é a perfeição moral, mas um amor profundo e humilde por Jesus. Jesus conclui profetizando que Pedro morreria como mártir, glorificando a Deus, e repete o chamado original: "Segue-me".',
    concl: 'A restauração de Pedro nos ensina que o nosso fracasso não é o fim da nossa história com Deus. Quando falhamos, a tendência é voltarmos para a nossa "velha vida" (as nossas redes). Mas Jesus nos encontra na praia da nossa frustração, alimenta-nos com a Sua graça, cura as nossas feridas com o Seu amor e nos chama novamente para segui-Lo e servir ao Seu povo.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 17');
