const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'mt_4_1_11',
    intro: 'O deserto não é o fim, é a escola de aprovação e o campo de batalha onde as vitórias espirituais são forjadas. Logo após ser batizado nas águas do Jordão e ter Sua identidade publicamente afirmada pela voz do Pai ("Este é o meu Filho amado"), Jesus é intencionalmente levado pelo Espírito Santo ao deserto para ser tentado pelo diabo. Este não foi um acidente, mas um confronto cósmico planejado. Onde o primeiro Adão falhou no paraíso cercado de abundância, o Último Adão (Cristo) triunfaria no deserto árido, cercado de privações. Sua vitória não apenas prova Sua qualificação como o Messias sem pecado, mas garante a nossa vitória, ensinando-nos que a arma definitiva contra as artimanhas do inferno é a submissão inabalável à Palavra de Deus.',
    desc1: 'O inimigo ataca na área da necessidade humana mais básica e legítima: a fome após 40 dias de jejum. A tentação não era apenas sobre comida, mas sobre independência. Satanás sugere que Jesus use Seu poder divino para benefício próprio, contornando a provisão e o tempo do Pai ("Se és Filho de Deus, manda que estas pedras se tornem em pães"). Jesus responde citando Deuteronômio 8:3, priorizando a Palavra sobre o pão. Ele demonstra que a verdadeira vida não é sustentada apenas por calorias, mas pela obediência absoluta a cada palavra que sai da boca de Deus.',
    desc2: 'Derrotado na área do apetite, o diabo muda a tática e usa a própria Escritura (Salmo 91) de forma distorcida, omitindo partes do texto para tentar Jesus a testar Deus publicamente no pináculo do templo. A tentação aqui é a presunção espiritual: forçar Deus a agir através de um espetáculo para provar Seu cuidado. Jesus rebate com Deuteronômio 6:16, mostrando que a verdadeira fé não exige provas espetaculares nem coloca Deus contra a parede. Confiar em Deus significa descansar em Seu caráter, não manipular Seu poder para nossa glória.',
    desc3: 'A cartada final é a oferta de todos os reinos do mundo e sua glória, sem a necessidade de passar pela agonia da cruz. Era um atalho para a coroa que exigia apenas um momento de idolatria ("se, prostrado, me adorares"). Satanás oferece o mundo, mas cobra a alma. Jesus rejeita violentamente o atalho, citando Deuteronômio 6:13, reafirmando que a verdadeira adoração e o serviço pertencem única e exclusivamente a Deus. Não há coroa sem cruz, e não há Reino sem submissão ao Rei dos reis.',
    concl: 'Com a tríplice derrota, o diabo o deixou "até momento oportuno", e imediatamente os anjos vieram e O serviram. A vitória de Cristo no deserto desfaz a derrota de Adão no Éden e quebra o poder da tentação sobre a humanidade. Quando enfrentarmos nossos próprios desertos, a Palavra de Deus não é apenas um livro de conselhos, mas a nossa espada afiada. Em Cristo, não lutamos para obter a vitória, mas lutamos a partir da vitória que Ele já conquistou por nós.'
  },
  {
    id: 'ps_23',
    intro: 'Davi, um pastor de ovelhas que foi ungido e se tornou o maior rei de Israel, usa a metáfora que ele melhor conhece para descrever o cuidado íntimo, pessoal e constante de Deus por Seu povo. O Salmo 23 não é apenas um poema de consolo recitado em funerais para amenizar a dor da morte; é, antes de tudo, um poderoso manifesto de confiança e provisão para a vida diária. Ele descreve a jornada completa da alma humana: desde os pastos verdes da provisão, passando pelos vales escuros da provação, até chegar ao banquete da exaltação e à habitação eterna na casa do Pai.',
    desc1: 'A declaração de posse ("O Senhor é o meu pastor") é o fundamento de tudo; por Ele ser meu, "nada me faltará". Deus não apenas dá coisas, Ele se dá a nós. Ele oferece descanso intencional ("faz-me repousar em pastos verdes"), paz em meio ao caos ("guia-me mansamente a águas tranquilas") e uma restauração profunda para a alma ferida e cansada ("refrigera a minha alma"). Ele não nos guia por atalhos, mas pelas "veredas da justiça", garantindo que nossa caminhada glorifique o Seu santo nome.',
    desc2: 'Ocorre uma transição teológica profunda no versículo 4: Davi deixa de falar "sobre" Deus na terceira pessoa (Ele) e passa a falar "com" Deus na segunda pessoa (Tu). A intimidade cresce na adversidade. No "vale da sombra da morte" (ou vale de densas trevas), o medo é dissipado não pela ausência do perigo ou do sofrimento, mas pela presença tangível do Pastor. A "vara" serve para defesa contra os lobos, e o "cajado" serve para resgatar a ovelha que cai. A disciplina e a proteção de Deus são o nosso maior conforto.',
    desc3: 'A metáfora muda subitamente de um pastor no campo para um anfitrião real em um palácio. Deus prepara um banquete de honra "na presença dos meus inimigos", mostrando que a vindicação divina acontece publicamente. Ele unge a cabeça com óleo (símbolo de cura, alegria e favor real) e faz o cálice transbordar (abundância que excede a necessidade). A bondade e a misericórdia não são apenas sentimentos, mas tornam-se como dois cães de guarda divinos, "perseguindo" o crente todos os dias de sua vida.',
    concl: 'O Salmo termina com a maior de todas as promessas e a esperança final da fé cristã: "habitarei na Casa do Senhor para todo o sempre". A jornada que começa no pasto das ovelhas termina no palácio celestial. O Senhor que nos pastoreia na terra é o mesmo que nos receberá na glória, provando que Seu cuidado não é temporário, mas eterno.'
  },
  {
    id: 'eph_6_10_20',
    intro: 'A vida cristã não é um parque de diversões espiritual, mas um intenso campo de batalha cósmico. O apóstolo Paulo, escrevendo esta epístola enquanto estava possivelmente acorrentado a um soldado romano de elite, usa a armadura militar que via todos os dias como uma poderosa metáfora para as defesas espirituais que Deus nos fornece. Ele nos chama a despertar para a realidade invisível: estamos em guerra. No entanto, não somos chamados a lutar com nossas próprias forças, mas a nos revestirmos de toda a armadura de Deus para resistir aos ataques do império das trevas.',
    desc1: 'A exortação começa com um imperativo: "Fortalecei-vos no Senhor e na força do seu poder". Nossa força natural é inútil contra inimigos sobrenaturais. Paulo revela que o nosso verdadeiro inimigo não é humano ("não temos que lutar contra carne e sangue"), mas contra principados, potestades e forças espirituais do mal nas regiões celestiais. O objetivo da armadura não é avançar para conquistar novos territórios (pois Cristo já conquistou tudo na cruz), mas "resistir no dia mau" e, havendo feito tudo, "permanecer inabaláveis" na posição que Cristo nos deu.',
    desc2: 'As peças de defesa são fundamentais para a sobrevivência espiritual. O "cinto da verdade" sustenta toda a armadura, representando a integridade e o conhecimento doutrinário. A "couraça da justiça" protege os órgãos vitais (o coração), representando tanto a justiça imputada por Cristo quanto a santidade prática. Os "calçados da preparação do evangelho da paz" dão estabilidade e prontidão para marchar. O "escudo da fé" é a barreira móvel, capaz de apagar todos os dardos inflamados (dúvidas, medos, tentações) lançados pelo maligno.',
    desc3: 'A armadura se completa com o "capacete da salvação", que protege a mente contra o desespero e as mentiras do diabo, garantindo a certeza da nossa redenção. A única arma de ataque mencionada é a "espada do Espírito, que é a palavra de Deus" (rhema - a palavra específica aplicada ao momento da tentação). Tudo isso deve ser banhado em oração constante e súplica no Espírito, mantendo a linha de comunicação aberta com o Comandante Supremo, vigiando com perseverança por todos os santos.',
    concl: 'Não somos chamados para fabricar a armadura, mas para vesti-la diariamente. A vitória final já foi conquistada por Jesus Cristo no Calvário; nosso dever agora é manter a posição, não ceder terreno ao inimigo e lutar com as armas espirituais que Ele nos deu. Um soldado desarmado é uma presa fácil, mas um crente revestido da armadura de Deus é invencível.'
  },
  {
    id: 'gen_1_1_31',
    intro: 'O relato da criação em Gênesis 1 não é um mero tratado científico sobre como o mundo começou, mas uma profunda declaração teológica sobre QUEM o começou. Em um mundo antigo cercado por mitos de deuses caóticos que criavam o universo através de guerras e violência, Gênesis apresenta o único Deus verdadeiro, soberano e transcendente. Ele traz ordem ao caos, luz às trevas e vida ao vazio, revelando Seu poder absoluto, Seu propósito intencional e a bondade inerente de toda a Sua obra criadora.',
    desc1: 'O texto começa com a declaração mais majestosa da Escritura: "No princípio, criou Deus". Deus já existia antes do tempo, do espaço e da matéria. A terra inicial era "sem forma e vazia" (tohu va bohu), um estado de caos e escuridão profunda. No entanto, o "Espírito de Deus pairava sobre as águas", como uma ave chocando seus ovos, demonstrando que o caos não estava fora de controle, mas era o palco preparado para a manifestação gloriosa da Palavra criadora de Deus.',
    desc2: 'Deus não cria com as mãos, mas através do poder absoluto da Sua Palavra ("E disse Deus: Haja... e houve"). Nos primeiros três dias, Ele forma o universo, separando a luz das trevas, as águas de cima das de baixo, e a terra seca dos mares. Nos três dias seguintes, Ele preenche o que formou: os astros no céu, os peixes e aves, e os animais terrestres. Este padrão de "separar e preencher" demonstra que Ele é um Deus de ordem perfeita, beleza e abundância inesgotável.',
    desc3: 'O ápice e a coroa de toda a criação ocorre no sexto dia: a humanidade. Diferente de todas as outras criaturas, o homem e a mulher são criados "à imagem e semelhança de Deus" (Imago Dei). Eles recebem o mandato cultural para dominar a terra, governar sobre a criação e ser os representantes visíveis do Rei invisível. Ao final de toda a obra, Deus contempla tudo o que fez e declara que era "muito bom", estabelecendo a perfeição original antes da Queda.',
    concl: 'A criação revela um Criador intencional, infinitamente poderoso e essencialmente bom. O universo não é fruto do acaso cósmico, mas do design divino. Nós, como portadores da imagem de Deus, não somos acidentes biológicos, mas fomos criados com o propósito supremo de refletir o Seu caráter, cuidar da Sua obra e viver em comunhão eterna com Ele.'
  },
  {
    id: 'ex_20_1_17',
    intro: 'Os Dez Mandamentos (o Decálogo) não são um conjunto de restrições arbitrárias criadas para roubar a alegria humana, mas sim os trilhos morais sobre os quais a verdadeira liberdade deve correr. Entregues a Moisés no Monte Sinai em meio a trovões e fogo, eles formam a constituição do povo de Deus. Eles revelam o caráter santo do Legislador e estabelecem o padrão absoluto de como devemos nos relacionar verticalmente com Deus e horizontalmente com o nosso próximo, formando a base da ética judaico-cristã.',
    desc1: 'O fundamento de toda a Lei não é a exigência, mas a Graça. Antes de dar o primeiro mandamento, Deus declara: "Eu sou o Senhor teu Deus, que te tirei da terra do Egito, da casa da servidão". A libertação precedeu a legislação. Deus não deu a Lei para que o povo fosse salvo, mas porque o povo já havia sido salvo. A obediência bíblica nunca é a raiz da nossa salvação, mas sempre o fruto e a resposta de gratidão à redenção que já recebemos pela graça.',
    desc2: 'A primeira tábua da Lei (os quatro primeiros mandamentos) foca exclusivamente no nosso relacionamento com Deus. Exige adoração exclusiva ("Não terás outros deuses"), proíbe a idolatria e a redução de Deus a imagens ("Não farás para ti imagem de escultura"), exige reverência absoluta ao Seu caráter ("Não tomarás o nome do Senhor em vão") e estabelece o princípio do descanso sabático, que é uma declaração de confiança de que Deus sustenta o mundo enquanto nós descansamos.',
    desc3: 'A segunda tábua da Lei (os seis últimos mandamentos) trata do nosso relacionamento com o próximo, formando a base de uma sociedade justa. Começa no lar, exigindo honra aos pais. Em seguida, protege a vida ("Não matarás"), protege a pureza e o casamento ("Não adulterarás"), protege a propriedade ("Não furtarás"), protege a verdade e a reputação ("Não dirás falso testemunho") e, finalmente, atinge o coração, proibindo a cobiça ("Não cobiçarás"), mostrando que o pecado começa no desejo interno.',
    concl: 'A Lei é como um espelho: ela nos mostra o padrão perfeito da santidade de Deus e reflete a nossa total incapacidade de cumpri-lo perfeitamente. Ela expõe o nosso pecado e nos condena, mas o seu propósito final é nos conduzir como um aio (tutor) até Cristo, apontando a nossa necessidade desesperada da graça e do sacrifício perfeito que seria revelado na cruz.'
  },
  {
    id: 'ps_1_1_6',
    intro: 'O Salmo 1 serve como o grande portal de entrada para todo o livro dos Salmos. Ele funciona como um prefácio sapiencial que apresenta a escolha fundamental e inevitável da vida humana: existem apenas dois caminhos, duas mentalidades e dois destinos finais. De um lado, o caminho do justo, que é profundamente abençoado e enraizado em Deus; do outro, o caminho do ímpio, que parece prosperar temporariamente, mas que inevitavelmente caminha para a ruína e o julgamento eterno.',
    desc1: 'A verdadeira bênção (felicidade plena) começa com uma separação radical do mal. O justo é descrito pelo que ele NÃO faz: ele não anda no conselho dos ímpios (pensamento), não se detém no caminho dos pecadores (comportamento) e não se assenta na roda dos escarnecedores (pertencimento). Em vez disso, sua vida é definida pelo que ele FAZ: ele tem o seu prazer supremo na lei do Senhor, e nela medita (rumina, murmura, absorve) de dia e de noite, transformando a Palavra na bússola de sua alma.',
    desc2: 'O resultado dessa vida de meditação e separação é ilustrado por uma bela metáfora botânica: o justo é como "árvore plantada junto a correntes de águas". Ele não é um arbusto selvagem, mas foi intencionalmente plantado por Deus. Suas raízes são profundas, o que garante que ele dê o seu fruto na estação certa e que suas folhas não murchem mesmo durante as secas e adversidades da vida. Em tudo o que ele faz, há o selo da prosperidade divina (que é o cumprimento do propósito de Deus, não apenas riqueza material).',
    desc3: 'Em um contraste drástico e aterrorizante, o salmista descreve os ímpios. Eles "não são assim". Eles são comparados à "palha que o vento espalha": sem raiz, sem peso, sem substância e sem futuro. Por causa dessa superficialidade moral e espiritual, os ímpios não subsistirão no dia do juízo, nem os pecadores terão lugar na congregação dos justos. A ilusão da independência de Deus termina em condenação e isolamento eterno.',
    concl: 'O Salmo conclui resumindo a soberania de Deus sobre os destinos humanos: "O Senhor conhece (aprova, guarda, ama) o caminho dos justos, mas o caminho dos ímpios perecerá". Nossas escolhas diárias sobre onde plantamos nossas raízes e quem ouvimos determinam nosso destino eterno. A verdadeira felicidade só é encontrada na submissão alegre à Palavra de Deus.'
  },
  {
    id: 'isa_53_1_12',
    intro: 'Escrito cerca de 700 anos antes do nascimento de Cristo, Isaías 53 é o Santo dos Santos do Antigo Testamento. É a profecia mais clara, chocante e detalhada sobre a obra expiatória do Messias. O profeta levanta o véu do tempo e descreve o "Servo Sofredor" de Yahweh, revelando que a salvação do mundo não viria através de um conquistador militar montado em um cavalo branco, mas através de um substituto inocente que seria esmagado sob o peso da ira divina para pagar o preço da nossa redenção.',
    desc1: 'A profecia começa descrevendo a rejeição absoluta do Servo. Contrariando as expectativas humanas, Ele não tinha beleza física ou majestade real para nos atrair. Ele cresceu como uma "raiz em terra seca". Foi desprezado pelos homens, rejeitado pelo Seu próprio povo, e familiarizado com a dor e o sofrimento mais profundos. Ele foi tratado como alguém de quem os homens escondem o rosto, sendo considerado indigno de atenção ou respeito. O mundo não reconheceu o seu Criador disfarçado em fraqueza.',
    desc2: 'O coração do evangelho e a doutrina da Substituição Penal brilham nos versículos 4 a 6. O profeta declara que Ele tomou sobre si as NOSSAS enfermidades e as NOSSAS dores. Nós achávamos que Deus o estava punindo por Seus próprios pecados, mas a verdade é que Ele foi traspassado pelas NOSSAS transgressões e moído pelas NOSSAS iniquidades. O castigo que nos traz a paz (shalom) estava sobre Ele. Todos nós andávamos desgarrados como ovelhas perdidas, mas o Senhor fez cair sobre Ele a iniquidade de todos nós.',
    desc3: 'A submissão voluntária do Servo é comovente: Ele foi oprimido e afligido, mas não abriu a boca, sendo levado como um cordeiro mudo ao matadouro. Após Sua morte injusta, Ele foi sepultado no túmulo de um homem rico (cumprido em José de Arimateia). No entanto, a morte não é o fim. O versículo 10 revela que "ao Senhor agradou moê-lo", mostrando que a cruz foi o plano soberano do Pai. Após o sacrifício, Deus promete a ressurreição: Ele verá a Sua posteridade, prolongará os Seus dias e será exaltado acima de todos.',
    concl: 'A cruz de Cristo não foi um acidente trágico da história, mas o plano eterno e soberano de Deus para justificar a muitos. A ferida dEle é a nossa cura; a morte dEle é a nossa vida. Isaías 53 nos convida a olhar para o Calvário não com pena do mártir, mas com adoração profunda ao Salvador que bebeu o cálice da ira de Deus em nosso lugar.'
  },
  {
    id: 'mt_5_1_12',
    intro: 'As Bem-Aventuranças formam o majestoso pórtico de entrada do Sermão do Monte, o maior discurso ético de Jesus. Neste texto, Cristo vira os valores do mundo e da religião farisaica completamente de cabeça para baixo. Ele não está entregando um novo conjunto de regras sobre "o que fazer" para ser salvo, mas está descrevendo o caráter interno, a identidade e a atitude daqueles que JÁ pertencem ao Seu Reino. É o manifesto da contracultura cristã, revelando onde reside a verdadeira e eterna felicidade (makarios).',
    desc1: 'As primeiras bem-aventuranças tratam da nossa postura diante de Deus. "Bem-aventurados os pobres de espírito" refere-se àqueles que reconhecem sua total falência espiritual e incapacidade de salvar a si mesmos. "Os que choram" são aqueles que sentem profunda tristeza pelo seu próprio pecado e pela quebra do mundo. "Os mansos" não são fracos, mas pessoas que têm seu poder e força totalmente submetidos ao controle de Deus. A estes, Jesus promete o Reino dos céus, o consolo divino e a herança da terra.',
    desc2: 'O segundo grupo foca na nossa postura em relação à justiça e aos outros. "Os que têm fome e sede de justiça" são aqueles que anseiam desesperadamente pela retidão de Deus, tanto pessoal quanto social, como alguém que morre de inanição. "Os misericordiosos" são aqueles que estendem aos outros a mesma graça que receberam de Deus. "Os puros de coração" são aqueles cujas motivações são limpas e não divididas pela hipocrisia. A promessa é que eles serão fartos, alcançarão misericórdia e, o maior de todos os prêmios, verão a Deus.',
    desc3: 'O último grupo descreve a nossa postura diante de um mundo hostil. "Os pacificadores" não são apenas apaziguadores, mas aqueles que ativamente promovem a reconciliação entre os homens e Deus, refletindo o caráter do Pai. Finalmente, Jesus choca a multidão ao declarar "bem-aventurados os perseguidos por causa da justiça". Ele avisa que viver os valores do Reino inevitavelmente atrairá o ódio do mundo. No entanto, a perseguição não é sinal de derrota, mas a marca dos verdadeiros profetas e a garantia de uma grande recompensa nos céus.',
    concl: 'A verdadeira felicidade (bem-aventurança) não depende das circunstâncias externas, da riqueza ou da aprovação humana, mas de um coração transformado pela graça e radicalmente alinhado com os valores do Reino de Deus. O cidadão do Reino é um estrangeiro na terra, vivendo hoje as realidades da eternidade.'
  },
  {
    id: 'lk_15_11_32',
    intro: 'A Parábola do Filho Pródigo (ou melhor, a Parábola do Pai Misericordioso) é considerada a coroa de todas as parábolas de Jesus. Contada em resposta às críticas dos fariseus de que Jesus "recebia pecadores e comia com eles", esta história não é apenas sobre um filho rebelde que foge para o mundo. É uma exposição magistral sobre dois tipos de filhos perdidos (o rebelde e o religioso) e, acima de tudo, sobre o coração de um Pai cuja graça escandalosa transcende tanto a rebelião aberta quanto a religiosidade orgulhosa e legalista.',
    desc1: 'A história começa com a rebelião chocante do filho mais novo. Ao pedir sua parte da herança antes da morte do pai, ele está essencialmente dizendo: "Eu quero as tuas coisas, mas desejo que tu estejas morto". Ele pega os recursos do pai e foge para uma "terra distante", onde desperdiça tudo vivendo dissolutamente. A busca por liberdade e autonomia longe da casa do Pai sempre termina na mais profunda escravidão e degradação: ele acaba apascentando porcos (o fundo do poço para um judeu) e desejando comer a comida dos animais.',
    desc2: 'No fundo do poço, a graça começa a operar: ele "cai em si". Ele reconhece sua miséria e decide voltar, não exigindo seus direitos de filho, mas esperando ser aceito como um mero empregado. No entanto, o clímax da parábola ocorre quando o Pai o vê de longe. Quebrando todo o protocolo e dignidade patriarcal do Oriente Médio, o Pai corre ao encontro do filho sujo, o abraça e o beija. Ele não permite que o filho termine seu discurso de servo, mas o restaura imediatamente à posição de filho honrado, dando-lhe a melhor roupa, o anel (autoridade) e ordenando uma grande festa.',
    desc3: 'A parábola tem um segundo ato focado no filho mais velho, que representa os fariseus. Ele estava fisicamente no campo do pai, mas seu coração estava tão longe quanto o do irmão mais novo. Ele se recusa a entrar na festa, revelando que servia ao pai por obrigação e interesse ("nunca me deste um cabrito"), e se ressente profundamente da graça estendida ao pecador. O Pai sai novamente, desta vez para implorar ao filho religioso que abandone sua justiça própria e entre na alegria da salvação.',
    concl: 'Deus é o Pai que corre para abraçar pecadores arrependidos, cobrindo sua vergonha com a veste da justiça de Cristo. Ao mesmo tempo, Ele convida os religiosos orgulhosos a reconhecerem que a obediência sem amor é apenas outra forma de rebelião. A grande festa do Reino está aberta, mas só entram aqueles que aceitam a graça imerecida.'
  },
  {
    id: 'jn_1_1_14',
    intro: 'O Prólogo do Evangelho de João é um dos textos mais sublimes, profundos e teologicamente densos de toda a Escritura. Enquanto Mateus e Lucas começam a história de Jesus na manjedoura de Belém, traçando Sua genealogia humana, João retrocede muito além do tempo e do espaço, iniciando seu evangelho na eternidade passada. Ele apresenta Jesus Cristo não apenas como um profeta ou um bom mestre, mas como o Verbo (Logos), a expressão máxima, eterna e criadora do próprio Deus, que rasgou os céus e entrou na história humana para nos resgatar.',
    desc1: 'O texto abre com uma declaração de divindade inquestionável: "No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus". João estabelece que Jesus é eterno (já existia antes da criação), é distinto do Pai (estava com Deus) e compartilha a mesma essência divina (era Deus). Além disso, Ele é o Agente da Criação: "Todas as coisas foram feitas por intermédio dele". Nele estava a vida, e essa vida é a luz dos homens, uma luz tão poderosa que as trevas do pecado e da morte jamais poderão extingui-la ou compreendê-la.',
    desc2: 'João Batista é introduzido não como a luz, mas como a testemunha enviada por Deus para apontar para a verdadeira Luz. O texto então descreve a grande tragédia da encarnação: "Veio para o que era seu, e os seus não o receberam". O Criador foi rejeitado por Sua própria criação; o Messias foi crucificado por Seu próprio povo. No entanto, a tragédia dá lugar ao triunfo da graça: "Mas, a todos quantos o receberam... deu-lhes o poder de serem feitos filhos de Deus". Essa filiação não vem por descendência humana ou esforço carnal, mas pelo milagre do novo nascimento gerado por Deus.',
    desc3: 'O versículo 14 é o ápice da revelação cristã: "E o Verbo se fez carne e habitou entre nós". O infinito tornou-se finito; o invisível tornou-se visível; o Criador tornou-se criatura. A palavra "habitou" no grego (eskenosen) significa literalmente "armou sua tenda" ou "tabernaculou" entre nós. Assim como a glória de Deus enchia o Tabernáculo no deserto, agora a glória de Deus habita no corpo humano de Jesus Cristo, que é descrito como sendo "cheio de graça e de verdade".',
    concl: 'A encarnação é o maior milagre e o maior mistério da história do universo. Deus não nos enviou apenas um manual de instruções ou um anjo com uma mensagem; Ele veio pessoalmente, assumindo a nossa fragilidade, para nos resgatar e nos revelar o coração do Pai. Em Cristo, a graça que perdoa e a verdade que liberta se encontraram perfeitamente.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done');
