const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'mrk_5_25_34',
    intro: 'O encontro de Jesus com a mulher que sofria de fluxo de sangue é uma das narrativas mais tocantes sobre a fé desesperada e a compaixão de Cristo. Jesus estava a caminho da casa de Jairo, um importante líder da sinagoga, para curar a sua filha que estava morrendo. Uma grande multidão O apertava de todos os lados. No meio desse caos e da urgência da missão principal, uma mulher marginalizada, impura e exausta decide arriscar tudo por um toque. Esta história revela que, para Jesus, não há interrupções indesejadas quando se trata de responder à fé genuína.',
    desc1: 'A condição da mulher era desesperadora em todos os níveis. Fisicamente, ela sofria de uma hemorragia contínua há doze anos. Financeiramente, ela havia gasto tudo o que tinha com médicos, sem nenhum resultado, "indo antes a pior". Social e religiosamente, a lei levítica (Levítico 15) a declarava cerimonialmente impura; ela não podia participar da adoração no templo e qualquer pessoa que ela tocasse também se tornaria impura. Ela era uma intocável, vivendo em isolamento e vergonha. Muitas vezes, é apenas quando chegamos ao fim dos nossos recursos humanos que nos voltamos verdadeiramente para o poder divino.',
    desc2: 'Apesar de sua condição, ela ouviu falar de Jesus. A fé vem pelo ouvir. Ela não pediu uma audiência pública nem exigiu que Jesus impusesse as mãos sobre ela. A sua teologia era simples, mas poderosa: "Se eu apenas lhe tocar as vestes, ficarei curada". Ela rompe a multidão (um ato de extrema coragem, pois estava tornando os outros impuros ao tocá-los) e toca na orla da veste de Jesus. Imediatamente, a fonte do seu sangue seca, e ela sente no corpo que está curada. A fé verdadeira não espera passivamente; ela age e supera os obstáculos para alcançar Cristo.',
    desc3: 'Jesus para a multidão e pergunta: "Quem tocou nas minhas vestes?". Os discípulos acham a pergunta absurda, pois a multidão O apertava. Mas Jesus sabia a diferença entre o toque acidental da multidão e o toque intencional da fé. Ele não queria apenas curá-la fisicamente; Ele queria restaurá-la socialmente e salvá-la espiritualmente. Tremendo de medo, ela se prostra e conta "toda a verdade". Jesus não a repreende por tê-Lo tocado, mas a chama pelo título mais afetuoso: "Filha, a tua fé te salvou; vai-te em paz, e fica livre do teu mal".',
    concl: 'No meio de uma multidão barulhenta e de agendas urgentes, Jesus sempre sente o toque da fé de um coração quebrantado. Ele não apenas nos cura das nossas aflições físicas ou emocionais, mas nos chama de "filhos", remove a nossa vergonha e nos despede com a Sua paz perfeita.'
  },
  {
    id: 'gen_37_12_36',
    intro: 'O capítulo 37 de Gênesis marca o início da longa e complexa jornada de José. Sendo o filho favorito de Jacó, José recebeu uma túnica ornamentada e teve sonhos proféticos de grandeza, o que gerou um ódio profundo e inveja mortal em seus irmãos mais velhos. Quando Jacó envia José para verificar como estão os seus irmãos que apascentavam o rebanho longe de casa, a armadilha é armada. Esta narrativa é um estudo profundo sobre a anatomia da inveja, a crueldade humana e, acima de tudo, a providência invisível de Deus que orquestra até mesmo as piores tragédias para cumprir os Seus propósitos redentores.',
    desc1: 'A inveja dos irmãos havia se transformado em ódio assassino. Quando veem José de longe, antes mesmo que ele chegasse, eles conspiram: "Lá vem o sonhador! Vinde, pois, agora, matemo-lo... e veremos o que será dos seus sonhos". A inveja nunca é um pecado estático; se não for mortificada, ela sempre evolui para a destruição do outro. Rúben, o mais velho, tenta intervir e sugere que o joguem em um poço vazio, com a intenção de resgatá-lo mais tarde. Eles arrancam a túnica de José (o símbolo do favor do pai) e o lançam na cisterna escura e sem água.',
    desc2: 'O contraste na cena seguinte é chocante e revela a dureza dos corações dos irmãos: enquanto José está no fundo do poço, provavelmente clamando por misericórdia, eles se sentam "para comer pão". O pecado endurece a consciência a ponto de podermos desfrutar de uma refeição enquanto o nosso irmão sofre por nossa causa. Judá, vendo uma caravana de ismaelitas se aproximando, tem uma ideia movida pela ganância: em vez de matá-lo e esconder o sangue, por que não lucrar com ele? Eles vendem o próprio irmão como escravo por vinte moedas de prata.',
    desc3: 'Para encobrir o crime, os irmãos matam um cabrito, mancham a túnica de José com o sangue e a levam a Jacó, deixando que o pai tire a pior conclusão: "Uma besta-fera o devorou". Jacó entra em um luto inconsolável, recusando ser confortado. A mentira destrói a paz da família por décadas. Enquanto isso, José é levado para o Egito e vendido a Potifar, oficial de Faraó. O que parece ser o fim trágico dos sonhos de José e o triunfo da maldade dos irmãos é, na verdade, o primeiro passo geográfico e estratégico de Deus para salvar toda a família da fome que viria anos depois.',
    concl: 'A história da venda de José nos ensina que a maldade humana é real e dolorosa, mas nunca é soberana. Deus está trabalhando nos bastidores, transformando a cisterna da traição e a escravidão no Egito no caminho exato para a salvação. Como José diria mais tarde: "Vós intentastes o mal contra mim, mas Deus o tornou em bem".'
  },
  {
    id: 'exo_12_1_14',
    intro: 'O capítulo 12 de Êxodo descreve a instituição da Páscoa (Pessach), o evento central da redenção no Antigo Testamento e o clímax do confronto entre Deus e Faraó. Após nove pragas que devastaram o Egito, Faraó continuava com o coração endurecido. A décima e última praga — a morte dos primogênitos — seria o golpe definitivo que forçaria a libertação de Israel. No entanto, a Páscoa não é apenas sobre o juízo sobre o Egito; é, principalmente, sobre a provisão de Deus para salvar o Seu próprio povo da morte através do sangue de um cordeiro substituto, prefigurando perfeitamente o sacrifício de Jesus Cristo.',
    desc1: 'Deus instrui Moisés e Arão de que este mês seria o "princípio dos meses" para Israel. A redenção marca um novo começo, um novo calendário espiritual. No décimo dia do mês, cada família deveria escolher um cordeiro ou cabrito. As especificações eram estritas: o animal deveria ser "sem defeito, macho de um ano". A perfeição do cordeiro era essencial, pois ele representava a pureza exigida por Deus para um sacrifício aceitável. O cordeiro deveria ser guardado até o décimo quarto dia, permitindo que a família o observasse e atestasse a sua perfeição antes do sacrifício.',
    desc2: 'No crepúsculo do décimo quarto dia, toda a congregação de Israel deveria imolar o cordeiro. O sangue do animal não deveria ser guardado, mas aplicado com um feixe de hissopo nas duas ombreiras e na verga da porta das casas onde o comeriam. A carne deveria ser assada no fogo e comida naquela mesma noite, com pães asmos (sem fermento, símbolo de pureza e pressa) e ervas amargas (lembrança da amargura da escravidão). Eles deveriam comer apressadamente, com os lombos cingidos e cajado na mão, prontos para a jornada da libertação.',
    desc3: 'O propósito do sangue nas portas é o cerne do Evangelho: "E o sangue vos será por sinal nas casas em que estiverdes; vendo eu o sangue, passarei por cima de vós (Páscoa), e não haverá entre vós praga de mortandade, quando eu ferir a terra do Egito". O anjo destruidor não pouparia as casas dos israelitas porque eles eram moralmente superiores aos egípcios, mas exclusivamente porque estavam abrigados sob o sangue do cordeiro substituto. A salvação não dependia das boas obras de quem estava dentro da casa, mas do sangue aplicado do lado de fora.',
    concl: 'A Páscoa do Antigo Testamento é a sombra da qual Cristo é a realidade. Como Paulo declara: "Cristo, nossa Páscoa, foi sacrificado por nós" (1 Coríntios 5:7). O Cordeiro de Deus, sem pecado e sem defeito, derramou o Seu sangue na cruz para que o juízo de Deus "passe por cima" de todos aqueles que, pela fé, aplicam o Seu sangue nas portas dos seus corações.'
  },
  {
    id: '1sa_3_1_10',
    intro: 'O chamado de Samuel ocorre em um dos períodos mais sombrios da história espiritual de Israel. O texto começa com um diagnóstico triste: "E a palavra do Senhor era de muita valia naqueles dias; não havia visão manifesta". A liderança sacerdotal estava corrompida pelos filhos de Eli (Hofni e Fineias), e o próprio Eli, velho e com a visão enfraquecida, havia falhado em corrigir a sua casa. É nesse cenário de silêncio divino e decadência institucional que Deus decide falar novamente. Mas Ele não fala com o sumo sacerdote ou com os líderes políticos; Ele escolhe falar com um menino que servia no templo, ensinando-nos sobre a importância de ter ouvidos atentos e um coração submisso.',
    desc1: 'O cenário é descrito com detalhes simbólicos: Eli estava deitado no seu lugar, com os olhos escurecidos, enquanto Samuel dormia no templo do Senhor, "onde estava a arca de Deus", e a "lâmpada de Deus ainda não se havia apagado". A lâmpada tremeluzente representa a esperança de que Deus ainda não havia desistido de Israel. Deus chama Samuel pelo nome. Samuel, não conhecendo ainda a voz de Deus (pois a Palavra ainda não lhe tinha sido revelada), corre para Eli, achando que o velho sacerdote o havia chamado. A prontidão de Samuel em servir a Eli demonstra o seu coração obediente.',
    desc2: 'Isso acontece três vezes. A confusão de Samuel é natural; ele estava acostumado a ouvir apenas a voz humana no templo. Na terceira vez, Eli, apesar de suas falhas, percebe o que está acontecendo e dá a Samuel o melhor conselho teológico de sua vida: "Vai deitar-te e há de ser que, se te chamar, dirás: Fala, Senhor, porque o teu servo ouve". Eli ensina o menino a mudar o seu foco da voz humana para a voz divina e a assumir a postura correta de um discípulo: a submissão atenta.',
    desc3: 'Deus vem, põe-se ali e chama como das outras vezes: "Samuel, Samuel!". A repetição do nome indica urgência e afeto divino. Desta vez, Samuel responde exatamente como foi instruído: "Fala, porque o teu servo ouve". A partir desse momento, Deus começa a revelar a Samuel os Seus propósitos (começando com a dura mensagem de juízo sobre a casa de Eli). Samuel cresce, e o Senhor é com ele, e "nenhuma de todas as suas palavras deixou cair em terra". O menino que aprendeu a ouvir tornou-se o grande profeta que falou por Deus a toda a nação.',
    concl: 'Em tempos de confusão e silêncio espiritual, Deus ainda procura corações que estejam dispostos a ouvir. O chamado de Samuel nos ensina que a verdadeira intimidade com Deus não depende de idade, posição ou experiência religiosa, mas de uma postura humilde que diz diariamente: "Fala, Senhor, porque o teu servo ouve".'
  },
  {
    id: '2ki_5_1_14',
    intro: 'A história da cura de Naamã é uma das narrativas mais ricas do Antigo Testamento sobre a graça de Deus alcançando os gentios e sobre a necessidade absoluta de humildade para receber o milagre. Naamã era o comandante do exército da Síria, um homem de grande poder, prestígio, vitórias militares e respeito diante do rei. No entanto, o texto introduz um "porém" devastador: "era ele herói valoroso, porém leproso". A lepra era uma doença incurável, estigmatizante e fatal. Todo o poder, dinheiro e influência de Naamã eram inúteis diante da sua condição. A sua jornada em busca de cura revela que Deus não se impressiona com os nossos títulos, mas exige a rendição do nosso orgulho.',
    desc1: 'A esperança para Naamã não vem de um rei ou de um general, mas de uma fonte improvável: uma pequena menina israelita, levada cativa, que servia à esposa de Naamã. Apesar de ser escrava em terra estrangeira, ela não guarda amargura, mas compartilha a sua fé: "Tomara que o meu senhor estivesse diante do profeta que está em Samaria; ele o restauraria da sua lepra". Naamã, desesperado, agarra-se a essa esperança. Ele viaja para Israel com uma fortuna em prata, ouro e roupas finas, e com uma carta do rei da Síria para o rei de Israel. Ele tenta comprar o milagre usando a diplomacia e a riqueza.',
    desc2: 'Quando Naamã chega à porta da casa do profeta Eliseu com seus cavalos e carros (esperando ser recebido com honras de Estado), Eliseu nem sequer sai para recebê-lo. Em vez disso, envia um mensageiro com uma instrução simples e humilhante: "Vai, e lava-te sete vezes no Jordão, e a tua carne te tornará, e ficarás purificado". Naamã fica furioso. O seu orgulho é ferido por duas razões: primeiro, o profeta não o tratou com a deferência que ele achava que merecia (não fez um ritual mágico); segundo, o rio Jordão era barrento e inferior aos rios limpos de Damasco. O orgulho quase o faz perder o milagre.',
    desc3: 'Naamã dá as costas para ir embora indignado, mas os seus servos, com grande sabedoria, o confrontam: "Meu pai, se o profeta te dissesse alguma grande coisa, porventura não a farias? Quanto mais, dizendo-te ele: Lava-te, e ficarás purificado". Naamã é forçado a engolir o seu orgulho. Ele desce ao Jordão e mergulha sete vezes, conforme a palavra do homem de Deus. No sétimo mergulho, o milagre acontece: "a sua carne tornou-se como a carne de um menino, e ficou purificado". A cura não estava na água do Jordão, mas na obediência humilde à Palavra de Deus.',
    concl: 'A graça de Deus não pode ser comprada com as nossas riquezas nem exigida pelos nossos títulos. Ela só é recebida quando descemos do "carro" do nosso orgulho, reconhecemos a nossa condição incurável e obedecemos à Palavra de Deus, por mais simples ou humilhante que ela possa parecer à nossa lógica humana.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 9');
