const fs = require('fs');

const paragraphs = [
  "A Missiologia é o estudo sistemático da missão cristã. Ela não é apenas uma disciplina prática sobre 'como fazer missões', mas uma reflexão teológica profunda sobre o propósito de Deus para o mundo. No nível doutoral, entendemos que a missão nasce no coração da Trindade: o Pai envia o Filho, e o Pai e o Filho enviam o Espírito, que por sua vez envia a Igreja.",
  "O conceito de Missio Dei (Missão de Deus) revolucionou a missiologia moderna. Ele afirma que a missão não é uma invenção humana ou um programa da igreja, mas uma extensão do caráter de Deus. Deus é um Deus missionário. Isso significa que a Igreja não 'tem' uma missão, mas a Missão de Deus 'tem' uma Igreja para servi-la no mundo.",
  "A relação entre Evangelização e Responsabilidade Social é um dos grandes debates missiológicos. A Missão Integral defende que não há dicotomia entre o cuidado com a alma e o cuidado com o corpo. Assim como Jesus pregou o arrependimento e curou os enfermos, a Igreja é chamada a proclamar o Evangelho e lutar contra a injustiça e a pobreza.",
  "A Contextualização é a arte e a ciência de comunicar o Evangelho de forma que ele faça sentido em uma cultura específica. O desafio é ser 'culturalmente relevante' sem ser 'teologicamente infiel'. No nível avançado, estudamos como o Evangelho deve confrontar os ídolos de cada cultura enquanto utiliza suas formas de linguagem e pensamento para expressar a verdade eterna.",
  "A História das Missões revela ciclos de expansão e retração. Desde as viagens de Paulo até o movimento missionário moderno, vemos como Deus usa vasos de barro para levar o tesouro do Evangelho. Estudamos os erros do passado, como a associação entre missões e colonialismo, para construir um modelo de missão baseado na humildade e na parceria global.",
  "A Janela 10/40 e os Povos Não Alcançados (PNAs) continuam sendo prioridades estratégicas. Milhares de grupos étnicos ainda não têm acesso ao Evangelho em sua própria língua e cultura. A missiologia estratégica busca identificar esses grupos e desenvolver métodos criativos de entrada e plantação de igrejas em contextos hostis ou fechados.",
  "O papel do Missionário mudou na era da 'missão de todos os lugares para todos os lugares'. Hoje, o Sul Global (África, Ásia e América Latina) envia mais missionários do que o Norte Global. A missão não é mais um movimento do 'Ocidente para o Resto', mas um esforço policêntrico onde cada igreja local é um centro de envio e recepção.",
  "A Missiologia e as Religiões Mundiais exigem um diálogo respeitoso, mas fiel à exclusividade de Cristo. No nível doutoral, analisamos como abordar o Islã, o Hinduísmo e o Budismo com amor e clareza teológica. O objetivo não é apenas a comparação de religiões, mas a demonstração de que Jesus é o Caminho, a Verdade e a Vida para todos os povos.",
  "O sofrimento e o martírio são realidades intrínsecas à missão. A história da igreja é escrita com o sangue dos mártires. A missiologia do sofrimento nos ensina que a cruz é o modelo da missão. Onde o Evangelho avança, muitas vezes há oposição, e a fidelidade a Cristo em meio à perseguição é o testemunho mais poderoso que a Igreja pode dar.",
  "A Tecnologia e a Missão Digital abrem novas fronteiras. Redes sociais, aplicativos bíblicos e transmissões online permitem que o Evangelho ultrapasse fronteiras físicas. No entanto, discutimos como manter a natureza encarnacional da missão em um mundo virtual, garantindo que a tecnologia sirva para criar comunidades reais de discípulos.",
  "A Missiologia e a Ecologia (Missão e Criação) reconhecem que a redenção de Cristo abrange toda a criação. O cuidado com o meio ambiente é visto como parte da mordomia cristã e do testemunho do Reino de Deus. Uma igreja que negligencia a criação de Deus compromete sua mensagem sobre o Criador e Redentor.",
  "A Formação Missionária deve ser holística, envolvendo caráter, conhecimento e competência. Não basta ter paixão; é preciso ter preparo cultural, linguístico e teológico. No nível doutoral, enfatizamos a necessidade de missionários que sejam teólogos reflexivos e praticantes humildes, capazes de aprender com a cultura local enquanto ensinam a Palavra.",
  "A Missão Urbana foca nos grandes centros populacionais do mundo. As cidades são cadinhos de culturas e centros de influência. Pregar o Evangelho nas metrópoles exige estratégias específicas para lidar com o secularismo, a diversidade extrema e as desigualdades sociais gritantes, buscando a 'paz da cidade'.",
  "A Missiologia e a Unidade da Igreja (Ecumenismo Missionário) lembram que o mundo crerá quando formos um. A desunião cristã é um obstáculo à missão. Buscamos formas de cooperação entre diferentes tradições evangélicas para maximizar o impacto do Evangelho, mantendo a integridade doutrinária enquanto trabalhamos juntos pela causa de Cristo.",
  "A Escatologia e a Missão estão profundamente ligadas. A missão é o sinal do fim. Jesus afirmou que o Evangelho do Reino seria pregado em todo o mundo, e então viria o fim. A urgência missionária é alimentada pela esperança da volta de Cristo e pelo desejo de que pessoas de todas as tribos e línguas estejam diante do trono.",
  "A teologia da missão transcultural e o desafio da encarnação do Evangelho. No nível doutoral, exploramos como o missionário deve se despir de sua própria cultura para se revestir da cultura do outro, sem comprometer a verdade bíblica. O modelo é a encarnação de Cristo, que se fez um de nós para nos salvar. O objetivo é que a mensagem de Deus seja ouvida e compreendida em termos locais, permitindo que a fé floresça de forma autêntica e relevante em cada grupo étnico.",
  "O papel da antropologia missionária na compreensão das cosmovisões. No nível doutoral, analisamos como as crenças, os valores e os mitos de um povo moldam sua recepção do Evangelho. O missionário deve ser um estudioso da cultura, identificando as 'pontes de redenção' e os 'pontos de confronto'. O objetivo é uma comunicação eficaz que atinja o coração da cultura, transformando-a de dentro para fora pelo poder regenerador da Palavra de Deus.",
  "A importância da plantação de igrejas autóctones e a liderança local. No nível doutoral, discutimos como a missão deve visar a autonomia e a maturidade da igreja nacional. O missionário deve trabalhar para se tornar desnecessário, treinando líderes locais que assumam a responsabilidade pelo pastoreio e pela expansão. O objetivo é uma igreja que seja autogerida, autofinanciada e autopropagadora, refletindo a identidade e a força do povo que a compõe.",
  "O desafio da missão em contextos de perseguição religiosa extrema. No nível doutoral, analisamos as estratégias de sobrevivência e de crescimento da igreja sob regimes hostis. A missão 'sob o radar' exige criatividade, coragem e uma profunda dependência do Espírito Santo. O objetivo é que o testemunho cristão permaneça firme mesmo nas trevas, demonstrando que a luz de Cristo não pode ser apagada pela força humana e que o sangue dos mártires continua a ser a semente da igreja.",
  "A relação entre missão e desenvolvimento comunitário sustentável. No nível doutoral, exploramos como a igreja pode ser um agente de transformação social através de projetos de educação, saúde e geração de renda. A missão não deve apenas pregar, mas também demonstrar o amor de Deus de forma tangível. O objetivo é a melhoria da qualidade de vida das comunidades, combatendo a pobreza e a injustiça como uma expressão do Reino de Deus que traz dignidade e esperança para todos.",
  "O papel das missões de curto prazo e o voluntariado missionário. No nível doutoral, discutimos os benefícios e os riscos dessas viagens rápidas. Elas podem despertar a paixão missionária e oferecer suporte pontual, mas também podem gerar dependência ou causar danos culturais se não forem bem planejadas. O objetivo é que as missões de curto prazo sejam integradas a estratégias de longo prazo, servindo como um apoio real aos obreiros de campo e como uma ferramenta de mobilização para a igreja enviadora.",
  "A importância da intercessão missionária e do suporte espiritual aos obreiros. No nível doutoral, reafirmamos que a missão é uma batalha espiritual que se vence de joelhos. A igreja deve sustentar seus missionários com oração constante, combatendo as forças que se opõem ao avanço do Evangelho. O objetivo é uma cobertura espiritual que proteja a família missionária e que abra as portas para a pregação, reconhecendo que o sucesso da missão depende da intervenção soberana de Deus.",
  "O desafio da missão urbana e a evangelização das grandes metrópoles. No nível doutoral, analisamos a complexidade das cidades como centros de poder, diversidade e desigualdade. A missão urbana exige abordagens específicas para atingir diferentes classes sociais e subculturas. O objetivo é que a igreja seja uma presença profética e compassiva no coração da cidade, buscando a paz do centro urbano e oferecendo o Evangelho como a única resposta para o vazio e para a solidão das massas.",
  "A ética da parceria missionária e a cooperação entre agências e igrejas. No nível doutoral, exploramos como evitar a competição e o desperdício de recursos no campo missionário. A unidade do corpo de Cristo deve se manifestar na colaboração estratégica para atingir os povos não alcançados. O objetivo é uma rede global de cooperação onde cada parte contribui com seus dons e recursos, maximizando o impacto do Evangelho e demonstrando ao mundo a força da fraternidade cristã.",
  "A importância da teologia da missão para a igreja local (Igreja Missional). No nível doutoral, defendemos que cada congregação deve se ver como um posto avançado da missão de Deus em seu próprio bairro. A missão não é algo que acontece apenas 'lá longe', mas é a razão de ser da igreja em qualquer lugar. O objetivo é que cada membro se torne um missionário em seu cotidiano, testemunhando de Cristo em sua família, trabalho e comunidade, transformando a realidade local.",
  "O papel das artes e da criatividade na comunicação transcultural do Evangelho. No nível doutoral, analisamos como a música, a pintura, o teatro e a literatura podem ser usados para expressar as verdades bíblicas de forma que ressoe com a estética local. O objetivo é que o Evangelho não seja visto como uma religião estrangeira, mas como uma mensagem que fala a linguagem da alma e que utiliza a beleza para atrair as pessoas para a glória do Criador.",
  "O desafio da missão entre povos nômades e grupos de difícil acesso geográfico. No nível doutoral, exploramos as dificuldades logísticas e culturais de alcançar tribos isoladas ou populações em constante movimento. A missão exige perseverança, adaptação e o uso de tecnologias de comunicação que superem as barreiras físicas. O objetivo é que nenhum grupo humano seja esquecido e que a voz de Deus chegue aos lugares mais remotos e inóspitos da terra.",
  "A importância da pesquisa missiológica e do mapeamento de povos não alcançados. No nível doutoral, discutimos como o uso de dados e de estatísticas pode ajudar na definição de prioridades estratégicas. O objetivo é uma missão inteligente que direcione os recursos para onde a necessidade é maior, garantindo que o esforço missionário seja focado e eficaz na tarefa de levar o Evangelho a cada etnia e língua, conforme a ordem do Senhor.",
  "A visão da missão como um ato de adoração e de exaltação do nome de Jesus entre as nações. No nível doutoral, reafirmamos que o fim último da missão é que Deus seja adorado por todos os povos. A evangelização é o meio; a adoração é o fim. O objetivo é o dia em que uma grande multidão de todas as nações, tribos, povos e línguas estará diante do trono, proclamando que a salvação pertence ao nosso Deus e ao Cordeiro, para todo o sempre.",
  "A teologia da missão e a justiça social: uma perspectiva doutoral. Analisamos como o compromisso com o Evangelho exige uma postura ativa contra as estruturas de pecado que oprimem os pobres e marginalizados. A missão não é completa se ignorar o clamor por justiça. O objetivo é que a igreja seja um sinal do Reino, onde a retidão e a paz se beijam, e onde o amor de Deus se manifesta na restauração da dignidade de cada ser humano criado à Sua imagem.",
  "O papel da educação teológica na formação de uma mentalidade missional. No nível doutoral, discutimos como os seminários e institutos bíblicos devem preparar líderes que não sejam apenas acadêmicos, mas missionários apaixonados. A teologia deve ser feita em diálogo com a missão. O objetivo é uma liderança que saiba articular a fé de forma profunda e que saiba liderar a igreja para fora de suas fronteiras, em direção aos campos que já estão brancos para a ceifa.",
  "O desafio da missão em contextos de migração e deslocamento forçado. No nível doutoral, exploramos como a 'diáspora' pode ser uma oportunidade estratégica para o avanço do Evangelho. Deus muitas vezes move os povos para que eles O busquem. O objetivo é que a igreja acolha o estrangeiro e o refugiado, vendo neles não apenas uma necessidade social, mas um campo missionário prioritário e uma fonte de novos obreiros para as nações.",
  "A importância da saúde mental e do cuidado emocional do missionário. No nível doutoral, analisamos o impacto do estresse cultural, da solidão e do trauma no campo missionário. A missão exige resiliência, mas também exige suporte e vulnerabilidade. O objetivo é que as agências e igrejas desenvolvam sistemas de cuidado que garantam a longevidade e a saúde dos obreiros, reconhecendo que vasos de barro precisam de manutenção constante para carregar o tesouro do Evangelho.",
  "A relação entre missão e apologética no mundo pós-cristão. No nível doutoral, discutimos como defender a fé de forma mansa e respeitosa em culturas que abandonaram suas raízes cristãs. A missão exige uma resposta intelectualmente sólida para os questionamentos da modernidade e da pós-modernidade. O objetivo é uma pregação que convença a mente e que atraia o coração, demonstrando que o Evangelho é a verdade que liberta e que dá sentido à existência humana.",
  "O papel das mulheres na história e na prática das missões globais. No nível doutoral, resgatamos o legado de tantas mulheres que foram pioneiras em campos difíceis e que lideraram movimentos de transformação. A missão de Deus utiliza todos os Seus filhos e filhas. O objetivo é o reconhecimento e o encorajamento do ministério feminino na missão, garantindo que os dons de todas as pessoas sejam plenamente utilizados para a glória de Deus e para o bem das nações.",
  "A importância da tecnologia de tradução bíblica para os povos sem escrita. No nível doutoral, exploramos como o uso de softwares e de inteligência artificial pode acelerar a tarefa de dar a cada povo a Palavra de Deus em sua própria língua. O objetivo é que a Bíblia seja acessível a todos, pois a Palavra é o fundamento da fé e a ferramenta indispensável para o discipulado e para a plantação de igrejas saudáveis e duradouras.",
  "O desafio da missão entre a Geração Z e as novas juventudes globais. No nível doutoral, analisamos as mudanças de valores e de linguagem que exigem novas formas de evangelização. A missão deve ser autêntica, relacional e digitalmente presente. O objetivo é que a igreja saiba comunicar a mensagem eterna de Cristo de uma forma que ressoe com os anseios por propósito e por comunidade das novas gerações, garantindo a continuidade do testemunho cristão.",
  "A ética do financiamento missionário e a transparência na gestão de recursos. No nível doutoral, discutimos como a igreja deve administrar as ofertas para missões com integridade e prestação de contas. O dinheiro de missões é sagrado e deve ser usado com sabedoria e foco. O objetivo é uma gestão que honre a Deus e que gere confiança nos doadores, garantindo que o suporte chegue efetivamente ao campo e que os recursos sejam multiplicados para o avanço do Reino.",
  "A importância da teologia da hospitalidade na missão transcultural. No nível doutoral, exploramos como o ato de abrir a casa e a vida pode ser a ferramenta mais poderosa de evangelização. A missão é feita de relacionamentos. O objetivo é que o missionário aprenda a ser um hóspede humilde antes de ser um mestre, ganhando o direito de ser ouvido através do serviço e do amor sacrificial que acolhe o outro como Cristo nos acolheu.",
  "O papel das missões empresariais (Business as Mission - BAM). No nível doutoral, analisamos como o trabalho secular pode ser uma plataforma legítima e eficaz para a missão em países fechados. O profissional cristão é um missionário em tempo integral em seu local de trabalho. O objetivo é a integração entre fé e profissão, onde o sucesso nos negócios serve para a glória de Deus e para a criação de oportunidades de testemunho em contextos onde a religião é restrita.",
  "O desafio da missão em contextos de conflito armado e de violência urbana. No nível doutoral, exploramos como a igreja pode ser uma agente de reconciliação e de paz em meio ao caos. A missão exige uma presença corajosa que denuncie a violência e que ofereça o perdão de Cristo. O objetivo é que a igreja seja um refúgio de esperança e um exemplo de como o amor pode superar o ódio, transformando inimigos em irmãos através do poder da cruz.",
  "A importância da mentoria e do discipulado de novos missionários. No nível doutoral, discutimos a necessidade de um acompanhamento geracional que transmita a sabedoria e a experiência dos veteranos para os novatos. A missão não se aprende apenas nos livros, mas na vida compartilhada. O objetivo é uma sucessão saudável no campo missionário, onde o bastão da fé é passado com cuidado e onde os novos obreiros são fortalecidos pela herança de fidelidade dos que vieram antes.",
  "A visão da missão como uma participação na vitória final de Cristo. No nível doutoral, reafirmamos que a missão não é um esforço incerto, mas a proclamação de um triunfo já conquistado na cruz e na ressurreição. O objetivo é uma igreja que caminha com confiança e com autoridade, sabendo que as portas do inferno não prevalecerão contra ela e que o Senhor Jesus está conosco todos os dias, até a consumação dos séculos.",
  "A teologia da missão e a escatologia: uma perspectiva doutoral. Analisamos como a missão é impulsionada pela esperança do retorno de Cristo e pelo estabelecimento pleno do Seu Reino. A pregação do Evangelho a todas as nações é o prelúdio para o fim. O objetivo é que a igreja viva com um senso de urgência e de expectativa, trabalhando incansavelmente para que o maior número possível de pessoas conheça a salvação antes do grande dia do Senhor.",
  "O papel da missiologia na revitalização de igrejas locais em declínio. No nível doutoral, discutimos como o foco na missão externa pode trazer vida e propósito para congregações que se tornaram introspectivas. Uma igreja que não evangeliza, morre. O objetivo é que a visão missionária renove o fervor espiritual e a relevância da igreja em sua comunidade, transformando-a de um clube social em um exército de proclamadores da graça de Deus.",
  "O desafio da missão em contextos de secularização e de indiferença religiosa. No nível doutoral, exploramos como despertar o interesse pelo sagrado em sociedades que consideram Deus irrelevante. A missão exige uma abordagem que fale aos anseios profundos do ser humano por significado e por transcendência. O objetivo é demonstrar que o Evangelho oferece uma resposta superior às ideologias seculares, trazendo uma esperança que não decepciona.",
  "A importância da ética missionária no trato com outras religiões e culturas. No nível doutoral, analisamos como evitar o proselitismo coercitivo e o desrespeito às crenças alheias. A missão deve ser feita com amor, verdade e liberdade. O objetivo é um testemunho que atraia pela integridade e pela beleza da vida cristã, permitindo que as pessoas façam uma escolha consciente e livre por seguir a Cristo, baseada na convicção do Espírito Santo.",
  "A relação entre missão e a unidade visível do corpo de Cristo. No nível doutoral, discutimos como a fragmentação denominacional prejudica o testemunho cristão perante o mundo. A missão exige cooperação e humildade entre as diferentes tradições evangélicas. O objetivo é que o mundo veja o nosso amor uns pelos outros e creia que o Pai enviou o Filho, reconhecendo que a mensagem do Evangelho é validada pela nossa unidade em torno do essencial.",
  "O papel das missões entre povos indígenas e a preservação da identidade cultural. No nível doutoral, exploramos como o Evangelho pode ser plantado em culturas tribais sem destruir sua herança linguística e social. A missão deve valorizar a diversidade da criação de Deus. O objetivo é que cada povo adore a Deus em sua própria língua e com suas próprias formas de expressão, enriquecendo o mosaico da igreja global com sua singularidade.",
  "A importância da teologia da missão para a compreensão da identidade da igreja. No nível doutoral, reafirmamos que a igreja não existe para si mesma, mas para o mundo. A missão é a essência da igreja, não um departamento. O objetivo é que cada crente compreenda que sua vocação cristã é intrinsecamente missionária, e que sua vida deve ser um reflexo da luz de Cristo em todos os lugares onde ele estiver inserido.",
  "O desafio da missão em contextos de extrema pobreza e de injustiça estrutural. No nível doutoral, analisamos como a pregação do Evangelho deve ser acompanhada por ações que promovam a justiça e a dignidade humana. A missão integral não separa o espiritual do social. O objetivo é que a igreja seja a voz dos sem voz e a mão que socorre o necessitado, demonstrando que o Reino de Deus é um Reino de justiça, de paz e de alegria no Espírito.",
  "A ética do uso de mídias sociais e de ferramentas digitais na evangelização global. No nível doutoral, discutimos como aproveitar o alcance da internet sem cair na superficialidade ou na manipulação. A missão digital deve visar o discipulado real e a formação de comunidades autênticas. O objetivo é que a tecnologia seja um canal para encontros genuínos com a Palavra de Deus, levando as pessoas do mundo virtual para a comunhão viva da igreja local.",
  "A importância da formação de redes de oração e de intercessão por missões mundiais. No nível doutoral, reafirmamos que a obra missionária é sustentada pelo poder de Deus liberado através da oração da igreja. O objetivo é uma mobilização global de intercessores que clamem pelas nações, pelos missionários e pelos povos não alcançados, reconhecendo que sem a unção do Espírito, todo esforço humano é em vão na tarefa de salvar almas.",
  "O papel da missiologia na reflexão sobre o colonialismo e o pós-colonialismo. No nível doutoral, analisamos criticamente como a missão foi muitas vezes confundida com a expansão cultural e política do Ocidente. A missão hoje deve ser marcada pelo arrependimento e pela busca de modelos de parceria igualitária. O objetivo é um movimento missionário que seja genuinamente global e que respeite a soberania e a dignidade de cada povo e nação.",
  "O desafio da missão entre as elites intelectuais e os formadores de opinião. No nível doutoral, exploramos como comunicar o Evangelho em ambientes acadêmicos e de alta influência social. A missão exige uma apologética sofisticada e uma presença cristã que demonstre a coerência e a relevância da fé para todos os campos do saber. O objetivo é que a luz de Cristo brilhe também nos centros de pensamento, transformando a cultura a partir de suas lideranças.",
  "A importância da teologia do sofrimento para a perseverança missionária em campos hostis. No nível doutoral, discutimos como a compreensão bíblica da dor e da perseguição fortalece o obreiro diante das dificuldades. A missão não promete facilidades, mas a presença constante de Cristo. O objetivo é que o missionário encontre em Deus a força para permanecer fiel, sabendo que seu trabalho não é em vão e que a glória futura compensa qualquer aflição presente.",
  "A visão da missão como o cumprimento da promessa de Deus a Abraão de abençoar todas as famílias da terra. No nível doutoral, reafirmamos que a missão é o fio condutor de toda a história bíblica, desde o Gênesis até o Apocalipse. O objetivo é que a igreja se veja como herdeira dessa promessa e como instrumento de Deus para que a Sua bênção chegue a cada etnia, cumprindo o plano eterno de redenção da humanidade.",
  "A teologia da missão e a ecologia: uma perspectiva doutoral. Analisamos como o cuidado com a criação é uma dimensão essencial da missão de Deus. A redenção de Cristo abrange todo o cosmos. O objetivo é que a igreja seja um exemplo de mordomia ambiental, demonstrando que o amor ao Criador implica no respeito e na preservação da Sua obra, e que a crise ecológica é também uma oportunidade de testemunho cristão.",
  "O papel da missiologia na compreensão da urbanização global e das favelas. No nível doutoral, discutimos como o Evangelho deve ser encarnado nos contextos de precariedade e de exclusão social das grandes cidades. A missão deve ir para onde as pessoas estão. O objetivo é a plantação de comunidades de fé vibrantes nos assentamentos informais, trazendo a luz de Cristo para os lugares mais esquecidos e densamente povoados da terra.",
  "O desafio da missão entre os povos de cultura oral e a importância da narrativa bíblica. No nível doutoral, exploramos como o uso de histórias, de provérbios e de canções pode ser mais eficaz do que o ensino sistemático ocidental. A missão deve respeitar as formas de aprendizado de cada povo. O objetivo é que a história da salvação seja contada e recontada de forma que penetre na memória e no coração das culturas orais.",
  "A importância da teologia da missão para a saúde da igreja local. No nível doutoral, reafirmamos que uma igreja que não olha para fora adoece e morre. A missão é o antídoto para o legalismo e para o egoísmo congregacional. O objetivo é que a visão das nações cure a igreja de suas picuinhas internas, unindo os membros em torno do propósito maior de glorificar a Deus entre todos os povos.",
  "A ética da missão e a questão do sincretismo religioso. No nível doutoral, analisamos como distinguir entre a contextualização legítima e a mistura perigosa com elementos pagãos. A missão deve ser pura na doutrina e flexível na forma. O objetivo é uma fé que seja verdadeiramente bíblica e verdadeiramente local, sem comprometer a exclusividade de Cristo como o único Senhor e Salvador.",
  "O papel das missões de misericórdia em tempos de desastres naturais e de crises humanitárias. No nível doutoral, exploramos como a igreja pode ser a primeira a chegar e a última a sair nos locais de tragédia. A missão é feita de presença e de socorro. O objetivo é que o amor de Cristo seja demonstrado através da ajuda prática, abrindo corações para a mensagem da esperança eterna em meio ao sofrimento temporal.",
  "A importância da formação de líderes missiológicos no Sul Global. No nível doutoral, discutimos a necessidade de que as igrejas da África, da Ásia e da América Latina desenvolvam sua própria reflexão teológica sobre a missão. O objetivo é um movimento missionário policêntrico, onde cada região contribui com suas perspectivas e experiências, enriquendo a compreensão global da Missio Dei.",
  "O desafio da missão entre os povos muçulmanos e a importância do amor sacrificial. No nível doutoral, analisamos as barreiras históricas e teológicas que dificultam a evangelização no mundo islâmico. A missão exige paciência, amizade e um testemunho que demonstre a graça de Deus em Cristo. O objetivo é que as pontes de ódio sejam derrubadas pelo amor de Deus, levando muitos a conhecerem a paz que só Jesus pode dar.",
  "A ética do uso de recursos financeiros em missões transculturais. No nível doutoral, discutimos como evitar a criação de dependência e como promover a generosidade local. A missão deve visar a sustentabilidade da igreja nacional. O objetivo é que os recursos estrangeiros sejam usados como um catalisador, e não como uma muleta, permitindo que a igreja local cresça em maturidade e em responsabilidade financeira.",
  "A importância da teologia da missão para a compreensão do ministério pastoral. No nível doutoral, reafirmamos que o pastor deve ser o principal mobilizador missionário de sua igreja. O pastoreio não é um fim em si mesmo, mas um meio de preparar os santos para a obra do ministério no mundo. O objetivo é que cada sermão e cada reunião de oração tenha um horizonte missionário, lembrando a igreja de sua vocação global.",
  "O papel da missiologia na reflexão sobre a globalização e o transnacionalismo. No nível doutoral, analisamos como o movimento constante de pessoas e de ideias afeta a tarefa missionária. A missão hoje acontece em um mundo interconectado. O objetivo é que a igreja saiba navegar pelas complexidades da modernidade líquida, mantendo a solidez da mensagem do Evangelho enquanto utiliza as redes globais para a Sua propagação.",
  "O desafio da missão entre os povos budistas e a importância da meditação na Palavra. No nível doutoral, exploramos como comunicar a paz de Cristo em culturas que buscam a iluminação e o desapego. A missão exige um diálogo profundo com a filosofia oriental. O objetivo é demonstrar que Jesus é a verdadeira luz que ilumina todo homem e que Nele encontramos o descanso real para as nossas almas inquietas.",
  "A importância da teologia da missão para a adoração comunitária. No nível doutoral, discutimos como os cânticos e a liturgia devem refletir o desejo de Deus pelas nações. Uma igreja que adora verdadeiramente, deseja que todos os povos também O adorem. O objetivo é que a nossa adoração seja um ensaio para o grande coro celestial, onde pessoas de todas as línguas cantarão louvores ao Cordeiro que foi morto e que reviveu.",
  "A visão da missão como a manifestação do Reino de Deus na história humana. No nível doutoral, reafirmamos que a missão é a prova de que Deus não desistiu do mundo. O objetivo é que a igreja seja uma antecipação da nova criação, vivendo os valores do Reino aqui e agora, enquanto aguarda a consumação final. Que sejamos instrumentos da graça de Deus, transformando a realidade ao nosso redor até que Ele venha.",
  "A importância da pregação sobre a soberania de Deus na missão. No nível doutoral, analisamos como a confiança no controle divino sobre a história nos dá coragem para enfrentar qualquer desafio missionário. O pregador deve mostrar que Deus é o Senhor das nações e que o Seu plano de redenção não pode ser frustrado. O objetivo é uma igreja que descansa na providência de Deus enquanto trabalha com diligência para a Sua glória.",
  "O papel da missiologia na formação de uma consciência de interdependência global. No nível doutoral, exploramos como as igrejas de diferentes partes do mundo podem aprender umas com as outras. A missão não é apenas dar, mas também receber e ser enriquecido pela fé dos outros. O objetivo é uma fraternidade cristã que demonstre ao mundo que em Cristo não há barreiras de raça, de cultura ou de nacionalidade.",
  "A visão da missão como um ato de amor que transborda do coração de Deus para o mundo. No nível doutoral, reafirmamos que a motivação última da missão é o amor. Evangelizamos porque fomos amados primeiro e porque desejamos que outros experimentem a mesma graça. O objetivo é que a nossa vida seja um testemunho constante da compaixão de Cristo, atraindo as pessoas para a fonte da vida eterna.",
  "A Missiologia e a tradução cultural: como o Evangelho se veste de novas roupagens sem perder sua essência divina. No nível doutoral, estudamos os limites da inculturação, garantindo que o núcleo do querigma permaneça intacto enquanto a forma de comunicação se adapta perfeitamente ao receptor.",
  "O desafio da missão entre as crianças em situação de risco e vulnerabilidade social. No nível doutoral, reconhecemos que a missão deve proteger os mais fracos. A teologia da criança nos ensina que o Reino pertence a elas, e a igreja deve ser um escudo contra a exploração e o abandono.",
  "A importância da teologia da missão para a compreensão do sofrimento humano e da teodiceia. No nível doutoral, a missão não oferece respostas fáceis para a dor, mas oferece a presença do Deus que sofre conosco. A cruz é a resposta missiológica definitiva para o problema do mal.",
  "O papel da missiologia na construção de uma ética global de paz e reconciliação. No nível doutoral, a missão é vista como o ministério da reconciliação. A igreja é chamada a mediar conflitos e a promover a paz de Cristo em um mundo dilacerado por guerras e ódios étnicos.",
  "A visão da missão como um convite para participar da dança trinitária de amor e comunhão. No nível doutoral, a missão não é um fardo, mas um privilégio. Somos convidados a entrar na comunhão do Pai, do Filho e do Espírito Santo, e a estender esse convite a toda a humanidade.",
  "Em conclusão final, a Missiologia é o fôlego da igreja e a esperança das nações. No nível doutoral, reconhecemos que a missão é a razão pela qual ainda estamos aqui. Que a nossa paixão por Deus e pelas pessoas nos impulsione a ir além das nossas fronteiras, até que toda a terra seja cheia do conhecimento da glória do Senhor. Amém."
];

const fsPath = '/app/applet/data/academy_data.ts';
let content = fs.readFileSync(fsPath, 'utf8');

const startIdx = content.indexOf("id: 'missiologia'");
if (startIdx === -1) {
  console.log("missiologia not found");
  process.exit(1);
}

const contentStartIdx = content.indexOf("content: [", startIdx);
if (contentStartIdx === -1) {
  console.log("content array not found");
  process.exit(1);
}

// Find the end of the content array for missiologia
// We look for the closing bracket of the content array
// It is followed by "    ]\n  }\n]" since it's the last item in the file
const contentEndIdx = content.indexOf("    ]\n  }\n]", contentStartIdx);
if (contentEndIdx === -1) {
  console.log("content end not found");
  process.exit(1);
}

// Generate the new content array string
const newContentStr = "content: [\n" + paragraphs.map(p => `      "${p}"`).join(",\n") + "\n";

// Replace the old content array with the new one
const newFileContent = content.substring(0, contentStartIdx) + newContentStr + content.substring(contentEndIdx);

fs.writeFileSync(fsPath, newFileContent, 'utf8');
console.log("Successfully replaced missiologia content with " + paragraphs.length + " paragraphs.");
