const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'gen_22_1_14',
    intro: 'O capítulo 22 de Gênesis, conhecido na tradição judaica como a "Akedah" (A Amarração de Isaque), é uma das narrativas mais tensas, profundas e teologicamente ricas de toda a Escritura. Após décadas de espera, Abraão finalmente tem o filho da promessa, Isaque. No entanto, Deus o submete ao teste supremo, pedindo que ele sacrifique exatamente aquilo que ele mais ama e que representa o cumprimento de todas as promessas divinas. Este teste não foi desenhado para destruir Abraão, mas para revelar a prioridade absoluta do seu coração e para prefigurar, com detalhes impressionantes, o sacrifício definitivo que o próprio Deus faria no Calvário.',
    desc1: 'O teste começa com um chamado claro e doloroso: "Toma agora o teu filho, o teu único filho, Isaque, a quem amas, e vai-te à terra de Moriá, e oferece-o ali em holocausto". O pedido ataca a lógica humana e a própria promessa de Deus (pois a descendência viria por Isaque). O teste revela se Abraão amava mais a dádiva (o filho) ou o Doador (Deus). A fé verdadeira é provada quando Deus nos pede para entregar o nosso "Isaque" – aquilo que consideramos essencial para a nossa felicidade e futuro.',
    desc2: 'A resposta de Abraão é um monumento à fé obediente. Ele "levantou-se de madrugada", não argumentou, não pediu explicações e não adiou a obediência. A viagem durou três dias (três dias em que Isaque esteve "morto" na mente de Abraão). Ao chegarem ao pé do monte, Abraão diz aos servos: "Ficai-vos aqui... eu e o moço iremos até ali; e havendo adorado, tornaremos a vós". Ele acreditava tão firmemente no caráter e na promessa de Deus que, como Hebreus 11:19 explica, ele confiava que Deus era poderoso para ressuscitar Isaque dentre os mortos.',
    desc3: 'No topo do monte (o mesmo monte onde mais tarde seria construído o Templo em Jerusalém), Isaque faz a pergunta cortante: "Onde está o cordeiro?". Abraão profetiza: "Deus proverá para si o cordeiro". Quando Abraão levanta o cutelo, o Anjo do Senhor intervém. Deus não queria a morte de Isaque; Ele queria a rendição do coração de Abraão. Imediatamente, Abraão vê um carneiro preso pelos chifres em um arbusto e o oferece em sacrifício substitutivo. O lugar é chamado de "Jeová-Jireh" (O Senhor Proverá). O carneiro substituiu Isaque, assim como Cristo nos substituiu na cruz.',
    concl: 'A verdadeira adoração custa tudo, mas a obediência radical sempre resulta em provisão divina. A história de Isaque aponta diretamente para a cruz: séculos depois, no mesmo monte Moriá, o próprio Deus Pai entregaria o Seu único Filho, a quem amava. Mas dessa vez, não haveria um anjo para interromper o sacrifício, nem um carneiro para substituir, porque Jesus era o Cordeiro definitivo que Deus proveu para a nossa salvação.'
  },
  {
    id: '1ki_18_20_39',
    intro: 'O confronto no Monte Carmelo é o ápice do ministério do profeta Elias e um dos duelos espirituais mais dramáticos do Antigo Testamento. Israel estava mergulhado em uma profunda crise espiritual e econômica. Sob a liderança do rei Acabe e da rainha Jezabel, a nação havia abandonado a aliança com Yahweh para adorar Baal (o falso deus cananeu da tempestade e da fertilidade). Após três anos e meio de seca severa (provando que Baal não controlava a chuva), Elias convoca toda a nação e os 450 profetas de Baal para um teste definitivo de fogo, a fim de expor a futilidade da idolatria e restaurar a adoração ao único Deus verdadeiro.',
    desc1: 'Elias começa confrontando a paralisia espiritual do povo: "Até quando coxeareis entre dois pensamentos? Se o Senhor é Deus, segui-o, e se Baal, segui-o". O povo estava tentando misturar a adoração a Yahweh com a adoração a Baal (sincretismo). Elias deixa claro que o meio-termo espiritual é inaceitável para Deus. A verdadeira fé exige devoção exclusiva. O desafio é simples e justo: dois altares, dois sacrifícios, e o Deus que responder com fogo (o elemento que Baal supostamente controlava) seria reconhecido como o verdadeiro Deus.',
    desc2: 'Os profetas de Baal têm a primeira chance. Desde a manhã até o meio-dia, eles clamam, dançam freneticamente ao redor do altar e, em desespero, começam a se cortar com facas até sangrar, tentando chamar a atenção de seu deus. Elias zomba deles, sugerindo que Baal está dormindo ou viajando. O texto conclui de forma trágica: "Porém não houve voz, nem quem respondesse, nem quem atendesse". A idolatria é barulhenta, exige sacrifícios dolorosos de seus adoradores, mas no final, é vazia e impotente para salvar.',
    desc3: 'Chega a vez de Elias. Ele não faz um show. Primeiro, ele "repara o altar do Senhor que estava quebrado" (a restauração começa com a adoração bíblica). Ele usa doze pedras (representando a unidade das doze tribos). Para impossibilitar qualquer fraude, ele manda encharcar o altar e a lenha com doze cântaros de água. Sua oração é curta (apenas 63 palavras no hebraico), sem gritos, focada inteiramente na glória de Deus e na conversão do povo: "Responde-me, Senhor... para que este povo conheça que tu és o Senhor Deus". Imediatamente, o fogo do Senhor cai, consumindo o sacrifício, a lenha, as pedras e até a água.',
    concl: 'Diante da manifestação inegável do poder de Deus, o povo cai com o rosto em terra e declara: "Só o Senhor é Deus! Só o Senhor é Deus!". O Monte Carmelo nos ensina que Deus não divide a Sua glória com ídolos. Ele ainda responde com o "fogo" do Seu Espírito àqueles que reparam o altar da adoração, rejeitam o sincretismo e oram com fé, buscando exclusivamente a glória do Seu Nome.'
  },
  {
    id: 'luk_1_26_38',
    intro: 'A Anunciação a Maria é o momento em que a eternidade invade o tempo e a promessa de redenção começa a se tornar carne. O anjo Gabriel é enviado não a um palácio em Roma ou ao Templo em Jerusalém, mas a uma cidade obscura e desprezada chamada Nazaré, na Galileia. Ele não aparece a uma rainha ou a uma sacerdotisa, mas a uma jovem virgem, pobre e comum, chamada Maria, que estava noiva de um carpinteiro. Este encontro revela a natureza surpreendente da graça de Deus e nos oferece o modelo perfeito de submissão radical e fé incondicional à vontade divina.',
    desc1: 'A saudação do anjo quebra todos os protocolos humanos: "Salve, agraciada; o Senhor é contigo; bendita és tu entre as mulheres". Maria fica perturbada, não com o anjo em si, mas com o significado da saudação. A palavra "agraciada" (kecharitomene) indica que ela foi alvo do favor imerecido de Deus. Deus não a escolheu porque ela era divina ou sem pecado, mas a escolheu por pura graça soberana. Deus frequentemente ignora os centros de poder humano e usa os humildes, os improváveis e os esquecidos para realizar os Seus propósitos mais grandiosos, a fim de que toda a glória seja dEle.',
    desc2: 'A mensagem de Gabriel é a essência do Evangelho: Maria conceberia e daria à luz um filho, e Seu nome seria Jesus (Yahweh Salva). O anjo descreve a identidade e o destino do menino com títulos reais e divinos: Ele será grande, será chamado Filho do Altíssimo, e Deus Lhe dará o trono de Davi. O Seu Reino não terá fim. Esta é a garantia de que a aliança davídica (2 Samuel 7) estava se cumprindo. O bebê no ventre de Maria não seria apenas um profeta, mas o Rei eterno e o próprio Filho de Deus encarnado.',
    desc3: 'Maria faz uma pergunta lógica e pura: "Como se fará isto, visto que não conheço homem?". Ela não duvida da promessa (como Zacarias fez), mas pergunta sobre o processo. Gabriel explica o milagre da concepção virginal: "Descerá sobre ti o Espírito Santo, e a virtude do Altíssimo te cobrirá com a sua sombra". A encarnação é uma obra exclusiva da Trindade. O anjo conclui com a garantia absoluta: "Porque para Deus nada é impossível". Diante do mistério e do risco social (uma gravidez inexplicável antes do casamento poderia resultar em apedrejamento), a resposta de Maria é o ápice da fé: "Eis aqui a serva (escrava) do Senhor; cumpra-se em mim segundo a tua palavra".',
    concl: 'A resposta de Maria é o modelo de discipulado para todos os cristãos. Deus continua procurando pessoas comuns que estejam dispostas a dizer "sim" aos Seus planos impossíveis, mesmo quando isso custa a sua reputação, os seus planos pessoais e a sua segurança. A verdadeira grandeza no Reino de Deus começa com a rendição total à Sua Palavra.'
  },
  {
    id: 'jhn_4_1_26',
    intro: 'O encontro de Jesus com a mulher samaritana no poço de Jacó é uma das narrativas mais longas e teologicamente ricas dos Evangelhos. Para chegar à Galileia, Jesus "tinha que passar" por Samaria (uma necessidade divina, não apenas geográfica). Ao meio-dia, sob o sol escaldante, Ele se senta exausto junto ao poço e inicia uma conversa com uma mulher que era triplamente marginalizada: era mulher (rabinos não falavam com mulheres em público), era samaritana (judeus e samaritanos se odiavam por razões étnicas e religiosas) e tinha uma má reputação moral. Jesus destrói todas essas barreiras para oferecer a ela a água viva.',
    desc1: 'O diálogo começa com um pedido simples de Jesus: "Dá-me de beber". A mulher fica chocada com a quebra de protocolo. Jesus usa a água física do poço como uma ponte para uma realidade espiritual profunda: "Se tu conheceras o dom de Deus, e quem é o que te diz: Dá-me de beber, tu lhe pedirias, e ele te daria água viva". Jesus aponta para a futilidade das fontes terrenas. Quem bebe da água deste mundo (seja sexo, dinheiro, poder ou religião) "tornará a ter sede". As cisternas do mundo são furadas. Mas a água que Jesus oferece (o Espírito Santo e a salvação) torna-se uma fonte interna que jorra para a vida eterna, saciando definitivamente a sede da alma.',
    desc2: 'Para que a mulher pudesse receber a água viva, ela precisava reconhecer a sua sede e o seu pecado. Jesus, com precisão profética e amor cirúrgico, diz: "Vai, chama o teu marido, e vem cá". Quando ela responde que não tem marido, Jesus expõe a sua ferida mais profunda: ela já teve cinco maridos, e o homem com quem vivia agora não era seu marido. Jesus não expõe o pecado dela para humilhá-la ou condená-la, mas para curá-la. Ele mostra que ela estava tentando saciar a sua sede de amor e significado em relacionamentos quebrados. O diagnóstico preciso do pecado é o pré-requisito para a cura da graça.',
    desc3: 'Sentindo-se exposta, a mulher tenta mudar de assunto e inicia um debate teológico sobre o local correto de adoração (no monte Gerizim ou em Jerusalém). Jesus eleva a conversa, declarando que a verdadeira adoração não é uma questão de geografia ou de rituais externos, mas de essência: "Os verdadeiros adoradores adorarão o Pai em espírito e em verdade; porque o Pai procura a tais que assim o adorem". A adoração deve ser movida pelo Espírito Santo e baseada na verdade da revelação de Deus em Cristo. O encontro culmina com a mulher mencionando o Messias, e Jesus declarando abertamente: "Eu o sou, eu que falo contigo".',
    concl: 'A mulher deixa o seu cântaro de água (o símbolo da sua velha vida e da sua sede insaciável) e corre para a cidade para testemunhar. A graça de Cristo nos encontra na nossa vergonha, expõe o nosso pecado com amor, sacia a nossa sede mais profunda e nos transforma em verdadeiros adoradores e testemunhas do Seu poder.'
  },
  {
    id: 'act_16_16_34',
    intro: 'A história de Paulo e Silas em Filipos é um testemunho poderoso de que a obediência à vontade de Deus não nos isenta de sofrimento e injustiça. Eles haviam chegado à Macedônia em resposta a uma visão divina, mas o resultado não foi um tapete vermelho, e sim perseguição severa. Após libertarem uma jovem escrava de um espírito de adivinhação, eles afetam a economia local. Como resultado, são espancados publicamente com varas e lançados no cárcere interior (a cela mais escura e segura), com os pés presos no tronco. No entanto, eles transformam a masmorra romana em um santuário de adoração, provando que a verdadeira liberdade está no espírito, não nas circunstâncias.',
    desc1: 'A prisão de Paulo e Silas revela a raiz econômica de muita perseguição religiosa. Os donos da jovem escrava não se importavam com a teologia de Paulo; eles ficaram furiosos porque a sua fonte de lucro (a exploração espiritual da menina) havia secado. O sistema do mundo tolera a religião até o momento em que ela confronta os seus ídolos financeiros e morais. A multidão se levanta contra eles, e os magistrados, sem um julgamento justo, ordenam o açoitamento. A obediência radical ao Evangelho frequentemente atrai a fúria do sistema do mundo.',
    desc2: 'A reação de Paulo e Silas na prisão é um dos maiores milagres do livro de Atos. "Perto da meia-noite, Paulo e Silas oravam e cantavam hinos a Deus, e os outros presos os escutavam". Com as costas sangrando, no escuro, no frio e presos a um tronco, eles escolhem a adoração em vez da murmuração. O louvor na "meia-noite" da vida não é uma negação da dor, mas uma declaração de que Deus é maior do que a dor. A adoração deles não apenas mudou o ambiente espiritual da cela, mas atraiu a presença de Deus de forma física: um grande terremoto abalou os alicerces da prisão, todas as portas se abriram e as algemas de todos caíram.',
    desc3: 'O carcereiro, acordando e vendo as portas abertas, tira a espada para se matar (pois a lei romana exigia a vida do guarda se os prisioneiros fugissem). Paulo grita: "Não te faças nenhum mal, que todos aqui estamos". O verdadeiro milagre não foi o terremoto, mas o fato de nenhum preso ter fugido. O amor e a integridade de Paulo quebram o coração do carcereiro, que cai tremendo e faz a pergunta mais importante da vida: "Senhores, que devo fazer para me salvar?". A resposta é o cerne do Evangelho: "Crê no Senhor Jesus Cristo e serás salvo, tu e a tua casa". Naquela mesma noite, o carcereiro lava as feridas deles e é batizado com toda a sua família.',
    concl: 'As nossas reações na "meia-noite" das nossas provações são o nosso maior testemunho para o mundo que nos observa (os "outros presos"). Deus frequentemente permite que sejamos lançados em prisões injustas não para nos destruir, mas para que o nosso louvor provoque terremotos que libertem aqueles que estão presos na escuridão ao nosso redor.'
  },
  {
    id: 'dan_6_10_23',
    intro: 'A história de Daniel na Cova dos Leões é um dos relatos mais icônicos sobre a constância da fé diante da perseguição política e religiosa. Daniel, agora um homem idoso, havia sobrevivido à queda do Império Babilônico e ascendido a uma posição de extrema autoridade no novo Império Medo-Persa sob o rei Dario. Sua integridade, excelência e "espírito excelente" despertaram a inveja mortal dos outros presidentes e príncipes. Incapazes de encontrar qualquer corrupção ou negligência em seu trabalho, eles percebem que a única maneira de derrubá-lo seria criando um conflito direto entre a lei do Estado e a lei do seu Deus.',
    desc1: 'Os inimigos de Daniel manipulam o rei Dario para assinar um decreto irrevogável: durante trinta dias, qualquer pessoa que fizesse uma petição a qualquer deus ou homem, exceto ao rei, seria lançada na cova dos leões. O decreto era uma armadilha perfeita, apelando para o ego do rei. Quando Daniel soube que o documento estava assinado, sua reação define o que é a verdadeira devoção. Ele não protesta, não organiza uma revolta, não tenta orar em segredo e não faz concessões. Ele vai para casa, abre as janelas em direção a Jerusalém e ora de joelhos três vezes ao dia, "como costumava fazer". A fidelidade inabalável na crise é apenas o fruto de uma vida de fidelidade na rotina.',
    desc2: 'A obediência a Deus tem consequências. Os inimigos flagram Daniel orando e o denunciam. O rei Dario, percebendo que havia sido enganado, tenta desesperadamente encontrar uma brecha legal para salvar Daniel, mas a lei dos medos e persas não podia ser alterada. Com o coração pesado, o rei ordena que Daniel seja lançado na cova dos leões, expressando uma esperança vacilante: "O teu Deus, a quem tu continuamente serves, ele te livrará". A pedra é selada sobre a cova. A fé verdadeira não nos isenta de sermos lançados na cova; ela nos sustenta quando estamos lá dentro.',
    desc3: 'Após uma noite de insônia e jejum, o rei corre para a cova ao amanhecer e clama com voz triste. A resposta de Daniel ecoa das profundezas: "Ó rei, vive para sempre! O meu Deus enviou o seu anjo, e fechou a boca dos leões, para que não me fizessem dano, porque foi achada em mim inocência diante dele". O livramento foi total; nenhum arranhão foi encontrado nele, "porque crera no seu Deus". A maior vitória, no entanto, não foi apenas a sobrevivência de Daniel, mas o impacto do seu testemunho. O rei Dario emite um novo decreto para todo o império, ordenando que todos tremam e temam diante do "Deus vivo" de Daniel.',
    concl: 'A integridade inegociável de um único homem pode abalar um império inteiro. Quando escolhemos ser fiéis a Deus, mesmo sob a ameaça dos "leões" da nossa cultura (perda de emprego, reputação ou vida), Deus usa a nossa constância na cova para revelar a Sua glória e o Seu poder àqueles que estão do lado de fora observando.'
  },
  {
    id: 'exo_14_15_31',
    intro: 'A travessia do Mar Vermelho é o evento redentor central do Antigo Testamento, o milagre pelo qual todos os outros milagres seriam medidos na história de Israel. Após as dez pragas e a saída do Egito, o povo de Israel encontra-se em uma armadilha mortal: o Mar Vermelho à frente, montanhas intransponíveis dos lados e o exército de elite de Faraó, com seus carros de guerra, aproximando-se rapidamente por trás. O pânico se instaura, e o povo murmura contra Moisés, desejando voltar à escravidão. O que parece ser um beco sem saída humano e um erro estratégico é, na verdade, o cenário perfeitamente orquestrado por Deus para demonstrar o Seu poder soberano e a Sua salvação definitiva.',
    desc1: 'Diante do desespero do povo, Moisés tenta acalmá-los: "Não temais; estai quietos, e vede o livramento do Senhor... o Senhor pelejará por vós". No entanto, a resposta de Deus a Moisés é surpreendente: "Por que clamas a mim? Dize aos filhos de Israel que marchem". Há momentos em que a oração deve dar lugar à ação obediente. A fé exige movimento. Deus ordena que Moisés levante o seu bordão e estenda a mão sobre o mar para dividi-lo. O milagre não aconteceria enquanto eles estivessem paralisados pelo medo; o mar só se abriria quando eles começassem a marchar em direção à água.',
    desc2: 'Antes de abrir o mar, Deus providencia proteção. O Anjo de Deus e a coluna de nuvem, que iam adiante do acampamento, movem-se para trás, colocando-se entre os israelitas e os egípcios. Para o Egito, a nuvem era trevas e confusão; para Israel, era luz e proteção. A mesma presença de Deus traz juízo para os rebeldes e salvação para o Seu povo. Durante toda a noite, Deus faz soprar um forte vento oriental que divide as águas, criando um caminho seco no meio do mar, com as águas formando um muro à direita e à esquerda. Deus cria um caminho onde a lógica humana dizia que não existia saída.',
    desc3: 'Os egípcios, endurecidos pelo orgulho, tentam seguir Israel pelo mesmo caminho no meio do mar. No entanto, o que foi o caminho da salvação para o povo de Deus tornou-se a armadilha do juízo para os opressores. Na vigília da manhã, Deus causa pânico no exército egípcio e emperra as rodas dos seus carros. Ao amanhecer, Moisés estende a mão novamente, e as águas retornam ao seu lugar, cobrindo todo o exército de Faraó. "Não ficou nem sequer um deles". O resultado desse livramento espetacular é duplo: Israel vê o grande poder do Senhor, teme a Deus e crê nEle e no Seu servo Moisés.',
    concl: 'A travessia do Mar Vermelho nos ensina que Deus é especialista em becos sem saída. Quando os inimigos nos cercam e não há opções humanas, o nosso papel não é entrar em pânico ou desejar voltar à escravidão do passado, mas confiar na proteção de Deus e continuar marchando pela fé, sabendo que Ele abrirá o caminho e pelejará por nós.'
  },
  {
    id: 'jhn_6_1_14',
    intro: 'A multiplicação dos pães e peixes é o único milagre de Jesus (além da ressurreição) registrado nos quatro Evangelhos, o que destaca a sua profunda importância teológica. Uma grande multidão de cerca de cinco mil homens (além de mulheres e crianças) segue Jesus até um lugar deserto, atraída pelos Seus milagres de cura. O dia avança, e a fome da multidão cria uma crise logística impossível. Jesus usa essa situação de escassez extrema não apenas para demonstrar o Seu poder sobre a criação, mas para ensinar aos Seus discípulos uma lição vital sobre fé, provisão e a Sua própria identidade como o Pão da Vida que desceu do céu.',
    desc1: 'Jesus toma a iniciativa e testa a fé de Filipe: "Onde compraremos pão, para estes comerem?". O texto diz que Jesus já sabia o que ia fazer, mas queria provar o discípulo. Filipe responde com a lógica humana e a matemática da escassez: "Duzentos denários (oito meses de salário) de pão não lhes bastarão, para que cada um tome um pouco". A visão de Filipe estava limitada aos recursos naturais e financeiros disponíveis. A lógica humana sempre foca no que está faltando e conclui que a situação é impossível. Quando olhamos apenas para os nossos recursos, o desespero é inevitável.',
    desc2: 'André, outro discípulo, traz uma pequena esperança, mas logo a descarta: "Está aqui um rapaz que tem cinco pães de cevada (o pão dos pobres) e dois peixinhos; mas que é isto para tantos?". A oferta era insignificante e ridícula diante do tamanho da necessidade. No entanto, Deus frequentemente escolhe usar o que consideramos pequeno, insuficiente e desprezível para realizar o extraordinário. O milagre começa com a disposição de um menino anônimo de entregar tudo o que tinha nas mãos do Mestre. Jesus não exige que tenhamos muito; Ele apenas pede que entreguemos o que temos.',
    desc3: 'Jesus organiza o caos, mandando a multidão assentar-se na relva. Ele toma os pães, dá graças (eucharisteo) e os distribui. O milagre da multiplicação não aconteceu nas mãos dos discípulos, mas nas mãos de Jesus enquanto Ele partia o pão. O resultado é a abundância divina: "comeram todos, e saciaram-se". A provisão de Cristo não apenas atende à necessidade básica, mas a excede abundantemente. Jesus manda recolher os pedaços que sobraram "para que nada se perca", e eles enchem doze cestos (um para cada apóstolo que havia duvidado). A graça de Deus é superabundante, mas nunca desperdiçada.',
    concl: 'Não importa o quão pouco você acha que tem (seja talento, recursos, tempo ou força); quando esse "pouco" é entregue nas mãos de Jesus com gratidão, torna-se mais do que suficiente para abençoar a muitos. Jesus não é apenas o provedor do pão; Ele é o próprio Pão da Vida que satisfaz a fome eterna da nossa alma.'
  },
  {
    id: 'jhn_11_32_44',
    intro: 'A ressurreição de Lázaro é o sétimo e maior "sinal" no Evangelho de João, o clímax do ministério público de Jesus antes da Sua própria paixão. Jesus recebe a notícia de que Seu amigo Lázaro está doente, mas Ele intencionalmente demora dois dias antes de ir para Betânia. Quando Ele chega, Lázaro já está morto e sepultado há quatro dias (o que, na crença judaica da época, significava que a alma já havia deixado o corpo e não havia mais esperança). Jesus entra em um cenário de luto profundo, choro e decepção para demonstrar que Ele não apenas tem o poder de dar a vida, mas que Ele é a própria Ressurreição e a Vida.',
    desc1: 'Quando Maria encontra Jesus, ela cai a Seus pés e expressa a dor e a frustração de todos: "Senhor, se tu estivesses aqui, meu irmão não teria morrido". Ela acreditava no poder de Jesus para curar, mas achava que Ele havia chegado tarde demais. Ao ver o choro de Maria e dos judeus, Jesus "moveu-se muito em espírito, e perturbou-se". O versículo 35 registra a emoção mais profunda do Salvador: "Jesus chorou". Ele não chora porque perdeu o controle (Ele sabia que ia ressuscitar Lázaro), mas chora por compaixão e por indignação contra a morte, o pecado e a dor que destroem a Sua criação. O nosso Deus não é apático; Ele sofre conosco.',
    desc2: 'Jesus vai ao sepulcro, uma caverna fechada com uma pedra, e ordena: "Tirai a pedra". Marta, a irmã pragmática, tenta impedi-Lo, focando na realidade física e na impossibilidade humana: "Senhor, já cheira mal, porque é já de quatro dias". A lógica humana diz que a morte é o fim e que algumas situações estão além de qualquer restauração. Jesus a repreende suavemente, lembrando-a da promessa: "Não te hei dito que, se creres, verás a glória de Deus?". A fé exige que removamos as pedras da incredulidade e permitamos que a Palavra de Cristo entre nos lugares de morte em nossas vidas.',
    desc3: 'Após orar ao Pai em voz alta (para que a multidão cresse que Ele foi enviado por Deus), Jesus clama com grande voz: "Lázaro, vem para fora!". A voz do Criador, que no princípio chamou o universo à existência, agora chama um homem morto de volta à vida. Lázaro sai do sepulcro, vivo, mas ainda com as mãos e os pés atados com faixas e o rosto envolto em um lenço. Jesus dá uma ordem final à comunidade: "Desatai-o, e deixai-o ir". A vida é dada exclusivamente pelo poder da palavra de Cristo, mas a libertação das amarras do passado é um trabalho que Ele delega à comunidade da igreja.',
    concl: 'A ressurreição de Lázaro prova que Jesus tem a última palavra sobre a morte e sobre qualquer situação impossível. Não há casamento, ministério, sonho ou vida tão "morta" ou "cheirando mal" que a voz do Filho de Deus não possa ressuscitar. Ele é a Ressurreição e a Vida; quem crê nEle, ainda que esteja morto, viverá.'
  },
  {
    id: 'act_7_54_60',
    intro: 'O martírio de Estêvão é um momento crucial na história da Igreja Primitiva. Estêvão não era um dos doze apóstolos, mas um dos sete diáconos escolhidos para servir às mesas. No entanto, cheio de graça e poder, ele realizava grandes prodígios e pregava com uma sabedoria irresistível. Levado perante o Sinédrio (a mesma corte que condenou Jesus), ele profere o mais longo discurso do livro de Atos, fazendo um resumo magistral da história de Israel para provar que a nação sempre rejeitou os libertadores enviados por Deus, culminando na rejeição e assassinato do Justo, Jesus Cristo. O capítulo 7 termina com a reação furiosa da religião à verdade e o testemunho triunfante do primeiro mártir cristão.',
    desc1: 'A pregação de Estêvão foi como uma espada afiada. Ao ouvirem a acusação de que eram "incircuncisos de coração e de ouvidos" e que resistiam ao Espírito Santo, os membros do Sinédrio "enfureciam-se em seus corações, e rangiam os dentes contra ele". A verdade do Evangelho, quando pregada com o poder do Espírito, nunca deixa as pessoas neutras; ela produz arrependimento profundo ou ódio mortal. Enquanto a sala se enchia de fúria assassina, Estêvão, cheio do Espírito Santo, levanta os olhos para o céu e tem uma visão gloriosa: ele vê a glória de Deus e "Jesus em pé à direita de Deus". Normalmente, Jesus é descrito assentado (indicando que Sua obra redentora está consumada), mas aqui o Rei se levanta para honrar e receber o Seu servo fiel que está prestes a morrer por Ele.',
    desc2: 'Quando Estêvão declara a sua visão ("Eis que vejo os céus abertos, e o Filho do Homem em pé à direita de Deus"), a fúria religiosa atinge o seu limite. Eles tapam os ouvidos (uma recusa física de ouvir a verdade), gritam com grande voz e investem contra ele em um linchamento descontrolado. Eles o arrastam para fora da cidade e começam a apedrejá-lo. O texto menciona um detalhe aparentemente menor, mas historicamente monumental: as testemunhas (que deveriam atirar as primeiras pedras) deixaram as suas vestes aos pés de um jovem chamado Saulo. Aquele que supervisionava a morte de Estêvão seria, mais tarde, o apóstolo Paulo. O sangue dos mártires é a semente da Igreja.',
    desc3: 'Enquanto as pedras esmagam o seu corpo, a atitude de Estêvão é o reflexo perfeito do seu Mestre. Ele não amaldiçoa os seus assassinos nem pede vingança. Ele faz duas orações que ecoam as palavras de Jesus na cruz. Primeiro, ele ora pela sua própria alma: "Senhor Jesus, recebe o meu espírito". Depois, pondo-se de joelhos, ele clama com grande voz pelos seus inimigos: "Senhor, não lhes imputes este pecado". Tendo dito isto, ele "adormeceu" (uma bela metáfora cristã para a morte). O verdadeiro discipulado nos conforma à imagem de Cristo, capacitando-nos a amar e perdoar até mesmo no vale da sombra da morte.',
    concl: 'A morte de Estêvão não foi uma derrota, mas um triunfo glorioso. O seu testemunho de graça e perdão sob as pedras plantou uma semente inesquecível na mente do jovem Saulo de Tarso. A história de Estêvão nos ensina que a vitória cristã não é necessariamente escapar do sofrimento ou da morte, mas permanecer fiel a Cristo e refletir o Seu amor até o último suspiro.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done');
