const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: '1th_4_1_12',
    intro: 'Paulo exorta os tessalonicenses a progredirem na vida cristã. Ele aborda áreas práticas onde o comportamento do crente deve contrastar radicalmente com a cultura pagã ao redor, especificamente na pureza sexual e no amor fraternal. A santificação não é uma opção, mas a vontade expressa de Deus.',
    desc1: 'A Vontade de Deus: Santificação. Paulo é direto: a vontade de Deus é a santificação, o que significa abster-se da imoralidade sexual (porneia). No Império Romano, a pureza sexual era rara; a religião pagã frequentemente envolvia prostituição cultual. Paulo ensina que o corpo do crente é um vaso que deve ser possuído em santidade e honra, não na paixão de desejos carnais. Pecar sexualmente não é apenas quebrar uma regra, mas rejeitar o próprio Deus que nos deu o Seu Espírito Santo.',
    desc2: 'O Amor Fraternal (Philadelphía). Paulo elogia os tessalonicenses pelo amor que já demonstravam uns pelos outros, ensinados pelo próprio Deus. No entanto, na vida cristã, nunca há um ponto onde o amor é "suficiente". Ele os exorta a "aumentar cada vez mais" nesse amor. O amor cristão é dinâmico, prático e deve estar em constante expansão, alcançando não apenas os amigos próximos, mas todos os irmãos na fé.',
    desc3: 'Uma Vida Tranquila e Honesta. Paulo instrui os crentes a terem a ambição de viver uma vida tranquila, cuidar dos seus próprios negócios e trabalhar com as próprias mãos. Alguns na igreja, talvez antecipando a volta iminente de Cristo, haviam abandonado seus empregos e se tornado intrometidos. Paulo corrige isso: o trabalho honesto é um testemunho poderoso para os de fora (os não-crentes) e garante que a igreja não seja um fardo para a sociedade.',
    concl: 'A vida que agrada a Deus é marcada por um contraste visível com o mundo: pureza em uma cultura imoral, amor crescente em uma sociedade egoísta e trabalho honesto em um mundo de exploração. A nossa santificação é o maior testemunho do evangelho.'
  },
  {
    id: '2th_2_1_12',
    intro: 'A igreja em Tessalônica estava em pânico. Falsos mestres, possivelmente usando cartas forjadas em nome de Paulo, ensinavam que o "Dia do Senhor" (o julgamento final e a reunião com Cristo) já havia chegado, e eles haviam sido deixados para trás em meio à perseguição. Paulo escreve para acalmar seus corações, corrigindo a escatologia deles e revelando que eventos específicos, incluindo a manifestação do "homem da iniquidade", devem ocorrer antes do retorno triunfal de Jesus.',
    desc1: 'A Apostasia e o Anticristo. Paulo garante que o Dia do Senhor não virá sem que antes ocorra a "apostasia" (uma rebelião global contra Deus) e seja revelado o "homem da iniquidade" (o Anticristo). Este líder maligno não será apenas um ditador político, mas uma figura religiosa blasfema que se oporá a tudo o que é divino, chegando ao ponto de se assentar no santuário de Deus, proclamando-se o próprio Deus.',
    desc2: 'O Mistério da Iniquidade e Aquele que o Detém. Paulo lembra que já havia ensinado isso pessoalmente. Ele menciona "o que o detém" (ou "aquele que o detém"), uma força ou pessoa (frequentemente interpretada como o Espírito Santo atuando através da Igreja ou o governo humano ordenado por Deus) que restringe a manifestação total do mal. O "mistério da iniquidade" já está operando secretamente, mas quando a restrição for removida, o iníquo será revelado abertamente.',
    desc3: 'A Derrota do Iníquo e o Julgamento da Mentira. O reinado de terror do Anticristo, apoiado por "todo o poder, e sinais e prodígios de mentira" operados por Satanás, será curto. Paulo descreve a sua derrota com um contraste majestoso: o Senhor Jesus o matará com o "sopro da sua boca" e o destruirá com o "esplendor da sua vinda". Aqueles que perecem são os que "não receberam o amor da verdade para se salvarem", sendo entregues por Deus à operação do erro para acreditarem na mentira.',
    concl: 'A profecia bíblica não nos é dada para satisfazer a nossa curiosidade sobre o futuro ou causar medo, mas para nos dar paz e firmeza no presente. Por mais sombrio que o mundo se torne e por mais poderoso que o mal pareça, o Senhor Jesus tem a palavra final e a vitória garantida.'
  },
  {
    id: '1ti_6_6_19',
    intro: 'Em Éfeso, falsos mestres estavam usando a religião como um meio de enriquecimento ilícito, associando a piedade ao lucro financeiro. O apóstolo Paulo escreve ao jovem pastor Timóteo para desmascarar essa teologia da prosperidade distorcida. Ele apresenta a verdadeira perspectiva cristã sobre o dinheiro, alertando sobre os perigos mortais da ganância, definindo o que é a verdadeira riqueza e encarregando Timóteo (e todos os crentes) a lutar o "bom combate da fé".',
    desc1: 'O Contentamento e a Raiz de Todos os Males. Paulo redefine o lucro: "Mas é grande ganho a piedade com contentamento". A verdadeira riqueza não é ter tudo o que se quer, mas estar satisfeito com o que se tem em Deus. Ele lembra uma verdade universal: não trouxemos nada para o mundo e não levaremos nada dele. O desejo obsessivo de ficar rico é uma armadilha que afoga os homens na ruína. A famosa frase "o amor ao dinheiro é a raiz de toda a espécie de males" não condena o dinheiro em si, mas a idolatria do coração que se desvia da fé e se fere com muitas dores.',
    desc2: 'O Bom Combate da Fé. Em contraste com os gananciosos, Paulo chama Timóteo de "ó homem de Deus" e ordena que ele fuja dessas coisas. Em vez de buscar riquezas, ele deve buscar "a justiça, a piedade, a fé, o amor, a paciência, a mansidão". A vida cristã não é um parque de diversões, mas um campo de batalha: "Milita a boa milícia da fé". Timóteo é encarregado de guardar o mandamento imaculado até a vinda de Cristo, o "único Soberano, Rei dos reis e Senhor dos senhores".',
    desc3: 'Um Encargo aos Ricos. Paulo não manda os ricos jogarem seu dinheiro fora, mas lhes dá um encargo pastoral. Primeiro, uma advertência contra a atitude: não sejam arrogantes nem coloquem a esperança na incerteza das riquezas, mas em Deus, que nos dá tudo abundantemente. Segundo, uma instrução sobre a ação: pratiquem o bem, sejam ricos de boas obras, generosos e prontos a repartir. Ao fazerem isso, eles "entesouram para si mesmos um bom fundamento para o futuro", agarrando a verdadeira vida.',
    concl: 'O dinheiro é um excelente servo, mas um péssimo mestre. A verdadeira prosperidade cristã é encontrada no contentamento, na busca pela piedade e na generosidade radical. Quando usamos os recursos temporais para propósitos eternos, experimentamos a verdadeira vida que Deus planejou para nós.'
  },
  {
    id: '2ti_4_1_8',
    intro: 'Estas são as últimas palavras registradas do apóstolo Paulo. A cena é sombria, mas triunfante. Paulo está preso em uma masmorra fria em Roma, abandonado por muitos amigos e aguardando a sua iminente execução por ordem do imperador Nero. Sabendo que a sua corrida chegou ao fim, ele escreve esta carta profundamente pessoal para passar o bastão do ministério ao seu filho na fé, Timóteo. É um encargo solene, um chamado à fidelidade inabalável e um testemunho glorioso de um homem que está pronto para encontrar o seu Senhor.',
    desc1: 'Prega a Palavra. Paulo conjura Timóteo diante de Deus e de Cristo Jesus, o Juiz dos vivos e dos mortos. O encargo principal é simples, mas monumental: "Prega a palavra". Timóteo deve estar preparado "a tempo e fora de tempo" (quando for conveniente ou inconveniente). Ele deve repreender, exortar e consolar com toda a paciência e doutrina. O motivo dessa urgência é profético: virá um tempo em que as pessoas não suportarão a sã doutrina, mas cercar-se-ão de mestres que dizem apenas o que seus "ouvidos coçam" para ouvir, desviando-se da verdade para as fábulas.',
    desc2: 'O Chamado à Sobriedade e ao Sofrimento. Em contraste com a multidão que busca entretenimento espiritual, Timóteo deve ser diferente: "Tu, porém, sê sóbrio em todas as coisas". A sobriedade cristã é a clareza mental e espiritual em meio ao caos. Paulo também o chama a "suportar as aflições". O ministério fiel inevitavelmente atrai oposição. Timóteo deve fazer a obra de um evangelista e cumprir cabalmente o seu ministério, não recuando diante do sofrimento.',
    desc3: 'O Testemunho de uma Vida Derramada. Paulo muda o foco para si mesmo, usando a linguagem de um sacrifício: "Quanto a mim, já estou sendo derramado como libação, e o tempo da minha partida é chegado". Ele não vê a sua morte como uma tragédia, mas como uma oferta a Deus. Ele resume a sua vida com três metáforas poderosas: "Combati o bom combate" (o soldado fiel), "completei a carreira" (o atleta determinado) e "guardei a fé" (o mordomo leal). Ele agora aguarda a "coroa da justiça", que o Justo Juiz lhe dará, e não apenas a ele, mas a todos os que amam a Sua vinda.',
    concl: 'O legado de Paulo nos desafia a avaliar as nossas próprias vidas. O sucesso no Reino de Deus não é medido por popularidade ou conforto, mas pela fidelidade à Palavra e pela perseverança até o fim. Que possamos viver de tal maneira que, no final dos nossos dias, possamos dizer com Paulo: "Combati o bom combate, guardei a fé".'
  },
  {
    id: 'tit_2_11_15',
    intro: 'A ilha de Creta era famosa no mundo antigo pela imoralidade, mentira e corrupção dos seus habitantes. O apóstolo Paulo deixou Tito lá com a difícil missão de organizar a igreja e ensinar os crentes a viverem de forma santa em um ambiente tóxico. Neste texto, Paulo resume o coração do evangelho e a motivação para a vida cristã. Ele revela que a graça de Deus não é apenas o meio pelo qual somos salvos do inferno, mas também a professora divina que nos educa e nos capacita a viver de forma justa e piedosa no presente.',
    desc1: 'A Aparição da Graça Salvadora. Paulo declara: "Porque a graça salvadora de Deus se há manifestado a todos os homens". A graça não é um conceito abstrato; ela "se manifestou" (epiphaneia, de onde vem a palavra epifania) historicamente na pessoa e obra de Jesus Cristo. Esta graça não é exclusiva para uma elite religiosa ou uma nação específica, mas traz salvação a "todos os homens" (judeus, gentios, escravos, livres, homens e mulheres), oferecendo perdão imerecido a pecadores perdidos.',
    desc2: 'A Pedagogia da Graça. A mesma graça que salva é a graça que santifica. Paulo diz que a graça nos "ensina" (ou educa, treina). A educação da graça tem dois lados. O lado negativo: renunciar à impiedade e às paixões mundanas. A graça nos dá o poder de dizer "não" ao pecado. O lado positivo: viver "neste presente século sóbria, e justa, e piamente". A sobriedade refere-se ao controle de si mesmo; a justiça, ao nosso relacionamento com os outros; e a piedade, ao nosso relacionamento com Deus. A verdadeira graça nunca é uma licença para pecar.',
    desc3: 'A Esperança e o Propósito da Redenção. Enquanto vivemos piedosamente, a graça nos ensina a olhar para o futuro: "Aguardando a bem-aventurada esperança e o aparecimento da glória do grande Deus e nosso Senhor Jesus Cristo". A nossa santificação é alimentada pela expectativa da volta de Cristo. Paulo lembra o propósito da cruz: Ele "se deu a si mesmo por nós para nos remir de toda a iniquidade, e purificar para si um povo seu especial, zeloso de boas obras". Fomos salvos não apenas para ir para o céu, mas para sermos um povo purificado e apaixonado por fazer o bem na terra.',
    concl: 'A graça de Deus é a força mais transformadora do universo. Ela nos resgata do passado, nos educa e nos capacita a viver em santidade no presente, e nos dá uma esperança inabalável para o futuro. Uma compreensão correta da graça inevitavelmente produzirá uma vida zelosa de boas obras.'
  },
  {
    id: 'phm_1_8_22',
    intro: 'A carta a Filemom é a menor e mais pessoal das epístolas de Paulo, mas contém uma das mais profundas ilustrações práticas do evangelho. Onésimo era um escravo que havia roubado o seu senhor, Filemom (um líder da igreja em Colossos), e fugido para Roma. Lá, providencialmente, ele encontrou o apóstolo Paulo na prisão, ouviu o evangelho e se converteu a Cristo. Agora, Paulo está enviando Onésimo de volta a Filemom, não mais como um escravo fugitivo, mas como um irmão amado. Paulo usa toda a sua influência pastoral para apelar a Filemom por perdão e reconciliação.',
    desc1: 'O Apelo Baseado no Amor, não na Autoridade. Paulo, como apóstolo, tinha autoridade para ordenar a Filemom que perdoasse Onésimo. No entanto, ele escolhe o caminho da graça: "por amor te rogo". Paulo se apresenta como "o velho, e agora também prisioneiro de Jesus Cristo", apelando à compaixão de Filemom. Ele chama Onésimo de "meu filho, que gerei nas minhas prisões". Paulo faz um jogo de palavras com o nome Onésimo (que significa "útil"): antes ele era inútil para Filemom, mas agora, transformado por Cristo, ele é útil tanto para Filemom quanto para Paulo.',
    desc2: 'A Providência Divina e a Nova Identidade. Paulo oferece uma perspectiva teológica sobre a fuga de Onésimo: "Porque bem pode ser que ele se tenha separado de ti por algum tempo, para que o retivesses para sempre". Deus usou o pecado de Onésimo (a fuga) para trazê-lo à salvação. A grande mudança é a nova identidade de Onésimo: ele não deve ser recebido "como servo, antes, mais do que servo, como irmão amado". O evangelho destrói as barreiras sociais e de classe; em Cristo, o senhor e o escravo tornam-se irmãos iguais diante da cruz. Paulo pede: "Recebe-o como a mim mesmo".',
    desc3: 'A Imputação e o Pagamento da Dívida. O versículo 18 é uma das mais belas ilustrações da doutrina da imputação (como Cristo pagou a nossa dívida): "E, se te fez algum dano, ou te deve alguma coisa, põe isso à minha conta". Paulo, de próprio punho, assina uma nota promissória assumindo a dívida do escravo. É exatamente isso que Jesus fez por nós na cruz: Ele assumiu a nossa dívida de pecado e nos cobriu com a Sua justiça. Paulo confia que Filemom fará "ainda mais do que digo", insinuando não apenas o perdão, mas possivelmente a libertação (alforria) de Onésimo.',
    concl: 'A carta a Filemom é o evangelho em ação. Assim como Onésimo, nós éramos fugitivos, inúteis e devedores a Deus. Mas Cristo intercedeu por nós, pagou a nossa dívida e pediu ao Pai que nos recebesse como filhos amados. O perdão que recebemos de Cristo deve ser o padrão do perdão que oferecemos aos outros.'
  },
  {
    id: 'heb_4_14_16',
    intro: 'O livro de Hebreus foi escrito para cristãos judeus que, sob intensa perseguição, estavam tentados a abandonar a fé em Cristo e voltar aos rituais do judaísmo do Antigo Testamento. O autor argumenta ao longo da carta que Cristo é superior a tudo: aos anjos, a Moisés e ao sistema sacrificial. Nestes versículos, ele apresenta Jesus como o "Grande Sumo Sacerdote". Diferente dos sacerdotes levíticos que eram pecadores e ministravam em um templo terreno, Jesus é o Filho de Deus que penetrou os céus. Esta passagem oferece um profundo conforto, mostrando que a majestade divina de Cristo não anula a Sua compaixão humana.',
    desc1: 'O Sacerdote que Penetrou os Céus. O autor declara: "Visto que temos um grande sumo sacerdote, Jesus, Filho de Deus, que penetrou nos céus, retenhamos firmemente a nossa confissão". No Dia da Expiação (Yom Kippur), o sumo sacerdote terreno entrava no Santo dos Santos, atrás do véu, uma vez por ano. Jesus, no entanto, após a Sua ressurreição e ascensão, "penetrou nos céus" (o verdadeiro Santo dos Santos), entrando na própria presença de Deus Pai. Porque temos um mediador tão exaltado e vitorioso, somos exortados a não desistir da nossa fé ("reter a confissão"), independentemente da oposição.',
    desc2: 'A Simpatia do Sacerdote Sem Pecado. A grandeza de Jesus poderia nos afastar, fazendo-nos pensar que Ele é inacessível. O autor imediatamente corrige isso: "Porque não temos um sumo sacerdote que não possa compadecer-se das nossas fraquezas". A palavra "compadecer-se" (sympatheo) significa sofrer com, sentir a mesma dor. Jesus não é um Deus distante; Ele se tornou carne. Ele foi "tentado em todas as coisas, à nossa semelhança, mas sem pecado". Ele conheceu a fome, a traição, a dor física, a angústia mental e a tentação diabólica. Ele entende a nossa luta por experiência própria, mas, por não ter pecado, Ele tem o poder para nos socorrer.',
    desc3: 'O Trono da Graça. A conclusão lógica dessa teologia é um convite ousado: "Cheguemos, pois, com confiança ao trono da graça, para que possamos alcançar misericórdia e achar graça, a fim de sermos ajudados em tempo oportuno". No Antigo Testamento, o trono de Deus (a arca da aliança) era um lugar de terror e julgamento para o pecador; ninguém se aproximava com confiança. Mas, por causa do sangue de Cristo, o trono do julgamento foi transformado no "trono da graça". Podemos nos aproximar com "confiança" (parrhesia, liberdade de fala), sabendo que encontraremos misericórdia para os nossos pecados passados e graça para as nossas lutas presentes.',
    concl: 'Não precisamos de mediadores humanos ou rituais complexos para chegar a Deus. Temos Jesus, o Grande Sumo Sacerdote, que é perfeitamente divino para nos salvar e perfeitamente humano para nos compreender. Quando estivermos fracos, tentados ou falhos, não devemos fugir de Deus, mas correr ousadamente para o Seu trono, onde a graça sempre nos espera.'
  },
  {
    id: 'jas_3_1_12',
    intro: 'Tiago, o irmão do Senhor, escreve o manual mais prático do Novo Testamento sobre a vida cristã. No capítulo 3, ele aborda um dos problemas mais universais e destrutivos da humanidade: os pecados da fala. A igreja primitiva estava sofrendo com fofocas, divisões e falsos mestres. Tiago usa uma série de ilustrações vívidas da natureza (cavalos, navios, fogo, feras e fontes) para demonstrar que a língua, embora seja um membro pequeno do corpo, tem um poder desproporcional para direcionar a vida, destruir relacionamentos e revelar a verdadeira condição do coração.',
    desc1: 'O Poder de Direcionar. Tiago começa com um aviso aos que desejam ser mestres, pois eles receberão um juízo mais severo, já que o ensino envolve o uso constante da palavra. Ele reconhece que "todos tropeçamos em muitas coisas", mas aquele que não tropeça no falar é um "varão perfeito" (maduro), capaz de controlar todo o corpo. Para ilustrar o poder de direção da língua, ele usa duas imagens: o freio na boca do cavalo (que controla um animal forte) e o pequeno leme do navio (que direciona uma grande embarcação contra ventos fortes). A língua dita o curso da nossa vida e dos nossos relacionamentos.',
    desc2: 'O Poder de Destruir. A terceira ilustração é aterrorizante: "Vede quão grande bosque um pequeno fogo incendeia". Uma simples faísca (uma fofoca, uma mentira, uma palavra irada) pode destruir reputações, famílias e igrejas inteiras. Tiago chama a língua de "um mundo de iniquidade" que contamina todo o corpo e é "inflamada pelo inferno". Ele contrasta a língua com o reino animal: o homem conseguiu domar feras, aves e serpentes, mas "nenhum homem pode domar a língua". Ela é um "mal que não se pode refrear; está cheia de peçonha mortal". Isso mostra que a transformação da fala requer um milagre sobrenatural, não apenas esforço humano.',
    desc3: 'A Inconsistência do Coração. Tiago aponta a hipocrisia trágica dos crentes: "Com ela bendizemos a Deus e Pai, e com ela amaldiçoamos os homens, feitos à semelhança de Deus". Da mesma boca procedem louvor e maldição. Ele declara enfaticamente: "Meus irmãos, não convém que isto se faça assim". Para provar o absurdo dessa inconsistência, ele usa ilustrações da natureza: uma fonte não pode jorrar água doce e salgada ao mesmo tempo; uma figueira não pode produzir azeitonas. A natureza da raiz determina o fruto. Se a nossa fala é amarga, isso revela que o nosso coração (a fonte) precisa ser purificado por Deus.',
    concl: 'As nossas palavras não são inofensivas; elas têm o poder de dar vida ou causar destruição. Tiago nos ensina que não podemos domar a língua com a nossa própria força de vontade. Precisamos submeter o nosso coração ao Espírito Santo diariamente, para que a fonte da nossa vida seja purificada e as nossas palavras se tornem instrumentos de graça, cura e edificação.'
  },
  {
    id: '1pe_2_4_10',
    intro: 'O apóstolo Pedro escreve a cristãos que estavam espalhados pela Ásia Menor, sofrendo perseguição, marginalização e sentindo-se como exilados na sociedade. Para encorajar esses crentes rejeitados pelo mundo, Pedro os lembra da sua nova e gloriosa identidade em Cristo. Usando ricas metáforas do Antigo Testamento relacionadas ao templo e ao sacerdócio, Pedro mostra que a Igreja não é um edifício de tijolos, mas um organismo vivo, construído sobre a fundação inabalável de Jesus Cristo, com o propósito de proclamar as virtudes de Deus ao mundo.',
    desc1: 'A Pedra Angular e o Templo Espiritual. Pedro convida os crentes a se chegarem a Cristo, descrevendo-O como uma "pedra viva, reprovada, na verdade, pelos homens, mas para com Deus eleita e preciosa". Jesus foi rejeitado pelos líderes religiosos (os construtores), mas Deus O fez a pedra angular (a pedra principal que sustenta e alinha todo o edifício). Ao nos unirmos a Cristo, nós também nos tornamos "pedras vivas", sendo edificados para formar uma "casa espiritual" (o novo templo onde Deus habita pelo Seu Espírito). Não precisamos mais ir a um templo físico em Jerusalém; a Igreja é o templo vivo de Deus.',
    desc2: 'O Sacerdócio Santo e a Pedra de Tropeço. Além de sermos o templo, somos também o "sacerdócio santo, para oferecer sacrifícios espirituais agradáveis a Deus por Jesus Cristo". No Antigo Testamento, apenas a tribo de Levi podia ser sacerdote; agora, todo crente tem acesso direto a Deus e o privilégio de oferecer sacrifícios de louvor, oração e boas obras. Pedro então contrasta o destino dos crentes com o dos incrédulos. Para os que creem, Cristo é precioso. Mas para os desobedientes, a mesma pedra angular torna-se uma "pedra de tropeço e rocha de escândalo". O evangelho inevitavelmente divide a humanidade.',
    desc3: 'A Nova Identidade e Missão. O versículo 9 é uma das declarações mais majestosas sobre a identidade da Igreja: "Mas vós sois a geração eleita, o sacerdócio real, a nação santa, o povo adquirido". Pedro aplica à Igreja os títulos de honra que Deus havia dado a Israel no Sinai. Somos reais (pertencemos ao Rei) e santos (separados para Deus). O propósito dessa eleição não é o orgulho, mas a missão: "para que anuncieis as virtudes daquele que vos chamou das trevas para a sua maravilhosa luz". Antes não éramos povo, mas agora somos o povo de Deus, recipientes da Sua misericórdia.',
    concl: 'Quando o mundo nos rejeita ou nos marginaliza, devemos lembrar quem somos em Cristo. Somos pedras vivas no templo de Deus, sacerdotes reais com acesso direto ao Pai, e um povo escolhido com uma missão gloriosa. A nossa resposta à hostilidade do mundo não deve ser o medo ou o isolamento, mas a proclamação ousada da luz e da misericórdia de Deus através das nossas palavras e vidas.'
  },
  {
    id: '2pe_3_1_13',
    intro: 'A Segunda Epístola de Pedro foi escrita pouco antes do martírio do apóstolo. A igreja estava enfrentando uma ameaça interna perigosa: falsos mestres e escarnecedores que zombavam da promessa da segunda vinda de Cristo e do julgamento final. Eles argumentavam que, como o mundo parecia continuar o mesmo desde a criação, a intervenção divina era um mito, usando isso como desculpa para viverem na imoralidade. Pedro escreve para refutar esse ceticismo, explicando a razão da aparente "demora" de Deus e exortando os crentes a viverem em santidade à luz da eternidade.',
    desc1: 'A Refutação dos Escarnecedores. Pedro lembra os crentes das palavras dos profetas e apóstolos. Ele avisa que nos últimos dias virão escarnecedores, andando segundo as suas próprias concupiscências, perguntando com deboche: "Onde está a promessa da sua vinda?". Eles argumentam a uniformidade da natureza (tudo continua como sempre foi). Pedro refuta isso apontando para a história: eles esquecem voluntariamente que Deus já interveio no mundo através do dilúvio nos dias de Noé, destruindo o mundo antigo com água. O mesmo Deus que julgou o mundo com água preservou os céus e a terra atuais pela Sua Palavra, reservando-os para o julgamento final com fogo.',
    desc2: 'A Perspectiva Divina do Tempo e a Graça. Pedro aborda a questão da "demora" de Deus. Primeiro, ele ensina que Deus não está sujeito ao nosso relógio: "um dia para o Senhor é como mil anos, e mil anos como um dia". O que parece uma eternidade para nós é um breve momento para Deus. Segundo, a aparente demora não é negligência, mas misericórdia (v. 9): "O Senhor não retarda a sua promessa... mas é longânimo para convosco, não querendo que alguns se percam, senão que todos venham a arrepender-se". O tempo extra é o tempo da graça. No entanto, o "Dia do Senhor" virá inevitavelmente e de forma repentina, "como o ladrão de noite", trazendo a dissolução cósmica dos céus e da terra.',
    desc3: 'A Ética Escatológica. A profecia bíblica sempre tem um propósito prático. Pedro faz a pergunta crucial: "Visto que todas estas coisas hão de ser assim desfeitas, que pessoas vos convém ser em santo trato, e piedade?". A certeza do julgamento final e da destruição do mundo material deve nos libertar do materialismo e nos impulsionar à santidade. Pedro diz que devemos "aguardar, e apressar a vinda do dia de Deus" através da nossa vida piedosa e evangelismo. A nossa esperança não termina na destruição, mas na recriação (v. 13): "Mas nós, segundo a sua promessa, aguardamos novos céus e nova terra, em que habita a justiça".',
    concl: 'A zombaria do mundo não anula a promessa de Deus. A volta de Cristo é certa, e a Sua aparente demora é apenas a extensão da Sua misericórdia para que mais pessoas sejam salvas. Viver à luz da eternidade significa não nos apegarmos às coisas passageiras deste mundo, mas investirmos a nossa vida em santidade, piedade e na proclamação do evangelho, aguardando com alegria o novo mundo de justiça que Ele preparou para nós.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 35');
