const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'luk_19_28_40',
    intro: 'A Entrada Triunfal (celebrada no Domingo de Ramos) marca o início da semana mais importante da história da humanidade: a Semana da Paixão. Durante todo o Seu ministério, Jesus havia evitado a publicidade excessiva e proibido que O chamassem abertamente de Messias, pois o Seu tempo ainda não havia chegado e o povo tinha uma visão distorcida de um Messias político e militar. No entanto, neste dia específico, Jesus orquestra deliberadamente uma demonstração pública e profética da Sua identidade messiânica. Ele entra em Jerusalém não como um conquistador romano em um cavalo de guerra, mas como o Rei da Paz montado em um jumentinho, forçando a nação a tomar uma decisão final sobre quem Ele é.',
    desc1: 'A preparação para a entrada é meticulosa. Jesus envia dois discípulos a uma aldeia próxima com instruções precisas para trazerem um jumentinho "em que nenhum homem ainda montou". O uso de um animal nunca montado era reservado para propósitos sagrados ou reais. Quando os donos perguntam por que estão soltando o jumentinho, os discípulos respondem exatamente como Jesus instruiu: "O Senhor precisa dele". Jesus está reivindicando autoridade soberana sobre a propriedade dos homens. Ao montar no jumentinho, Jesus está cumprindo intencionalmente a profecia de Zacarias 9:9: "Alegra-te muito, ó filha de Sião... eis que o teu rei virá a ti, justo e Salvador, pobre, e montado sobre um jumento".',
    desc2: 'A reação da multidão (composta em grande parte por peregrinos galileus que subiam para a Páscoa) é de euforia messiânica. Eles estendem as suas vestes no caminho (um ato de submissão real, como fizeram com o rei Jeú no Antigo Testamento) e começam a louvar a Deus em alta voz por todos os milagres que tinham visto. Eles cantam o Salmo 118 (um salmo messiânico): "Bendito o Rei que vem em nome do Senhor; paz no céu, e glória nas alturas!". A multidão reconhece Jesus como o Rei prometido da linhagem de Davi. No entanto, a sua expectativa era de libertação política de Roma, não de salvação espiritual do pecado.',
    desc3: 'A adoração pública incomoda profundamente a elite religiosa. Alguns fariseus no meio da multidão dizem a Jesus: "Mestre, repreende os teus discípulos". Eles entendiam as implicações teológicas e políticas daqueles cânticos e queriam que Jesus negasse a Sua identidade messiânica para evitar a ira dos romanos. A resposta de Jesus é uma das declarações mais poderosas sobre a inevitabilidade do louvor a Deus: "Digo-vos que, se estes se calarem, as próprias pedras clamarão". A glória de Cristo é tão grande e o momento profético é tão crucial que, se a humanidade falhasse em reconhecê-Lo, a própria criação inanimada romperia o silêncio para adorar o seu Criador.',
    concl: 'A Entrada Triunfal nos ensina que Jesus é o Rei legítimo, mas o Seu reino não é deste mundo. Ele não vem para nos dar vitórias políticas ou conforto terreno, mas para trazer a paz verdadeira através do Seu sacrifício. A história também nos desafia: se a multidão O louvou por motivos errados e os fariseus tentaram silenciá-Lo, qual será a nossa resposta? Nós O adoraremos pelo que Ele realmente é, ou deixaremos que as pedras clamem em nosso lugar?'
  },
  {
    id: 'gen_11_1_9',
    intro: 'O relato da Torre de Babel é o evento culminante da história primitiva da humanidade antes do chamado de Abraão. Após o dilúvio, Deus havia ordenado a Noé e aos seus descendentes: "Frutificai e multiplicai-vos, e enchei a terra" (Gênesis 9:1). O propósito de Deus era que a humanidade se espalhasse e administrasse toda a criação. No entanto, em Gênesis 11, encontramos a humanidade unida não em obediência, mas em rebelião. Eles decidem se concentrar em um único lugar (a planície de Sinar) e usar a tecnologia humana (tijolos e betume) para construir uma cidade e uma torre que alcançasse os céus. A história de Babel é o arquétipo do humanismo secular: a tentativa do homem de construir um paraíso na terra e alcançar a divindade sem a necessidade de Deus.',
    desc1: 'A motivação dos construtores é revelada de forma clara: "E disseram: Eia, edifiquemos nós uma cidade e uma torre cujo cume toque nos céus, e façamo-nos um nome, para que não sejamos espalhados sobre a face de toda a terra". O projeto era movido por dois pecados fundamentais: o orgulho ("façamo-nos um nome", em oposição a glorificar o nome de Deus) e a rebelião direta contra a ordem divina ("para que não sejamos espalhados"). A torre (provavelmente um zigurate, um templo em forma de pirâmide em degraus) era uma tentativa religiosa de manipular os deuses e alcançar o céu pelo próprio esforço humano. A unidade humana, quando não está centrada em Deus, inevitavelmente se torna uma força para o mal.',
    desc2: 'A resposta de Deus é descrita com uma ironia divina maravilhosa. Os homens estavam construindo a torre mais alta possível para "tocar nos céus", mas o texto diz: "Então desceu o Senhor para ver a cidade e a torre que os filhos dos homens edificavam". A maior conquista arquitetônica da humanidade era tão minúscula que Deus teve que "descer" para conseguir vê-la. Deus avalia a situação: "Eis que o povo é um, e todos têm uma mesma linguagem... e agora não haverá restrição para tudo o que eles intentarem fazer". Deus reconhece o potencial destrutivo da humanidade unida no pecado. A intervenção de Deus não é por medo da concorrência humana, mas um ato de misericórdia para impedir que a humanidade se destruísse rapidamente na sua própria arrogância.',
    desc3: 'A solução divina é cirúrgica e eficaz: "Eia, desçamos e confundamos ali a sua linguagem, para que não entenda um a linguagem do outro". Deus não destrói a torre com um raio nem mata os construtores; Ele simplesmente quebra a comunicação. Sem a capacidade de se entenderem, a cooperação torna-se impossível, a desconfiança cresce e o projeto entra em colapso. O resultado é exatamente o que eles tentaram evitar: "Assim o Senhor os espalhou dali sobre a face de toda a terra; e cessaram de edificar a cidade". O lugar foi chamado Babel (que soa como a palavra hebraica para "confusão").',
    concl: 'A Torre de Babel nos ensina que qualquer projeto humano (seja uma civilização, uma empresa ou uma igreja) construído para exaltar o nome do homem e ignorar a vontade de Deus está fadado à confusão e ao fracasso. A verdadeira unidade não é alcançada pela uniformidade de linguagem ou tecnologia, mas pelo Espírito Santo, como visto no Pentecostes (Atos 2), onde Deus reverteu a maldição de Babel, permitindo que pessoas de todas as línguas ouvissem as grandezas de Deus e se unissem em Cristo.'
  },
  {
    id: 'exo_3_13_22',
    intro: 'O encontro de Moisés com Deus na sarça ardente é o momento de revelação teológica mais importante do Antigo Testamento. Deus havia acabado de chamar Moisés (um pastor exilado de 80 anos) para a tarefa impossível de libertar Israel da escravidão do Egito. Moisés, cheio de dúvidas e inseguranças, tenta encontrar desculpas para não ir. A sua segunda objeção é uma pergunta fundamental sobre a identidade de Deus: "Eis que quando eu for aos filhos de Israel, e lhes disser: O Deus de vossos pais me enviou a vós; e eles me disserem: Qual é o seu nome? Que lhes direi?". A resposta de Deus a essa pergunta não apenas revela o Seu nome, mas define a Sua própria essência, natureza e poder absoluto para todas as gerações.',
    desc1: 'No antigo Oriente Médio, o nome de um deus revelava o seu caráter, a sua função e a sua esfera de poder (por exemplo, o deus do sol, o deus da fertilidade). Moisés sabia que os israelitas, imersos na cultura politeísta do Egito, exigiriam saber qual era a "especialidade" desse Deus que prometia libertá-los. A resposta de Deus destrói qualquer tentativa de categorizá-Lo: "EU SOU O QUE SOU" (em hebraico, Ehyeh asher ehyeh). Deus não Se define em relação a nada criado. Ele não diz "Eu sou o Deus da força" ou "Eu sou o Deus do céu". Ele simplesmente É. Essa declaração revela a asseidade de Deus: Ele é autoexistente, eterno, imutável e não depende de nada nem de ninguém para existir.',
    desc2: 'Deus então instrui Moisés a usar uma forma abreviada desse nome para o povo: "Assim dirás aos filhos de Israel: EU SOU me enviou a vós". A partir dessa raiz hebraica (o verbo ser/existir) deriva o nome sagrado YHWH (Yahweh ou Jeová), o nome pactual de Deus. Deus acrescenta: "O Senhor (Yahweh), o Deus de vossos pais, o Deus de Abraão, o Deus de Isaque, e o Deus de Jacó, me enviou a vós; este é meu nome eternamente". O "EU SOU" não é um conceito filosófico abstrato; Ele é o Deus pessoal que faz alianças e entra na história humana para salvar o Seu povo. O Seu nome é a garantia de que as Suas promessas não falharão, pois Ele é o mesmo ontem, hoje e eternamente.',
    desc3: 'Com a autoridade do nome revelado, Deus detalha o plano de libertação. Moisés deve reunir os anciãos de Israel e declarar que Deus "visitou" o Seu povo e viu a sua aflição. Deus promete tirá-los do Egito e levá-los a uma terra que mana leite e mel. Deus também antecipa a resistência de Faraó: "Eu sei, porém, que o rei do Egito não vos deixará ir, nem ainda por uma mão forte". O "EU SOU" não é pego de surpresa pela oposição humana. Ele promete estender a Sua mão, ferir o Egito com maravilhas e, no final, o povo não sairá de mãos vazias, mas despojará os egípcios. A libertação será completa e gloriosa.',
    concl: 'A revelação do "EU SOU" nos ensina que a nossa segurança não está nas nossas próprias capacidades (como Moisés temia), mas na natureza imutável do Deus que nos chama. Quando Jesus declarou "Antes que Abraão existisse, EU SOU" (João 8:58), Ele estava reivindicando para Si mesmo esse mesmo nome divino. O "EU SOU" é tudo o que precisamos em qualquer situação: se estamos fracos, Ele é a força; se estamos perdidos, Ele é o caminho.'
  },
  {
    id: 'num_21_4_9',
    intro: 'A história da serpente de bronze é um dos episódios mais estranhos e, ao mesmo tempo, mais profundamente proféticos do Antigo Testamento. O povo de Israel estava na reta final da sua jornada de quarenta anos no deserto, contornando a terra de Edom. O caminho era longo e difícil, e, mais uma vez, o povo perde a paciência e cai no seu pecado crônico: a murmuração. Eles reclamam contra Deus e contra Moisés, desprezando a provisão divina. A resposta de Deus é um juízo imediato e letal, seguido por uma provisão de salvação tão singular que o próprio Jesus a usaria séculos mais tarde (em João 3) como a ilustração perfeita da Sua morte na cruz e da salvação pela fé.',
    desc1: 'A rebelião do povo é expressa com uma ingratidão chocante: "Por que nos fizestes subir do Egito, para que morramos neste deserto? Pois aqui nem pão nem água há; e a nossa alma tem fastio deste pão tão vil (o maná)". Eles chamam a provisão milagrosa e diária de Deus de "pão vil" (miserável, sem valor). A murmuração não é apenas uma reclamação sobre as circunstâncias; é um ataque direto ao caráter e à bondade de Deus. Como consequência do seu desprezo pela graça, Deus remove a Sua mão protetora e "enviou serpentes ardentes entre o povo, que morderam o povo; e morreu muita gente em Israel". O veneno das serpentes era o reflexo físico do veneno da rebelião que já estava nos seus corações.',
    desc2: 'O juízo traz o povo de volta à realidade. Eles correm para Moisés, confessam o seu pecado ("Pecamos, porquanto falamos contra o Senhor e contra ti") e pedem intercessão: "Ora ao Senhor que tire de nós estas serpentes". Moisés, demonstrando mais uma vez o coração de um mediador, ora pelo povo. A resposta de Deus é surpreendente. Ele não mata as serpentes nem fornece um antídoto médico. Ele ordena a Moisés: "Faze-te uma serpente ardente, e põe-na sobre uma haste; e será que viverá todo o que, tendo sido picado, olhar para ela". A cura viria através de um símbolo que representava a própria causa da sua morte.',
    desc3: 'Moisés obedece, faz uma serpente de metal (bronze ou cobre) e a levanta em um poste no meio do acampamento. O método de salvação era escandalosamente simples: "quando uma serpente picava a alguém, e esse olhava para a serpente de metal, vivia". A cura não exigia obras, sacrifícios, dinheiro ou mérito moral; exigia apenas fé. A pessoa picada precisava reconhecer que estava morrendo (o veneno estava no seu sangue) e escolher olhar para a provisão de Deus com a expectativa de ser curada. O olhar de fé era a única ponte entre a morte certa e a vida milagrosa.',
    concl: 'Jesus explicou o significado definitivo desta história a Nicodemos: "E, como Moisés levantou a serpente no deserto, assim importa que o Filho do homem seja levantado; para que todo aquele que nele crê não pereça, mas tenha a vida eterna" (João 3:14-15). Jesus (que não tinha pecado) foi feito pecado por nós na cruz (representado pela serpente de bronze). A salvação hoje exige a mesma atitude: reconhecer que o veneno do pecado está em nós e olhar com fé exclusiva para Cristo crucificado para recebermos a vida eterna.'
  },
  {
    id: '1sa_24_1_22',
    intro: 'O capítulo 24 de 1 Samuel narra um dos testes de caráter mais intensos da vida de Davi. Davi, o herói ungido de Israel, estava vivendo como um fugitivo no deserto de En-Gedi, caçado implacavelmente pelo rei Saul, que estava consumido pela inveja e pela paranoia. Saul leva três mil soldados de elite para procurar Davi e os seus seiscentos homens entre as rochas escarpadas. Durante a busca, Saul entra sozinho em uma caverna para "cobrir os pés" (fazer as suas necessidades), sem saber que Davi e os seus homens estavam escondidos exatamente no fundo daquela mesma caverna. É o cenário perfeito para a vingança. A maneira como Davi lida com essa oportunidade revela a diferença entre a sabedoria humana (que busca o poder a qualquer custo) e a sabedoria divina (que confia no tempo e na justiça de Deus).',
    desc1: 'Quando os homens de Davi veem Saul vulnerável na caverna, eles interpretam a situação como uma providência divina: "Eis aqui o dia, do qual o Senhor te dizia: Eis que te dou o teu inimigo nas tuas mãos, e far-lhe-ás como te parecer bem aos teus olhos". A tentação era enorme. Matar Saul resolveria todos os problemas de Davi instantaneamente: ele deixaria de ser um fugitivo, salvaria a vida dos seus homens e assumiria o trono que Deus já lhe havia prometido. A lógica humana e a pressão dos seus seguidores diziam que era a vontade de Deus matar o rei. No entanto, Davi se levanta silenciosamente e apenas corta a orla do manto de Saul.',
    desc2: 'Imediatamente após cortar o manto, a consciência de Davi pesa. Ele percebe que até mesmo esse pequeno ato de desrespeito era uma violação do princípio de autoridade. Ele diz aos seus homens: "O Senhor me guarde de que eu faça tal coisa ao meu senhor, ao ungido do Senhor, estendendo eu a minha mão contra ele; pois é o ungido do Senhor". Davi entende que, embora Saul fosse um rei mau e rejeitado por Deus, ele ainda ocupava a posição de autoridade estabelecida por Deus. Davi recusa-se a tomar o trono com as próprias mãos manchadas de sangue. Ele confia que Deus, que lhe prometeu a coroa, também providenciaria o meio e o tempo certo para entregá-la, sem que Davi precisasse pecar para obtê-la.',
    desc3: 'Quando Saul sai da caverna, Davi sai atrás dele, prostra-se com o rosto em terra (demonstrando submissão) e o confronta com a verdade. Ele mostra o pedaço do manto como prova irrefutável da sua inocência: "Olha, pois, meu pai, vê aqui a orla do teu manto na minha mão... reconhece e vê que não há mal nem rebeldia na minha mão". Davi apela para o tribunal divino: "Julgue o Senhor entre mim e ti, e vingue-me o Senhor de ti; porém a minha mão não será contra ti". Saul, quebrado pela graça inesperada de Davi, chora em voz alta e confessa: "Mais justo és do que eu; pois tu me recompensaste com bem, e eu te recompensei com mal". Saul reconhece publicamente que Davi será o futuro rei de Israel.',
    concl: 'A atitude de Davi na caverna de En-Gedi nos ensina que os fins não justificam os meios no Reino de Deus. Nunca devemos usar métodos pecaminosos (vingança, traição, desrespeito à autoridade) para alcançar as promessas de Deus. A verdadeira fé não é apenas acreditar que Deus nos dará a vitória, mas confiar que Ele o fará à Sua maneira e no Seu tempo, permitindo-nos manter as nossas mãos limpas e o nosso coração puro.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 24');
