const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: '1jn_4_7_21',
    intro: 'A Primeira Epístola de João foi escrita para combater falsos mestres (gnósticos) que afirmavam ter um conhecimento espiritual superior, mas cujas vidas eram marcadas pela arrogância e pela falta de amor aos irmãos. Em resposta, João, o "apóstolo do amor", escreve a passagem mais profunda de toda a Bíblia sobre a natureza do amor. Ele argumenta que o amor não é apenas um mandamento ético ou um sentimento humano elevado; o amor é a própria essência do caráter divino. Consequentemente, a verdadeira marca de alguém que "conhece a Deus" não é o misticismo intelectual, mas a prática do amor sacrificial.',
    desc1: 'A Origem e a Essência do Amor. João começa com um imperativo: "Amados, amemo-nos uns aos outros". A razão para isso é ontológica: "porque o amor é de Deus". O amor verdadeiro não se origina no coração humano caído; ele flui de Deus. João faz uma das declarações teológicas mais absolutas da Escritura: "Deus é amor" (v. 8). Isso não significa que "amor é Deus" (reduzindo Deus a um sentimento), mas que todos os atributos de Deus são permeados pelo Seu amor. Portanto, "qualquer que ama é nascido de Deus e conhece a Deus", enquanto "aquele que não ama não conhece a Deus".',
    desc2: 'A Manifestação Histórica do Amor. O amor de Deus não permaneceu como um conceito abstrato no céu; ele foi demonstrado na história. "Nisto se manifestou o amor de Deus para conosco: que Deus enviou seu Filho unigênito ao mundo, para que por ele vivamos" (v. 9). João define o amor não pelos nossos sentimentos em relação a Deus, mas pela ação de Deus em relação a nós: Ele enviou o Seu Filho para ser a "propiciação" (o sacrifício que apazigua a ira divina e remove a culpa) pelos nossos pecados. O amor verdadeiro é sempre sacrificial e toma a iniciativa.',
    desc3: 'A Prática e o Aperfeiçoamento do Amor. A conclusão lógica da cruz é a comunidade: "Se Deus assim nos amou, também nós devemos amar uns aos outros" (v. 11). Ninguém jamais viu a Deus, mas quando nos amamos, o Deus invisível torna-se visível no meio da congregação, e o Seu amor é "aperfeiçoado" (atinge o seu propósito) em nós. João também aborda o efeito interno do amor: "No amor não há temor, antes o perfeito amor lança fora o temor" (v. 18). O amor de Deus nos liberta do medo do julgamento final. O capítulo termina com um teste de hipocrisia: é impossível amar o Deus invisível se odiamos o irmão visível.',
    concl: 'O amor cristão não é uma emoção passageira, mas uma ação sacrificial baseada na cruz de Cristo. João nos ensina que a nossa teologia não vale nada se não resultar em amor prático pelos nossos irmãos. O mundo não conhecerá que Deus é amor através dos nossos discursos, mas através da forma como nos amamos uns aos outros.'
  },
  {
    id: '2jn_1_4_11',
    intro: 'A Segunda Epístola de João é uma carta curta, dirigida à "senhora eleita e a seus filhos" (provavelmente uma metáfora para uma igreja local e seus membros). No final do primeiro século, o cristianismo se espalhava através de missionários itinerantes que dependiam da hospitalidade das igrejas locais. No entanto, falsos mestres (anticristos) também viajavam, espalhando heresias, especialmente negando a encarnação física de Jesus Cristo. João escreve esta carta para equilibrar duas virtudes cristãs essenciais que frequentemente entram em tensão: o amor e a verdade. Ele ensina que o verdadeiro amor cristão não pode ser divorciado da verdade bíblica.',
    desc1: 'O Andar na Verdade e no Amor. João expressa grande alegria por encontrar os filhos da "senhora eleita" andando na verdade. Para João, a verdade não é apenas um conjunto de doutrinas para se acreditar, mas um caminho para se "andar" (viver). Imediatamente, ele une a verdade ao mandamento do amor: "que nos amemos uns aos outros" (v. 5). Ele define o amor de forma muito prática: "E o amor é este: que andemos segundo os seus mandamentos" (v. 6). O amor bíblico não é um sentimento anárquico; ele se expressa na obediência à Palavra de Deus. O amor sem verdade é sentimentalismo cego; a verdade sem amor é legalismo frio.',
    desc2: 'O Perigo dos Enganadores. A razão para a ênfase na verdade torna-se clara no versículo 7: "Porque já muitos enganadores entraram no mundo". Estes falsos mestres negavam que "Jesus Cristo veio em carne" (uma heresia conhecida como docetismo, que afirmava que Jesus era apenas um espírito que parecia humano). João não mede palavras; ele os chama de "o enganador e o anticristo". Negar a encarnação é destruir o evangelho, pois se Jesus não se tornou humano, Ele não poderia morrer como nosso substituto. João exorta a igreja a ter cuidado para não perder o galardão do seu trabalho espiritual.',
    desc3: 'Os Limites da Hospitalidade. João estabelece uma regra estrita sobre como lidar com esses falsos mestres (v. 10-11): "Se alguém vem ter convosco, e não traz esta doutrina, não o recebais em casa, nem tampouco o saudeis". No contexto antigo, receber alguém em casa e dar-lhe saudações significava aprovar e financiar o seu ministério. João não está proibindo a hospitalidade a não-cristãos ou pecadores (Jesus comia com eles), mas está proibindo o apoio financeiro e a plataforma a falsos mestres que distorcem o evangelho. Apoiar um herege é ser "cúmplice das suas más obras".',
    concl: 'A Segunda Carta de João nos ensina que a tolerância não é a virtude suprema do cristianismo; a verdade e o amor são. Devemos amar a todos, mas não devemos tolerar ou financiar doutrinas que destroem a pessoa e a obra de Jesus Cristo. O verdadeiro amor protege a igreja dos lobos que tentam devorar o rebanho com falsos ensinos.'
  },
  {
    id: '3jn_1_5_12',
    intro: 'A Terceira Epístola de João é uma carta profundamente pessoal dirigida a um líder cristão chamado Gaio. Enquanto a Segunda Carta de João alertava contra a hospitalidade a falsos mestres, a Terceira Carta encoraja a hospitalidade aos verdadeiros missionários. A carta nos dá um vislumbre fascinante da política interna e dos conflitos de liderança na igreja primitiva. João contrasta três homens: Gaio (o crente fiel e hospitaleiro), Diótrefes (o líder arrogante e ditatorial) e Demétrio (o obreiro de bom testemunho). Através desses exemplos, João ensina sobre a verdadeira liderança e a importância de apoiar a obra de Deus.',
    desc1: 'O Exemplo de Gaio: Hospitalidade Fiel. João elogia Gaio pelo seu "fiel procedimento" ao receber os irmãos, mesmo sendo estrangeiros (missionários itinerantes). Esses missionários deram testemunho do amor de Gaio perante a igreja. João o encoraja a continuar ajudando-os na sua viagem "de um modo digno de Deus" (v. 6). A razão para esse apoio é nobre: esses missionários saíram "por amor do Nome" (de Jesus), não aceitando sustento dos pagãos para não comprometer o evangelho. João conclui que, ao hospedar e sustentar tais obreiros, nos tornamos "cooperadores da verdade" (v. 8). Quem financia a missão participa da recompensa da missão.',
    desc2: 'O Mau Exemplo de Diótrefes: Arrogância e Divisão. Em forte contraste com Gaio, João expõe Diótrefes, um líder que "gosta de ter a primazia" (querer ser o primeiro, o chefe absoluto) na igreja. O orgulho de Diótrefes o levou a quatro atitudes destrutivas: 1) Ele não recebia a autoridade do apóstolo João; 2) Ele proferia palavras maliciosas contra os apóstolos; 3) Ele se recusava a receber os missionários itinerantes; 4) Ele excomungava (expulsava da igreja) aqueles que queriam receber os missionários. Diótrefes tratava a igreja como sua propriedade particular, colocando o seu próprio ego acima do Reino de Deus.',
    desc3: 'O Bom Exemplo de Demétrio e a Exortação Final. João promete que, quando for visitá-los, lidará pessoalmente com as obras más de Diótrefes. Ele então dá um conselho crucial a Gaio (v. 11): "Amado, não sigas o mal, mas o bem. Quem faz o bem é de Deus; mas quem faz o mal não tem visto a Deus". A liderança abusiva não deve ser imitada. Finalmente, João apresenta Demétrio (provavelmente o portador da carta) como um modelo a ser seguido. Demétrio tinha um bom testemunho de todos, da própria verdade e dos apóstolos. A verdadeira liderança cristã é validada pelo caráter e pelo testemunho, não pela força ou intimidação.',
    concl: 'A Terceira Carta de João nos ensina que a igreja não é o lugar para egos inflados ou ditadores espirituais. A verdadeira grandeza no Reino de Deus é vista na hospitalidade generosa, no apoio à obra missionária e em um caráter que reflete a verdade do evangelho. Devemos fugir do exemplo de Diótrefes e imitar a fidelidade de Gaio e Demétrio.'
  },
  {
    id: 'jud_1_17_25',
    intro: 'A Epístola de Judas, escrita pelo meio-irmão de Jesus, é um dos textos mais urgentes e intensos do Novo Testamento. Judas planejava escrever uma carta calma sobre a salvação comum, mas foi compelido pelo Espírito Santo a mudar de tom e exortar os crentes a "batalharem pela fé". Falsos mestres haviam se infiltrado secretamente na igreja, transformando a graça de Deus em libertinagem (licença para pecar) e negando a Cristo. Após descrever o caráter corrupto e o julgamento inevitável desses apóstatas, Judas conclui a sua carta (v. 17-25) com um manual de sobrevivência espiritual, ensinando a igreja como permanecer firme e como resgatar aqueles que estão sendo enganados.',
    desc1: 'A Lembrança das Profecias e a Identificação dos Escarnecedores. Judas começa a sua conclusão dizendo aos "amados" que não deveriam estar surpresos com a crise. Os apóstolos de Cristo já haviam profetizado que "no último tempo haveria escarnecedores que andariam segundo as suas ímpias concupiscências" (v. 18). A apostasia não é um acidente, mas uma parte prevista da história da igreja. Judas identifica esses falsos mestres com três características: eles "causam divisões", são "sensuais" (guiados por instintos naturais e emoções terrenas, não pela Palavra) e "não têm o Espírito" (apesar de talvez alegarem ter experiências espirituais superiores).',
    desc2: 'A Edificação Pessoal: O Manual de Sobrevivência. Para não serem arrastados pela apostasia, os crentes devem assumir a responsabilidade pela sua própria saúde espiritual (v. 20-21). Judas dá quatro imperativos: 1) "Edificando-vos sobre a vossa santíssima fé" (crescendo no conhecimento da doutrina bíblica); 2) "Orando no Espírito Santo" (oração dependente e guiada pelo Espírito); 3) "Conservai-vos a vós mesmos no amor de Deus" (permanecendo na esfera da obediência onde o amor de Deus é desfrutado); 4) "Esperando a misericórdia de nosso Senhor Jesus Cristo para a vida eterna" (mantendo o foco na volta de Cristo). A defesa contra a heresia é uma vida espiritual profunda e disciplinada.',
    desc3: 'O Resgate dos Caídos e a Doxologia Final. A igreja não deve apenas se proteger, mas também agir como uma equipe de resgate (v. 22-23). Judas instrui a tratar as vítimas dos falsos mestres com discernimento: ter compaixão dos que duvidam; salvar outros "arrebatando-os do fogo" (uma intervenção urgente); e ter misericórdia de outros com "temor" (cuidado extremo), "aborrecendo até a roupa manchada da carne" (odiando o pecado enquanto tenta salvar o pecador). A carta termina com uma das mais belas doxologias da Bíblia (v. 24-25), louvando a Deus, que é o único "poderoso para vos guardar de tropeçar, e apresentar-vos irrepreensíveis, com alegria, perante a sua glória". A nossa segurança final não está no nosso esforço, mas no poder de Deus.',
    concl: 'Judas nos ensina que a fé cristã é uma batalha que exige vigilância constante. Não podemos ser ingênuos em relação aos falsos ensinos que distorcem a graça. Para sobrevivermos, devemos nos aprofundar na Palavra, orar no Espírito, resgatar os que estão caindo e, acima de tudo, confiar no poder do Deus que nos guarda de tropeçar até o dia final.'
  },
  {
    id: 'lev_16_1_22',
    intro: 'O capítulo 16 de Levítico descreve o dia mais sagrado, solene e importante do calendário judaico: o Yom Kippur, ou o Dia da Expiação. Era o único dia do ano em que o Sumo Sacerdote tinha permissão para entrar no Santo dos Santos (o lugar mais íntimo do tabernáculo, onde a presença de Deus habitava sobre a Arca da Aliança). Este ritual complexo não era apenas uma cerimônia de purificação nacional para os israelitas, mas é a mais profunda e detalhada prefiguração (tipo) no Antigo Testamento da obra redentora que Jesus Cristo realizaria na cruz. O Yom Kippur lidava com o problema fundamental da humanidade: como um Deus perfeitamente santo pode habitar no meio de um povo pecador sem destruí-lo.',
    desc1: 'A Preparação e a Entrada no Santo dos Santos. O ritual começa com um aviso severo: Arão (o sumo sacerdote) não pode entrar no Santo dos Santos quando quiser, para que não morra (como aconteceu com seus filhos Nadabe e Abiú). A santidade de Deus é perigosa para o pecador. Antes de ministrar pelo povo, Arão deve lavar-se e vestir roupas simples de linho branco (simbolizando pureza e humildade), deixando de lado as suas vestes gloriosas. Ele deve primeiro oferecer um novilho como sacrifício pelo seu próprio pecado e pelo da sua família. Ele entra no Santo dos Santos com uma nuvem de incenso para cobrir o propiciatório (a tampa da arca), protegendo-o da glória letal de Deus, e asperge o sangue do novilho.',
    desc2: 'O Bode Expiatório (O Sacrifício). O coração do ritual envolve dois bodes, que juntos representam as duas facetas da expiação. Lança-se sortes sobre eles: um para o Senhor e outro para "Azazel" (o bode emissário). O primeiro bode é morto como oferta pelo pecado do povo. Arão leva o sangue deste bode para dentro do Santo dos Santos e o asperge sobre o propiciatório. O sangue representa uma vida inocente dada em troca da vida dos culpados. O sangue "cobre" os pecados do povo e purifica o próprio santuário das impurezas de Israel. A justiça de Deus é satisfeita através do sacrifício substitutivo.',
    desc3: 'O Bode Emissário (A Remoção). A segunda faceta da expiação é demonstrada com o bode vivo. Arão coloca as duas mãos sobre a cabeça do bode vivo e confessa sobre ele "todas as iniquidades dos filhos de Israel, e todas as suas transgressões". Simbolicamente, a culpa da nação é transferida para o animal. Em seguida, o bode é levado por um homem designado para o deserto, uma terra solitária, e solto lá. O bode leva sobre si os pecados do povo para longe da presença de Deus e do acampamento. O primeiro bode mostra que o pecado foi pago (propiciação); o segundo bode mostra que o pecado foi removido e esquecido (expiação).',
    concl: 'O Dia da Expiação é o evangelho em sombras. Jesus Cristo cumpriu perfeitamente este ritual: Ele é o nosso Sumo Sacerdote sem pecado (que não precisou oferecer sacrifício por Si mesmo); Ele é o primeiro bode, cujo sangue pagou a nossa dívida e satisfez a justiça de Deus; e Ele é o bode emissário, que levou os nossos pecados para longe, para nunca mais serem lembrados. O véu foi rasgado, e agora temos acesso diário à presença de Deus.'
  },
  {
    id: 'deu_6_4_9',
    intro: 'O livro de Deuteronômio é uma série de sermões de despedida de Moisés à nova geração de israelitas que estava prestes a entrar na Terra Prometida. O capítulo 6 contém o texto mais importante da fé judaica, conhecido como o "Shemá" (da palavra hebraica para "Ouve", a primeira palavra do versículo 4). Jesus mais tarde identificaria este texto como o "maior e primeiro mandamento" (Mateus 22:38). O Shemá não é apenas uma declaração teológica sobre a unicidade de Deus, mas um chamado radical a um amor total e exclusivo, e um manual prático sobre como transmitir a fé para a próxima geração em um mundo cheio de ídolos.',
    desc1: 'A Declaração de Fé e o Grande Mandamento. Moisés começa com a confissão central de Israel (v. 4): "Ouve, Israel, o Senhor nosso Deus é o único Senhor" (ou "O Senhor é o nosso Deus, o Senhor é um"). Em um mundo antigo dominado pelo politeísmo (crença em muitos deuses), Israel é chamado a reconhecer a soberania exclusiva de Yahweh. A resposta lógica a essa verdade teológica é o mandamento do versículo 5: "Amarás, pois, o Senhor teu Deus de todo o teu coração, e de toda a tua alma, e de todas as tuas forças". Deus não pede apenas obediência externa ou rituais frios; Ele exige a devoção total do ser humano: intelecto, emoções, vontade e energia física. O amor a Deus não pode ser parcial ou dividido.',
    desc2: 'A Internalização da Palavra. Antes que os pais possam ensinar os filhos, a Palavra deve estar enraizada neles mesmos (v. 6): "E estas palavras, que hoje te ordeno, estarão no teu coração". A religião não pode ser apenas uma tradição cultural; ela deve ser uma convicção interna. Deus quer que a Sua lei seja escrita no coração, não apenas em tábuas de pedra. Um pai ou uma mãe não pode transmitir uma paixão por Deus que eles mesmos não possuem. A hipocrisia em casa é o maior obstáculo para a transmissão da fé.',
    desc3: 'A Pedagogia do Cotidiano. Moisés instrui como a fé deve ser ensinada à próxima geração (v. 7-9): "E as intimarás (inculcarás) a teus filhos". A palavra "inculcar" significa repetir com insistência, como quem afia uma espada. O ensino não deve ser restrito a um momento religioso formal (como a escola dominical), mas deve permear a vida diária: "falando delas assentado em tua casa, e andando pelo caminho, e deitando-te e levantando-te". A fé deve ser o assunto natural das conversas em família. Além disso, a Palavra deve governar as ações (atar por sinal na mão), a visão de mundo (frontais entre os olhos) e a vida pública e doméstica (escrever nos umbrais das portas e nas portas).',
    concl: 'O Shemá nos ensina que o cristianismo não é um compartimento da nossa vida, mas o centro absoluto dela. Amar a Deus com todo o nosso ser significa que a Sua Palavra deve governar a nossa mente, as nossas ações e a nossa casa. A maior herança que podemos deixar para os nossos filhos não é riqueza material, mas o testemunho diário e intencional de um coração que ama a Deus acima de todas as coisas.'
  },
  {
    id: 'jdg_7_1_22',
    intro: 'O livro de Juízes narra um período sombrio na história de Israel, marcado por ciclos de rebelião, opressão inimiga e libertação divina. O capítulo 7 conta a história de Gideão, um homem medroso que Deus chamou para libertar Israel da opressão devastadora dos midianitas. O exército inimigo era vasto, "como gafanhotos em multidão" (cerca de 135.000 homens). Gideão consegue reunir um exército de 32.000 israelitas. O que se segue é uma das estratégias militares mais estranhas e contra-intuitivas da história. Deus intencionalmente reduz o exército de Gideão a um número ridículo para garantir que a vitória seja reconhecida como um milagre divino, e não como uma conquista humana.',
    desc1: 'A Redução do Exército: O Teste do Medo e da Atenção. Deus diz a Gideão que o exército é grande demais (v. 2). A razão de Deus é teológica: "para que Israel não se glorie contra mim, dizendo: A minha mão me livrou". Deus sabe que o coração humano é rápido em roubar a glória divina. O primeiro teste é o do medo: quem for "medroso e tímido", que volte para casa. Chocantemente, 22.000 homens vão embora. Restam 10.000. Deus diz que ainda são muitos. O segundo teste é na água: Deus separa os que se ajoelham para beber (baixando a guarda) dos que levam a água à boca com a mão, lambendo como cães (mantendo-se alertas). Apenas 300 homens passam no teste. Gideão agora enfrentará 135.000 inimigos com 300 homens (uma proporção de 450 para 1).',
    desc2: 'O Encorajamento Divino no Acampamento Inimigo. Deus sabe que a fé de Gideão está abalada. Ele diz a Gideão para descer ao acampamento inimigo à noite para ouvir o que eles estão dizendo. Gideão e seu servo Fura se esgueiram e ouvem um soldado midianita contando um sonho a um companheiro: um pão de cevada (um alimento de camponeses pobres, representando Israel) rolou e derrubou a tenda midianita. O companheiro interpreta: "Não é isto outra coisa, senão a espada de Gideão... Deus tem dado na sua mão aos midianitas". Deus usou o medo do inimigo para fortalecer a fé do Seu servo. Gideão adora a Deus e volta encorajado.',
    desc3: 'A Vitória pelas Armas Improváveis. A estratégia de batalha de Gideão não envolve espadas ou lanças. Ele divide os 300 homens em três grupos e lhes dá armas absurdas: trombetas (buzinas), cântaros vazios e tochas escondidas dentro dos cântaros. No meio da noite, eles cercam o acampamento inimigo. Ao sinal de Gideão, eles quebram os cântaros (revelando a luz), tocam as trombetas e gritam: "Espada do Senhor, e de Gideão!". O barulho repentino e as luzes ao redor do acampamento causam pânico total entre os midianitas, que, na escuridão e confusão, começam a matar uns aos outros com as suas próprias espadas e fogem.',
    concl: 'A história dos 300 de Gideão nos ensina que Deus não precisa de maiorias, de recursos abundantes ou de força humana para realizar os Seus propósitos. Na verdade, Ele frequentemente remove as nossas seguranças humanas para que aprendamos a depender exclusivamente dEle. Quando os nossos "cântaros" (o nosso orgulho e autossuficiência) são quebrados, a luz do poder de Deus brilha, e a vitória é dEle.'
  },
  {
    id: '2sa_7_1_17',
    intro: 'O capítulo 7 de 2 Samuel é um dos textos teológicos mais importantes de todo o Antigo Testamento. Ele estabelece a "Aliança Davídica", que se torna a base para toda a esperança messiânica de Israel. O rei Davi finalmente havia conquistado a paz, estabelecido Jerusalém como capital e trazido a Arca da Aliança para a cidade. Morando em um palácio luxuoso de cedro, Davi sente-se incomodado pelo fato de a Arca de Deus ainda habitar em uma tenda humilde. Ele decide construir um grande templo para Deus. A resposta de Deus a Davi, entregue através do profeta Natã, vira a intenção de Davi de cabeça para baixo: Deus não precisa que Davi construa uma casa para Ele; em vez disso, Deus construirá uma "casa" (dinastia) eterna para Davi.',
    desc1: 'O Desejo de Davi e a Resposta de Deus. Davi compartilha seu plano com o profeta Natã, que inicialmente aprova a ideia ("Vai, e faze tudo quanto está no teu coração"). No entanto, naquela mesma noite, Deus fala a Natã. Deus lembra a Davi que, desde o dia em que tirou Israel do Egito, Ele nunca pediu uma casa de cedro, mas caminhou com o povo em uma tenda (tabernáculo). Deus não pode ser contido em edifícios humanos. Deus então lembra a Davi de onde o tirou: "Eu te tomei da malhada, de detrás das ovelhas, para que fosses o soberano sobre o meu povo". Tudo o que Davi é e tem é resultado da graça soberana de Deus.',
    desc2: 'A Promessa da Casa (Dinastia). Deus faz um jogo de palavras com o termo "casa" (bayith). Davi queria construir uma casa (templo) para Deus, mas Deus declara (v. 11): "O Senhor te faz saber que ele te fará casa". Deus promete construir uma dinastia para Davi. Deus promete que, quando Davi morrer, Ele levantará a sua semente (descendência) e estabelecerá o seu reino. Será esse descendente (Salomão, inicialmente) quem construirá a casa (o templo físico) para o nome de Deus.',
    desc3: 'A Aliança Eterna e o Cumprimento Messiânico. O coração da aliança está nos versículos 13 a 16. Deus promete sobre o descendente de Davi: "Eu serei seu pai, e ele será meu filho". Se ele pecar, será castigado com varas de homens (disciplina terrena), mas a misericórdia de Deus não se apartará dele, como aconteceu com Saul. A promessa culmina com uma garantia eterna (v. 16): "Porém a tua casa e o teu reino serão firmados para sempre diante de ti; teu trono será firme para sempre". Salomão cumpriu esta promessa parcialmente, mas a dinastia terrena de Davi eventualmente caiu. A promessa de um trono "para sempre" só encontra o seu cumprimento perfeito e final em Jesus Cristo, o "Filho de Davi", cujo Reino não terá fim (Lucas 1:32-33).',
    concl: 'A Aliança Davídica nos ensina que os propósitos de Deus são infinitamente maiores do que as nossas melhores intenções. Nós frequentemente queremos fazer grandes obras "para" Deus, mas a verdadeira grandeza espiritual está em receber o que Deus, pela Sua graça, quer fazer "em" e "através" de nós. A promessa a Davi é a nossa garantia de que o Rei Jesus governa para sempre.'
  },
  {
    id: '1ki_18_20_40',
    intro: 'O capítulo 18 de 1 Reis narra o confronto épico no Monte Carmelo, um dos momentos mais dramáticos da história de Israel. A nação, sob a liderança do rei Acabe e da rainha Jezabel, havia mergulhado na idolatria, adorando Baal (o deus cananeu da tempestade e da fertilidade). O profeta Elias havia declarado uma seca de três anos e meio como julgamento divino, provando que Baal não tinha poder sobre a chuva. Agora, Elias convoca todo o Israel e os 450 profetas de Baal para um desafio público no topo do monte. O objetivo não é apenas um milagre espetacular, mas forçar a nação a tomar uma decisão definitiva sobre quem é o verdadeiro Deus.',
    desc1: 'O Desafio e a Indecisão do Povo. Elias começa confrontando a apatia espiritual do povo (v. 21): "Até quando coxeareis entre dois pensamentos? Se o Senhor é Deus, segui-o, e se Baal, segui-o". O povo estava tentando misturar a adoração a Yahweh com a adoração a Baal (sincretismo). O povo responde com silêncio absoluto. Elias propõe o teste: dois bezerros serão preparados para o sacrifício, mas nenhum fogo será aceso. "O deus que responder por fogo, esse será Deus". O povo concorda. Como Baal era o deus do raio e do fogo, o desafio era no "território" dele.',
    desc2: 'O Fracasso dos Profetas de Baal. Os profetas de Baal preparam o sacrifício e clamam desde a manhã até o meio-dia: "Ah! Baal, responde-nos!". Eles saltam sobre o altar, mas "não houve voz, nem quem respondesse". Ao meio-dia, Elias começa a zombar deles com sarcasmo mordaz: "Gritai com grandes vozes... talvez esteja meditando, ou tenha algum trabalho, ou faça uma viagem, ou talvez durma, e desperte". No desespero, os profetas de Baal começam a se cortar com facas até sangrarem, uma prática pagã para chamar a atenção da divindade. O dia passa, e o resultado é o vazio: "não houve voz, nem resposta, nem atenção alguma". Os ídolos são surdos e mortos.',
    desc3: 'A Oração de Elias e o Fogo do Céu. Chegada a hora do sacrifício da tarde, Elias chama o povo. Ele restaura o altar do Senhor que estava quebrado, usando 12 pedras (representando a unidade das 12 tribos). Para eliminar qualquer suspeita de fraude, ele manda derramar quatro cântaros de água sobre o sacrifício e a lenha, três vezes, até encher a trincheira ao redor. A oração de Elias (v. 36-37) é curta, focada na glória de Deus e na conversão do povo: "Senhor... manifeste-se hoje que tu és Deus em Israel... para que este povo conheça que tu... fizeste voltar o seu coração". Imediatamente, o fogo do Senhor cai, consumindo não apenas o sacrifício e a lenha, mas também as pedras, o pó e a água. O povo cai com o rosto em terra e grita: "O Senhor é Deus! O Senhor é Deus!".',
    concl: 'O confronto no Monte Carmelo nos ensina que Deus não aceita um coração dividido. Não podemos "coxear" entre a adoração ao Criador e a devoção aos ídolos do nosso tempo (dinheiro, prazer, aprovação humana). Os ídolos sempre nos decepcionarão no dia da angústia, mas o Deus vivo responde àqueles que oram com fé e buscam a Sua glória.'
  },
  {
    id: 'exo_4_24_26',
    intro: 'Êxodo 4:24-26 é uma das passagens mais estranhas, abruptas e misteriosas de toda a Bíblia. Moisés havia acabado de ter o encontro glorioso com Deus na sarça ardente, recebido o seu chamado para libertar Israel, realizado milagres e iniciado a sua jornada de volta ao Egito com a sua esposa Zípora e seus filhos. De repente, a narrativa é interrompida por um incidente aterrorizante: em uma estalagem no caminho, o próprio Deus, que havia acabado de comissionar Moisés, vem ao seu encontro para matá-lo. A crise só é resolvida quando Zípora realiza uma circuncisão de emergência no seu filho. Este texto chocante ensina uma lição vital sobre a santidade de Deus e a importância da obediência à aliança.',
    desc1: 'O Ataque Divino Inesperado. O versículo 24 diz: "E aconteceu no caminho, numa estalagem, que o Senhor o encontrou, e o quis matar". O texto não explica imediatamente o motivo. Moisés está a caminho para cumprir a vontade de Deus, mas está sob a ira de Deus. Isso nos ensina que o serviço a Deus não nos isenta da obediência aos mandamentos de Deus. Deus não ignora o pecado ou a negligência na vida dos Seus líderes apenas porque eles têm uma "grande missão". A santidade de Deus exige que os Seus representantes vivam em conformidade com a Sua aliança.',
    desc2: 'A Causa: A Negligência da Aliança. O contexto (a ação imediata de Zípora) revela o problema: Moisés havia negligenciado a circuncisão do seu filho (provavelmente o mais novo, Eliezer). A circuncisão era o sinal inegociável da aliança abraâmica (Gênesis 17:14), e a penalidade para a não circuncisão era ser "cortado" do povo. Moisés estava indo para o Egito para exigir que Faraó libertasse o "filho primogênito" de Deus (Israel), mas ele mesmo estava em desobediência em relação ao seu próprio filho. Moisés não podia ser o libertador da aliança se ele mesmo era um violador da aliança. A negligência (talvez por influência da sua esposa midianita, Zípora) quase lhe custou a vida.',
    desc3: 'A Intervenção Sangrenta de Zípora. Moisés estava aparentemente incapacitado (talvez por uma doença súbita enviada por Deus). Zípora, percebendo a causa da ira divina, age rapidamente. Ela pega uma pedra aguda, circuncida o seu filho e lança o prepúcio aos pés de Moisés (ou do anjo do Senhor), dizendo: "Certamente me és um esposo sanguinário". A ação de Zípora, embora feita com repulsa, apazigua a ira de Deus: "E desviou-se dele". O derramamento do sangue da aliança salvou a vida de Moisés. Zípora reconhece que o seu casamento com Moisés a colocou sob as exigências rigorosas e "sanguinárias" do Deus de Israel.',
    concl: 'Este incidente perturbador nos lembra que Deus leva as Suas alianças a sério. Não podemos liderar publicamente se vivemos em desobediência na nossa vida privada e familiar. A graça de Deus que nos chama para o ministério é a mesma santidade que exige a nossa obediência total. A nossa segurança não está no nosso chamado, mas em estarmos cobertos pelo sangue da aliança.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 36');
