const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'job_1_1_22',
    intro: 'O primeiro capítulo do livro de Jó introduz o debate teológico mais profundo da Bíblia sobre o sofrimento humano e a natureza da verdadeira adoração. Jó é apresentado como um homem "íntegro, reto, temente a Deus e que se desviava do mal". Ele também era o homem mais rico do Oriente, abençoado com uma grande família e vastos rebanhos. No entanto, a cena muda da terra para a corte celestial, onde Satanás (o Acusador) lança um desafio direto ao caráter de Deus e à motivação de Jó. Satanás argumenta que a adoração de Jó é puramente mercenária: ele só serve a Deus por causa das bênçãos e da proteção que recebe. O que se segue é um teste devastador que destrói a teologia da retribuição (a ideia de que os justos sempre prosperam e os ímpios sempre sofrem) e revela a essência da fé incondicional.',
    desc1: 'O desafio de Satanás é cínico e direto: "Porventura teme Jó a Deus debalde? Não o cercaste tu de bens...? Estende a tua mão, e toca-lhe em tudo quanto tem, e verás se não blasfema de ti na tua face". Satanás afirma que o amor de Jó por Deus é, na verdade, amor pelos presentes de Deus. Se os presentes forem removidos, o amor desaparecerá. Deus permite que Satanás teste Jó, com a única restrição de não tocar na sua vida. A permissão divina não significa que Deus é o autor do mal, mas que Ele é soberano sobre ele e o usa para provar a genuinidade da fé dos Seus servos.',
    desc2: 'A tragédia atinge Jó com uma velocidade e uma intensidade aterrorizantes. Em um único dia, quatro mensageiros chegam sucessivamente com notícias catastróficas. Os sabeus roubam os bois e jumentos e matam os servos; o "fogo de Deus" (raios) consome as ovelhas e os pastores; os caldeus roubam os camelos e matam mais servos; e, finalmente, a notícia mais devastadora: um grande vento derruba a casa onde os dez filhos de Jó estavam banqueteando, matando todos eles. Em questão de horas, o homem mais rico e abençoado do Oriente perde o seu império financeiro e a sua família inteira. A dor é inimaginável.',
    desc3: 'A reação de Jó diante da perda total é o clímax do capítulo. Ele não nega a dor nem tenta ser estoico; ele expressa o seu luto rasgando o seu manto, rapando a cabeça e lançando-se em terra. Mas, em vez de amaldiçoar a Deus (como Satanás previu), ele adora: "Nu saí do ventre de minha mãe e nu tornarei para lá; o Senhor o deu, e o Senhor o tomou: bendito seja o nome do Senhor". Jó não culpa o diabo, os sabeus ou o vento; ele reconhece a soberania absoluta de Deus sobre tudo o que ele tinha. Ele entende que não era dono de nada, apenas um administrador. O texto conclui: "Em tudo isto Jó não pecou, nem atribuiu a Deus falta alguma". A adoração de Jó provou que Deus é digno de ser amado por quem Ele é, e não apenas pelo que Ele dá.',
    concl: 'O primeiro capítulo de Jó nos confronta com a pergunta mais difícil da vida cristã: Por que servimos a Deus? Se perdêssemos a nossa saúde, a nossa família e os nossos bens, continuaríamos a adorá-Lo? A fé de Jó nos ensina que a verdadeira adoração não é um contrato de negócios com Deus, mas uma submissão incondicional à Sua soberania, mesmo quando não entendemos os Seus caminhos no meio da dor mais profunda.'
  },
  {
    id: 'psa_42_1_11',
    intro: 'O Salmo 42 é um dos lamentos mais profundos, honestos e psicologicamente ricos do Antigo Testamento. Escrito pelos filhos de Corá, ele descreve a experiência de um crente que está exilado (provavelmente na região do Monte Hermom, longe de Jerusalém), separado da adoração pública no templo e enfrentando uma depressão espiritual severa. O salmista está cercado por inimigos que zombam da sua fé, enquanto ele mesmo luta com a sensação de que Deus o abandonou. Este salmo é um guia essencial para a vida cristã, pois nos ensina como lidar com a "noite escura da alma", não negando a dor, mas confrontando as nossas próprias emoções com a verdade teológica.',
    desc1: 'O salmo começa com uma das metáforas mais famosas da Bíblia para o desejo espiritual: "Como o cervo brama pelas correntes das águas, assim suspira a minha alma por ti, ó Deus". O cervo não está apenas com sede; ele está ofegante, desesperado por água em um ambiente árido, talvez fugindo de predadores. O salmista declara: "A minha alma tem sede de Deus, do Deus vivo". A sua dor não é apenas a saudade de casa ou a perda de status; é a agonia da ausência sentida de Deus. A sua tristeza é tão profunda que ele perdeu o apetite: "As minhas lágrimas servem-me de mantimento de dia e de noite". Para piorar, os seus inimigos o atormentam continuamente com a pergunta mais cruel para um crente em sofrimento: "Onde está o teu Deus?".',
    desc2: 'No versículo 4, o salmista tenta encontrar consolo nas memórias do passado, mas isso só aumenta a sua dor: "Quando me lembro disto, dentro de mim derramo a minha alma; pois eu havia ido com a multidão... à casa de Deus, com voz de alegria e louvor". Lembrar dos dias de glória e comunhão quando se está no abismo do isolamento pode ser torturante. Ele descreve a sua condição emocional como um afogamento: "Um abismo chama outro abismo, ao ruído das tuas catadupas; todas as tuas ondas e as tuas vagas têm passado sobre mim". Ele sente que está sendo esmagado pelas provações que o próprio Deus permitiu.',
    desc3: 'O clímax do salmo (que se repete no v. 11 e no Salmo 43:5) é o momento em que o salmista para de ouvir as suas emoções e começa a pregar para a sua própria alma: "Por que estás abatida, ó minha alma, e por que te perturbas em mim? Espera em Deus, pois ainda o louvarei pela salvação da sua face". Ele não permite que a depressão tenha a última palavra. Ele confronta o seu abatimento com a esperança teológica. Ele decide que, mesmo que não sinta a presença de Deus agora, ele escolherá esperar nEle e confiar que o louvor retornará. A fé verdadeira não é a ausência de tristeza, mas a recusa em deixar que a tristeza destrua a esperança.',
    concl: 'O Salmo 42 nos ensina que a depressão espiritual e a sensação de abandono não são sinais de falta de fé, mas experiências comuns até mesmo para os crentes mais profundos. Quando as lágrimas são o nosso alimento e o mundo zomba da nossa fé, devemos seguir o exemplo do salmista: expressar a nossa dor honestamente a Deus, lembrar da Sua fidelidade passada e pregar a esperança do Evangelho para a nossa própria alma abatida.'
  },
  {
    id: 'ecc_3_1_15',
    intro: 'O capítulo 3 de Eclesiastes contém um dos poemas filosóficos mais famosos e belos da literatura mundial. O "Pregador" (tradicionalmente identificado como Salomão), que passou os capítulos anteriores buscando o sentido da vida na sabedoria humana, nos prazeres, no trabalho e nas riquezas (e concluindo que tudo "debaixo do sol" é vaidade), agora volta a sua atenção para a natureza inexorável do tempo. Ele observa que a vida humana é governada por ciclos inalteráveis de eventos opostos. A mensagem central deste texto não é um fatalismo deprimente, mas um convite à humildade e à confiança na soberania de Deus, que orquestra todas as estações da vida com um propósito eterno que a mente humana não consegue compreender totalmente.',
    desc1: 'O poema começa com uma declaração absoluta: "Tudo tem o seu tempo determinado, e há tempo para todo o propósito debaixo do céu". O Pregador lista então quatorze pares de opostos que abrangem a totalidade da experiência humana: tempo de nascer e morrer, plantar e arrancar, matar e curar, chorar e rir, abraçar e afastar-se, calar e falar, amar e odiar, guerra e paz. Nós não controlamos essas estações; nós apenas passamos por elas. A ilusão humana é achar que podemos manter o "tempo de rir" para sempre ou evitar o "tempo de chorar". A sabedoria consiste em reconhecer a estação em que estamos e aceitar que Deus está no controle das mudanças que não podemos impedir.',
    desc2: 'Após listar os ciclos, o Pregador faz uma pergunta existencial (v. 9): "Que proveito tem o trabalhador naquilo em que trabalha?". Se tudo é cíclico e inevitável, qual é o sentido do nosso esforço? Ele responde observando o trabalho que Deus deu aos homens. O versículo 11 é a chave teológica do livro: "Tudo fez formoso em seu tempo; também pôs o mundo (a eternidade) no coração do homem, sem que este possa descobrir a obra que Deus fez desde o princípio até ao fim". Deus nos criou com um anseio pela eternidade, um desejo de entender o quadro completo. No entanto, Ele não nos dá a capacidade de compreender todos os Seus propósitos. Vivemos com a tensão de ter corações eternos presos em um mundo temporal.',
    desc3: 'Diante dessa tensão, o Pregador oferece uma conclusão prática (v. 12-14). Como não podemos controlar o tempo nem entender todos os mistérios de Deus, a melhor resposta é a gratidão e a reverência. Ele diz que não há nada melhor do que "alegrar-se e fazer bem na sua vida" e que comer, beber e gozar do fruto do trabalho é "dom de Deus". A alegria nas coisas simples não é hedonismo, mas a aceitação grata da provisão diária de Deus. Ele conclui reconhecendo a imutabilidade dos decretos divinos: "Eu sei que tudo quanto Deus faz durará eternamente; nada se lhe deve acrescentar, e nada se lhe deve tirar; e isto faz Deus para que haja temor diante dele". A soberania de Deus sobre o tempo deve produzir em nós um temor reverente.',
    concl: 'Eclesiastes 3 nos liberta da ansiedade de tentar controlar o incontrolável. Não podemos parar o relógio nem evitar as estações de dor, mas podemos confiar que o Deus que colocou a eternidade nos nossos corações está orquestrando cada "tempo" para a Sua glória e para o nosso bem final. A verdadeira paz é encontrada quando paramos de lutar contra as estações de Deus e começamos a temê-Lo e a desfrutar dos Seus dons diários.'
  },
  {
    id: 'dan_3_1_30',
    intro: 'A história da fornalha de fogo ardente no capítulo 3 de Daniel é um dos relatos mais dramáticos de coragem civil, fidelidade religiosa e livramento divino no Antigo Testamento. O rei Nabucodonosor da Babilônia, o monarca mais poderoso do mundo na época, ergue uma estátua de ouro colossal na planície de Dura e emite um decreto exigindo que todos os oficiais do império se prostrem e a adorem ao som da música. A recusa significava a morte imediata em uma fornalha. Três jovens judeus exilados (Sadraque, Mesaque e Abede-Nego), que haviam sido promovidos na administração babilônica, enfrentam a escolha suprema: comprometer a sua fé para salvar as suas vidas e carreiras, ou permanecer fiéis ao Deus de Israel e enfrentar uma morte terrível.',
    desc1: 'A cerimônia de dedicação da estátua é um espetáculo de poder e intimidação. Quando a música toca, todos os povos e nações se prostram. A pressão para o conformismo era absoluta. No entanto, alguns caldeus (provavelmente movidos por inveja política) denunciam os três jovens judeus ao rei: "não fizeram caso de ti; a teus deuses não servem, nem a estátua de ouro, que levantaste, adoraram". Nabucodonosor, furioso, manda chamá-los e oferece uma segunda chance, acompanhada de uma ameaça arrogante: "se não a adorardes, sereis lançados... numa fornalha de fogo ardente; e quem é o Deus que vos poderá livrar das minhas mãos?". O rei desafia diretamente o poder de Yahweh.',
    desc2: 'A resposta dos três jovens (v. 16-18) é uma das maiores declarações de fé incondicional da Bíblia. Eles não pedem tempo para pensar, não tentam negociar um acordo e não dão desculpas teológicas (como "vamos nos curvar fisicamente, mas adorar a Deus no coração"). Eles dizem: "Não necessitamos de te responder sobre este negócio. Eis que o nosso Deus, a quem nós servimos, é que nos pode livrar... e nos livrará das tuas mãos, ó rei". Eles afirmam o poder absoluto de Deus para salvá-los. Mas a grandeza da sua fé está na frase seguinte: "E, se não, fica sabendo ó rei, que não serviremos a teus deuses nem adoraremos a estátua de ouro que levantaste". A fé deles não dependia do livramento. Eles preferiam morrer queimados a cometer idolatria.',
    desc3: 'Nabucodonosor, cheio de fúria, manda aquecer a fornalha sete vezes mais do que o normal e ordena que os seus soldados mais fortes amarrem e lancem os jovens no fogo. O fogo era tão intenso que matou os soldados que os lançaram. Mas, quando o rei olha para dentro da fornalha, ele fica espantado: "Eu, porém, vejo quatro homens soltos, que andam passeando dentro do fogo, sem sofrer nenhum dano; e o aspecto do quarto é semelhante ao Filho de Deus". Deus não apagou o fogo nem impediu que eles fossem lançados nele; Ele desceu na fornalha e caminhou com eles no meio do fogo. A única coisa que o fogo queimou foram as cordas que os prendiam. Quando eles saem, nem sequer o cheiro de fumaça estava nas suas roupas.',
    concl: 'A fornalha de fogo ardente nos ensina que a verdadeira fé não é a garantia de que Deus nos livrará de todas as provações, mas a convicção de que Ele é digno de obediência, independentemente das consequências ("e, se não"). Quando nos recusamos a nos curvar aos ídolos do mundo, podemos ser lançados no fogo da perseguição, mas é exatamente lá que experimentaremos a presença mais íntima e libertadora do Filho de Deus.'
  },
  {
    id: 'mal_3_1_12',
    intro: 'O capítulo 3 de Malaquias contém uma das repreensões mais diretas e práticas do Antigo Testamento sobre a relação entre a vida financeira e a fidelidade espiritual. O povo de Israel, que havia retornado do exílio babilônico, havia caído em um estado de cinismo e apatia religiosa. Eles duvidavam do amor de Deus, ofereciam sacrifícios defeituosos e questionavam a justiça divina. Deus, através do profeta Malaquias, confronta a nação com a evidência mais tangível da sua rebelião: a retenção dos dízimos e das ofertas. Este texto não é primariamente sobre dinheiro, mas sobre o coração. Ele revela que a nossa atitude em relação aos recursos materiais é o termômetro mais preciso da nossa confiança e submissão a Deus.',
    desc1: 'O confronto começa com uma acusação chocante (v. 8): "Roubará o homem a Deus? Todavia vós me roubais, e dizeis: Em que te roubamos? Nos dízimos e nas ofertas". O povo estava retendo a décima parte da sua renda (que pertencia a Deus por lei para o sustento dos levitas e do templo) e as ofertas voluntárias. Deus não os acusa de má administração, mas de roubo direto. A consequência dessa desobediência era severa: "Com maldição sois amaldiçoados, porque a mim me roubais, sim, toda esta nação". A retenção egoísta dos recursos que pertencem a Deus não traz prosperidade, mas atrai a maldição divina sobre os frutos do trabalho. A avareza é uma forma de idolatria que fecha as portas da bênção.',
    desc2: 'Em vez de apenas condenar, Deus faz um desafio extraordinário e único em toda a Bíblia (v. 10): "Trazei todos os dízimos à casa do tesouro, para que haja mantimento na minha casa, e depois fazei prova de mim nisto, diz o Senhor dos Exércitos". Deus convida o povo a testá-Lo na área financeira. A promessa que acompanha a obediência é extravagante: "se eu não vos abrir as janelas do céu, e não derramar sobre vós uma bênção tal até que não haja espaço suficiente para a recolherdes". A obediência financeira destranca as "janelas do céu". Deus promete uma provisão que excede a capacidade humana de armazenamento, demonstrando que Ele é um Pai generoso que honra aqueles que O honram.',
    desc3: 'A promessa de Deus vai além da provisão positiva; ela inclui proteção ativa contra as forças destrutivas (v. 11): "E por causa de vós repreenderei o devorador, e ele não destruirá os frutos da vossa terra; e a vossa vide no campo não será estéril". No contexto agrícola de Israel, o "devorador" representava pragas (como gafanhotos) ou secas que destruíam a colheita. Deus promete proteger o fruto do trabalho daqueles que são fiéis. O resultado final dessa fidelidade não é apenas o conforto pessoal, mas um testemunho global (v. 12): "E todas as nações vos chamarão bem-aventurados; porque vós sereis uma terra deleitosa". A generosidade e a bênção de Deus sobre o Seu povo atrairão as nações para Ele.',
    concl: 'Malaquias 3 nos ensina que o dízimo não é um imposto religioso, mas um ato de adoração, confiança e reconhecimento da soberania de Deus sobre tudo o que temos. Quando retemos o que pertence a Deus, roubamos a nós mesmos da Sua bênção e proteção. Quando entregamos com fidelidade, abrimos as janelas do céu e permitimos que Deus demonstre a Sua fidelidade extravagante nas nossas vidas.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 28');
