const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: '1sam_17_38_51',
    intro: 'O confronto no vale de Elá entre Davi e Golias é muito mais do que uma clássica história de "azarão" vencendo o favorito. É um duelo teológico profundo entre a arrogância do poder humano (representada pelo gigante filisteu e sua armadura impenetrável) e a eficácia da aliança divina (representada por um jovem pastor armado apenas com uma funda e uma fé inabalável). Enquanto todo o exército de Israel, incluindo o rei Saul, estava paralisado pelo medo porque comparava o tamanho de Golias com o seu próprio tamanho, Davi comparou o tamanho de Golias com o tamanho do seu Deus.',
    desc1: 'A preparação para a batalha revela um contraste de confianças. O rei Saul tenta vestir Davi com sua própria armadura real. Saul confiava no equipamento militar e na lógica humana. Davi, no entanto, rejeita a armadura porque não estava acostumado com ela. Ele não podia lutar a batalha do Senhor usando as armas da carne ou a experiência de outro homem. Ele escolhe as armas simples do seu dia a dia (um cajado, uma funda e cinco pedras lisas do ribeiro), confiando que Deus usaria o que ele já tinha nas mãos, santificado pela fé.',
    desc2: 'O encontro no campo de batalha começa com intimidação psicológica. Golias, ofendido por enviarem um menino sem armadura, amaldiçoa Davi pelos seus deuses e promete dar sua carne às aves. O inimigo sempre tenta vencer a batalha na mente antes do confronto físico, usando o medo, o desprezo e palavras de derrota. A resposta de Davi é um manifesto de fé: "Tu vens a mim com espada, com lança e com escudo; porém eu venho a ti em nome do Senhor dos Exércitos, o Deus dos exércitos de Israel, a quem tens afrontado". Davi não foca no gigante, mas na ofensa à glória de Deus.',
    desc3: 'A vitória é rápida e decisiva. Davi declara profeticamente o resultado antes de lançar a pedra: "Hoje mesmo o Senhor te entregará na minha mão... para que toda a terra saiba que há Deus em Israel". Ele corre em direção à linha de batalha (a fé não recua), lança a pedra e atinge o único ponto vulnerável de Golias. O gigante cai de bruços (uma postura de adoração forçada diante do Deus de Israel). Davi então usa a própria espada de Golias para cortar-lhe a cabeça, provando que o Senhor não precisa de espada nem de lança para salvar.',
    concl: 'A história de Davi e Golias nos ensina que o tamanho do nosso obstáculo é irrelevante quando a nossa confiança está firmada na aliança com Deus. A verdadeira fé não ignora a realidade do gigante, mas o enfrenta com a certeza de que "a batalha é do Senhor". Quando lutamos para a glória de Deus, Ele garante a vitória.'
  },
  {
    id: 'neh_1_1_11',
    intro: 'O livro de Neemias começa não com um projeto de engenharia, mas com um coração quebrantado. Neemias era o copeiro do rei da Pérsia, uma posição de extremo conforto, influência e segurança no palácio de Susã. No entanto, quando ele recebe a notícia de que os judeus que retornaram a Jerusalém estavam em grande miséria e que os muros da cidade estavam fendidos e as portas queimadas, ele não fica indiferente. Este capítulo nos ensina a anatomia da restauração: toda grande obra de Deus começa quando o fardo divino é transferido para o coração de um homem ou mulher através da oração.',
    desc1: 'A reação inicial de Neemias à má notícia não é formar um comitê ou fazer um planejamento estratégico, mas entrar em luto profundo. Ele diz: "Assentei-me, e chorei, e lamentei por alguns dias; e estive jejuando e orando perante o Deus dos céus". O primeiro passo para a restauração é a empatia espiritual; é ter o coração quebrantado pelas coisas que quebrantam o coração de Deus. Neemias estava seguro no palácio, mas seu coração estava nas ruínas de Jerusalém. A verdadeira liderança cristã nasce da compaixão, não da ambição.',
    desc2: 'A oração de Neemias é um modelo de intercessão bíblica. Ele começa exaltando a grandeza e a fidelidade de Deus ("Deus grande e terrível, que guardas a aliança"). Em seguida, ele passa para uma confissão de pecados profunda e inclusiva. Ele não aponta o dedo para os outros; ele se inclui na culpa: "Temos pecado contra ti; tanto eu como a casa de meu pai pecamos". Ele reconhece que a ruína física dos muros era apenas um sintoma da ruína espiritual do povo. A restauração exige arrependimento genuíno e apropriação da responsabilidade.',
    desc3: 'Na segunda metade de sua oração, Neemias apela para as promessas da Palavra de Deus. Ele lembra a Deus do que Ele mesmo havia dito a Moisés: que se o povo se voltasse para Ele, Ele os congregaria novamente. A oração eficaz é baseada nas promessas de Deus. Finalmente, Neemias termina com um pedido específico: "Faze prosperar hoje o teu servo, e dá-lhe graça perante este homem (o rei)". A oração de Neemias não era uma desculpa para a inércia; era a preparação para a ação. Ele estava disposto a arriscar sua vida e sua posição para ser a resposta à sua própria oração.',
    concl: 'A reconstrução de muros caídos (sejam eles em uma cidade, em uma família ou em uma igreja) sempre começa na presença de Deus. Quando unimos um coração que se importa profundamente com a glória de Deus a mãos dispostas a trabalhar e arriscar, Deus move o coração de reis e reconstrói nações.'
  },
  {
    id: 'dan_3_16_28',
    intro: 'A história da Fornalha de Fogo Ardente é um dos maiores testemunhos de fidelidade inegociável em toda a Escritura. O rei Nabucodonosor, o monarca mais poderoso do mundo, ergue uma estátua de ouro gigante e exige que todos os povos se curvem e a adorem ao som da música. A penalidade para a desobediência era ser lançado vivo em uma fornalha. Três jovens judeus exilados (Sadraque, Mesaque e Abede-Nego) enfrentam o teste definitivo: conformar-se com a idolatria do sistema mundial para salvar suas vidas ou manter a lealdade exclusiva a Deus e enfrentar a morte.',
    desc1: 'Quando confrontados pelo rei enfurecido, a resposta dos três jovens é um monumento de coragem e fé. Eles não pedem tempo para pensar, não tentam negociar um meio-termo e não dão desculpas (como "vamos nos curvar fisicamente, mas adorar a Deus no coração"). Eles declaram: "O nosso Deus, a quem servimos, pode livrar-nos da fornalha... e ele nos livrará da tua mão, ó rei". Eles têm certeza do poder de Deus. No entanto, a grandeza da fé deles está no versículo 18: "E, se não... fica sabendo, ó rei, que não serviremos a teus deuses". A verdadeira adoração não é condicional; eles serviriam a Deus mesmo que Ele escolhesse não os livrar da morte.',
    desc2: 'A resposta do mundo à fé inegociável é a fúria irracional. Nabucodonosor se enche de ira, seu semblante muda e ele ordena que a fornalha seja aquecida sete vezes mais do que o normal. O calor era tão intenso que matou os próprios soldados de elite que lançaram os jovens no fogo. O sistema do mundo não tolera a lealdade exclusiva a Cristo e tentará destruir, com força máxima, aqueles que se recusam a se curvar aos seus ídolos (sejam eles o poder, o dinheiro, a popularidade ou ideologias).',
    desc3: 'O milagre que se segue é surpreendente. O rei olha para a fornalha e fica atônito: "Não lançamos nós três homens atados dentro do fogo? ... Eu, porém, vejo quatro homens soltos, que andam passeando dentro do fogo, e nada há de lesão neles; e o aspecto do quarto é semelhante ao filho dos deuses". O fogo não consumiu os jovens; consumiu apenas as cordas que os prendiam. E, mais importante, eles não estavam sozinhos. O próprio Filho de Deus (uma teofania pré-encarnada de Cristo) desceu à fornalha para estar com eles na provação.',
    concl: 'A promessa de Deus não é que seremos isentos das fornalhas da vida, mas que Ele estará conosco dentro delas. Deus nem sempre nos livra *do* fogo, mas Ele sempre nos livra *no* fogo. A nossa fidelidade inegociável a Deus no meio do sofrimento é o maior testemunho que podemos dar a um mundo que não O conhece.'
  },
  {
    id: 'luk_24_13_35',
    intro: 'A narrativa do Caminho de Emaús é uma das histórias mais belas e psicologicamente profundas sobre a ressurreição. Ocorre no próprio domingo de Páscoa. Dois discípulos estão caminhando para longe de Jerusalém, voltando para casa, com os corações esmagados pela decepção. Eles haviam colocado toda a sua esperança em Jesus, mas a cruz pareceu ser o fim de tudo. O Cristo ressurreto se junta a eles na estrada de forma anônima, iniciando um processo terapêutico e teológico que transformaria a tristeza profunda deles em corações ardentes e fé inabalável.',
    desc1: 'O texto diz que "os olhos deles estavam como que impedidos de o reconhecer". A cegueira deles não era apenas física, mas espiritual, causada pela dor e por expectativas teológicas erradas. Quando o Estranho pergunta sobre o que conversam, Cleopas resume a tragédia: "Nós esperávamos que fosse ele o que remisse Israel". A esperança deles estava no passado ("esperávamos"). Eles queriam um Messias político que derrotasse Roma, não um Messias sofredor que morresse em uma cruz. A decepção acontece quando Deus não age de acordo com o nosso roteiro.',
    desc2: 'A resposta de Jesus não é um abraço consolador imediato, mas uma repreensão amorosa e uma aula de teologia: "Ó néscios, e tardos de coração para crer tudo o que os profetas disseram! Porventura não convinha que o Cristo padecesse estas coisas e entrasse na sua glória?". Em seguida, começando por Moisés e por todos os profetas, Jesus expõe as Escrituras, mostrando que a cruz não foi um acidente de percurso ou uma falha no plano, mas o cumprimento exato de todo o Antigo Testamento. A Palavra de Deus é o único remédio para a decepção espiritual.',
    desc3: 'Ao chegarem à aldeia, eles insistem para que o Estranho fique com eles. Durante a refeição, o Hóspede assume o papel de Anfitrião. Ele toma o pão, abençoa, parte e lhes dá. Nesse momento exato (talvez ao verem as marcas dos cravos nas mãos, ou pelo gesto familiar da Última Ceia), "abriram-se-lhes os olhos, e o conheceram; e ele desapareceu-lhes". A reação deles é imediata: "Não ardia em nós o nosso coração quando, pelo caminho, nos falava, e quando nos abria as Escrituras?". A revelação da Palavra e a comunhão com Cristo restauram a esperança, fazendo-os voltar imediatamente a Jerusalém, à noite, para testemunhar.',
    concl: 'Quando as nossas esperanças são frustradas e a vida parece não fazer sentido, a solução não é fugir, mas voltar às Escrituras. É na exposição fiel da Palavra de Deus e na comunhão íntima com o Cristo ressurreto que os nossos olhos são abertos, a nossa tristeza é dissipada e os nossos corações voltam a arder com o fogo do Evangelho.'
  },
  {
    id: 'act_9_1_19',
    intro: 'A conversão de Saulo de Tarso (mais tarde conhecido como o apóstolo Paulo) é o evento mais importante da história da Igreja após o Pentecostes. Saulo não era um pecador comum; ele era um fariseu zeloso, um intelectual brilhante e o inimigo público número um dos cristãos. Ele respirava "ameaças e mortes" e estava a caminho de Damasco com cartas de autorização para prender e arrastar os seguidores do "Caminho" para Jerusalém. No entanto, Deus tinha um plano soberano para transformar o principal perseguidor da Igreja no seu principal missionário e teólogo.',
    desc1: 'A conversão de Saulo não foi resultado de uma busca espiritual, mas de uma interceptação divina. Perto de Damasco, uma luz do céu, mais brilhante que o sol do meio-dia, o cerca e o derruba por terra. Ele ouve uma voz: "Saulo, Saulo, por que me persegues?". A pergunta revela uma verdade teológica profunda sobre a união mística entre Cristo e Sua Igreja: perseguir os cristãos é perseguir o próprio Jesus. Saulo pergunta: "Quem és, Senhor?". A resposta destrói toda a sua teologia farisaica: "Eu sou Jesus, a quem tu persegues". O Jesus que ele considerava um falso profeta morto estava vivo e glorificado.',
    desc2: 'O encontro com a glória de Cristo deixa Saulo fisicamente cego. O homem que achava que via a verdade mais claramente do que todos agora precisa ser guiado pela mão como uma criança. Durante três dias, ele fica em Damasco, sem ver, sem comer e sem beber. Esse período de escuridão e jejum foi o tempo em que a sua velha teologia, baseada na justiça própria e nas obras da lei, foi completamente desconstruída. Ele estava morrendo para si mesmo para poder nascer de novo. O quebrantamento profundo sempre precede a verdadeira utilidade no Reino de Deus.',
    desc3: 'Deus então chama Ananias, um discípulo comum em Damasco, para ir orar por Saulo. Ananias hesita, conhecendo a reputação terrível do perseguidor, mas Deus declara o Seu propósito soberano: "Vai, porque este é para mim um vaso escolhido, para levar o meu nome diante dos gentios, e dos reis e dos filhos de Israel. E eu lhe mostrarei quanto deve padecer pelo meu nome". Ananias obedece, chama o antigo inimigo de "Irmão Saulo", impõe as mãos sobre ele. As escamas caem de seus olhos, ele é curado, cheio do Espírito Santo e batizado. A transformação é imediata e radical.',
    concl: 'A conversão de Paulo é a prova definitiva de que ninguém está fora do alcance da graça de Deus. A salvação não depende do nosso mérito, mas da eleição soberana e do poder transformador de Cristo. A mesma luz divina que nos cega para a nossa própria justiça é a luz que abre os nossos olhos para a beleza do Evangelho e nos comissiona para a missão.'
  },
  {
    id: 'jos_6_1_20',
    intro: 'A conquista de Jericó é a primeira e mais emblemática batalha de Israel na Terra Prometida. Jericó era uma cidade-estado poderosa, com muralhas duplas e intransponíveis, estrategicamente localizada para bloquear o avanço de Israel. Humanamente falando, a conquista era impossível para um povo de ex-escravos sem máquinas de cerco. No entanto, Deus dá a Josué uma estratégia militar que parecia absurda e ridícula aos olhos humanos. Esta narrativa não é um manual de táticas de guerra, mas uma profunda lição espiritual sobre como a vitória no Reino de Deus não é alcançada pela força carnal, mas pela obediência radical e incondicional à Palavra de Deus.',
    desc1: 'Antes mesmo da batalha começar, Deus declara a Josué: "Olha, tenho dado na tua mão a Jericó, ao seu rei e aos seus homens valentes". A cidade ainda estava trancada e os muros intactos, mas Deus fala no passado, como um fato já consumado. A fé bíblica não é lutar com ansiedade para tentar obter uma vitória incerta; é lutar com confiança a partir de uma vitória que já foi garantida pelas promessas de Deus. A nossa responsabilidade não é produzir o milagre, mas alinhar as nossas ações com a Palavra dEle.',
    desc2: 'A estratégia divina exigia disciplina e fé extremas. Durante seis dias, o exército, os sacerdotes com a Arca da Aliança e as trombetas deveriam marchar ao redor da cidade uma vez por dia, em absoluto silêncio. O silêncio era crucial: ele impedia a murmuração (que havia destruído a geração anterior no deserto), construía a expectativa e forçava o povo a focar na presença de Deus (a Arca) em vez de focar no tamanho dos muros. A obediência frequentemente exige que continuemos caminhando e fazendo a vontade de Deus mesmo quando nada parece estar acontecendo e os muros parecem inabaláveis.',
    desc3: 'No sétimo dia, a ordem muda. Eles marcham sete vezes e, na sétima volta, ao som longo das trombetas, Josué ordena: "Gritai, porque o Senhor vos tem dado a cidade". O povo grita com grande estrondo, e os muros de Jericó caem "abaixo" (literalmente, caem sobre si mesmos, afundando no chão). O grito do povo não foi a causa física da queda dos muros; foi a expressão de fé e a resposta de obediência que liberou o poder sobrenatural de Deus. A vitória foi total e a cidade foi consagrada ao Senhor.',
    concl: 'As fortalezas e os obstáculos em nossas vidas não caem pela nossa própria força, inteligência ou lógica humana. Eles caem quando confiamos nas promessas de Deus e obedecemos às Suas instruções, por mais ilógicas que pareçam ao mundo. Onde a capacidade humana termina, o poder de Deus triunfa gloriosamente.'
  },
  {
    id: 'ezk_37_1_14',
    intro: 'A visão do Vale de Ossos Secos é uma das imagens mais poderosas e dramáticas do Antigo Testamento. O profeta Ezequiel, ministrando aos judeus exilados na Babilônia, é levado pelo Espírito a um vale cheio de ossos humanos, espalhados e "mui secos". Esses ossos representavam a nação de Israel: derrotada, destruída, sem templo, sem terra e sem esperança ("Os nossos ossos se secaram, e pereceu a nossa esperança"). Esta visão é uma revelação profunda sobre a anatomia do reavivamento e sobre como Deus é especialista em trazer vida abundante onde só existe morte, ruína e desesperança.',
    desc1: 'A visão começa com um diagnóstico brutal da realidade. Deus faz Ezequiel andar ao redor dos ossos para ver a extensão da morte, e então faz a pergunta impossível: "Filho do homem, poderão viver estes ossos?". Humanamente, a resposta era um sonoro "não". Mas Ezequiel, conhecendo a soberania de Deus, responde: "Senhor Deus, tu o sabes". O primeiro passo para qualquer restauração espiritual é reconhecer a nossa total incapacidade e falência. Não podemos gerar vida por nós mesmos; dependemos inteiramente do poder do Criador.',
    desc2: 'Deus então ordena que Ezequiel faça algo aparentemente ridículo: pregar para os ossos mortos. "Profetiza sobre estes ossos, e dize-lhes: Ossos secos, ouvi a palavra do Senhor". A Palavra de Deus não é apenas informativa; ela é criativa e performática. Quando Ezequiel obedece e profetiza, ocorre um milagre de reestruturação: há um ruído, um tremor, os ossos se juntam (cada osso ao seu osso), e nervos, carne e pele os cobrem. A estrutura foi restaurada, a ortodoxia estava correta, a organização estava perfeita, mas o texto diz: "porém não havia neles o fôlego (espírito)". A religião sem o Espírito é apenas um cadáver bem arrumado.',
    desc3: 'A restauração completa exige uma segunda ação. Deus ordena: "Profetiza ao espírito... e dize ao espírito... Vem dos quatro ventos, ó espírito, e assopra sobre estes mortos, para que vivam". A palavra hebraica "Ruah" significa vento, fôlego e Espírito. Quando Ezequiel profetiza, o Espírito entra neles, eles vivem e se colocam em pé, formando um "exército sobremodo grande". O reavivamento verdadeiro e a vida espiritual genuína só acontecem quando a pregação fiel da Palavra de Deus é acompanhada pelo sopro vivificador do Espírito Santo.',
    concl: 'Não há situação, casamento, ministério, igreja ou vida pessoal tão "seca", arruinada ou morta que o poder combinado da Palavra de Deus e do Seu Espírito Santo não possa ressuscitar. O nosso Deus é o Deus da ressurreição, que transforma vales de morte em exércitos vivos para a Sua glória.'
  },
  {
    id: 'jon_1_1_17',
    intro: 'O livro de Jonas é único entre os profetas menores. Em vez de focar nas profecias, ele foca no próprio profeta rebelde. Jonas recebe um chamado claro e direto de Deus para ir a Nínive (a capital do cruel Império Assírio, inimigo mortal de Israel) e clamar contra a sua maldade. No entanto, Jonas não foge por medo, mas por teologia e nacionalismo: ele sabia que Deus era misericordioso e não queria que os inimigos de Israel fossem perdoados. O capítulo 1 é a crônica de uma fuga impossível e revela a disciplina severa, porém profundamente amorosa, de Deus para com o Seu servo desobediente.',
    desc1: 'A rebelião de Jonas é deliberada e custosa. Deus diz "Levanta-te e vai a Nínive" (para o leste), e Jonas se levanta para fugir para Társis (o extremo oeste do mundo conhecido). O texto repete que ele tentava fugir "da presença do Senhor". O pecado sempre nos leva para baixo: ele "desceu" a Jope, "desceu" ao navio e, mais tarde, "desceu" ao porão. Ele pagou a passagem com seu próprio dinheiro. A desobediência a Deus sempre exige um preço alto e nos afasta do nosso propósito, criando a ilusão de que podemos escapar da jurisdição do Criador.',
    desc2: 'Deus não permite que Seu profeta fuja em paz. Ele "lança" um grande vento no mar, criando uma tempestade tão violenta que o navio ameaçava despedaçar-se. Ironicamente, os marinheiros pagãos estão orando desesperadamente aos seus deuses e jogando a carga ao mar, enquanto o profeta do Deus verdadeiro está dormindo profundamente no porão (o sono da letargia espiritual). O capitão acorda Jonas e exige que ele ore. O pecado de um crente nunca é puramente privado; a desobediência de Jonas trouxe uma tempestade que ameaçou a vida de todos os que estavam ao seu redor.',
    desc3: 'Quando as sortes são lançadas e caem sobre Jonas, ele confessa sua identidade: "Sou hebreu, e temo ao Senhor, o Deus do céu, que fez o mar e a terra seca". Ele reconhece que a tempestade é culpa sua e oferece a única solução: "Tomai-me, e lançai-me ao mar, e o mar se vos aquietará". Os marinheiros tentam remar, mas não conseguem lutar contra Deus. Eles clamam a Yahweh, lançam Jonas ao mar, e a fúria do mar cessa imediatamente. Deus, em Sua soberana misericórdia, "preparou um grande peixe" para engolir Jonas. O peixe não foi um instrumento de destruição, mas o meio de salvação e a "sala de aula" onde Deus redirecionaria o coração do profeta.',
    concl: 'A história de Jonas nos ensina que é impossível fugir da presença e da vontade de Deus. Quando nos rebelamos, Deus nos ama o suficiente para enviar tempestades para interromper a nossa fuga. As provações e até mesmo os "grandes peixes" que nos engolem são, muitas vezes, os instrumentos severos da graça divina para nos salvar de nós mesmos e nos trazer de volta ao centro da Sua vontade.'
  },
  {
    id: 'mrk_10_46_52',
    intro: 'O encontro com o cego Bartimeu ocorre em Jericó, a última parada de Jesus antes de Sua entrada triunfal em Jerusalém e Sua subsequente crucificação. Esta narrativa é muito mais do que um milagre de cura física; é um modelo poderoso de fé persistente, discipulado verdadeiro e visão espiritual. Enquanto os líderes religiosos e até mesmo os próprios discípulos de Jesus estavam cegos para a verdadeira natureza do Seu messianado (buscando poder e posições de honra), um mendigo cego à beira do caminho enxerga com clareza quem Jesus realmente é e o que Ele veio fazer.',
    desc1: 'Bartimeu estava sentado à beira do caminho, mendigando. Quando ouve que é Jesus de Nazaré que está passando, ele não pede esmolas, mas clama por misericórdia usando um título messiânico: "Jesus, Filho de Davi, tem misericórdia de mim!". A multidão, incomodada com o barulho e considerando o mendigo insignificante, tenta silenciá-lo. No entanto, a verdadeira fé não se intimida com a oposição, com a religiosidade formal ou com o protocolo social. Quanto mais o repreendiam, "cada vez gritava mais". A fé desesperada rompe as barreiras para chegar a Cristo.',
    desc2: 'O clamor de Bartimeu para o Rei do Universo. Jesus para e diz: "Chamai-o". A atitude de Bartimeu ao ser chamado é reveladora: "lançando de si a sua capa, levantou-se de um salto e foi ter com Jesus". A capa era provavelmente a sua única posse de valor, o seu abrigo contra o frio e o instrumento que ele estendia para receber esmolas. Ao lançar a capa, ele está abandonando a sua velha identidade de mendigo e a sua antiga fonte de segurança antes mesmo de receber a cura. É um ato de fé radical e desapego total.',
    desc3: 'Jesus faz a ele a mesma pergunta que havia feito aos discípulos Tiago e João pouco antes: "Que queres que eu te faça?". Enquanto os discípulos pediram posições de poder (sentar à direita e à esquerda), Bartimeu pede o essencial: "Mestre, que eu torne a ver". Jesus o cura imediatamente, declarando: "Vai, a tua fé te salvou". O detalhe mais importante está no final do versículo: Bartimeu não foi embora para aproveitar a sua nova visão no mundo; ele "seguia a Jesus pelo caminho". O caminho que Jesus estava trilhando era o caminho para a cruz em Jerusalém.',
    concl: 'Jesus nunca está ocupado demais ou focado demais em Sua própria missão para ouvir o clamor de um coração quebrantado. A história de Bartimeu nos ensina que quando Cristo abre os nossos olhos espirituais e nos salva pela Sua graça, a única resposta lógica e aceitável é abandonar a nossa velha vida e segui-Lo, custe o que custar, pelo caminho do discipulado.'
  },
  {
    id: 'luk_19_1_10',
    intro: 'A história de Zaqueu é um dos relatos mais belos e emblemáticos do Evangelho de Lucas sobre a graça transformadora de Jesus. Zaqueu não era apenas um cobrador de impostos; ele era o "chefe dos publicanos" em Jericó, uma cidade rica. Isso significava que ele havia enriquecido extorquindo seu próprio povo em favor do opressor Império Romano. Ele era um homem pequeno em estatura, mas gigante em riqueza e em rejeição social. Este encontro demonstra que ninguém está tão perdido, tão corrupto ou tão odiado que não possa ser alcançado e radicalmente transformado pela presença salvadora de Cristo.',
    desc1: 'A narrativa começa com a busca curiosa de Zaqueu. Ele "procurava ver quem era Jesus", mas a multidão (que o odiava) e a sua baixa estatura o impediam. Deixando de lado a dignidade e o orgulho que sua posição e riqueza exigiam, ele corre adiante e sobe em um sicômoro. Ele achava que estava apenas tentando ver um profeta famoso de longe, mas não sabia que o Bom Pastor já estava naquela cidade especificamente para buscar a ovelha perdida. A nossa busca por Deus é sempre uma resposta à busca prévia dEle por nós.',
    desc2: 'O clímax da história ocorre quando Jesus chega debaixo da árvore, olha para cima e faz um convite escandaloso: "Zaqueu, desce depressa, porque importa que eu fique hoje em tua casa". Jesus o chama pelo nome e se convida para entrar na intimidade do seu lar. A reação da multidão religiosa é de murmuração e indignação: "Entrou para ser hóspede de um homem pecador". A religião legalista afasta os pecadores para manter a pureza; a graça de Jesus se aproxima dos pecadores para trazer purificação. Jesus não exigiu arrependimento antes de entrar; a Sua presença graciosa é que produziu o arrependimento.',
    desc3: 'A transformação de Zaqueu é imediata, pública e afeta o seu bolso (a área mais sensível de sua vida). Ele se levanta e declara a Jesus: "Senhor, resolvo dar aos pobres a metade dos meus bens; e, se nalguma coisa tenho defraudado alguém, restituo quatro vezes mais" (indo além do que a Lei de Moisés exigia). A verdadeira salvação não é apenas uma experiência emocional ou uma mudança de destino eterno; ela produz uma transformação ética radical. O coração que foi tocado pela graça torna-se generoso e busca reparar as injustiças do passado.',
    concl: 'Jesus sela o encontro com a declaração gloriosa: "Hoje houve salvação nesta casa... Porque o Filho do Homem veio buscar e salvar o perdido". A história de Zaqueu é o resumo do Evangelho: a graça de Deus nos alcança onde estamos, nos aceita incondicionalmente, mas nos transforma tão profundamente que a nossa vida, os nossos valores e as nossas finanças passam a refletir o caráter do Reino de Deus.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done');
