const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'ezr_7_1_10',
    intro: 'O capítulo 7 de Esdras marca o início da segunda grande fase do retorno dos judeus do exílio babilônico. Quase 60 anos após a reconstrução do templo sob a liderança de Zorobabel, a comunidade em Jerusalém estava lutando com o declínio espiritual e a assimilação cultural. Deus levanta Esdras, um sacerdote e "escriba hábil na lei de Moisés", para liderar um novo grupo de volta a Jerusalém com a missão de restaurar a adoração e a obediência à Palavra de Deus. O texto destaca repetidamente que o sucesso de Esdras não se devia à sua habilidade política, mas ao fato de que "a mão do Senhor seu Deus estava sobre ele". O versículo 10 revela o segredo dessa bênção divina, apresentando o modelo definitivo para qualquer pessoa que deseja ser usada por Deus no ensino da Sua Palavra.',
    desc1: 'A narrativa começa traçando a linhagem de Esdras (v. 1-5), provando a sua autoridade sacerdotal como descendente direto de Arão. No entanto, a sua verdadeira autoridade não vinha apenas da sua genealogia, mas da sua vocação: ele era um "escriba hábil" (v. 6). No contexto do Antigo Testamento, um escriba não era apenas um copista, mas um estudioso, intérprete e professor da Lei. O rei Artaxerxes da Pérsia concede a Esdras tudo o que ele pede para a viagem. O autor faz questão de explicar o porquê desse favor real: "segundo a mão do Senhor seu Deus, que estava sobre ele". O favor humano (mesmo de um rei pagão) é frequentemente o resultado da providência divina agindo em favor daqueles que estão alinhados com os propósitos de Deus.',
    desc2: 'A viagem da Babilônia a Jerusalém levou exatamente quatro meses (v. 8-9). Foi uma jornada longa e perigosa através do deserto, carregando grandes tesouros para o templo, sem escolta militar (Esdras 8:22). Mais uma vez, o texto afirma: "segundo a boa mão do seu Deus sobre ele". A proteção e a provisão durante a jornada não foram acidentes, mas a evidência da presença ativa de Deus. A "boa mão de Deus" é a frase-chave do livro de Esdras e Neemias para descrever a graça capacitadora de Deus que garante o sucesso da missão.',
    desc3: 'O versículo 10 é o coração do capítulo e revela a preparação interna que atraiu a "boa mão de Deus": "Porque Esdras tinha preparado o seu coração para buscar a lei do Senhor e para a cumprir e para ensinar em Israel os seus estatutos e os seus juízos". Esdras não começou ensinando; ele começou "preparando o coração" (focando a sua vontade e afeições). A sua preparação seguiu uma ordem inegociável: primeiro, "buscar" (estudar diligentemente a Palavra); segundo, "cumprir" (obedecer e aplicar a Palavra à sua própria vida); e só então, "ensinar". O ensino sem estudo é ignorância; o ensino sem obediência é hipocrisia. A autoridade de Esdras vinha do fato de que a sua vida era a ilustração do seu sermão.',
    concl: 'A história de Esdras nos ensina que a "boa mão de Deus" não repousa sobre aqueles que buscam apenas o sucesso ou a influência, mas sobre aqueles que se dedicam apaixonadamente à Sua Palavra. Se queremos impactar a nossa geração, devemos seguir a ordem de Esdras: preparar o coração, estudar as Escrituras com profundidade, obedecer com integridade e, finalmente, ensinar com a autoridade de uma vida transformada.'
  },
  {
    id: 'ps_51_1_17',
    intro: 'O Salmo 51 é o mais famoso e profundo dos sete salmos penitenciais da Bíblia. O cabeçalho do salmo fornece o contexto histórico trágico: "Salmo de Davi, quando o profeta Natã veio a ele, depois dele ter possuído a Bate-Seba". Davi, o homem segundo o coração de Deus, havia cometido adultério, tentado encobrir o seu pecado com engano e, finalmente, orquestrado o assassinato de Urias, o marido de Bate-Seba. Durante quase um ano, Davi viveu em hipocrisia e miséria espiritual (descrita no Salmo 32), até ser confrontado por Natã. O Salmo 51 é a oração de um homem cujo coração foi despedaçado pela convicção do pecado. Ele não oferece desculpas, não culpa as circunstâncias e não tenta barganhar com Deus. Ele oferece o único sacrifício que Deus não despreza: um coração quebrantado e contrito.',
    desc1: 'A oração começa com um apelo desesperado à graça, não à justiça (v. 1-2): "Tem misericórdia de mim, ó Deus, segundo a tua benignidade; apaga as minhas transgressões, segundo a multidão das tuas misericórdias". Davi sabe que, pela lei, ele merece a morte. A sua única esperança é o caráter de Deus (a Sua hesed, o Seu amor leal). Davi usa três palavras para descrever a sua falha: "transgressões" (rebelião deliberada), "iniquidade" (natureza torta) e "pecado" (errar o alvo). Ele pede para ser lavado e purificado. No versículo 3, ele assume total responsabilidade: "Porque eu conheço as minhas transgressões, e o meu pecado está sempre diante de mim". Ele não diz "eu errei", mas "eu pequei".',
    desc2: 'O versículo 4 contém a declaração teológica mais profunda sobre a natureza do pecado: "Contra ti, contra ti somente pequei, e fiz o que é mal à tua vista". Davi havia pecado contra Bate-Seba, contra Urias, contra a nação e contra a sua própria família. Mas ele entende que todo pecado, em última análise, é uma ofensa cósmica contra o Criador e Juiz do universo. Ele reconhece que Deus é perfeitamente justo em condená-lo. Davi também reconhece a raiz do seu problema (v. 5): "Eis que em iniquidade fui formado, e em pecado me concebeu minha mãe". Ele não está culpando a sua mãe, mas confessando a doutrina do pecado original: nós não somos pecadores apenas porque pecamos; nós pecamos porque nascemos com uma natureza pecaminosa.',
    desc3: 'A partir do versículo 7, Davi clama por restauração interna: "Purifica-me com hissopo (o ramo usado para aspergir sangue nos sacrifícios), e ficarei puro; lava-me, e ficarei mais branco do que a neve". Ele não pede apenas perdão legal, mas uma cirurgia cardíaca (v. 10): "Cria em mim, ó Deus, um coração puro, e renova em mim um espírito reto". Ele teme a perda da presença de Deus mais do que a perda do trono (v. 11): "Não me lances fora da tua presença, e não retires de mim o teu Espírito Santo". Davi conclui (v. 16-17) reconhecendo que Deus não quer rituais religiosos externos para cobrir o pecado: "Os sacrifícios para Deus são o espírito quebrantado; a um coração quebrantado e contrito não desprezarás, ó Deus".',
    concl: 'O Salmo 51 nos ensina que o verdadeiro arrependimento não é apenas o remorso pelas consequências do pecado, mas a dor profunda por ter ofendido a santidade de Deus. Quando caímos, não devemos tentar esconder o nosso pecado com desculpas ou rituais religiosos. Devemos correr para a misericórdia de Deus, confessar a nossa culpa sem reservas e clamar por um coração novo, sabendo que Ele nunca rejeita um pecador genuinamente quebrantado.'
  },
  {
    id: 'zec_4_1_14',
    intro: 'O capítulo 4 de Zacarias contém a quinta das oito visões noturnas dadas ao profeta. O contexto histórico é crucial: os judeus haviam retornado do exílio babilônico e começado a reconstruir o templo em Jerusalém sob a liderança do governador Zorobabel e do sumo sacerdote Josué. No entanto, devido à oposição política, à falta de recursos e à apatia do próprio povo, a obra estava paralisada há quase 16 anos. Zorobabel estava desanimado, sentindo que a tarefa era grande demais (uma montanha) e os seus recursos pequenos demais. Deus envia esta visão a Zacarias com uma mensagem específica para encorajar Zorobabel, revelando que a obra de Deus não é realizada pelo esforço humano, mas pelo poder invisível e inesgotável do Espírito Santo.',
    desc1: 'A visão começa com o anjo acordando Zacarias como se ele estivesse dormindo. Zacarias vê "um castiçal todo de ouro" (semelhante à menorá do tabernáculo) com um vaso de azeite no topo e sete lâmpadas. O detalhe mais importante da visão são as "duas oliveiras, uma à direita do vaso e outra à sua esquerda". No sistema do tabernáculo, os sacerdotes tinham que esmagar as azeitonas e encher as lâmpadas manualmente todos os dias. Na visão de Zacarias, o azeite flui diretamente e continuamente das oliveiras vivas para o castiçal através de tubos de ouro. É um sistema de suprimento perpétuo e automático, que não depende do esforço humano para manter a luz brilhando.',
    desc2: 'Zacarias não entende a visão e pergunta ao anjo o seu significado. O anjo responde com a mensagem central para Zorobabel (v. 6): "Esta é a palavra do Senhor a Zorobabel, dizendo: Não por força nem por violência, mas sim pelo meu Espírito, diz o Senhor dos Exércitos". A "força" (poder militar ou recursos financeiros) e a "violência" (poder político ou esforço humano) não seriam suficientes para terminar o templo. O azeite abundante na visão representa o Espírito Santo. A obra de Deus só pode ser concluída pelo suprimento contínuo do Espírito de Deus. Com esse poder, os obstáculos intransponíveis desapareceriam (v. 7): "Quem és tu, ó grande monte? Diante de Zorobabel tornar-te-ás uma campina".',
    desc3: 'Deus dá a Zorobabel uma promessa específica (v. 9): "As mãos de Zorobabel fundaram esta casa; também as suas mãos a acabarão". Ele teria a alegria de colocar a "pedra de remate" (a última pedra) com aclamações de "Graça, graça a ela". O anjo também repreende o desânimo do povo (v. 10): "Porque, quem despreza o dia das coisas pequenas?". O alicerce do novo templo parecia insignificante em comparação com a glória do templo de Salomão, mas Deus se alegrava com aquele pequeno começo. Finalmente, o anjo explica que as duas oliveiras representam "os dois ungidos" (literalmente, "filhos do óleo fresco"), referindo-se a Zorobabel (o líder civil/real) e Josué (o líder religioso/sacerdotal), que eram os canais através dos quais o Espírito de Deus fluía para a comunidade.',
    concl: 'A visão do castiçal e das oliveiras nos ensina que, quando enfrentamos "montanhas" de oposição ou tarefas que parecem grandes demais para os nossos recursos, não devemos confiar na nossa própria força, inteligência ou dinheiro. O sucesso no Reino de Deus depende inteiramente da nossa conexão contínua com a fonte inesgotável do Espírito Santo. Não devemos desprezar os pequenos começos, pois o que Deus começa pela graça, Ele termina pelo Seu Espírito.'
  },
  {
    id: 'phl_4_4_13',
    intro: 'O capítulo 4 de Filipenses é um dos textos mais amados e citados do Novo Testamento, conhecido por suas promessas sobre a paz de Deus e a força em Cristo. O que torna este texto extraordinário não é apenas a sua teologia, mas o seu contexto. O apóstolo Paulo não escreveu estas palavras de um retiro de férias, mas de uma prisão romana, acorrentado a um guarda, aguardando um julgamento que poderia resultar na sua execução. A igreja de Filipos, por sua vez, enfrentava perseguição externa e conflitos internos. É neste cenário de ansiedade e sofrimento que Paulo revela o segredo de uma alegria que não depende das circunstâncias e de uma paz que guarda a mente como uma guarnição militar.',
    desc1: 'Paulo começa com um mandamento que parece impossível (v. 4): "Regozijai-vos sempre no Senhor; outra vez digo, regozijai-vos". A alegria cristã não é um sentimento superficial que ignora a dor, mas uma escolha deliberada de focar "no Senhor". As circunstâncias mudam, mas o Senhor é imutável. Em seguida, ele aborda o maior inimigo da paz (v. 6): "Não estejais inquietos (ansiosos) por coisa alguma". A ansiedade é a tentativa de carregar o peso do futuro que pertence a Deus. O antídoto para a ansiedade não é a meditação vazia, mas a oração específica: "antes as vossas petições sejam em tudo conhecidas diante de Deus pela oração e súplica, com ação de graças". A gratidão muda o foco do que nos falta para o que Deus já fez.',
    desc2: 'O resultado dessa oração confiante é uma promessa magnífica (v. 7): "E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos sentimentos em Cristo Jesus". A paz de Deus não é a ausência de problemas, mas a presença de Deus no meio dos problemas. Ela "excede o entendimento" porque não faz sentido lógico (ter paz na prisão). A palavra "guardará" é um termo militar; a paz de Deus age como uma sentinela armada na porta da nossa mente, impedindo que a ansiedade e o medo entrem. Para manter essa paz, Paulo instrui sobre a dieta mental do crente (v. 8): devemos pensar em tudo o que é verdadeiro, honesto, justo, puro, amável e de boa fama. A mente não pode estar em paz se estiver se alimentando de lixo.',
    desc3: 'Paulo conclui revelando o seu próprio testemunho de contentamento (v. 11-13). Ele diz que aprendeu a estar contente em qualquer situação. O contentamento não é natural; é uma disciplina aprendida na escola do sofrimento. Ele diz: "Sei estar abatido, e sei também ter abundância... tanto a ter fartura, como a ter fome". A prosperidade pode ser um teste tão difícil quanto a pobreza. O segredo para sobreviver a ambos os extremos é o versículo 13: "Posso todas as coisas em Cristo que me fortalece". Este versículo não é um slogan motivacional para vencer jogos de futebol ou enriquecer; é a declaração de que, através da união com Cristo, Paulo tinha força para suportar a fome, a prisão e a morte sem perder a alegria.',
    concl: 'Filipenses 4 nos ensina que a ansiedade e as circunstâncias difíceis não têm a palavra final na vida do crente. Quando escolhemos nos alegrar no Senhor, trocar as nossas preocupações por orações com gratidão e disciplinar a nossa mente com a verdade, experimentamos uma paz que o mundo não pode dar nem tirar. O segredo da vida cristã não é a ausência de dor, mas a presença fortalecedora de Cristo em todas as coisas.'
  },
  {
    id: 'col_1_15_23',
    intro: 'O capítulo 1 de Colossenses (versículos 15 a 23) contém um dos mais sublimes e profundos hinos cristológicos de toda a Bíblia. O apóstolo Paulo escreveu esta carta para combater uma heresia perigosa (a "heresia colossense") que estava se infiltrando na igreja. Esses falsos mestres ensinavam uma mistura de misticismo, legalismo judaico e filosofia grega, sugerindo que Jesus era apenas uma emanação divina entre muitas, um anjo superior, mas não o Criador supremo ou o único mediador. Para destruir essa heresia, Paulo não apenas argumenta; ele exalta Cristo. Ele apresenta uma visão de Jesus tão vasta, tão cósmica e tão suprema que qualquer outra filosofia ou poder espiritual é reduzido a nada em comparação.',
    desc1: 'O hino começa exaltando a supremacia de Cristo sobre a primeira criação (o universo físico e espiritual). Paulo declara (v. 15): "O qual é imagem do Deus invisível, o primogênito de toda a criação". Jesus não é uma cópia de Deus; Ele é a manifestação exata e visível do Deus invisível. O termo "primogênito" (prototokos) não significa que Ele foi o primeiro ser criado (como ensinam as seitas), mas é um título de soberania e herança; Ele é o herdeiro e governante de tudo. Paulo prova isso no v. 16: "Porque nele foram criadas todas as coisas que há nos céus e na terra, visíveis e invisíveis, sejam tronos, sejam dominações, sejam principados, sejam potestades". Jesus não é um anjo; Ele criou os anjos. Tudo foi criado "por ele e para ele". Ele é a origem e o destino do universo.',
    desc2: 'Além de ser o Criador, Cristo é o Sustentador do universo (v. 17): "E ele é antes de todas as coisas, e todas as coisas subsistem por ele". A gravidade e as leis da física não mantêm o universo unido; é a palavra de Cristo que impede o cosmos de se desintegrar no caos. No versículo 18, Paulo muda da primeira criação (o universo) para a nova criação (a Igreja): "E ele é a cabeça do corpo, da igreja; é o princípio e o primogênito dentre os mortos, para que em tudo tenha a preeminência". Assim como Ele governa o universo, Ele governa a Igreja. A Sua ressurreição ("primogênito dentre os mortos") garante a nossa ressurreição. O propósito de tudo isso é singular: a preeminência (supremacia absoluta) de Cristo em todas as coisas.',
    desc3: 'O hino culmina com a obra da reconciliação (v. 19-23). Paulo afirma que "foi do agrado do Pai que toda a plenitude nele habitasse". Toda a essência de Deus habita em Cristo corporalmente. E através dEle, Deus reconciliou consigo mesmo "todas as coisas... fazendo a paz pelo sangue da sua cruz". O pecado havia quebrado a harmonia do universo, mas a cruz de Cristo é o evento cósmico que restaura a paz. Paulo aplica isso pessoalmente aos colossenses: "A vós também, que noutro tempo éreis estranhos, e inimigos no entendimento pelas vossas obras más, agora contudo vos reconciliou no corpo da sua carne, pela morte". O objetivo dessa reconciliação é apresentar-nos "santos, e irrepreensíveis, e inculpáveis" diante de Deus, desde que permaneçamos firmes na fé do evangelho.',
    concl: 'Colossenses 1 nos ensina que Jesus Cristo não é apenas um bom mestre moral ou um guia espiritual entre muitos. Ele é o Criador do universo, o Sustentador da realidade, a Cabeça da Igreja e o único Reconciliador entre Deus e os homens. Quando compreendemos a supremacia absoluta de Cristo, percebemos que não precisamos de filosofias humanas, rituais místicos ou mediadores angelicais. Cristo é tudo, e nEle temos tudo.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 34');
