const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'est_4_1_17',
    intro: 'O capítulo 4 de Ester é o ponto de virada de todo o livro. Hamã, o segundo no comando do Império Persa, havia manipulado o rei Assuero para assinar um decreto irrevogável que ordenava o extermínio de todos os judeus do império em um único dia. Quando Mardoqueu (primo de Ester) descobre o complô, ele se veste de pano de saco e cinza, lamentando amargamente. A rainha Ester, que mantinha a sua identidade judaica em segredo no palácio, é confrontada com o maior dilema de sua vida: permanecer em silêncio para proteger a sua própria vida e posição, ou arriscar tudo para tentar salvar o seu povo. Esta narrativa é uma aula magistral sobre providência, coragem e propósito.',
    desc1: 'Quando Ester tenta enviar roupas para Mardoqueu tirar o pano de saco (tentando resolver o desconforto externo sem entender a crise real), ele recusa e envia a ela uma cópia do decreto de morte, ordenando que ela vá ao rei suplicar pelo seu povo. Ester responde com uma objeção lógica e aterrorizante: qualquer pessoa que entrasse no pátio interior do rei sem ser chamada seria morta, a menos que o rei estendesse o cetro de ouro. E ela não era chamada havia trinta dias. Ester estava presa entre o decreto de Hamã (que mataria o seu povo) e a lei do rei (que poderia matá-la imediatamente).',
    desc2: 'A resposta de Mardoqueu a Ester é uma das declarações teológicas mais profundas do Antigo Testamento sobre a providência divina. Ele a adverte: "Não imagines no teu íntimo que, por estares na casa do rei, escaparás só tu entre todos os judeus". O silêncio não a salvaria. Em seguida, ele declara: "Porque, se de todo te calares neste tempo, socorro e livramento de outra parte virá para os judeus, mas tu e a casa de teu pai perecereis". Mardoqueu tem fé absoluta de que Deus não permitirá a extinção do Seu povo da aliança. Se Ester falhar, Deus usará outro meio, mas ela perderá o privilégio de ser o instrumento de Deus.',
    desc3: 'O clímax do argumento de Mardoqueu é a pergunta que ecoa através dos séculos: "E quem sabe se para tal tempo como este chegaste a este reino?". Ele sugere que a beleza de Ester e a sua ascensão ao trono não foram acidentes, mas um plano soberano de Deus para posicioná-la exatamente onde ela precisava estar para salvar o Seu povo. Diante dessa revelação de propósito, Ester toma a sua decisão. Ela pede que todos os judeus jejuem por ela durante três dias, e declara a sua resolução corajosa: "Irei ter com o rei, ainda que não é segundo a lei; e se perecer, pereci". Ela escolhe a cruz do sacrifício em vez do conforto do palácio.',
    concl: 'A história de Ester nos ensina que Deus frequentemente nos coloca em posições de influência (seja no trabalho, na família ou na sociedade) não para o nosso próprio conforto, mas para sermos instrumentos de livramento para os outros. Quando descobrimos que fomos chamados "para um tempo como este", a única resposta aceitável é a coragem sacrificial.'
  },
  {
    id: 'mt_25_1_13',
    intro: 'A Parábola das Dez Virgens é contada por Jesus no contexto do Seu discurso escatológico (sobre o fim dos tempos) no Monte das Oliveiras. O objetivo da parábola é ilustrar a necessidade vital de vigilância e preparação espiritual contínua para a Sua Segunda Vinda. Jesus usa a figura de um casamento judaico do primeiro século, onde as virgens (damas de honra) deveriam esperar o noivo à noite para acompanhá-lo com lâmpadas acesas até o banquete nupcial. A diferença trágica entre as cinco virgens prudentes e as cinco loucas não estava na aparência externa, mas na preparação invisível do azeite.',
    desc1: 'As dez virgens tinham muito em comum: todas foram convidadas para o casamento, todas vestiam roupas de festa, todas tinham lâmpadas, todas saíram ao encontro do noivo e, quando o noivo demorou, todas tosquenejaram e adormeceram. Aos olhos humanos, elas eram idênticas. A diferença crucial estava no que não se via imediatamente: "As loucas, tomando as suas lâmpadas, não levaram azeite consigo. Mas as prudentes levaram azeite em suas vasilhas, com as suas lâmpadas". O azeite na Bíblia é frequentemente um símbolo do Espírito Santo, da graça interna e de um relacionamento genuíno com Deus. As loucas tinham a religião externa (a lâmpada), mas faltava-lhes a vida interna (o azeite).',
    desc2: 'A crise revela a verdadeira condição de cada uma. À meia-noite (a hora mais escura e inesperada), ouve-se o clamor: "Aí vem o esposo, saí-lhe ao encontro". Todas acordam e preparam as suas lâmpadas. As loucas percebem com desespero que as suas lâmpadas estão se apagando, pois não têm reserva de azeite. Elas pedem azeite às prudentes, mas a resposta é não: "Não seja caso que nos falte a nós e a vós". A preparação espiritual é intransferível. Você não pode pegar emprestado o relacionamento com Deus, o caráter ou a fé de outra pessoa na hora da crise ou do juízo.',
    desc3: 'Enquanto as loucas vão comprar azeite, o noivo chega. As que estavam preparadas entram com ele para as bodas, e "cerrou-se a porta". A porta fechada representa a finalidade do juízo e o fim do tempo da graça. Quando as loucas retornam e batem na porta clamando "Senhor, Senhor, abre-nos", a resposta do noivo é aterrorizante: "Em verdade vos digo que vos não conheço". O problema não era apenas a falta de azeite, mas a falta de intimidade e conhecimento relacional com o noivo. Jesus conclui com a exortação central: "Vigiai, pois, porque não sabeis o dia nem a hora em que o Filho do homem há de vir".',
    concl: 'A vigilância cristã não é viver em pânico sobre o fim do mundo, mas viver em constante comunhão com o Espírito Santo, cultivando uma vida interna de fé e obediência. A aparência religiosa pode enganar os homens, mas quando a meia-noite chegar, apenas o "azeite" de um relacionamento genuíno com Cristo nos garantirá a entrada no banquete eterno.'
  },
  {
    id: 'mrk_2_1_12',
    intro: 'A cura do paralítico em Cafarnaum é um dos relatos mais dinâmicos e teologicamente profundos do ministério de Jesus. Jesus estava ensinando em uma casa que rapidamente ficou tão lotada que não havia espaço "nem mesmo junto à porta". A narrativa destaca a determinação extraordinária de quatro amigos que trazem um paralítico para ser curado, mas o clímax da história não é o milagre físico. Jesus usa a fé audaciosa desses homens para fazer uma declaração chocante sobre a Sua própria identidade divina e para demonstrar que a maior necessidade humana não é a cura do corpo, mas o perdão dos pecados.',
    desc1: 'A fé dos quatro amigos é ativa, criativa e imparável. Ao encontrarem a porta bloqueada pela multidão (muitas vezes, os próprios religiosos bloqueiam o acesso a Jesus), eles não desistem nem voltam para casa. Eles sobem ao telhado (feito de barro, galhos e telhas), abrem um buraco e descem o leito onde jazia o paralítico bem diante de Jesus. O texto diz: "E Jesus, vendo a fé deles...". A fé que chama a atenção de Jesus não é apenas um assentimento intelectual, mas uma ação ousada que rompe telhados e supera obstáculos para colocar os necessitados aos pés do Salvador.',
    desc2: 'A resposta de Jesus surpreende a todos. Em vez de dizer "Levanta-te e anda", Ele olha para o paralítico e diz: "Filho, perdoados estão os teus pecados". Jesus ignora a necessidade óbvia e imediata (a paralisia física) para tratar a necessidade invisível e eterna (a paralisia espiritual). A doença física é temporária, mas o pecado não perdoado é eterno. Os escribas presentes imediatamente acusam Jesus de blasfêmia em seus corações, raciocinando corretamente: "Quem pode perdoar pecados, senão Deus?". Eles entenderam a implicação: Jesus estava reivindicando prerrogativas divinas.',
    desc3: 'Conhecendo os pensamentos deles, Jesus lança um desafio: "Qual é mais fácil? dizer ao paralítico: Estão perdoados os teus pecados; ou dizer-lhe: Levanta-te, e toma o teu leito, e anda?". Dizer que os pecados estão perdoados é fácil, pois o resultado é invisível e não pode ser comprovado. Dizer "levanta-te" é difícil, pois o resultado é imediato e visível. Para provar que Ele tem autoridade na terra para fazer o invisível (perdoar pecados), Jesus faz o visível: Ele ordena ao paralítico que se levante, pegue o seu leito e vá para casa. O homem se levanta imediatamente, e todos glorificam a Deus.',
    concl: 'A cura do paralítico nos ensina que Jesus é o Deus encarnado com autoridade suprema para perdoar pecados. Ele se importa com as nossas dores físicas e emocionais, mas o Seu maior milagre é a cura da nossa alma. Além disso, a história nos desafia a ter a fé "rompedora de telhados" daqueles quatro amigos, dispostos a fazer qualquer coisa para levar as pessoas a Cristo.'
  },
  {
    id: 'luk_23_39_43',
    intro: 'A cena da crucificação no Evangelho de Lucas apresenta o diálogo mais extraordinário que ocorreu no Calvário. Jesus está pendurado na cruz, ladeado por dois malfeitores (ladrões ou rebeldes). Em meio à agonia física, às zombarias dos líderes religiosos e à escuridão que se aproximava, a cruz se torna o tribunal final onde dois destinos eternos são decididos. A interação entre Jesus e o ladrão arrependido é a demonstração mais pura, radical e incontestável de que a salvação é exclusivamente pela graça, mediante a fé, sem qualquer mérito ou obra humana.',
    desc1: 'O contraste entre os dois criminosos revela as duas únicas respostas possíveis diante de Cristo. O primeiro malfeitor junta-se à multidão e blasfema contra Jesus, exigindo uma salvação egoísta e terrena: "Se tu és o Cristo, salva-te a ti mesmo, e a nós". Ele quer escapar da cruz, mas não quer ser salvo do seu pecado. O sofrimento não produz automaticamente arrependimento; muitas vezes, ele apenas endurece o coração rebelde. O segundo malfeitor, no entanto, repreende o primeiro, demonstrando o temor de Deus: "Nem tu temes a Deus, estando na mesma condenação?".',
    desc2: 'O arrependimento do segundo ladrão é profundo e teologicamente preciso. Primeiro, ele reconhece a sua própria culpa e a justiça da sua condenação: "E nós, na verdade, com justiça, porque recebemos o que os nossos feitos mereciam". Não há desculpas nem vitimização. Segundo, ele reconhece a impecabilidade e a justiça de Cristo: "Mas este nenhum mal fez". Terceiro, ele demonstra uma fé monumental. Enquanto os discípulos haviam fugido e a multidão zombava de um rei derrotado e moribundo, o ladrão olha para Jesus sangrando e vê o Rei do Universo. Ele faz um pedido simples e humilde: "Senhor, lembra-te de mim, quando entrares no teu reino".',
    desc3: 'A resposta de Jesus é a garantia mais consoladora de toda a Escritura: "Em verdade te digo que hoje estarás comigo no Paraíso". Jesus não exige que o ladrão desça da cruz para ser batizado, não pede que ele faça restituição pelos seus crimes, nem que cumpra rituais religiosos (o que seria impossível na sua condição). A salvação é concedida instantaneamente com base unicamente na graça de Cristo e na fé do pecador. A promessa de Jesus ("hoje") anula qualquer ideia de purgatório ou sono da alma; a morte para o crente é a transição imediata para a presença consciente de Cristo ("comigo no Paraíso").',
    concl: 'A história do ladrão na cruz destrói qualquer teologia de salvação por obras. Ela nos ensina que ninguém está tão longe que não possa ser alcançado pela graça de Deus, e que o perdão está disponível até o último suspiro para aquele que se volta para Cristo com um coração quebrantado e crente.'
  },
  {
    id: 'jhn_9_1_12',
    intro: 'O capítulo 9 de João narra a cura do homem cego de nascença, o sexto "sinal" no Evangelho. Jesus e Seus discípulos encontram um homem que vivia na escuridão total desde o ventre de sua mãe. O encontro começa com um debate teológico sobre a causa do sofrimento, mas Jesus rapidamente transforma a tragédia em uma oportunidade para manifestar a glória de Deus. Esta narrativa não é apenas sobre a restauração da visão física, mas uma profunda alegoria sobre a cegueira espiritual da humanidade e como Jesus, a Luz do Mundo, abre os nossos olhos para a verdade.',
    desc1: 'Ao verem o cego, os discípulos fazem uma pergunta baseada na teologia retributiva da época (a ideia de que todo sofrimento é resultado direto de um pecado específico): "Rabi, quem pecou, este ou seus pais, para que nascesse cego?". Eles veem o homem como um problema teológico a ser resolvido ou um caso para ser julgado. Jesus rejeita essa premissa cruel e muda o foco da causa (o passado) para o propósito (o futuro): "Nem ele pecou nem seus pais; mas foi assim para que se manifestem nele as obras de Deus". Jesus nos ensina a parar de procurar culpados para o sofrimento e começar a procurar oportunidades para a graça de Deus agir.',
    desc2: 'Jesus declara: "Enquanto estou no mundo, sou a luz do mundo". Em seguida, Ele realiza o milagre de uma forma altamente simbólica e incomum. Ele cospe na terra, faz lodo com a saliva e unta os olhos do cego. Esta ação remete diretamente a Gênesis 2, onde Deus formou o homem do pó da terra. Jesus está realizando um ato de nova criação; Ele está dando ao homem os olhos que ele nunca teve. O lodo nos olhos também serviu para testar a fé do homem, exigindo que ele obedecesse a uma instrução específica para receber a cura.',
    desc3: 'Jesus ordena: "Vai, lava-te no tanque de Siloé (que significa o Enviado)". O homem, mesmo sem nunca ter visto o rosto de Jesus, obedece. Ele vai cego, lava-se e "voltou vendo". A obediência à Palavra de Cristo é o caminho para a iluminação. O milagre causa um alvoroço na comunidade. Os vizinhos mal conseguem reconhecê-lo, debatendo se era ele mesmo ou alguém parecido. A transformação que Jesus faz é tão radical que muda a nossa identidade. O homem responde com a simplicidade inegável do testemunho pessoal: "Sou eu... O homem, chamado Jesus, fez lodo, untou-me os olhos, e disse-me: Vai ao tanque de Siloé, e lava-te. Então fui, e lavei-me, e vi".',
    concl: 'Todos nós nascemos espiritualmente cegos, incapazes de ver a glória de Deus. A cura do cego de nascença nos ensina que a salvação é uma obra de nova criação realizada por Jesus, a Luz do Mundo. Quando obedecemos à Sua Palavra, os nossos olhos são abertos, e o nosso maior argumento contra a incredulidade do mundo é o nosso próprio testemunho: "Eu era cego, e agora vejo".'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 10');
