const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'luk_14_26',
    intro: 'No capítulo 14 de Lucas, Jesus está cercado por "grandes multidões" que O acompanhavam. Muitas dessas pessoas provavelmente O seguiam pelos motivos errados: fascínio pelos milagres, esperança de pão grátis ou expectativa de uma revolução política contra Roma. Jesus, que nunca se impressionou com números e nunca diluiu a Sua mensagem para atrair multidões, vira-se para eles e profere palavras chocantes para filtrar os verdadeiros discípulos dos meros simpatizantes. O versículo 26 estabelece os termos inegociáveis do discipulado, usando uma linguagem tão forte que ofenderia qualquer pessoa que não estivesse disposta a uma rendição total.',
    desc1: 'O Paradoxo do "Ódio" à Família. Jesus diz: "Se alguém vier a mim, e não aborrecer (odiar) a seu pai, e mãe, e mulher, e filhos, e irmãos, e irmãs... não pode ser meu discípulo". Esta é uma das frases mais difíceis de Jesus. Ele não está anulando o mandamento de amar o próximo ou honrar os pais. No idioma semítico, "odiar" frequentemente significa "amar menos" ou "escolher um em detrimento do outro".',
    desc2: 'A Hierarquia da Lealdade. Jesus está exigindo que o nosso amor e lealdade a Ele sejam tão absolutos e supremos que, em comparação, o nosso amor pela nossa família mais próxima pareça ódio. A devoção a Cristo deve ser a prioridade número um, inquestionável e inegociável. Se a vontade da família entrar em conflito com a vontade de Cristo, o discípulo deve escolher Cristo sem hesitação.',
    desc3: 'A Renúncia da Própria Vida. A exigência de Jesus vai além da família e atinge o núcleo do ego humano: "...e ainda também a sua própria vida, não pode ser meu discípulo". O verdadeiro discipulado exige o fim da autonomia. Não podemos seguir a Jesus e, ao mesmo tempo, insistir em ser os senhores do nosso próprio destino. Seguir a Cristo significa entregar a Ele a escritura de propriedade da nossa vida.',
    concl: 'Jesus não oferece um evangelho barato. Ele nos chama para morrermos para nós mesmos. O verdadeiro discipulado custa tudo o que temos e tudo o que somos. Mas a promessa implícita do evangelho é que Aquele que nos pede tudo é o único que é digno de receber tudo.'
  },
  {
    id: 'joh_14_28',
    intro: 'No capítulo 14 de João, Jesus está no Cenáculo com os Seus discípulos na noite anterior à Sua crucificação. Os discípulos estão angustiados porque Jesus anunciou que os deixaria. Jesus profere palavras de profundo conforto, prometendo o Espírito Santo e a paz. No versículo 28, Ele diz algo que tem sido frequentemente mal interpretado e usado por grupos que negam a divindade de Cristo (como as Testemunhas de Jeová): "Ouvistes que eu vos disse: Vou, e venho para vós. Se me amásseis, certamente exultaríeis por ter dito: Vou para o Pai; porque o meu Pai é maior do que eu". Como Jesus pode dizer que o Pai é "maior" se Ele e o Pai são um (João 10:30)?',
    desc1: 'A Distinção entre Natureza e Posição. A chave para entender esta declaração é a doutrina da Encarnação (a Kenosis, Filipenses 2:6-8). Quando Jesus diz "o Pai é maior do que eu", Ele não está falando sobre a Sua essência divina ou natureza (ontologia). Em essência, o Pai, o Filho e o Espírito Santo são coiguais e coeternos. Jesus está falando sobre a Sua posição e função durante o Seu estado de humilhação terrena. Como o Filho encarnado, Jesus assumiu voluntariamente uma posição de subordinação e submissão ao Pai para cumprir a obra da redenção.',
    desc2: 'O Retorno à Glória. O contexto do versículo explica o motivo da alegria que os discípulos deveriam sentir. Jesus está dizendo: "Eu estou voltando para o Pai". Durante a Sua vida terrena, a glória de Jesus estava velada; Ele sofreu fome, cansaço, rejeição e estava prestes a sofrer a morte na cruz. O Pai, no céu, não estava sujeito a essas limitações e humilhações (neste sentido, a posição do Pai era "maior" ou mais gloriosa naquele momento). O retorno de Jesus ao Pai significava o fim da Sua humilhação e a Sua exaltação de volta à glória que Ele tinha antes da fundação do mundo (João 17:5).',
    desc3: 'O Benefício para os Discípulos. Jesus repreende gentilmente o egoísmo da tristeza dos discípulos. Se eles realmente O amassem, eles se alegrariam com a Sua partida, pois isso significava a Sua exaltação e o Seu triunfo. Além disso, a Sua ida para o Pai era necessária para que o Espírito Santo (o Consolador) fosse enviado a eles (João 16:7). A ascensão de Cristo ao Pai "maior" (exaltado no céu) garantiria a vitória e o poder da Igreja na terra.',
    concl: 'A declaração "o Pai é maior do que eu" não nega a divindade de Cristo; ela destaca o sacrifício incrível da Sua encarnação. O Filho de Deus, coigual ao Pai, voluntariamente se humilhou e se submeteu para nos salvar. A Sua ascensão de volta ao Pai é a garantia da nossa própria salvação e da presença do Espírito Santo em nós.'
  },
  {
    id: 'rom_9_13',
    intro: 'O capítulo 9 de Romanos é o texto mais profundo do apóstolo Paulo sobre a soberania de Deus na eleição. Para provar que a salvação não depende de descendência física ou de obras humanas, mas exclusivamente da escolha livre de Deus, Paulo usa o exemplo dos gêmeos Jacó e Esaú. No versículo 13, ele cita o profeta Malaquias (1:2-3) para resumir a escolha divina: "Como está escrito: Amei a Jacó, e aborreci a Esaú". Esta declaração choca a sensibilidade moderna. Como um Deus de amor pode "aborrecer" (odiar) alguém antes mesmo de nascer? Para entender este texto, precisamos compreender a linguagem bíblica da aliança e a natureza da graça.',
    desc1: 'O Significado de "Aborrecer" no Contexto da Aliança. Na linguagem semítica e no contexto das alianças do Antigo Testamento, os termos "amar" e "odiar" frequentemente não se referem a emoções psicológicas (como afeição calorosa versus raiva maliciosa), mas a ações de escolha e rejeição. "Amar" significa escolher, favorecer e trazer para um relacionamento de aliança (como um rei escolhendo um vassalo). "Odiar" significa não escolher, rejeitar ou preterir. Deus escolheu Jacó para ser o herdeiro da promessa messiânica e não escolheu Esaú. (Jesus usa o mesmo idioma em Lucas 14:26 sobre "odiar" pai e mãe para segui-Lo).',
    desc2: 'A Base da Escolha: A Graça Soberana. O escândalo do texto não é que Deus "odiou" Esaú, mas que Ele amou Jacó. Os versículos anteriores (11-12) deixam claro que a escolha foi feita antes de os meninos nascerem ou fazerem qualquer bem ou mal. Se a escolha fosse baseada no caráter, Deus teria rejeitado ambos, pois Jacó era um enganador e Esaú um profano. A justiça estrita de Deus exigiria a condenação de ambos. O fato de Deus escolher Jacó é um ato de pura, imerecida e soberana graça. A eleição não é Deus sendo injusto com Esaú (Esaú recebeu a justiça que merecia pelos seus próprios pecados posteriores); a eleição é Deus sendo incrivelmente misericordioso com Jacó.',
    desc3: 'A Defesa da Justiça de Deus. Paulo antecipa a nossa objeção no versículo 14: "Que diremos pois? que há injustiça da parte de Deus? De modo nenhum!". A justiça de Deus não O obriga a salvar ninguém. Se um governador perdoa um criminoso no corredor da morte (um ato de misericórdia), ele não é obrigado a perdoar todos os outros criminosos para ser "justo". A misericórdia, por definição, é um dom livre, não um direito. Deus tem o direito soberano de ter misericórdia de quem Ele quiser (v. 15).',
    concl: 'Romanos 9:13 destrói a ideia de que Deus nos escolhe porque vê algo de bom em nós. A salvação é do Senhor do início ao fim. Esta doutrina não deve nos levar ao fatalismo ou à arrogância, mas à mais profunda humildade e adoração, sabendo que, se fomos trazidos para a família de Deus, foi unicamente por causa do Seu amor soberano e imerecido.'
  },
  {
    id: '1co_11_14',
    intro: 'O capítulo 11 de 1 Coríntios lida com a ordem e o decoro no culto público, especificamente a questão do uso do véu pelas mulheres e o comprimento do cabelo. A igreja em Corinto estava inserida em uma cultura greco-romana decadente, e a confusão sobre os papéis de gênero estava se infiltrando na congregação. Paulo argumenta que as distinções visuais entre homens e mulheres devem ser mantidas no culto, refletindo a ordem da criação. No versículo 14, ele faz um apelo à "natureza" para apoiar o seu argumento: "Ou não vos ensina a mesma natureza que é desonra para o homem ter cabelo crescido?". Esta afirmação levanta questões sobre o que Paulo quer dizer com "natureza" e se isso é uma lei universal para todos os tempos.',
    desc1: 'O Apelo à "Natureza" (Physis). Quando Paulo usa a palavra "natureza" (physis em grego), ele não está se referindo à biologia estrita (biologicamente, o cabelo dos homens cresce tanto quanto o das mulheres). No contexto filosófico e cultural da época, "natureza" frequentemente se referia à ordem natural das coisas, ao senso comum, aos instintos inatos ou aos costumes profundamente arraigados de uma sociedade que refletem as distinções criacionais. Paulo está dizendo que o senso comum e a ordem cultural (que reflete a distinção divina entre os sexos) ensinam que os homens devem parecer homens e as mulheres devem parecer mulheres.',
    desc2: 'A Desonra da Confusão de Gênero. Na cultura greco-romana do primeiro século (e na cultura judaica), o cabelo curto era a marca aceita da masculinidade, enquanto o cabelo longo era a glória da mulher (v. 15). Homens com cabelos longos e elaborados frequentemente estavam associados à efeminação, à prostituição cultual ou à rebelião contra as normas sociais. Para um homem cristão em Corinto adotar o estilo de cabelo feminino era uma "desonra", pois obscurecia a distinção de gênero que Deus criou (Gênesis 1:27). A igreja não deveria ser um lugar de confusão andrógina.',
    desc3: 'O Princípio Universal vs. a Aplicação Cultural. É importante distinguir entre o princípio teológico e a aplicação cultural. O princípio universal e atemporal que Paulo está ensinando é que Deus criou homens e mulheres diferentes, e essa distinção é boa e deve ser mantida e celebrada, não apagada. A aplicação cultural (o comprimento exato do cabelo) pode variar de cultura para cultura (por exemplo, os guerreiros espartanos ou os nazireus do Antigo Testamento, como Sansão, tinham cabelos longos como sinal de força ou voto). O que é considerado "masculino" ou "feminino" visualmente muda, mas o princípio de manter a distinção permanece.',
    concl: '1 Coríntios 11:14 nos ensina que a nossa aparência física e o nosso comportamento não são moralmente neutros. Eles comunicam mensagens. Como cristãos, devemos rejeitar as tentativas da cultura de apagar as distinções entre os sexos. Devemos abraçar e expressar a nossa masculinidade ou feminilidade dada por Deus de maneiras que sejam culturalmente apropriadas e que honrem o Criador.'
  },
  {
    id: '1ti_2_15',
    intro: 'O capítulo 2 de 1 Timóteo contém instruções de Paulo sobre a ordem no culto público, incluindo a restrição de que as mulheres não devem exercer o ofício de ensino autoritativo (pastorado) sobre os homens na congregação (v. 12). Paulo baseia esta restrição na ordem da criação (Adão foi formado primeiro) e na dinâmica da queda (Eva foi enganada). Imediatamente após esta dura restrição, Paulo escreve o versículo 15, que é amplamente considerado um dos versículos mais difíceis e obscuros do Novo Testamento: "Salvar-se-á, porém, dando à luz filhos, se permanecer com sobriedade na fé, no amor e na santificação". O que isso significa? Ensina a salvação pelas obras (ter filhos)?',
    desc1: 'O Que o Texto NÃO Significa. Primeiro, devemos rejeitar qualquer interpretação que contradiga o ensino claro de Paulo em outras cartas. Paulo ensina exaustivamente que a salvação é somente pela graça, através da fé em Cristo, e não por obras (Efésios 2:8-9). Portanto, 1 Timóteo 2:15 não pode significar que uma mulher ganha a vida eterna engravidando e tendo filhos. Isso condenaria todas as mulheres solteiras, estéreis ou que morrem no parto. A palavra "salvar" (sozo) na Bíblia tem uma ampla gama de significados, incluindo preservação, libertação de falsos ensinos ou a salvação escatológica final.',
    desc2: 'A Interpretação do Papel Ordenado por Deus. A interpretação mais provável foca no contexto da rebelião de Eva. Eva caiu porque usurpou a liderança e abandonou o seu papel ordenado por Deus. Paulo está dizendo que a mulher cristã será "salva" (preservada da inutilidade, do engano dos falsos mestres e da rebelião de Eva) abraçando o seu papel distinto dado por Deus. A "maternidade" (dando à luz filhos) é usada aqui como uma sinédoque (uma parte representando o todo) para o papel feminino na família e no lar. Em vez de buscar a autoridade pública na igreja (o que foi proibido no v. 12), a mulher encontra profunda dignidade, propósito e santificação no seu chamado no lar.',
    desc3: 'A Condição da Santidade. A promessa de preservação não é automática apenas por ter filhos. Paulo adiciona uma condição crucial: "se permanecer com sobriedade na fé, no amor e na santificação". A maternidade ou o trabalho no lar não substituem a necessidade de uma vida cristã genuína. A verdadeira mulher de Deus é caracterizada pela fé em Cristo, pelo amor prático, pela busca da santidade e pela "sobriedade" (autocontrole e bom senso). É esta vida de fé vivida dentro da esfera do seu chamado que marca a mulher que está no caminho da salvação final.',
    concl: '1 Timóteo 2:15 não é uma doutrina bizarra de salvação pela maternidade, mas uma afirmação da dignidade do papel da mulher. Em uma cultura que frequentemente desvaloriza o lar e a maternidade em favor do sucesso público, Paulo lembra às mulheres cristãs que abraçar o design de Deus para as suas vidas (seja na maternidade ou em outros papéis femininos) é o caminho da honra, da proteção espiritual e da glória a Deus.'
  },
  {
    id: 'jam_2_24',
    intro: 'O capítulo 2 da Epístola de Tiago contém uma das passagens mais debatidas da história da teologia cristã, sendo o centro da controvérsia durante a Reforma Protestante. Tiago argumenta vigorosamente contra uma fé morta, puramente intelectual, que não produz mudança de vida. O clímax do seu argumento está no versículo 24: "Vedes então que o homem é justificado pelas obras, e não somente pela fé". À primeira vista, esta declaração parece contradizer diretamente o ensino do apóstolo Paulo, que afirmou repetidamente que "o homem é justificado pela fé sem as obras da lei" (Romanos 3:28). Como reconciliar Tiago e Paulo? A Bíblia se contradiz sobre a doutrina central da salvação?',
    desc1: 'A Definição de "Fé" em Tiago. A aparente contradição desaparece quando entendemos como Paulo e Tiago usam as palavras "fé" e "justificação" em contextos diferentes. Quando Tiago ataca a "fé somente" (v. 24), ele está atacando a definição de fé dos seus oponentes (v. 14): um mero assentimento intelectual a fatos teológicos (como acreditar que Deus existe, algo que até os demônios fazem, v. 19). Essa "fé" é morta e inútil. Paulo também rejeitaria essa fé falsa. Para Paulo, a fé que salva é uma confiança viva e ativa em Cristo que inevitavelmente "opera pelo amor" (Gálatas 5:6).',
    desc2: 'A Definição de "Justificação" em Tiago. A palavra "justificar" (dikaioo) pode significar "declarar justo" (o uso forense de Paulo diante do tribunal de Deus) ou "demonstrar/provar ser justo" (o uso demonstrativo de Tiago diante dos homens). Paulo está respondendo à pergunta: "Como um pecador é aceito por Deus?" (Resposta: Somente pela fé na obra de Cristo). Tiago está respondendo à pergunta: "Como uma pessoa prova que a sua fé é genuína?" (Resposta: Pelas obras que a fé produz). Tiago usa o exemplo de Abraão oferecendo Isaque (v. 21) não como o momento em que Abraão foi salvo (isso aconteceu anos antes, em Gênesis 15:6, pela fé), mas como o momento em que a sua fé foi vindicada e provada verdadeira pelas suas ações.',
    desc3: 'A Harmonia Teológica. Paulo e Tiago não são inimigos teológicos; eles estão lutando contra inimigos diferentes. Paulo luta contra o legalismo (pessoas que confiam nas suas obras para a salvação). Tiago luta contra o antinomianismo (pessoas que usam a graça como desculpa para o pecado e a preguiça moral). A teologia reformada resumiu perfeitamente a harmonia entre os dois: "Somos justificados somente pela fé, mas a fé que justifica nunca está só". A verdadeira fé sempre produz o fruto das boas obras.',
    concl: 'Tiago 2:24 é um alerta vital contra a hipocrisia religiosa. Não podemos reivindicar o perdão de Deus se as nossas vidas não mostram nenhuma evidência de transformação. As nossas obras não compram a nossa salvação, mas são a prova inegável de que fomos verdadeiramente salvos pela graça.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 40');
