const fs = require('fs');

let content = fs.readFileSync('data/pericopes.ts', 'utf8');

const replacements = [
  {
    id: 'rev_3_14_22',
    intro: 'A carta à igreja de Laodiceia é a sétima e última das cartas de Jesus às igrejas da Ásia Menor no livro do Apocalipse. É também a mais severa e a única que não contém absolutamente nenhum elogio. Laodiceia era uma cidade extremamente rica, famosa pelo seu setor bancário, pela produção de lã negra e por uma escola de medicina que produzia um colírio famoso. No entanto, a cidade tinha um problema crônico: a sua água, que chegava por aquedutos, era morna e intragável. Jesus usa a geografia, a economia e a cultura da cidade para fazer um diagnóstico espiritual devastador de uma igreja que se achava autossuficiente, mas que, na realidade, havia deixado o próprio Cristo do lado de fora.',
    desc1: 'Jesus se apresenta como o "Amém, a testemunha fiel e verdadeira", contrastando a Sua fidelidade com a infidelidade da igreja. O diagnóstico é direto: "Conheço as tuas obras, que nem és frio nem quente; quem dera foras frio ou quente!". A água fria (como a de Colossos) era refrescante; a água quente (como as fontes termais de Hierápolis) era terapêutica. Mas a água morna de Laodiceia causava náuseas. A igreja não era abertamente hostil ao Evangelho (fria), nem apaixonada e útil (quente); era espiritualmente apática, confortável e inútil. A reação de Jesus à religiosidade morna é o vômito: "vomitar-te-ei da minha boca".',
    desc2: 'A raiz da mornidão era a ilusão da autossuficiência material. A igreja dizia: "Rico sou, e estou enriquecido, e de nada tenho falta". Eles confundiram a prosperidade econômica com a aprovação divina. Jesus destrói essa ilusão com a realidade espiritual: "e não sabes que és um desgraçado, e miserável, e pobre, e cego, e nu". A riqueza bancária não cobria a pobreza espiritual; a lã negra não cobria a nudez moral; e o colírio famoso não curava a cegueira para as coisas de Deus. Jesus os aconselha a comprar dEle o verdadeiro ouro (fé provada no fogo), vestes brancas (justiça) e colírio espiritual (discernimento).',
    desc3: 'Apesar da severidade do diagnóstico, a carta termina com uma das mais belas expressões do amor e da graça de Cristo. Ele diz: "Eu repreendo e castigo a todos quantos amo; sê pois zeloso, e arrepende-te". O juízo é um convite ao arrependimento. Em seguida, a imagem mais trágica e esperançosa: "Eis que estou à porta, e bato". A igreja havia trancado Jesus do lado de fora dos seus cultos e vidas confortáveis. No entanto, o Soberano do universo não arromba a porta; Ele bate e espera que alguém ouça a Sua voz e abra, prometendo entrar e cear em intimidade com aquele que se arrepender.',
    concl: 'A carta a Laodiceia é um alerta urgente contra o perigo do conforto material e da apatia espiritual. A verdadeira riqueza não se mede pela nossa conta bancária, mas pela nossa intimidade com Cristo. Ele ainda está à porta das nossas igrejas e corações, batendo e convidando-nos a abandonar a mornidão para cearmos com Ele.'
  },
  {
    id: 'psa_1_1_6',
    intro: 'O Salmo 1 serve como o portal de entrada e o prefácio teológico para todo o livro dos Salmos. Ele não é uma oração ou um hino de louvor, mas um salmo de sabedoria que destila toda a vida humana em uma escolha fundamental entre dois caminhos, duas atitudes e dois destinos finais. O salmista contrasta a vida do homem justo (que encontra a sua alegria e estabilidade na Palavra de Deus) com a vida do ímpio (que é instável e destituída de valor eterno). Este salmo nos ensina que a verdadeira felicidade (bem-aventurança) não é o resultado do acaso, mas de escolhas deliberadas sobre quem ouvimos e o que amamos.',
    desc1: 'O salmo começa definindo a bem-aventurança (felicidade profunda e aprovação divina) de forma negativa, descrevendo o que o homem justo não faz. Há uma progressão sutil e perigosa no envolvimento com o pecado: primeiro ele "anda no conselho dos ímpios" (ouve e adota a sua forma de pensar), depois "se detém no caminho dos pecadores" (começa a imitar o seu comportamento e estilo de vida), e finalmente "se assenta na roda dos escarnecedores" (torna-se confortável na zombaria contra Deus e Sua verdade). O pecado sempre começa na mente, desce para os pés e termina paralisando a pessoa na cadeira do cinismo.',
    desc2: 'Em contraste, o salmista descreve a atitude positiva do homem justo: "Antes tem o seu prazer na lei do Senhor, e na sua lei medita de dia e de noite". A obediência do justo não é um fardo legalista, mas um "prazer" (deleite). Ele não apenas lê a Palavra superficialmente, mas "medita" nela continuamente. A meditação bíblica não é esvaziar a mente (como no misticismo oriental), mas encher a mente com a verdade de Deus até que ela molde os pensamentos, as emoções e as ações. O resultado dessa vida enraizada na Palavra é a estabilidade e a frutificação: ele é como uma árvore plantada junto a ribeiros de águas, que dá fruto no tempo certo e cujas folhas não murcham.',
    desc3: 'O destino dos ímpios é descrito em forte contraste com a árvore frutífera. "Não são assim os ímpios; mas são como a moinha (palha) que o vento espalha". A palha é a casca inútil do trigo, leve, seca, sem raiz e sem valor, que é soprada para longe no momento da peneiração. A vida longe de Deus pode parecer atraente, mas no final, revela-se vazia e instável. O salmo conclui com o veredito final: o Senhor "conhece" (aprova e guarda) o caminho dos justos, mas o caminho dos ímpios perecerá no juízo. O destino final é a consequência inevitável do caminho escolhido.',
    concl: 'O Salmo 1 nos convida a examinar as nossas raízes. A verdadeira felicidade e a estabilidade duradoura não são encontradas seguindo os conselhos deste mundo, mas plantando a nossa vida profundamente na Palavra de Deus. A escolha do nosso caminho hoje determinará o nosso destino na eternidade.'
  },
  {
    id: 'luk_10_25_37',
    intro: 'A Parábola do Bom Samaritano é uma das histórias mais famosas e revolucionárias contadas por Jesus. Ela surge de um debate teológico com um doutor da lei (um especialista nas Escrituras) que tenta testar Jesus com a pergunta: "Que farei para herdar a vida eterna?". Jesus o leva de volta à Lei: amar a Deus sobre todas as coisas e ao próximo como a si mesmo. Querendo justificar-se (e limitar a sua responsabilidade de amar), o religioso faz a pergunta que motiva a parábola: "E quem é o meu próximo?". Jesus responde com uma história que destrói as fronteiras raciais, religiosas e sociais, redefinindo o amor prático e expondo a hipocrisia da religião sem compaixão.',
    desc1: 'A história começa com um homem (presumivelmente judeu) descendo de Jerusalém para Jericó, uma estrada perigosa e conhecida por assaltos. Ele é atacado, roubado, espancado e deixado quase morto. A primeira oportunidade de ajuda vem da elite religiosa: um sacerdote e, em seguida, um levita passam pelo caminho. Ambos veem o homem ferido, mas "passam de largo". Eles provavelmente tinham desculpas teológicas e rituais (tocar em um cadáver os tornaria impuros para o serviço no templo). A parábola expõe a tragédia de uma religião que prioriza a pureza ritual e as regras acima da misericórdia e da vida humana.',
    desc2: 'O herói da história é a pessoa mais improvável e odiada pela audiência judaica: um samaritano. Judeus e samaritanos tinham uma inimizade histórica, racial e religiosa profunda. No entanto, quando o samaritano vê o homem ferido, ele "move-se de íntima compaixão". A compaixão quebra as barreiras do preconceito. O samaritano não pergunta a religião ou a etnia do homem; ele simplesmente vê a necessidade e age. Ele se aproxima, ata as feridas (aplicando azeite e vinho), coloca-o sobre a sua própria cavalgadura, leva-o para uma estalagem e cuida dele pessoalmente.',
    desc3: 'O amor do samaritano é prático, sacrificial e custoso. No dia seguinte, ele dá dois denários (o salário de dois dias) ao hospedeiro e promete pagar qualquer despesa extra no seu retorno. Jesus então inverte a pergunta original do doutor da lei. Em vez de perguntar "Quem é o meu próximo?" (tentando definir quem merece ser amado), Jesus pergunta: "Qual destes três te parece que foi o próximo daquele que caiu nas mãos dos salteadores?". O religioso, incapaz de pronunciar a palavra "samaritano", responde: "O que usou de misericórdia para com ele". Jesus conclui com a ordem: "Vai, e faze da mesma maneira".',
    concl: 'A parábola do Bom Samaritano nos ensina que o amor cristão não é um sentimento passivo, mas uma ação sacrificial que atravessa as fronteiras do preconceito e da conveniência. O nosso "próximo" não é apenas aquele que é parecido conosco, mas qualquer pessoa em necessidade que Deus coloca no nosso caminho. A verdadeira religião sempre se manifesta através da misericórdia prática.'
  },
  {
    id: 'jhn_11_38_44',
    intro: 'A ressurreição de Lázaro é o sétimo e maior "sinal" no Evangelho de João, o clímax do ministério público de Jesus antes da Sua própria paixão. Jesus recebe a notícia de que Seu amigo Lázaro está doente, mas Ele intencionalmente demora dois dias antes de ir para Betânia. Quando Ele chega, Lázaro já está morto e sepultado há quatro dias (o que, na crença judaica da época, significava que a alma já havia deixado o corpo e não havia mais esperança). Jesus entra em um cenário de luto profundo, choro e decepção para demonstrar que Ele não apenas tem o poder de dar a vida, mas que Ele é a própria Ressurreição e a Vida.',
    desc1: 'Quando Maria encontra Jesus, ela cai a Seus pés e expressa a dor e a frustração de todos: "Senhor, se tu estivesses aqui, meu irmão não teria morrido". Ela acreditava no poder de Jesus para curar, mas achava que Ele havia chegado tarde demais. Ao ver o choro de Maria e dos judeus, Jesus "moveu-se muito em espírito, e perturbou-se". O versículo 35 registra a emoção mais profunda do Salvador: "Jesus chorou". Ele não chora porque perdeu o controle (Ele sabia que ia ressuscitar Lázaro), mas chora por compaixão e por indignação contra a morte, o pecado e a dor que destroem a Sua criação. O nosso Deus não é apático; Ele sofre conosco.',
    desc2: 'Jesus vai ao sepulcro, uma caverna fechada com uma pedra, e ordena: "Tirai a pedra". Marta, a irmã pragmática, tenta impedi-Lo, focando na realidade física e na impossibilidade humana: "Senhor, já cheira mal, porque é já de quatro dias". A lógica humana diz que a morte é o fim e que algumas situações estão além de qualquer restauração. Jesus a repreende suavemente, lembrando-a da promessa: "Não te hei dito que, se creres, verás a glória de Deus?". A fé exige que removamos as pedras da incredulidade e permitamos que a Palavra de Cristo entre nos lugares de morte em nossas vidas.',
    desc3: 'Após orar ao Pai em voz alta (para que a multidão cresse que Ele foi enviado por Deus), Jesus clama com grande voz: "Lázaro, vem para fora!". A voz do Criador, que no princípio chamou o universo à existência, agora chama um homem morto de volta à vida. Lázaro sai do sepulcro, vivo, mas ainda com as mãos e os pés atados com faixas e o rosto envolto em um lenço. Jesus dá uma ordem final à comunidade: "Desatai-o, e deixai-o ir". A vida é dada exclusivamente pelo poder da palavra de Cristo, mas a libertação das amarras do passado é um trabalho que Ele delega à comunidade da igreja.',
    concl: 'A ressurreição de Lázaro prova que Jesus tem a última palavra sobre a morte e sobre qualquer situação impossível. Não há casamento, ministério, sonho ou vida tão "morta" ou "cheirando mal" que a voz do Filho de Deus não possa ressuscitar. Ele é a Ressurreição e a Vida; quem crê nEle, ainda que esteja morto, viverá.'
  },
  {
    id: 'act_16_25_34',
    intro: 'A história de Paulo e Silas em Filipos é um testemunho poderoso de que a obediência à vontade de Deus não nos isenta de sofrimento e injustiça. Eles haviam chegado à Macedônia em resposta a uma visão divina, mas o resultado não foi um tapete vermelho, e sim perseguição severa. Após libertarem uma jovem escrava de um espírito de adivinhação, eles afetam a economia local. Como resultado, são espancados publicamente com varas e lançados no cárcere interior (a cela mais escura e segura), com os pés presos no tronco. No entanto, eles transformam a masmorra romana em um santuário de adoração, provando que a verdadeira liberdade está no espírito, não nas circunstâncias.',
    desc1: 'A prisão de Paulo e Silas revela a raiz econômica de muita perseguição religiosa. Os donos da jovem escrava não se importavam com a teologia de Paulo; eles ficaram furiosos porque a sua fonte de lucro (a exploração espiritual da menina) havia secado. O sistema do mundo tolera a religião até o momento em que ela confronta os seus ídolos financeiros e morais. A multidão se levanta contra eles, e os magistrados, sem um julgamento justo, ordenam o açoitamento. A obediência radical ao Evangelho frequentemente atrai a fúria do sistema do mundo.',
    desc2: 'A reação de Paulo e Silas na prisão é um dos maiores milagres do livro de Atos. "Perto da meia-noite, Paulo e Silas oravam e cantavam hinos a Deus, e os outros presos os escutavam". Com as costas sangrando, no escuro, no frio e presos a um tronco, eles escolhem a adoração em vez da murmuração. O louvor na "meia-noite" da vida não é uma negação da dor, mas uma declaração de que Deus é maior do que a dor. A adoração deles não apenas mudou o ambiente espiritual da cela, mas atraiu a presença de Deus de forma física: um grande terremoto abalou os alicerces da prisão, todas as portas se abriram e as algemas de todos caíram.',
    desc3: 'O carcereiro, acordando e vendo as portas abertas, tira a espada para se matar (pois a lei romana exigia a vida do guarda se os prisioneiros fugissem). Paulo grita: "Não te faças nenhum mal, que todos aqui estamos". O verdadeiro milagre não foi o terremoto, mas o fato de nenhum preso ter fugido. O amor e a integridade de Paulo quebram o coração do carcereiro, que cai tremendo e faz a pergunta mais importante da vida: "Senhores, que devo fazer para me salvar?". A resposta é o cerne do Evangelho: "Crê no Senhor Jesus Cristo e serás salvo, tu e a tua casa". Naquela mesma noite, o carcereiro lava as feridas deles e é batizado com toda a sua família.',
    concl: 'As nossas reações na "meia-noite" das nossas provações são o nosso maior testemunho para o mundo que nos observa (os "outros presos"). Deus frequentemente permite que sejamos lançados em prisões injustas não para nos destruir, mas para que o nosso louvor provoque terremotos que libertem aqueles que estão presos na escuridão ao nosso redor.'
  }
];

replacements.forEach(rep => {
  const regex = new RegExp(`(id: '${rep.id}',[\\s\\S]*?introduction: )'[^']*'(,[\\s\\S]*?points: \\[[\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?description: )'[^']*'([\\s\\S]*?conclusion: )'[^']*'`, 'g');
  
  content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
    return `${p1}\`${rep.intro}\`${p2}\`${rep.desc1}\`${p3}\`${rep.desc2}\`${p4}\`${rep.desc3}\`${p5}\`${rep.concl}\``;
  });
});

fs.writeFileSync('data/pericopes.ts', content, 'utf8');
console.log('Done batch 13');
